Add playground container change-jdk CLI command #5584

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -95,6 +95,7 @@ playground_usage() {
   printf "  %s   💀 Kill all containers\n" "$(green "container kill-all")               "
   printf "  %s   🕵️  Tail and follow container logs\n" "$(green "container logs")                   "
   printf "  %s   🛬 SSH into container\n" "$(green "container ssh")                    "
+  printf "  %s   🤎 Change java JDK version using Azul JDK (https://www.azul.com/downloads/#downloads-table-zulu)\n" "$(green "container change-jdk")             "
   printf "  %s   🪄  Execute command in a container\n" "$(green "container exec")                   "
   printf "  %s   🔁 Restart a container\n" "$(green "container restart")                "
   printf "  %s   ⏸️  Pause a container\n" "$(green "container pause")                  "
@@ -3294,6 +3295,7 @@ playground_container_usage() {
   printf "  %s   💀 Kill all containers\n" "$(green "kill-all")        "
   printf "  %s   🕵️  Tail and follow container logs\n" "$(green "logs")            "
   printf "  %s   🛬 SSH into container\n" "$(green "ssh")             "
+  printf "  %s   🤎 Change java JDK version using Azul JDK (https://www.azul.com/downloads/#downloads-table-zulu)\n" "$(green "change-jdk")      "
   printf "  %s   🪄  Execute command in a container\n" "$(green "exec")            "
   printf "  %s   🔁 Restart a container\n" "$(green "restart")         "
   printf "  %s   ⏸️  Pause a container\n" "$(green "pause")           "
@@ -3564,6 +3566,56 @@ playground_container_ssh_usage() {
     printf "  playground ssh -c connect\n"
     printf "  playground ssh -c connect -s sh\n"
     printf "  playground ssh --container connect --shell sh\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_container_change_jdk_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground container change-jdk\n"
+    echo
+
+    printf "  🤎 Change java JDK version using Azul JDK\n  (https://www.azul.com/downloads/#downloads-table-zulu)\n  \n  PS: It works for UBI8 docker images only\n"
+    echo
+
+  else
+    printf "playground container change-jdk - 🤎 Change java JDK version using Azul JDK (https://www.azul.com/downloads/#downloads-table-zulu)\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground container change-jdk [OPTIONS]\n"
+  printf "  playground container change-jdk --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    🐳 Container name\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--version VERSION (required)")"
+    printf "    🤎 JDK version to use\n"
+    printf "    Allowed: 8, 11, 17, 21, 22\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground change-jdk --container connect --version jdk17-lts\n"
     echo
 
   fi
@@ -17830,6 +17882,33 @@ playground_container_ssh_command() {
 }
 
 # :command.function
+playground_container_change_jdk_command() {
+  # src/commands/container/change-jdk.sh
+  container="${args[--container]}"
+  version="${args[--version]}"
+
+  log "🤎 Installing Azul JDK ${version} on container ${container}" /usr/lib/jvm/java-11-zulu-openjdk/bin/java
+  playground container exec --container "${container}" --root --command "yum install -y https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm ; yum -y install zulu${version}-jdk"
+  if [ $? -eq 0 ]
+  then
+      java_path=$(playground --output-level ERROR container exec --container "${container}" --root --command "update-alternatives --display java | grep \"java-${version}-zulu-openjdk\" | grep \"priority\" | head -1 | cut -d \" \" -f 1")
+      if [ -n "$java_path" ]
+      then
+          playground container exec --container "${container}" --root --command "update-alternatives --set java \"$java_path\""
+      else
+          logerror "could not find java ${version} in alternatives list"
+      fi
+      playground container restart --container "${container}"
+
+      sleep 5
+
+      playground container exec --container "${container}" --command "java -version"
+  else
+      logerror "❌ failed to install Azul JDK ${version}"
+  fi
+}
+
+# :command.function
 playground_container_exec_command() {
   # src/commands/container/exec.sh
   container="${args[--container]}"
@@ -28896,6 +28975,13 @@ playground_container_parse_requirements() {
       shift $#
       ;;
 
+    change-jdk)
+      action="change-jdk"
+      shift
+      playground_container_change_jdk_parse_requirements "$@"
+      shift $#
+      ;;
+
     exec)
       action="exec"
       shift
@@ -29367,6 +29453,92 @@ playground_container_ssh_parse_requirements() {
   # :command.whitelist_filter
   if [[ ${args['--shell']:-} ]] && [[ ! ${args['--shell']:-} =~ ^(bash|sh|ksh|zsh)$ ]]; then
     printf "%s\n" "--shell must be one of: bash, sh, ksh, zsh" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_container_change_jdk_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_container_change_jdk_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="container change-jdk"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --version)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--version']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--version requires an argument: --version VERSION" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--version']+x} ]]; then
+    printf "missing required flag: --version VERSION\n" >&2
+    exit 1
+  fi
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+  # :command.whitelist_filter
+  if [[ ${args['--version']:-} ]] && [[ ! ${args['--version']:-} =~ ^(8|11|17|21|22)$ ]]; then
+    printf "%s\n" "--version must be one of: 8, 11, 17, 21, 22" >&2
     exit 1
   fi
 
@@ -33457,6 +33629,7 @@ run() {
     "container kill-all") playground_container_kill_all_command ;;
     "container logs") playground_container_logs_command ;;
     "container ssh") playground_container_ssh_command ;;
+    "container change-jdk") playground_container_change_jdk_command ;;
     "container exec") playground_container_exec_command ;;
     "container restart") playground_container_restart_command ;;
     "container pause") playground_container_pause_command ;;
