wip switch

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -6536,36 +6536,36 @@ function set_profiles() {
   if [ -z "$ENABLE_CONTROL_CENTER" ]
   then
     log "🛑 control-center is disabled"
-    playground state del env.ENABLE_CONTROL_CENTER
+    playground state del flags.ENABLE_CONTROL_CENTER
   else
     log "💠 control-center is enabled"
     log "Use http://localhost:9021 to login"
     profile_control_center_command="--profile control-center"
-    playground state set env.ENABLE_CONTROL_CENTER 1
+    playground state set flags.ENABLE_CONTROL_CENTER 1
   fi
 
   profile_ksqldb_command=""
   if [ -z "$ENABLE_KSQLDB" ]
   then
     log "🛑 ksqldb is disabled"
-    playground state del env.ENABLE_KSQLDB
+    playground state del flags.ENABLE_KSQLDB
   else
     log "🚀 ksqldb is enabled"
     log "🔧 You can use ksqlDB with CLI using:"
     log "docker exec -i ksqldb-cli ksql http://ksqldb-server:8088"
     profile_ksqldb_command="--profile ksqldb"
-    playground state set env.ENABLE_KSQLDB 1
+    playground state set flags.ENABLE_KSQLDB 1
   fi
 
   profile_rest_proxy_command=""
   if [ -z "$ENABLE_RESTPROXY" ]
   then
     log "🛑 REST Proxy is disabled"
-    playground state del env.ENABLE_RESTPROXY
+    playground state del flags.ENABLE_RESTPROXY
   else
     log "📲 REST Proxy is enabled"
     profile_rest_proxy_command="--profile rest-proxy"
-    playground state set env.ENABLE_RESTPROXY 1
+    playground state set flags.ENABLE_RESTPROXY 1
   fi
 
   # defined grafana variable and when profile is included/excluded
@@ -6573,40 +6573,40 @@ function set_profiles() {
   if [ -z "$ENABLE_JMX_GRAFANA" ]
   then
     log "🛑 Grafana is disabled"
-    playground state del env.ENABLE_JMX_GRAFANA
+    playground state del flags.ENABLE_JMX_GRAFANA
   else
     log "📊 Grafana is enabled"
     profile_grafana_command="--profile grafana"
-    playground state set env.ENABLE_JMX_GRAFANA 1
+    playground state set flags.ENABLE_JMX_GRAFANA 1
   fi
   profile_kcat_command=""
   if [ -z "$ENABLE_KCAT" ]
   then
     log "🛑 kcat is disabled"
-    playground state del env.ENABLE_KCAT
+    playground state del flags.ENABLE_KCAT
   else
     log "🧰 kcat is enabled"
     profile_kcat_command="--profile kcat"
-    playground state set env.ENABLE_KCAT 1
+    playground state set flags.ENABLE_KCAT 1
   fi
   profile_conduktor_command=""
   if [ -z "$ENABLE_CONDUKTOR" ]
   then
     log "🛑 conduktor is disabled"
-    playground state del env.ENABLE_CONDUKTOR
+    playground state del flags.ENABLE_CONDUKTOR
   else
     log "🐺 conduktor is enabled"
     log "Use http://localhost:8080/console (admin/admin) to login"
     profile_conduktor_command="--profile conduktor"
-    playground state set env.ENABLE_CONDUKTOR 1
+    playground state set flags.ENABLE_CONDUKTOR 1
   fi
   profile_sql_datagen_command=""
   if [ ! -z "$SQL_DATAGEN" ]
   then
     profile_sql_datagen_command="--profile sql_datagen"
-    playground state set env.SQL_DATAGEN 1
+    playground state set flags.SQL_DATAGEN 1
   else
-    playground state del env.SQL_DATAGEN
+    playground state del flags.SQL_DATAGEN
   fi
 
   #define kafka_nodes variable and when profile is included/excluded
@@ -6614,11 +6614,11 @@ function set_profiles() {
   if [ -z "$ENABLE_KAFKA_NODES" ]
   then
     profile_kafka_nodes_command=""
-    playground state del env.ENABLE_KAFKA_NODES
+    playground state del flags.ENABLE_KAFKA_NODES
   else
     log "3️⃣  Multi broker nodes enabled"
     profile_kafka_nodes_command="--profile kafka_nodes"
-    playground state set env.ENABLE_KAFKA_NODES 1
+    playground state set flags.ENABLE_KAFKA_NODES 1
   fi
 
   # Adding Schema Registry plugin profile
@@ -6626,30 +6626,30 @@ function set_profiles() {
   if [ -z "$ENABLE_SR_MAVEN_PLUGIN_NODE" ]
   then
     profile_schema_registry_command=""
-    playground state del env.ENABLE_SR_MAVEN_PLUGIN_NODE
+    playground state del flags.ENABLE_SR_MAVEN_PLUGIN_NODE
   else
     log " Starting Schema Registry plugin profile"
     profile_schema_registry_command="--profile sr_plugin_app"
-    playground state set env.ENABLE_SR_MAVEN_PLUGIN_NODE 1
+    playground state set flags.ENABLE_SR_MAVEN_PLUGIN_NODE 1
   fi
 
   # defined 3 Connect variable and when profile is included/excluded
   profile_connect_nodes_command=""
   if [ -z "$ENABLE_CONNECT_NODES" ]
   then
-    playground state del env.ENABLE_CONNECT_NODES
+    playground state del flags.ENABLE_CONNECT_NODES
   elif [ ${nb_connect_services} -gt 1 ]
   then
     log "🥉 Multiple Connect nodes mode is enabled, connect2 and connect 3 containers will be started"
     profile_connect_nodes_command="--profile connect_nodes"
     export CONNECT_NODES_PROFILES="connect_nodes"
-    playground state set env.CONNECT_NODES_PROFILES 1
+    playground state set flags.CONNECT_NODES_PROFILES 1
   else
     if [ ! -f "${DOCKER_COMPOSE_FILE_OVERRIDE}" ]
     then
       log "🥉 Multiple connect nodes mode is enabled, connect2 and connect 3 containers will be started"
       profile_connect_nodes_command="--profile connect_nodes"
-      playground state set env.CONNECT_NODES_PROFILES 1
+      playground state set flags.CONNECT_NODES_PROFILES 1
     else
       logerror "🛑 Could not find connect2 and connect3 in ${DOCKER_COMPOSE_FILE_OVERRIDE}. Update the yaml files to contain the connect2 && connect3 in ${DOCKER_COMPOSE_FILE_OVERRIDE}"
       exit 1
@@ -7803,6 +7803,13 @@ function bootstrap_ccloud_environment () {
     logerror "ERROR: $DELTA_CONFIGS_ENV has not been generated"
     exit 1
   fi
+
+  playground state set ccloud.ENVIRONMENT "$ENVIRONMENT"
+  playground state set ccloud.CLUSTER_NAME "$CLUSTER_NAME"
+  playground state set ccloud.CLUSTER_CLOUD "$CLUSTER_CLOUD"
+  playground state set ccloud.CLUSTER_REGION "$CLUSTER_REGION"
+  playground state set ccloud.CLUSTER_CREDS "$CLUSTER_CREDS"
+  playground state set ccloud.SCHEMA_REGISTRY_CREDS "$SCHEMA_REGISTRY_CREDS"
 
   # trick
   playground state set environment "ccloud"
@@ -9717,10 +9724,10 @@ function load_env_variables () {
   for item in {ENABLE_CONTROL_CENTER,ENABLE_KSQLDB,ENABLE_RESTPROXY,ENABLE_JMX_GRAFANA,ENABLE_KCAT,ENABLE_CONDUKTOR,SQL_DATAGEN,ENABLE_KAFKA_NODES,ENABLE_SR_MAVEN_PLUGIN_NODE,CONNECT_NODES_PROFILES,CONNECT_NODES_PROFILES}
   do
     set +e
-    playground state get "env.${item}" > /dev/null 2>&1
+    playground state get "flags.${item}" > /dev/null 2>&1
     if [ $? -ne 1 ]
     then
-      log "❇️ exporting environment variable ${item}"
+      log "⛳ exporting environment variable ${item}"
       export "${item}"=1
     fi
   done
@@ -10875,67 +10882,63 @@ playground_run_ccloud_command() {
 # :command.function
 playground_switch_ccloud_command() {
   # src/switch_ccloud_command.sh
-  if [ -f /tmp/switch-playground-command ] || [ -f /tmp/switch-playground-run ]
-  then
-      log "🌩️ you have already switched to ccloud environment"
-      exit 0
-  fi
-
-  if [ -f /tmp/playground-command ]
-  then
-      mv /tmp/playground-command /tmp/switch-playground-command
-  fi
-
-  if [ -f /tmp/playground-run ]
-  then
-      mv /tmp/playground-run /tmp/switch-playground-run
-  fi
-
   log "🌩️ switch to ccloud environment"
+
+  ENVIRONMENT=$(playground state get ccloud.ENVIRONMENT)
+  CLUSTER_NAME=$(playground state get ccloud.CLUSTER_NAME)
+  CLUSTER_CLOUD=$(playground state get ccloud.CLUSTER_CLOUD)
+  CLUSTER_REGION=$(playground state get ccloud.CLUSTER_REGION)
+  CLUSTER_CREDS=$(playground state get ccloud.CLUSTER_CREDS)
+  SCHEMA_REGISTRY_CREDS=$(playground state get ccloud.SCHEMA_REGISTRY_CREDS)
+
+  if [ -z $ENVIRONMENT ] || [ -z $CLUSTER_CLOUD ] || [ -z $CLUSTER_CLOUD ] || [ -z $CLUSTER_REGION ] || [ -z $CLUSTER_CREDS ]
+  then
+      logerror "One mandatory environment variable to use your cluster is missing:"
+      logerror "ENVIRONMENT=$ENVIRONMENT"
+      logerror "CLUSTER_NAME=$CLUSTER_NAME"
+      logerror "CLUSTER_CLOUD=$CLUSTER_CLOUD"
+      logerror "CLUSTER_REGION=$CLUSTER_REGION"
+      logerror "CLUSTER_CREDS=$CLUSTER_CREDS"
+      exit 1
+  fi
+
+  playground state set environment_before_switch "$(playground state get environment)"
+
+  log "🔌 boostrapping ccloud environment"
   bootstrap_ccloud_environment
 
   if [ -f /tmp/delta_configs/env.delta ]
   then
-       source /tmp/delta_configs/env.delta
+      source /tmp/delta_configs/env.delta
   else
-       logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
-       exit 1
+      logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
+      exit 1
   fi
 }
 
 # :command.function
 playground_switch_onprem_command() {
   # src/switch_onprem_command.sh
-  if [ -f /tmp/switch-playground-command ]
+  log "💺 Switch back to onprem environment"
+  set +e
+  playground state get environment_before_switch > /dev/null 2>&1
+  if [ $? -ne 0 ]
   then
-      log "💺 Switch back to onprem environment"
-      mv /tmp/switch-playground-command /tmp/playground-command
-  else
-      logwarn "/tmp/switch-playground-command was not found, switch-ccloud was probably not executed before"
+      logerror "switch-ccloud was probably not executed before"
+      exit 1
   fi
+  set -e
 
-  if [ -f /tmp/switch-playground-run ]
-  then
-      mv /tmp/switch-playground-run /tmp/playground-run
-  else
-      logwarn "/tmp/switch-playground-run was not found, switch-ccloud was probably not executed before"
-  fi
+  playground state set environment "$(playground state get environment_before_switch)"
+  playground state del environment_before_switch
 
-  if [ ! -f /tmp/playground-run ]
-  then
-    logerror "File containing re-run command /tmp/playground-run does not exist!"
-    logerror "Make sure to use <playground run> command !"
-    exit 1
-  fi
-
-  test_file=$(cat /tmp/playground-run | awk '{ print $4}')
+  test_file=$(playground state get test_file)
 
   if [ ! -f $test_file ]
   then
 
-  logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
-  logerror "Make sure to use <playground run> command !"
-  exit 1
+      logerror "File $test_file retrieved from $root_folder/playground.ini does not exist!"
+      exit 1
   fi
 
   last_two_folders=$(basename $(dirname $(dirname $test_file)))/$(basename $(dirname $test_file))
