wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -13695,10 +13695,9 @@ playground_compile_all_connector_plugins_command() {
   # src/commands/compile-all-connector-plugins.sh
   confluent_only="${args[--confluent-only]}"
 
-  rm -rf "${root_folder}/connector-plugin-sourcecode"
-
   function handle_signal {
     echo "Stopping..."
+    playground config clipboard true
     stop=1
   }
   # Set the signal handler
@@ -13706,6 +13705,7 @@ playground_compile_all_connector_plugins_command() {
 
   set +e
 
+  playground config clipboard false
   export GITHUB_RUN_NUMBER=1
 
   if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
@@ -13747,6 +13747,8 @@ playground_compile_all_connector_plugins_command() {
       echo ""
 
   done < "${root_folder}/scripts/cli/confluent-hub-plugin-list.txt"
+
+  playground config clipboard true
 }
 
 # :command.function
@@ -19241,7 +19243,7 @@ for component in $list
 do
     set +e
     log "🏗 Building jar for \${component}"
-    docker run -i --rm -e KAFKA_CLIENT_TAG=\$KAFKA_CLIENT_TAG -e TAG=\$TAG_BASE -v "\${DIR}/\${component}":/usr/src/mymaven -v "\$HOME/.m2":/root/.m2 -v "\$PWD/../../scripts/settings.xml:/tmp/settings.xml" -v "\${DIR}/\${component}/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-11-alpine mvn -s /tmp/settings.xml -Dkafka.tag=\$TAG -Dkafka.client.tag=\$KAFKA_CLIENT_TAG package > /tmp/result.log 2>&1
+    docker run -i --rm -e KAFKA_CLIENT_TAG=\$KAFKA_CLIENT_TAG -e TAG=\$TAG_BASE -v "\${DIR}/\${component}":/usr/src/mymaven -v "\$HOME/.m2":/root/.m2 -v "\$PWD/../../scripts/settings.xml:/tmp/settings.xml" -v "\${DIR}/\${component}/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-11 mvn -s /tmp/settings.xml -Dkafka.tag=\$TAG -Dkafka.client.tag=\$KAFKA_CLIENT_TAG package > /tmp/result.log 2>&1
     if [ \$? != 0 ]
     then
         logerror "❌ failed to build java component $component"
@@ -19415,7 +19417,7 @@ for component in $custom_smt_name
 do
     set +e
     log "🏗 Building jar for \${component}"
-    docker run -i --rm -e KAFKA_CLIENT_TAG=\$KAFKA_CLIENT_TAG -e TAG=\$TAG_BASE -v "\${DIR}/\${component}":/usr/src/mymaven -v "\$HOME/.m2":/root/.m2 -v "\$PWD/../../scripts/settings.xml:/tmp/settings.xml" -v "\${DIR}/\${component}/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-11-alpine mvn -s /tmp/settings.xml -Dkafka.tag=\$TAG -Dkafka.client.tag=\$KAFKA_CLIENT_TAG package > /tmp/result.log 2>&1
+    docker run -i --rm -e KAFKA_CLIENT_TAG=\$KAFKA_CLIENT_TAG -e TAG=\$TAG_BASE -v "\${DIR}/\${component}":/usr/src/mymaven -v "\$HOME/.m2":/root/.m2 -v "\$PWD/../../scripts/settings.xml:/tmp/settings.xml" -v "\${DIR}/\${component}/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-11 mvn -s /tmp/settings.xml -Dkafka.tag=\$TAG -Dkafka.client.tag=\$KAFKA_CLIENT_TAG package > /tmp/result.log 2>&1
     if [ \$? != 0 ]
     then
         logerror "❌ failed to build java component $component"
@@ -20555,7 +20557,7 @@ EOF
 
   set +e
   log "🔮 Calling derive-schema maven plugin (see https://docs.confluent.io/platform/current/schema-registry/develop/maven-plugin.html#schema-registry-derive-schema)"
-  docker run -i --rm -v "${tmp_dir}":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-11-alpine mvn -s /tmp/settings.xml io.confluent:kafka-schema-registry-maven-plugin:derive-schema > /tmp/result.log 2>&1
+  docker run -i --rm -v "${tmp_dir}":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-11 mvn -s /tmp/settings.xml io.confluent:kafka-schema-registry-maven-plugin:derive-schema > /tmp/result.log 2>&1
   if [ $? != 0 ]
   then
       logerror "❌ error while calling derive-schema"
@@ -23797,7 +23799,7 @@ playground_topic_produce_command() {
           exit 1
       fi
       log "🏗 Building jar for schema-validator"
-      docker run -i --rm -e TAG=$tag -v "${root_folder}/scripts/cli/src/schema-validator":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -v "${root_folder}/scripts/cli/src/schema-validator/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-11-alpine mvn -s /tmp/settings.xml -Dkafka.tag=$tag package > /tmp/result.log 2>&1
+      docker run -i --rm -e TAG=$tag -v "${root_folder}/scripts/cli/src/schema-validator":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -v "${root_folder}/scripts/cli/src/schema-validator/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-11 mvn -s /tmp/settings.xml -Dkafka.tag=$tag package > /tmp/result.log 2>&1
       if [ $? != 0 ]
       then
           logerror "❌ failed to build java component schema-validator"
@@ -24881,7 +24883,7 @@ playground_connector_plugin_sourcecode_command() {
   sourcecode_url=$(echo "$output" | cut -d "|" -f 2)
   if [ "$sourcecode_url" == "null" ] || [ "$sourcecode_url" == "" ]
   then
-      logerror "❌ could not found sourcecode url for plugin $connector_plugin. It is probably proprietary"
+      logwarn "🤷‍♂️ could not found sourcecode url for plugin $connector_plugin. It is probably proprietary"
       if [[ "$sourcecode_url" == *"confluentinc"* ]]
       then
           if [ $is_confluent_employee -eq 1 ]
@@ -25007,12 +25009,26 @@ playground_connector_plugin_sourcecode_command() {
     esac
   }
 
+  function check_if_compile()
+  {
+    if [ ! -z "$GITHUB_RUN_NUMBER" ]
+    then
+        recompile="0"
+        # running with github actions, continue
+        return
+    fi
+    read -p "👷 do you want to compile anyway (y/n)?" choice
+    case "$choice" in
+    y|Y ) recompile="1";;
+    n|N ) recompile="0";;
+    * ) logwarn "invalid response <$choice>! Please enter y or n."; check_if_compile;;
+    esac
+  }
+
   function check_if_delete_folder()
   {
       if [ ! -z "$GITHUB_RUN_NUMBER" ]
       then
-          # running with github actions, delete
-          rm -rf "${repo_folder}"
           return
       fi
 
@@ -25115,6 +25131,10 @@ playground_connector_plugin_sourcecode_command() {
           then
               # specific case
               repo_folder="${repo_folder}/kafka-connect-couchbase"
+          elif [[ "${repo_name}" == "debezium-v2-private" ]]
+          then
+              # specific case
+              repo_folder="${repo_folder}/debezium"
           elif [[ "${repo_name}" == "kafka-connect-redis-private" ]]
           then
               # specific case
@@ -25198,6 +25218,10 @@ playground_connector_plugin_sourcecode_command() {
                   then
                       compile_jdk_version=11
                       log "⚠️  detected maven compiler version '$chosen' from pom.xml, but 8 is too old, forcing --compile-jdk-version to $compile_jdk_version"
+                  elif [ "$chosen" == "12" ]
+                  then
+                      compile_jdk_version=11
+                      log "⚠️  detected maven compiler version '$chosen' from pom.xml, but 12 is not supported, forcing --compile-jdk-version to $compile_jdk_version"
                   elif [ "$chosen" == "\${java.version}" ]
                   then
                       compile_jdk_version=11
@@ -25208,9 +25232,16 @@ playground_connector_plugin_sourcecode_command() {
               fi
           fi
 
-          if [ -z "$compile_jdk_version" ]; then
-              compile_jdk_version=11
-              log "⚠️  could not detect maven compiler version in pom.xml, defaulting to --compile-jdk-version $compile_jdk_version"
+          if [ -z "$compile_jdk_version" ]
+          then
+              if [[ "${repo_name}" == *"kafka-connect-salesforce" ]]
+              then
+                  compile_jdk_version=17
+                  log "⚠️  kafka-connect-salesforce requires Jdk 17, forcing --compile-jdk-version to $compile_jdk_version"
+              else
+                  compile_jdk_version=11
+                  log "🤷‍♂️ could not detect maven compiler version in pom.xml, defaulting to --compile-jdk-version $compile_jdk_version"
+              fi
           fi
       fi
 
@@ -25226,7 +25257,9 @@ playground_connector_plugin_sourcecode_command() {
                   exit 1
               fi
 
-              check_if_call_maven_login
+              # check_if_call_maven_login
+              log "🛂 execute maven-login"
+              source $HOME/.cc-dotfiles/caas.sh && code_artifact::maven_login -f;
 
               mvn_settings_file="/root/.m2/settings.xml"
           fi
@@ -25238,29 +25271,57 @@ playground_connector_plugin_sourcecode_command() {
       # echo ""
       # check_if_ready_to_continue
 
-      # --- 3. Compile with Maven ---
-      file_output="${repo_folder}/playground-compilation-$repo_name.log"
-      log "🏗  building with maven ${repo_folder}...it can take a while..⏳"
-      log "🏗  use --compile-verbose to see full output. compilation logs are also present in ${file_output}"
-      set +e
+      # Display each zip file
+      found=0
+      # declare -a array_zip_file_list=()
+      for zip_file in $(find "${repo_folder}" -type f -name "*.zip" | sort)
+      do
+          if [ -f "$zip_file" ]
+          then
+              found=1
+              log "📄 zip file $zip_file already present"
+          fi
+      done
 
-      if [[ -n "$verbose" ]]
+      recompile=1
+      if [ $found == 1 ]
       then
-          log "🐞 --compile-verbose is set, showing full output of compilation:"
-          docker run -i --rm -v "${repo_folder}":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-${compile_jdk_version}-alpine mvn -s $mvn_settings_file -Dquick -Dcheckstyle.skip -DskipTests -Dlicense.skip=true -DskipITs -Dskip.unit.tests=true clean package 2>&1 | tee "$file_output"
-          ret=${PIPESTATUS[0]}
+          log "some zip files are already present, do you want to recompile ?"
+          echo ""
+
+          check_if_compile
+      fi
+
+      if [ $recompile == 1 ]
+      then
+
+          # --- 3. Compile with Maven ---
+          file_output="${repo_folder}/playground-compilation-$repo_name.log"
+          log "🏗  building with maven ${repo_folder}...it can take a while..⏳"
+          log "🏗  use --compile-verbose to see full output. compilation logs are also present in ${file_output}"
+          set +e
+
+          if [[ -n "$verbose" ]]
+          then
+              log "🐞 --compile-verbose is set, showing full output of compilation:"
+              docker run -i --rm -v "${repo_folder}":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-${compile_jdk_version} mvn -s $mvn_settings_file -Dquick -Dcheckstyle.skip -DskipTests -Dlicense.skip=true -DskipITs -Dskip.unit.tests=true clean package 2>&1 | tee "$file_output"
+              ret=${PIPESTATUS[0]}
+          else
+              docker run -i --rm -v "${repo_folder}":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-${compile_jdk_version} mvn -s $mvn_settings_file -Dquick -Dcheckstyle.skip -DskipTests -Dlicense.skip=true -DskipITs -Dskip.unit.tests=true clean package > "$file_output" 2>&1
+              ret=$?
+          fi
+          if [ $ret != 0 ]
+          then
+              logerror "❌ failed to build ${repo_folder}, check the logs at ${file_output}"
+              exit 1
+          fi
+          set +e
+
+          log "👌 build complete! zip artifacts found are:"
       else
-          docker run -i --rm -v "${repo_folder}":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -w /usr/src/mymaven maven:3.9.11-eclipse-temurin-${compile_jdk_version}-alpine mvn -s $mvn_settings_file -Dquick -Dcheckstyle.skip -DskipTests -Dlicense.skip=true -DskipITs -Dskip.unit.tests=true clean package > "$file_output" 2>&1
-          ret=$?
+          log "👌 zip artifacts found are:"
       fi
-      if [ $ret != 0 ]
-      then
-          logerror "❌ failed to build ${repo_folder}, check the logs at ${file_output}"
-          exit 1
-      fi
-      set +e
 
-      log "👌 build complete! zip artifacts found are:"
       find "${repo_folder}" -type f -name "*.zip" | sort
 
       echo ""
@@ -25295,7 +25356,7 @@ playground_connector_plugin_sourcecode_command() {
 
       if [ $found == 0 ]
       then
-          logwarn "❌ no zip file in '${repo_folder}', that project is probably packaging releases in different way"
+          logwarn "🤷‍♂️ no zip file in '${repo_folder}', that project is probably packaging releases in different way"
       #else
           # array_declaration=$(declare -p array_zip_file_list)
           # encoded_array=$(echo "$array_declaration" | base64)
@@ -25423,7 +25484,7 @@ playground_connector_plugin_sourcecode_command() {
       fi
   fi
 
-  maybe_tag_prefix=""
+  maybe_tag_prefix="v"
   maybe_tag_suffix=""
   if [[ "$sourcecode_url" == *"confluentinc"* ]]
   then
@@ -25435,6 +25496,10 @@ playground_connector_plugin_sourcecode_command() {
       then
           # specific case
           maybe_tag_prefix=""
+      elif [[ "$sourcecode_url" == *"kafka-connect-spooldir" ]]
+      then
+          # specific case
+          maybe_tag_prefix="kafka-connect-spooldir-"
       else
           # confluent use v prefix for tags example v1.5.0
           maybe_tag_prefix="v"
@@ -25444,6 +25509,12 @@ playground_connector_plugin_sourcecode_command() {
       # debezium use v prefix for tags example 1.5.0
       maybe_tag_prefix="v"
       maybe_tag_suffix=".Final"
+  elif [[ "$sourcecode_url" == *"kafka-connect-transform-tojsonstring"* ]] || [[ "$sourcecode_url" == *"kafka-connect-zeebe"* ]] || [[ "$sourcecode_url" == *"kafka-connect-shell-source"* ]]
+  then
+      maybe_tag_prefix=""
+  elif [[ "$sourcecode_url" == *"kafka-connect-mongodb"* ]]
+  then
+      maybe_tag_prefix="r"
   fi
 
   if [ "$comparison_mode_versions" != "" ]
