wip Add playground tcp-proxy command to easily simulate tcp connection problems #5662

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -75,6 +75,10 @@ playground_usage() {
   printf "  %s   🔏 Set subject-level mode\n" "$(green "schema set-mode")                  "
   printf "  %s   🧟 Delete schema\n" "$(green "schema delete")                    "
   echo
+  printf "%s\n" "$(bold "TCP Proxy commands:")"
+  printf "  %s   🏚 TCP Proxy commands\n" "$(green "tcp-proxy")                        "
+  printf "  %s   💗 Start the TCP proxy\n" "$(green "tcp-proxy start")                  "
+  echo
   printf "%s\n" "$(bold "Debug commands:")"
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                            "
   printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "debug enable-remote-debugging")    "
@@ -2660,6 +2664,87 @@ playground_schema_delete_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_tcp_proxy_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground tcp-proxy\n"
+    echo
+
+    printf "  🏚 TCP Proxy commands\n  \n  emicklei/zazkia (https://github.com/emicklei/zazkia) is a nice tool to\n  simulate a TCP connection issues (reset,delay,throttle,corrupt)\n"
+    echo
+
+  else
+    printf "playground tcp-proxy - 🏚 TCP Proxy commands\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tcp-proxy COMMAND\n"
+  printf "  playground tcp-proxy [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "$(bold "== Commands ==")"
+  printf "  %s   💗 Start the TCP proxy\n" "$(green "start")"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_tcp_proxy_start_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground tcp-proxy start - 💗 Start the TCP proxy\n"
+    echo
+
+  else
+    printf "playground tcp-proxy start - 💗 Start the TCP proxy\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tcp-proxy start [OPTIONS]\n"
+  printf "  playground tcp-proxy start --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--hostname HOSTNAME (required)")"
+    printf "    Hostname used by the tcp proxy to forward request\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--port PORT (required)")"
+    printf "    Port used by the tcp proxy to forward request\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground tcp-proxy start\n"
     echo
 
   fi
@@ -17222,6 +17307,66 @@ playground_schema_delete_command() {
 }
 
 # :command.function
+playground_tcp_proxy_start_command() {
+  # src/commands/tcp-proxy/start.sh
+  hostname="${args[--hostname]}"
+  port="${args[--port]}"
+
+  docker_command=$(playground state get run.docker_command)
+  if [ "$docker_command" == "" ]
+  then
+    logerror "docker_command retrieved from $root_folder/playground.ini is empty !"
+    exit 1
+  fi
+
+  mkdir -p /tmp/zazkia
+    cat << EOF > /tmp/zazkia/zazkia-routes.json
+[
+    {
+        "label": "tcp-proxy",
+        "service-hostname": "$hostname",
+        "service-port": $port,
+        "listen-port": 49998,
+        "transport": {
+            "accept-connections": true,
+            "throttle-service-response": 0,
+            "delay-service-response": 0,
+            "break-service-response": 0,
+            "service-response-corrupt-method": "",
+            "sending-to-client": true,
+            "receiving-from-client": true,
+            "sending-to-service": true,
+            "receiving-from-service": true,
+            "verbose": true
+        }
+    }
+]
+EOF
+
+    cat << EOF > /tmp/docker-compose.override.zazkia.yml
+services:
+  zazkia:
+    hostname: zazkia
+    container_name: zazkia
+    image: emicklei/zazkia
+    ports:
+      - "9191:9191"
+    volumes:
+      - /tmp/zazkia:/data
+    environment:
+      DUMMY: $RANDOM
+EOF
+
+  echo "$docker_command" > /tmp/playground-command-zazkia
+  sed -i -E -e "s|up -d --quiet-pull|-f /tmp/docker-compose.override.zazkia.yml up -d --quiet-pull|g" /tmp/playground-command-zazkia
+  log "💫 adding container zazkia listening on port 49998"
+  bash /tmp/playground-command-zazkia
+
+  log "💗 you can now use tcp-proxy using <zazkia:49998>"
+  log "zazkia UI is available on http://localhost:9191"
+}
+
+# :command.function
 playground_debug_enable_remote_debugging_command() {
   # src/commands/debug/enable-remote-debugging.sh
   IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
@@ -23305,6 +23450,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    tcp-proxy)
+      action="tcp-proxy"
+      shift
+      playground_tcp_proxy_parse_requirements "$@"
+      shift $#
+      ;;
+
     debug)
       action="debug"
       shift
@@ -27846,6 +27998,161 @@ playground_schema_delete_parse_requirements() {
   filter_error=$(filter_schema_registry_running)
   if [[ -n $filter_error ]]; then
     echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_tcp_proxy_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_tcp_proxy_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    start)
+      action="start"
+      shift
+      playground_tcp_proxy_start_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      playground_tcp_proxy_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_tcp_proxy_start_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_tcp_proxy_start_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tcp-proxy start"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --hostname)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--hostname']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--hostname requires an argument: --hostname HOSTNAME" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --port)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--port']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--port requires an argument: --port PORT" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--hostname']+x} ]]; then
+    printf "missing required flag: --hostname HOSTNAME\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['--port']+x} ]]; then
+    printf "missing required flag: --port PORT\n" >&2
+    exit 1
+  fi
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--port'] && -n $(validate_integer "${args['--port']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--port PORT" "$(validate_integer "${args['--port']:-}")" >&2
     exit 1
   fi
 
@@ -33607,6 +33914,8 @@ run() {
     "schema get-mode") playground_schema_get_mode_command ;;
     "schema set-mode") playground_schema_set_mode_command ;;
     "schema delete") playground_schema_delete_command ;;
+    "tcp-proxy") playground_tcp_proxy_command ;;
+    "tcp-proxy start") playground_tcp_proxy_start_command ;;
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
     "debug testssl") playground_debug_testssl_command ;;
