🧠 add playground schema derive-schema command #6263

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -70,6 +70,7 @@ playground_usage() {
   printf "  %s   🔏 Set subject-level mode\n" "$(green "schema set-mode")                           "
   printf "  %s   🧽 Set normalize at schema registry level\n" "$(green "schema set-normalize")                      "
   printf "  %s   🧟 Delete schema\n" "$(green "schema delete")                             "
+  printf "  %s   🔮 Derive a schema based on payload. \n" "$(green "schema derive-schema")                      "
   echo
   printf "%s\n" "$(bold "TCP Proxy commands:")"
   printf "  %s   🏚 Zazkia TCP Proxy commands\n" "$(green "tcp-proxy")                                 "
@@ -2314,6 +2315,7 @@ playground_schema_usage() {
   printf "  %s   🔏 Set subject-level mode\n" "$(green "set-mode")         "
   printf "  %s   🧽 Set normalize at schema registry level\n" "$(green "set-normalize")    "
   printf "  %s   🧟 Delete schema\n" "$(green "delete")           "
+  printf "  %s   🔮 Derive a schema based on payload. \n" "$(green "derive-schema")    "
   echo
 
   # :command.long_usage
@@ -2663,6 +2665,46 @@ playground_schema_delete_usage() {
     echo
 
   fi
+}
+
+# :command.usage
+playground_schema_derive_schema_usage() {
+  printf "playground schema derive-schema - 🔮 Derive a schema based on payload. \n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground schema derive-schema [OPTIONS]\n"
+  printf "  playground schema derive-schema --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--payload PAYLOAD")"
+    printf "    📦 Payload to derive schema from\n"
+    printf "    %s\n" "Default: -"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--schema-type SCHEMA-TYPE")"
+    printf "    🧩 Schema Registry schema \"type\":\n    \n    - AVRO\n    - JSON (json schema)\n    - PROTOBUF\n    \n    Default is AVRO\n"
+    printf "    %s\n" "Allowed: AVRO, JSON, PROTOBUF"
+    printf "    %s\n" "Default: AVRO"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground schema derive-schema << EOF\n{\"name\": \"Foo\", \"Age\": {\"int\": 12}}\n{\"name\": \"Bar\", \"Age\": {\"string\": \"12\"}}\n{\"sport\": \"Football\"}\n{\"_id\":{\"key\":\"AA\"},\"duration\":{\"numberInt\":\"240\"},\"employeeNumber\":{\"numberInt\":\"12345\"},\"isActive\":\"Y\",\"plannedAbsenceKey\":\"AA\",\"startTimeMin\":{\"numberLong\":\"11599920\"}}\nEOF\n  \n  playground schema derive-schema --payload '{\"sport\": \"Football\"}'\n  --schema-type PROTOBUF\n"
+echo
+
+fi
 }
 
 # :command.usage
@@ -18592,6 +18634,102 @@ playground_schema_delete_command() {
 }
 
 # :command.function
+playground_schema_derive_schema_command() {
+  # src/commands/schema/derive-schema.sh
+  schema_type="${args[--schema-type]}"
+  payload="${args[--payload]}"
+  verbose="${args[--verbose]}"
+
+  tmp_dir=$(mktemp -d -t pg-XXXXXXXXXX)
+  if [ -z "$PG_VERBOSE_MODE" ]
+  then
+      trap 'rm -rf $tmp_dir' EXIT
+  else
+      log "🐛📂 not deleting tmp dir $tmp_dir"
+  fi
+
+  payload_file=$tmp_dir/payload_file
+
+  if [ "$payload" = "-" ]
+  then
+      # stdin
+      if [ -t 0 ]
+      then
+          logerror "❌ stdin is empty you probably forgot to set --payload !"
+          exit 1
+      else
+          payload_content=$(cat "$payload")
+          echo "$payload_content" > $payload_file
+      fi
+  else
+      if [[ $payload == @* ]]
+      then
+          # this is a payload file
+          argument_payload_file=$(echo "$payload" | cut -d "@" -f 2)
+          cp $argument_payload_file $payload_file
+      elif [ -f "$payload" ]
+      then
+          cp $payload $payload_file
+      else
+          payload_content=$payload
+          echo "$payload_content" > $payload_file
+      fi
+  fi
+
+  LATEST_TAG=$(grep "export TAG" $root_folder/scripts/utils.sh | head -1 | cut -d "=" -f 2 | cut -d " " -f 1)
+  if [ -z "$LATEST_TAG" ]
+  then
+      logerror "❌ error while getting default TAG "
+      exit 1
+  fi
+
+  cat << EOF > $tmp_dir/pom.xml
+<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
+
+http://maven.apache.org/xsd/maven-4.0.0.xsd">
+  <modelVersion>4.0.0</modelVersion>
+  <groupId>io.confluent.app</groupId>
+  <artifactId>my-app</artifactId>
+  <version>1</version>
+  <pluginRepositories>
+    <pluginRepository>
+      <id>confluent</id>
+      <url>https://packages.confluent.io/maven/</url>
+    </pluginRepository>
+  </pluginRepositories>
+  <build>
+    <plugins>
+      <plugin>
+        <groupId>io.confluent</groupId>
+        <artifactId>kafka-schema-registry-maven-plugin</artifactId>
+        <version>$LATEST_TAG</version>
+        <configuration>
+          <messagePath>/usr/src/mymaven/payload_file</messagePath>
+          <schemaType>$schema_type</schemaType>
+          <outputPath>/usr/src/mymaven/schema_file</outputPath>
+        </configuration>
+      </plugin>
+    </plugins>
+  </build>
+</project>
+EOF
+
+  set +e
+  log "🔮 Calling derive-schema maven plugin (see https://docs.confluent.io/platform/current/schema-registry/develop/maven-plugin.html#schema-registry-derive-schema)"
+  docker run -i --rm -v "${tmp_dir}":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -w /usr/src/mymaven maven:3.6.1-jdk-11 mvn -s /tmp/settings.xml io.confluent:kafka-schema-registry-maven-plugin:derive-schema > /tmp/result.log 2>&1
+  if [ $? != 0 ]
+  then
+      logerror "❌ error while calling derive-schema"
+      tail -500 /tmp/result.log
+      exit 1
+  fi
+
+  set -e
+  log "🔮 Schema file generated at $tmp_dir/schema_file"
+  cat $tmp_dir/schema_file | jq -r '.schemas[]|del(.messagesMatched)|.schema'
+}
+
+# :command.function
 playground_tcp_proxy_start_command() {
   # src/commands/tcp-proxy/start.sh
   hostname="${args[--hostname]}"
@@ -30503,6 +30641,13 @@ playground_schema_parse_requirements() {
       shift $#
       ;;
 
+    derive-schema)
+      action="derive-schema"
+      shift
+      playground_schema_derive_schema_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_schema_usage >&2
@@ -31416,6 +31561,95 @@ playground_schema_delete_parse_requirements() {
   fi
 
   filter_error=$(filter_schema_registry_running)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_schema_derive_schema_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_schema_derive_schema_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="schema derive-schema"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --payload)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--payload']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--payload requires an argument: --payload PAYLOAD" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --schema-type)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--schema-type']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--schema-type requires an argument: --schema-type SCHEMA-TYPE" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--payload']:-} ]] || args['--payload']="-"
+  [[ -n ${args['--schema-type']:-} ]] || args['--schema-type']="AVRO"
+
+  # :command.whitelist_filter
+  if [[ ${args['--schema-type']:-} ]] && [[ ! ${args['--schema-type']:-} =~ ^(AVRO|JSON|PROTOBUF)$ ]]; then
+    printf "%s\n" "--schema-type must be one of: AVRO, JSON, PROTOBUF" >&2
+    exit 1
+  fi
+
+  # :command.user_filter
+  filter_error=$(filter_not_mdc_environment)
   if [[ -n $filter_error ]]; then
     echo "$filter_error" >&2
     exit 1
@@ -39975,6 +40209,7 @@ run() {
     "schema set-mode") playground_schema_set_mode_command ;;
     "schema set-normalize") playground_schema_set_normalize_command ;;
     "schema delete") playground_schema_delete_command ;;
+    "schema derive-schema") playground_schema_derive_schema_command ;;
     "tcp-proxy") playground_tcp_proxy_command ;;
     "tcp-proxy start") playground_tcp_proxy_start_command ;;
     "tcp-proxy get-connections") playground_tcp_proxy_get_connections_command ;;
