🐛 playground run command always succeed even if test fails #6598

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -16286,15 +16286,17 @@ playground_run_command() {
   set -e
   if [ $ret -eq 0 ]
   then
-      log "####################################################"
-      log "✅ RESULT: SUCCESS for $filename ($ELAPSED - $CUMULATED)"
-      log "####################################################"
+    log "####################################################"
+    log "✅ RESULT: SUCCESS for $filename ($ELAPSED - $CUMULATED)"
+    log "####################################################"
   else
-      logerror "####################################################"
-      logerror "🔥 RESULT: FAILURE for $filename ($ELAPSED - $CUMULATED)"
-      logerror "####################################################"
+    logerror "####################################################"
+    logerror "🔥 RESULT: FAILURE for $filename ($ELAPSED - $CUMULATED)"
+    logerror "####################################################"
 
-      display_docker_container_error_log
+    display_docker_container_error_log
+
+    exit 1
   fi
   check_for_ec2_instance_running
 
