add get-docker-compose command

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -47,6 +47,7 @@ playground_usage() {
   printf "  %s   🛠  Bootstrap reproduction model\n" "$(green "bootstrap-reproduction-model")     "
   echo
   printf "%s\n" "$(bold "Kafka commands:")"
+  printf "  %s   🐋 Get docker-compose\n" "$(green "get-docker-compose")               "
   printf "  %s   📝 Get properties file from a container\n" "$(green "get-properties")                   "
   printf "  %s   🔰 Get all schemas versions for all subjects\n" "$(green "get-all-schemas")                  "
   printf "  %s   🔢 Get JMX metrics from a component\n" "$(green "get-jmx-metrics")                  "
@@ -1047,6 +1048,35 @@ playground_bootstrap_reproduction_model_usage() {
     printf "  playground bootstrap-reproduction-model -f hdfs2<tab> -d \"testing with 2\n  protobuf producers\" --producer protobuf --nb-producers 2\n"
     printf "  playground bootstrap-reproduction-model -f hdfs2<tab> -d \"testing custom smt\"\n  --custom-smt\n"
     printf "  playground bootstrap-reproduction-model -f debeziumpostgres<tab> -d \"create\n  pipeline\" --pipeline jdbcsink<tab>\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_get_docker_compose_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground get-docker-compose - 🐋 Get docker-compose\n"
+    echo
+
+  else
+    printf "playground get-docker-compose - 🐋 Get docker-compose\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground get-docker-compose\n"
+  printf "  playground get-docker-compose --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -9187,6 +9217,26 @@ playground_bootstrap_reproduction_model_command() {
 }
 
 # :command.function
+playground_get_docker_compose_command() {
+  # src/get_docker_compose_command.sh
+  # keep CONNECT TAG and ORACLE_IMAGE
+  export CONNECT_TAG=$(docker inspect -f '{{.Config.Image}}' connect | cut -d ":" -f 2)
+  export ORACLE_IMAGE=$(docker inspect -f '{{.Config.Image}}' oracle | cut -d ":" -f 2)
+
+  if [ ! -f /tmp/playground-command ]
+  then
+    logerror "File containing restart command /tmp/playground-command does not exist!"
+    exit 1
+  fi
+
+  sed -e "s|up -d|config|g" \
+      /tmp/playground-command > /tmp/playground-command-config
+
+  bash /tmp/playground-command-config
+
+}
+
+# :command.function
 playground_get_properties_command() {
   # src/get_properties_command.sh
   container="${args[--container]}"
@@ -11641,6 +11691,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    get-docker-compose)
+      action="get-docker-compose"
+      shift
+      playground_get_docker_compose_parse_requirements "$@"
+      shift $#
+      ;;
+
     get-properties)
       action="get-properties"
       shift
@@ -13610,6 +13667,50 @@ playground_bootstrap_reproduction_model_parse_requirements() {
     printf "%s\n" "--producer must be one of: none, avro, avro-with-key, protobuf, protobuf-with-key, json-schema, json-schema-with-key" >&2
     exit 1
   fi
+
+}
+
+# :command.parse_requirements
+playground_get_docker_compose_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_get_docker_compose_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="get-docker-compose"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
 
 }
 
@@ -17447,6 +17548,7 @@ run() {
     "open") playground_open_command ;;
     "stop") playground_stop_command ;;
     "bootstrap-reproduction-model") playground_bootstrap_reproduction_model_command ;;
+    "get-docker-compose") playground_get_docker_compose_command ;;
     "get-properties") playground_get_properties_command ;;
     "get-all-schemas") playground_get_all_schemas_command ;;
     "debug") playground_debug_command ;;
