🧠 Add playground schema validate-new-schemas #7652

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -86,6 +86,7 @@ playground_usage() {
   printf "  %s   🔏 Get subject-level mode\n" "$(green "schema get-mode")                           "
   printf "  %s   🔏 Set subject-level mode\n" "$(green "schema set-mode")                           "
   printf "  %s   🧽 Set normalize at schema registry level\n" "$(green "schema set-normalize")                      "
+  printf "  %s   🩺 Validate new schemas (default is true since CP 8.2.0)\n" "$(green "schema validate-new-schemas")               "
   printf "  %s   🧟 Delete schema\n" "$(green "schema delete")                             "
   printf "  %s   🪄 Derive a schema based on payload\n" "$(green "schema derive-schema")                      "
   echo
@@ -3126,15 +3127,16 @@ playground_schema_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Schema commands:")"
-  printf "  %s   🔰 Get all schemas versions for specified subject (if --subject is not specified, all subjects will be used)\n" "$(green "get")              "
-  printf "  %s   ⏺️ Register a schema in specified subject\n" "$(green "register")         "
-  printf "  %s   🛡️ Get subject-level compatibility\n" "$(green "get-compatibility")"
-  printf "  %s   🛡️ Set subject-level compatibility\n" "$(green "set-compatibility")"
-  printf "  %s   🔏 Get subject-level mode\n" "$(green "get-mode")         "
-  printf "  %s   🔏 Set subject-level mode\n" "$(green "set-mode")         "
-  printf "  %s   🧽 Set normalize at schema registry level\n" "$(green "set-normalize")    "
-  printf "  %s   🧟 Delete schema\n" "$(green "delete")           "
-  printf "  %s   🪄 Derive a schema based on payload\n" "$(green "derive-schema")    "
+  printf "  %s   🔰 Get all schemas versions for specified subject (if --subject is not specified, all subjects will be used)\n" "$(green "get")                 "
+  printf "  %s   ⏺️ Register a schema in specified subject\n" "$(green "register")            "
+  printf "  %s   🛡️ Get subject-level compatibility\n" "$(green "get-compatibility")   "
+  printf "  %s   🛡️ Set subject-level compatibility\n" "$(green "set-compatibility")   "
+  printf "  %s   🔏 Get subject-level mode\n" "$(green "get-mode")            "
+  printf "  %s   🔏 Set subject-level mode\n" "$(green "set-mode")            "
+  printf "  %s   🧽 Set normalize at schema registry level\n" "$(green "set-normalize")       "
+  printf "  %s   🩺 Validate new schemas (default is true since CP 8.2.0)\n" "$(green "validate-new-schemas")"
+  printf "  %s   🧟 Delete schema\n" "$(green "delete")              "
+  printf "  %s   🪄 Derive a schema based on payload\n" "$(green "derive-schema")       "
   echo
 
   # :command.long_usage
@@ -3418,6 +3420,45 @@ playground_schema_set_normalize_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground schema set-normalize [OPTIONS]\n"
   printf "  playground schema set-normalize --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--verbose, -v")"
+    printf "    🐞 Show command being ran.\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--value VALUE (required)")"
+    printf "    true or false\n"
+    printf "    %s\n" "Allowed: true, false"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_schema_validate_new_schemas_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground schema validate-new-schemas\n\n"
+    printf "  🩺 Validate new schemas (default is true since CP 8.2.0)\n  \n  See\n  https://docs.confluent.io/cloud/current/sr/fundamentals/serdes-develop/index.html#supported-formats:~:text=Strict%%20namespace%%20validation%%20with%%20Avro%%20version%%201.12\n\n"
+  else
+    printf "playground schema validate-new-schemas - 🩺 Validate new schemas (default is true since CP 8.2.0)\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground schema validate-new-schemas [OPTIONS]\n"
+  printf "  playground schema validate-new-schemas --help | -h\n"
   echo
 
   # :command.long_usage
@@ -21945,6 +21986,43 @@ playground_schema_set_normalize_command() {
 }
 
 # :command.function
+playground_schema_validate_new_schemas_command() {
+
+  # src/commands/schema/validate-new-schemas.sh
+  value="${args[--value]}"
+  verbose="${args[--verbose]}"
+
+  get_sr_url_and_security
+
+  log "🩺 Set validateNewSchemas to $value at schema registry level"
+  if [[ -n "$verbose" ]]
+  then
+      log "🐞 curl command used"
+      echo "curl $sr_security -s -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data "{\"validateNewSchemas\": \"${value}\"}" "${sr_url}/config""
+  fi
+  curl_output=$(curl $sr_security -s -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data "{\"validateNewSchemas\": \"${value}\"}" "${sr_url}/config" | jq .)
+  ret=$?
+  if [ $ret -eq 0 ]
+  then
+      if echo "$curl_output" | jq '. | has("error_code")' 2> /dev/null | grep -q true
+
+      then
+          error_code=$(echo "$curl_output" | jq -r .error_code)
+          message=$(echo "$curl_output" | jq -r .message)
+          logerror "Command failed with error code $error_code"
+          logerror "$message"
+          exit 1
+      else
+          validate_new_schemas=$(echo "$curl_output" | jq -r .validateNewSchemas)
+          echo "$validate_new_schemas"
+      fi
+  else
+      logerror "❌ curl request failed with error code $ret!"
+      exit 1
+  fi
+}
+
+# :command.function
 playground_schema_delete_command() {
 
   # src/commands/schema/delete.sh
@@ -38749,6 +38827,13 @@ playground_schema_parse_requirements() {
       shift $#
       ;;
 
+    validate-new-schemas)
+      action="validate-new-schemas"
+      shift
+      playground_schema_validate_new_schemas_parse_requirements "$@"
+      shift $#
+      ;;
+
     delete)
       action="delete"
       shift
@@ -39509,6 +39594,99 @@ playground_schema_set_normalize_parse_requirements() {
 
   # :command.command_filter
   action="schema set-normalize"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --verbose | -v)
+
+        # :flag.case_no_arg
+        args['--verbose']=1
+        shift
+        ;;
+
+      # :flag.case
+      --value)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--value']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--value requires an argument: --value VALUE" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--value']+x} ]]; then
+    printf "missing required flag: --value VALUE\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ ${args['--value']:-} ]] && [[ ! ${args['--value']:-} =~ ^(true|false)$ ]]; then
+    printf "%s\n" "--value must be one of: true, false" >&2
+    exit 1
+  fi
+
+  # :command.user_filter
+  filter_error=$(filter_not_mdc_environment)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+  filter_error=$(filter_schema_registry_running)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_schema_validate_new_schemas_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_schema_validate_new_schemas_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="schema validate-new-schemas"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -50524,6 +50702,7 @@ run() {
     "schema get-mode") playground_schema_get_mode_command ;;
     "schema set-mode") playground_schema_set_mode_command ;;
     "schema set-normalize") playground_schema_set_normalize_command ;;
+    "schema validate-new-schemas") playground_schema_validate_new_schemas_command ;;
     "schema delete") playground_schema_delete_command ;;
     "schema derive-schema") playground_schema_derive_schema_command ;;
     "tcp-proxy") playground_tcp_proxy_command ;;
