wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -8616,6 +8616,8 @@ function wait_for_ec2_instance_to_be_running () {
   do
     sleep 10
     playground ec2 status --instance $instance > /tmp/out.txt 2>&1
+    status=$(cat /tmp/out.txt)
+    log "⌛ current status: $status"
     cur_wait=$(( cur_wait+10 ))
     if [[ "$cur_wait" -gt "$max_wait" ]]
     then
@@ -8623,7 +8625,7 @@ function wait_for_ec2_instance_to_be_running () {
       return 1
     fi
   done
-  log "ec2 instance $instance is running"
+  log "🟢 ec2 instance $instance is running"
 }
 
 # src/lib/colors.sh
@@ -9467,6 +9469,16 @@ function aws() {
         log '$HOME/.aws/credentials does not exist.'
       fi
       return 1
+    fi
+
+    if [ -z "$AWS_REGION" ]
+    then
+        AWS_REGION=$(aws configure get region | tr '\r' '\n')
+        if [ "$AWS_REGION" == "" ]
+        then
+            logerror "ERROR: either the file $HOME/.aws/config is not present or environment variables AWS_REGION is not set!"
+            exit 1
+        fi
     fi
 
     if [ ! -f $HOME/.aws/config ]
@@ -25343,7 +25355,14 @@ playground_ec2_create_command() {
 
   wait_for_ec2_instance_to_be_running "$name"
 
-  playground ec2 open --instance "$(playground ec2 status --instance $name --all)"
+  instance="$(playground ec2 status --instance "$name" --all)"
+  if [ $? != 0 ] || [ -z "$instance" ]
+  then
+      logerror "❌ failed to get instance with name $name"
+      playground ec2 status --instance "$name" --all
+      exit 1
+  fi
+  playground ec2 open --instance "$instance"
 }
 
 # :command.function
