Added generic flag --output-level

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -151,6 +151,12 @@ playground_usage() {
     printf "    🐛 set verbose output (set -x)\n    \n    ❗ it can print sensitive information ❗\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--output-level, -o LEVEL")"
+    printf "    ❕Log level used by all commands\n    \n    Default is INFO (all INFO, WARN and ERROR will be printed in command output)\n"
+    printf "    Allowed: INFO, WARN, ERROR\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -6864,6 +6870,15 @@ function verbose_end () {
 }
 
 function log() {
+  if [ ! -z $PG_LOG_LEVEL ]
+  then
+    case "${PG_LOG_LEVEL}" in
+      WARN|ERROR)
+        return
+      ;;
+    esac
+  fi
+
   verbose_begin
   YELLOW='\033[0;33m'
   NC='\033[0m' # No Color
@@ -6880,6 +6895,14 @@ function logerror() {
 }
 
 function logwarn() {
+  if [ ! -z $PG_LOG_LEVEL ]
+  then
+    case "${PG_LOG_LEVEL}" in
+      INFO)
+        return
+      ;;
+    esac
+  fi
   verbose_begin
   PURPLE='\033[0;35m'
   NC='\033[0m' # No Color
@@ -21381,6 +21404,20 @@ parse_requirements() {
         shift
         ;;
 
+      # :flag.case
+      --output-level | -o)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--output-level']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--output-level requires an argument: --output-level, -o LEVEL" >&2
+          exit 1
+        fi
+        ;;
+
       *)
         break
         ;;
@@ -21737,6 +21774,12 @@ parse_requirements() {
 
     esac
   done
+
+  # :command.whitelist_filter
+  if [[ ${args['--output-level']:-} ]] && [[ ! ${args['--output-level']:-} =~ ^(INFO|WARN|ERROR)$ ]]; then
+    printf "%s\n" "--output-level must be one of: INFO, WARN, ERROR" >&2
+    exit 1
+  fi
 
   # :command.user_filter
   filter_error=$(filter_docker_running)
@@ -31419,6 +31462,7 @@ before_hook() {
   root_folder=$(echo ${dir1%/*})
 
   vvv="${args[--vvv]}"
+  level="${args[--output-level]}"
 
   if [[ -n "$vvv" ]]
   then
@@ -31426,6 +31470,12 @@ before_hook() {
       export PS4='\[\033[0;36m\]🐞$(date "+%H:%M:%S")[$(basename $0):${LINENO}] \[\033[0m\]'
       set -x
 
+  fi
+
+  if [[ -n "$level" ]]
+  then
+      export PG_LOG_LEVEL="$level"
+      log "🔖 --output-level is set with $level"
   fi
 }
 
