added --open

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1249,6 +1249,11 @@ playground_get_jmx_metrics_usage() {
     echo
 
     # :flag.usage
+    printf "  %s\n" "$(magenta "--open, -o")"
+    printf "    🔖 Save output to a file and open with text editor set with config.ini\n    (default is code)\n"
+    echo
+
+    # :flag.usage
     printf "  %s\n" "$(magenta "--domain, -d DOMAIN")"
     printf "    Domain name\n"
     echo
@@ -3878,6 +3883,7 @@ function get_jmx_metrics() {
 
   component="$1"
   domains="$2"
+  open="$3"
   if [ "$domains" = "" ]
   then
     # non existing domain: all domains will be in output !
@@ -3922,23 +3928,32 @@ exit
 EOF
   while read line; do echo "get *"  -b $line; done < /tmp/beans.log >> /tmp/commands
 
-  echo "####### domain $domain ########" >> /tmp/jmx_metrics.log
-  docker exec -i $component java -jar $JMXTERM_UBER_JAR  -l localhost:$port -n < /tmp/commands >> /tmp/jmx_metrics.log 2>&1
+  if [[ -n "$open" ]]
+  then
+    echo "####### domain $domain ########" >> /tmp/jmx_metrics.log
+    docker exec -i $component java -jar $JMXTERM_UBER_JAR  -l localhost:$port -n < /tmp/commands >> /tmp/jmx_metrics.log 2>&1
+  else
+    echo "####### domain $domain ########"
+    docker exec -i $component java -jar $JMXTERM_UBER_JAR  -l localhost:$port -n < /tmp/commands 2>&1
+  fi
 done
 
-  if config_has_key "editor"
+  if [[ -n "$open" ]]
   then
-    editor=$(config_get "editor")
-    log "📖 Opening /tmp/jmx_metrics.log using configured editor $editor"
-    $editor /tmp/jmx_metrics.log
-  else
-    if [[ $(type code 2>&1) =~ "not found" ]]
+    if config_has_key "editor"
     then
-      logerror "Could not determine an editor to use as default code is not found - you can change editor by updating config.ini"
-      exit 1
+      editor=$(config_get "editor")
+      log "📖 Opening /tmp/jmx_metrics.log using configured editor $editor"
+      $editor /tmp/jmx_metrics.log
     else
-      log "📖 Opening /tmp/jmx_metrics.log with code (default) - you can change editor by updating config.ini"
-      code /tmp/jmx_metrics.log
+      if [[ $(type code 2>&1) =~ "not found" ]]
+      then
+        logerror "Could not determine an editor to use as default code is not found - you can change editor by updating config.ini"
+        exit 1
+      else
+        log "📖 Opening /tmp/jmx_metrics.log with code (default) - you can change editor by updating config.ini"
+        code /tmp/jmx_metrics.log
+      fi
     fi
   fi
 }
@@ -8440,6 +8455,7 @@ playground_get_jmx_metrics_command() {
 
   component="${args[--component]}"
   domain="${args[--domain]}"
+  open="${args[--open]}"
 
   case "${component}" in
     zookeeper|broker|schema-registry|connect)
@@ -8450,7 +8466,7 @@ playground_get_jmx_metrics_command() {
     ;;
   esac
 
-  get_jmx_metrics "$component" "$domain"
+  get_jmx_metrics "$component" "$domain" "$open"
 }
 
 # :command.function
@@ -11986,6 +12002,14 @@ playground_get_jmx_metrics_parse_requirements() {
           printf "%s\n" "--component requires an argument: --component, -c COMPONENT" >&2
           exit 1
         fi
+        ;;
+
+      # :flag.case
+      --open | -o)
+
+        # :flag.case_no_arg
+        args['--open']=1
+        shift
         ;;
 
       # :flag.case
