wip #5662

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -82,6 +82,10 @@ playground_usage() {
   printf "  %s   ⏲️ Add milliseconds delay to service response.\n" "$(green "tcp-proxy delay")                    "
   printf "  %s   ❌ Close the Zazkia active TCP connections\n" "$(green "tcp-proxy close-connection")         "
   printf "  %s   🙅‍♂️ Change whether new connections can be accepted\n" "$(green "tcp-proxy toggle-accept-connections")"
+  printf "  %s   ✅ Change whether reading data from the client is enabled.\n" "$(green "tcp-proxy toggle-reads-client")      "
+  printf "  %s   ✅ Change whether reading data from the service is enabled.\n" "$(green "tcp-proxy toggle-reads-service")     "
+  printf "  %s   ✅ Change whether writing data to the client is enabled.\n" "$(green "tcp-proxy toggle-writes-client")     "
+  printf "  %s   ✅ Change whether reading data to the service is enabled.\n" "$(green "tcp-proxy toggle-writes-service")    "
   echo
   printf "%s\n" "$(bold "Debug commands:")"
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                              "
@@ -2728,6 +2732,10 @@ playground_tcp_proxy_usage() {
   printf "  %s   ⏲️ Add milliseconds delay to service response.\n" "$(green "delay")                    "
   printf "  %s   ❌ Close the Zazkia active TCP connections\n" "$(green "close-connection")         "
   printf "  %s   🙅‍♂️ Change whether new connections can be accepted\n" "$(green "toggle-accept-connections")"
+  printf "  %s   ✅ Change whether reading data from the client is enabled.\n" "$(green "toggle-reads-client")      "
+  printf "  %s   ✅ Change whether reading data from the service is enabled.\n" "$(green "toggle-reads-service")     "
+  printf "  %s   ✅ Change whether writing data to the client is enabled.\n" "$(green "toggle-writes-client")     "
+  printf "  %s   ✅ Change whether reading data to the service is enabled.\n" "$(green "toggle-writes-service")    "
   echo
 
   # :command.long_usage
@@ -2943,6 +2951,158 @@ playground_tcp_proxy_toggle_accept_connections_usage() {
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_tcp_proxy_toggle_reads_client_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground tcp-proxy toggle-reads-client\n"
+    echo
+
+    printf "  ✅ Change whether reading data from the client is enabled.\n  \n    See diagram in https://github.com/emicklei/zazkia#how-does-it-work- (or\n  locally http://localhost:9191/help.html)\n"
+    echo
+
+  else
+    printf "playground tcp-proxy toggle-reads-client - ✅ Change whether reading data from the client is enabled.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tcp-proxy toggle-reads-client [OPTIONS]\n"
+  printf "  playground tcp-proxy toggle-reads-client --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connection-id CONNECTION-ID")"
+    printf "    🧲 Zazkia TCP connection id\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_tcp_proxy_toggle_reads_service_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground tcp-proxy toggle-reads-service\n"
+    echo
+
+    printf "  ✅ Change whether reading data from the service is enabled.\n  \n    See diagram in https://github.com/emicklei/zazkia#how-does-it-work- (or\n  locally http://localhost:9191/help.html)\n"
+    echo
+
+  else
+    printf "playground tcp-proxy toggle-reads-service - ✅ Change whether reading data from the service is enabled.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tcp-proxy toggle-reads-service [OPTIONS]\n"
+  printf "  playground tcp-proxy toggle-reads-service --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connection-id CONNECTION-ID")"
+    printf "    🧲 Zazkia TCP connection id\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_tcp_proxy_toggle_writes_client_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground tcp-proxy toggle-writes-client\n"
+    echo
+
+    printf "  ✅ Change whether writing data to the client is enabled.\n  \n    See diagram in https://github.com/emicklei/zazkia#how-does-it-work- (or\n  locally http://localhost:9191/help.html)\n"
+    echo
+
+  else
+    printf "playground tcp-proxy toggle-writes-client - ✅ Change whether writing data to the client is enabled.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tcp-proxy toggle-writes-client [OPTIONS]\n"
+  printf "  playground tcp-proxy toggle-writes-client --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connection-id CONNECTION-ID")"
+    printf "    🧲 Zazkia TCP connection id\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_tcp_proxy_toggle_writes_service_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground tcp-proxy toggle-writes-service\n"
+    echo
+
+    printf "  ✅ Change whether reading data to the service is enabled.\n  \n    See diagram in https://github.com/emicklei/zazkia#how-does-it-work- (or\n  locally http://localhost:9191/help.html)\n"
+    echo
+
+  else
+    printf "playground tcp-proxy toggle-writes-service - ✅ Change whether reading data to the service is enabled.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tcp-proxy toggle-writes-service [OPTIONS]\n"
+  printf "  playground tcp-proxy toggle-writes-service --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connection-id CONNECTION-ID")"
+    printf "    🧲 Zazkia TCP connection id\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -17687,6 +17847,122 @@ playground_tcp_proxy_toggle_accept_connections_command() {
 }
 
 # :command.function
+playground_tcp_proxy_toggle_reads_client_command() {
+  # src/commands/tcp-proxy/toggle-reads-client.sh
+  connection_id="${args[--connection-id]}"
+
+  if [[ ! -n "$connection_id" ]]
+  then
+      connection_id=$(playground get-zazkia-connection-list)
+      if [ "$connection_id" == "" ]
+      then
+          logerror "❌ No active Zazkia TCP connection found, make sure that Zazkia is being used!"
+          exit 1
+      fi
+  fi
+
+  items=($connection_id)
+  length=${#items[@]}
+  if ((length > 1))
+  then
+      log "🧲 --connection-id flag was not provided, applying command to all active Zazkia TCP connections"
+  fi
+  for id in "${items[@]}"
+  do
+      log "✅ toggle-reads-client for connection id $id"
+      handle_onprem_connect_rest_api "curl -o /dev/null -w '%{http_code}' -s -X POST -H \"Content-Type: application/json\" \"http://localhost:9191/links/$id/toggle-reads-client\""
+      echo "$curl_output"
+  done
+}
+
+# :command.function
+playground_tcp_proxy_toggle_reads_service_command() {
+  # src/commands/tcp-proxy/toggle-reads-service.sh
+  connection_id="${args[--connection-id]}"
+
+  if [[ ! -n "$connection_id" ]]
+  then
+      connection_id=$(playground get-zazkia-connection-list)
+      if [ "$connection_id" == "" ]
+      then
+          logerror "❌ No active Zazkia TCP connection found, make sure that Zazkia is being used!"
+          exit 1
+      fi
+  fi
+
+  items=($connection_id)
+  length=${#items[@]}
+  if ((length > 1))
+  then
+      log "🧲 --connection-id flag was not provided, applying command to all active Zazkia TCP connections"
+  fi
+  for id in "${items[@]}"
+  do
+      log "✅ toggle-reads-service for connection id $id"
+      handle_onprem_connect_rest_api "curl -o /dev/null -w '%{http_code}' -s -X POST -H \"Content-Type: application/json\" \"http://localhost:9191/links/$id/toggle-reads-service\""
+      echo "$curl_output"
+  done
+}
+
+# :command.function
+playground_tcp_proxy_toggle_writes_client_command() {
+  # src/commands/tcp-proxy/toggle-writes-client.sh
+  connection_id="${args[--connection-id]}"
+
+  if [[ ! -n "$connection_id" ]]
+  then
+      connection_id=$(playground get-zazkia-connection-list)
+      if [ "$connection_id" == "" ]
+      then
+          logerror "❌ No active Zazkia TCP connection found, make sure that Zazkia is being used!"
+          exit 1
+      fi
+  fi
+
+  items=($connection_id)
+  length=${#items[@]}
+  if ((length > 1))
+  then
+      log "🧲 --connection-id flag was not provided, applying command to all active Zazkia TCP connections"
+  fi
+  for id in "${items[@]}"
+  do
+      log "✅ toggle-writes-client for connection id $id"
+      handle_onprem_connect_rest_api "curl -o /dev/null -w '%{http_code}' -s -X POST -H \"Content-Type: application/json\" \"http://localhost:9191/links/$id/toggle-writes-client\""
+      echo "$curl_output"
+  done
+}
+
+# :command.function
+playground_tcp_proxy_toggle_writes_service_command() {
+  # src/commands/tcp-proxy/toggle-writes-service.sh
+  connection_id="${args[--connection-id]}"
+
+  if [[ ! -n "$connection_id" ]]
+  then
+      connection_id=$(playground get-zazkia-connection-list)
+      if [ "$connection_id" == "" ]
+      then
+          logerror "❌ No active Zazkia TCP connection found, make sure that Zazkia is being used!"
+          exit 1
+      fi
+  fi
+
+  items=($connection_id)
+  length=${#items[@]}
+  if ((length > 1))
+  then
+      log "🧲 --connection-id flag was not provided, applying command to all active Zazkia TCP connections"
+  fi
+  for id in "${items[@]}"
+  do
+      log "✅ toggle-writes-service for connection id $id"
+      handle_onprem_connect_rest_api "curl -o /dev/null -w '%{http_code}' -s -X POST -H \"Content-Type: application/json\" \"http://localhost:9191/links/$id/toggle-writes-service\""
+      echo "$curl_output"
+  done
+}
+
+# :command.function
 playground_debug_enable_remote_debugging_command() {
   # src/commands/debug/enable-remote-debugging.sh
   IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
@@ -28433,6 +28709,34 @@ playground_tcp_proxy_parse_requirements() {
       shift $#
       ;;
 
+    toggle-reads-client)
+      action="toggle-reads-client"
+      shift
+      playground_tcp_proxy_toggle_reads_client_parse_requirements "$@"
+      shift $#
+      ;;
+
+    toggle-reads-service)
+      action="toggle-reads-service"
+      shift
+      playground_tcp_proxy_toggle_reads_service_parse_requirements "$@"
+      shift $#
+      ;;
+
+    toggle-writes-client)
+      action="toggle-writes-client"
+      shift
+      playground_tcp_proxy_toggle_writes_client_parse_requirements "$@"
+      shift $#
+      ;;
+
+    toggle-writes-service)
+      action="toggle-writes-service"
+      shift
+      playground_tcp_proxy_toggle_writes_service_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_tcp_proxy_usage >&2
@@ -28889,6 +29193,262 @@ playground_tcp_proxy_toggle_accept_connections_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_tcp_proxy_toggle_reads_client_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_tcp_proxy_toggle_reads_client_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tcp-proxy toggle-reads-client"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connection-id)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connection-id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connection-id requires an argument: --connection-id CONNECTION-ID" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--connection-id'] && -n $(validate_integer "${args['--connection-id']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--connection-id CONNECTION-ID" "$(validate_integer "${args['--connection-id']:-}")" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_tcp_proxy_toggle_reads_service_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_tcp_proxy_toggle_reads_service_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tcp-proxy toggle-reads-service"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connection-id)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connection-id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connection-id requires an argument: --connection-id CONNECTION-ID" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--connection-id'] && -n $(validate_integer "${args['--connection-id']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--connection-id CONNECTION-ID" "$(validate_integer "${args['--connection-id']:-}")" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_tcp_proxy_toggle_writes_client_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_tcp_proxy_toggle_writes_client_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tcp-proxy toggle-writes-client"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connection-id)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connection-id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connection-id requires an argument: --connection-id CONNECTION-ID" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--connection-id'] && -n $(validate_integer "${args['--connection-id']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--connection-id CONNECTION-ID" "$(validate_integer "${args['--connection-id']:-}")" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_tcp_proxy_toggle_writes_service_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_tcp_proxy_toggle_writes_service_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tcp-proxy toggle-writes-service"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connection-id)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connection-id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connection-id requires an argument: --connection-id CONNECTION-ID" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--connection-id'] && -n $(validate_integer "${args['--connection-id']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--connection-id CONNECTION-ID" "$(validate_integer "${args['--connection-id']:-}")" >&2
+    exit 1
+  fi
 
 }
 
@@ -34655,6 +35215,10 @@ run() {
     "tcp-proxy delay") playground_tcp_proxy_delay_command ;;
     "tcp-proxy close-connection") playground_tcp_proxy_close_connection_command ;;
     "tcp-proxy toggle-accept-connections") playground_tcp_proxy_toggle_accept_connections_command ;;
+    "tcp-proxy toggle-reads-client") playground_tcp_proxy_toggle_reads_client_command ;;
+    "tcp-proxy toggle-reads-service") playground_tcp_proxy_toggle_reads_service_command ;;
+    "tcp-proxy toggle-writes-client") playground_tcp_proxy_toggle_writes_client_command ;;
+    "tcp-proxy toggle-writes-service") playground_tcp_proxy_toggle_writes_service_command ;;
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
     "debug testssl") playground_debug_testssl_command ;;
