wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -140,6 +140,7 @@ playground_usage() {
   printf "  %s   🧰 Show current connector config\n" "$(green "connector show-config")                         "
   printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "connector show-config-parameters")              "
   printf "  %s   🔌 List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "connector search-jar")                          "
+  printf "  %s   🔌 useful snippets\n" "$(green "connector snippets")                            "
   printf "  %s   🧬 Set connect log level\n" "$(green "connector log-level")                           "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "connector create-or-update")                    "
   echo
@@ -4785,6 +4786,11 @@ playground_fully_managed_connector_show_config_parameters_usage() {
     printf "    📂 Only show the path of the file containing the configuration parameters\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--only-show-json")"
+    printf "    📗 Only show list of all available parameters for connector (with default\n    value when applicable)\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -4882,6 +4888,7 @@ playground_connector_usage() {
   printf "  %s   🧰 Show current connector config\n" "$(green "show-config")           "
   printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "show-config-parameters")"
   printf "  %s   🔌 List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "search-jar")            "
+  printf "  %s   🔌 useful snippets\n" "$(green "snippets")              "
   printf "  %s   🧬 Set connect log level\n" "$(green "log-level")             "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")      "
   echo
@@ -5351,6 +5358,11 @@ playground_connector_show_config_parameters_usage() {
     printf "    📂 Only show the path of the file containing the configuration parameters\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--only-show-json")"
+    printf "    📗 Only show list of all available parameters for connector (with default\n    value when applicable)\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -5405,6 +5417,52 @@ playground_connector_search_jar_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground connector search-jar --connector-plugin\n  confluentinc/kafka-connect-s3 --class WebIdentityTokenCredentialsProvider\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_snippets_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector snippets - 🔌 useful snippets\n"
+    echo
+
+  else
+    printf "playground connector snippets - 🔌 useful snippets\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector snippets [OPTIONS]\n"
+  printf "  playground connector snippets --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--converter CONVERTER")"
+    printf "    🔌 Converter\n"
+    printf "    Allowed: avro, protobuf, json-schema, json, json-schema-enabled, string, bytearray\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--dlq")"
+    printf "    🔗 dlq\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground connector snippets --converter avro --dlq\n"
     echo
 
   fi
@@ -8532,6 +8590,9 @@ function bootstrap_ccloud_environment () {
           then
             source $DELTA_CONFIGS_ENV
             log "🌱 cluster $CLUSTER_NAME is ready to be used!"
+
+            # trick
+            playground state set run.environment "ccloud"
             return
           else
             logwarn "$DELTA_CONFIGS_ENV has not been generated, doing it now..."
@@ -11225,9 +11286,9 @@ playground_run_command() {
   cd $test_file_directory
   if [[ -n "$enable_multiple_connect_workers" ]]
   then
-    trap "cp /tmp/playground-backup-docker-compose.yml $docker_compose_file;rm /tmp/playground-run-command-used;echo '';sleep 3;set +e;playground connector status;playground connector versions;playground open-docs --only-show-url" EXIT
+    trap "cp /tmp/playground-backup-docker-compose.yml $docker_compose_file;rm /tmp/playground-run-command-used;echo '';sleep 3;set +e;playground connector status;playground connector versions;playground open-docs --only-show-url;playground connector show-config-parameters --only-show-json" EXIT
   else
-    trap 'rm /tmp/playground-run-command-used;echo "";sleep 3;set +e;playground connector status;playground connector versions;playground open-docs --only-show-url' EXIT
+    trap 'rm /tmp/playground-run-command-used;echo "";sleep 3;set +e;playground connector status;playground connector versions;playground open-docs --only-show-url;playground connector show-config-parameters --only-show-json' EXIT
   fi
   playground generate-fzf-find-files &
   touch /tmp/playground-run-command-used
@@ -11806,7 +11867,7 @@ playground_run_ccloud_command() {
   log "####################################################"
   SECONDS=0
   cd $test_file_directory
-  trap 'rm /tmp/playground-run-command-used;echo "";sleep 3;set +e;playground connector status;playground fully-managed-connector status;playground connector versions' EXIT
+  trap 'rm /tmp/playground-run-command-used;echo "";sleep 3;set +e;playground connector status;playground fully-managed-connector status;playground connector versions;playground connector fully-managed-show-config-parameters --only-show-json' EXIT
   touch /tmp/playground-run-command-used
   playground generate-fzf-find-files &
   bash $filename ${other_args[*]}
@@ -16907,6 +16968,7 @@ playground_fully_managed_connector_show_config_parameters_command() {
   open="${args[--open]}"
   force_refresh="${args[--force-refresh]}"
   only_show_file_path="${args[--only-show-file-path]}"
+  only_show_json="${args[--only-show-json]}"
   verbose="${args[--verbose]}"
 
   get_ccloud_connect
@@ -16914,7 +16976,6 @@ playground_fully_managed_connector_show_config_parameters_command() {
   if [[ ! -n "$connector" ]]
   then
       set +e
-      log "✨ --connector flag was not provided, applying command to all ccloud connectors"
       connector=$(playground get-fully-managed-connector-list)
       if [ $? -ne 0 ]
       then
@@ -16924,7 +16985,7 @@ playground_fully_managed_connector_show_config_parameters_command() {
       fi
       if [ "$connector" == "" ]
       then
-          logerror "💤 No ccloud connector is running !"
+          logerror "💤 No fully managed connector is running !"
           exit 1
       fi
       set -e
@@ -16947,6 +17008,11 @@ playground_fully_managed_connector_show_config_parameters_command() {
   fi
 
   items=($connector)
+  length=${#items[@]}
+  if ((length > 1))
+  then
+      log "✨ --connector flag was not provided, applying command to all connectors"
+  fi
   for connector in ${items[@]}
   do
       json_config=$(curl -s --request GET "https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector/config" --header "authorization: Basic $authorization")
@@ -16972,9 +17038,20 @@ playground_fully_managed_connector_show_config_parameters_command() {
       fi
 
       filename="/tmp/config-$connector_class.txt"
+      json_filename="/tmp/config-$connector_class.json"
+
+      mkdir -p $root_folder/.connector_config
+      filename="$root_folder/.connector_config/config-$connector_class.txt"
+      json_filename="$root_folder/.connector_config/config-$connector_class.json"
 
       class=$(echo $connector_class | rev | cut -d '.' -f 1 | rev)
-      log "🔩 getting parameters for connector $connector ($class)"
+
+      if [[ -n "$only_show_json" ]]
+      then
+          log "🔩 list of all available parameters for connector $connector ($class) (with default value when applicable)"
+      else
+          log "🔩 getting parameters for connector $connector ($class)"
+      fi
 
       if [[ -n "$force_refresh" ]]
       then
@@ -16982,8 +17059,12 @@ playground_fully_managed_connector_show_config_parameters_command() {
           then
               rm -f $filename
           fi
+          if [ -f $json_filename ]
+          then
+              rm -f $json_filename
+          fi
       fi
-      if [ ! -f $filename ]
+      if [ ! -f $filename ] || [ ! -f $json_filename ]
       then
           set +e
           if [[ -n "$verbose" ]]
@@ -17063,6 +17144,12 @@ playground_fully_managed_connector_show_config_parameters_command() {
                       echo -e "\t - Importance: $importance" >> $filename
                       echo -e "\t - Required: $required" >> $filename
                       echo -e "" >> $filename
+
+                      if [ "$default" == "null" ]
+                      then
+                          default=""
+                      fi
+                      echo "\"$param\": \"$default\"," >> $json_filename
                   done
               fi
           else
@@ -17089,6 +17176,12 @@ playground_fully_managed_connector_show_config_parameters_command() {
               fi
           fi
       else
+          if [[ -n "$only_show_json" ]]
+          then
+              cat $json_filename
+              return
+          fi
+
           if [[ -n "$only_show_file_path" ]]
           then
               echo "$filename"
@@ -17843,14 +17936,14 @@ playground_connector_show_config_command() {
 # :command.function
 playground_connector_show_config_parameters_command() {
   # src/connector_show_config_parameters_command.sh
+  connector="${args[--connector]}"
   open="${args[--open]}"
   force_refresh="${args[--force-refresh]}"
   only_show_file_path="${args[--only-show-file-path]}"
+  only_show_json="${args[--only-show-json]}"
   verbose="${args[--verbose]}"
 
   get_connect_url_and_security
-
-  connector="${args[--connector]}"
 
   if [[ ! -n "$connector" ]]
   then
@@ -17900,10 +17993,18 @@ playground_connector_show_config_parameters_command() {
           exit 1
       fi
 
-      filename="/tmp/config-$connector_class-$version.txt"
+      mkdir -p $root_folder/.connector_config
+      filename="$root_folder/.connector_config/config-$connector_class-$version.txt"
+      json_filename="$root_folder/.connector_config/config-$connector_class-$version.json"
 
       class=$(echo $connector_class | rev | cut -d '.' -f 1 | rev)
-      log "🔩 getting parameters for connector $connector ($class) and version $version"
+
+      if [[ -n "$only_show_json" ]]
+      then
+          log "🔩 list of all available parameters for connector $connector ($class) and version $version (with default value when applicable)"
+      else
+          log "🔩 getting parameters for connector $connector ($class) and version $version"
+      fi
 
       if [[ -n "$force_refresh" ]]
       then
@@ -17911,8 +18012,12 @@ playground_connector_show_config_parameters_command() {
           then
               rm -f $filename
           fi
+          if [ -f $json_filename ]
+          then
+              rm -f $json_filename
+          fi
       fi
-      if [ ! -f $filename ]
+      if [ ! -f $filename ] || [ ! -f $json_filename ]
       then
           set +e
           if [[ -n "$verbose" ]]
@@ -17993,6 +18098,12 @@ playground_connector_show_config_parameters_command() {
                       echo -e "\t - Importance: $importance" >> $filename
                       echo -e "\t - Required: $required" >> $filename
                       echo -e "" >> $filename
+
+                      if [ "$default" == "null" ]
+                      then
+                          default=""
+                      fi
+                      echo "\"$param\": \"$default\"," >> $json_filename
                   done
               fi
           else
@@ -18019,6 +18130,12 @@ playground_connector_show_config_parameters_command() {
               fi
           fi
       else
+          if [[ -n "$only_show_json" ]]
+          then
+              cat $json_filename
+              return
+          fi
+
           if [[ -n "$only_show_file_path" ]]
           then
               echo "$filename"
@@ -18073,6 +18190,25 @@ playground_connector_search_jar_command() {
       done
     done
   fi
+}
+
+# :command.function
+playground_connector_snippets_command() {
+  # src/connector_snippets_command.sh
+  converter=${args[converter]}
+  dlq=${args[--dlq]}
+
+  environment=$(playground state get run.environment_before_switch)
+  if [ "$environment" = "" ]
+  then
+      environment=$(playground state get run.environment)
+  fi
+
+  if [ "$environment" = "" ]
+  then
+      environment="plaintext"
+  fi
+
 }
 
 # :command.function
@@ -27370,6 +27506,14 @@ playground_fully_managed_connector_show_config_parameters_parse_requirements() {
         shift
         ;;
 
+      # :flag.case
+      --only-show-json)
+
+        # :flag.case_no_arg
+        args['--only-show-json']=1
+        shift
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -27582,6 +27726,13 @@ playground_connector_parse_requirements() {
       action="search-jar"
       shift
       playground_connector_search_jar_parse_requirements "$@"
+      shift $#
+      ;;
+
+    snippets)
+      action="snippets"
+      shift
+      playground_connector_snippets_parse_requirements "$@"
       shift $#
       ;;
 
@@ -28359,6 +28510,14 @@ playground_connector_show_config_parameters_parse_requirements() {
         shift
         ;;
 
+      # :flag.case
+      --only-show-json)
+
+        # :flag.case_no_arg
+        args['--only-show-json']=1
+        shift
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -28480,6 +28639,78 @@ playground_connector_search_jar_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['--connector-tag']:-} ]] || args['--connector-tag']="latest"
+
+}
+
+# :command.parse_requirements
+playground_connector_snippets_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_snippets_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector snippets"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --converter)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--converter']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--converter requires an argument: --converter CONVERTER" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --dlq)
+
+        # :flag.case_no_arg
+        args['--dlq']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.whitelist_filter
+  if [[ ${args['--converter']:-} ]] && [[ ! ${args['--converter']:-} =~ ^(avro|protobuf|json-schema|json|json-schema-enabled|string|bytearray)$ ]]; then
+    printf "%s\n" "--converter must be one of: avro, protobuf, json-schema, json, json-schema-enabled, string, bytearray" >&2
+    exit 1
+  fi
 
 }
 
@@ -28839,6 +29070,7 @@ run() {
     "connector show-config") playground_connector_show_config_command ;;
     "connector show-config-parameters") playground_connector_show_config_parameters_command ;;
     "connector search-jar") playground_connector_search_jar_command ;;
+    "connector snippets") playground_connector_snippets_command ;;
     "connector log-level") playground_connector_log_level_command ;;
     "connector create-or-update") playground_connector_create_or_update_command ;;
   esac
