wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -77,6 +77,8 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   📤 Produce to a topic\n" "$(green "topic produce")                     "
   [[ -n $long_usage ]] && printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "topic set-schema-compatibility")    "
   [[ -n $long_usage ]] && printf "  %s   🧞 Easily identify the usage of different schema versions within a topic.\n" "$(green "topic display-schema-id-statistics")"
+  [[ -n $long_usage ]] && printf "  %s   🆕 Create topic\n" "$(green "topic create")                      "
+  [[ -n $long_usage ]] && printf "  %s   ❌ Delete topic\n" "$(green "topic delete")                      "
   echo
   printf "%s\n" "$(bold "Connector commands:")"
   printf "  %s   🔗☁️ Fully Managed Connector commands\n" "$(green "ccloud-connector")                  "
@@ -1824,6 +1826,8 @@ playground_topic_usage() {
   printf "  %s   📤 Produce to a topic\n" "$(green "produce")                     "
   printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "set-schema-compatibility")    "
   printf "  %s   🧞 Easily identify the usage of different schema versions within a topic.\n" "$(green "display-schema-id-statistics")"
+  printf "  %s   🆕 Create topic\n" "$(green "create")                      "
+  printf "  %s   ❌ Delete topic\n" "$(green "delete")                      "
   echo
 
   # :command.long_usage
@@ -2041,6 +2045,12 @@ playground_topic_produce_usage() {
     printf "    Default: 3\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--nb-partitions NB-PARTITIONS")"
+    printf "    Number of partitions for the topic. \n    \n    Important: If topic is existing, it will be re-created before producing to\n    topic.\n"
+    printf "    Default: 1\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -2122,6 +2132,94 @@ playground_topic_display_schema_id_statistics_usage() {
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--topic, -t TOPIC")"
+    printf "    🗳 Topic name\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_topic_create_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground topic create - 🆕 Create topic\n"
+    echo
+
+  else
+    printf "playground topic create - 🆕 Create topic\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground topic create [OPTIONS] [ARGUMENTS...]\n"
+  printf "  playground topic create --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--topic, -t TOPIC (required)")"
+    printf "    🗳 Topic name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--nb-partitions NB-PARTITIONS")"
+    printf "    Number of partitions for the topic.\n"
+    printf "    Default: 1\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    echo "  ARGUMENTS..."
+    printf "    Any arguments to be used with kafka-topics --create\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground topic create --topic atopic\n  playground topic create --topic atopic --nb-partitions 8 --config\n  retention.ms=30000\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_topic_delete_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground topic delete - ❌ Delete topic\n"
+    echo
+
+  else
+    printf "playground topic delete - ❌ Delete topic\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground topic delete [OPTIONS]\n"
+  printf "  playground topic delete --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--topic, -t TOPIC (required)")"
     printf "    🗳 Topic name\n"
     echo
 
@@ -7112,9 +7210,9 @@ playground_get_topic_list_command() {
     then
       if [[ -n "$skip_connect_internal_topics" ]]
       then
-        docker exec broker ls /var/lib/kafka/data | grep -v "checkpoint" | grep -v "meta.properties" | grep -v "connect-" | grep -v "^_" | sed 's/[^-]*$//' | sed 's/.$//' | sort | uniq
+        docker exec broker ls /var/lib/kafka/data | grep -v "checkpoint" | grep -v "meta.properties" | grep -v "connect-" | grep -v "^_" | grep -v "delete" | sed 's/[^-]*$//' | sed 's/.$//' | sort | uniq
       else
-        docker exec broker ls /var/lib/kafka/data | grep -v "checkpoint" | grep -v "meta.properties" | grep -v "^_" | sed 's/[^-]*$//' | sed 's/.$//' | sort | uniq
+        docker exec broker ls /var/lib/kafka/data | grep -v "checkpoint" | grep -v "meta.properties" | grep -v "^_" | grep -v "delete" | sed 's/[^-]*$//' | sed 's/.$//' | sort | uniq
       fi
     fi
   fi
@@ -9656,7 +9754,7 @@ playground_topic_produce_command() {
   # src/topic_produce_command.sh
   topic="${args[--topic]}"
   nb_messages="${args[--nb-messages]}"
-
+  nb_partitions="${args[--nb-partitions]}"
   schema="${args[--input]}"
 
   tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
@@ -10013,6 +10111,101 @@ playground_topic_display_schema_id_statistics_command() {
 
       rm -f /tmp/results.json $output_file
   done
+}
+
+# :command.function
+playground_topic_create_command() {
+  # src/topic_create_command.sh
+  topic="${args[--topic]}"
+  nb_partitions="${args[--nb-partitions]}"
+
+  ret=$(get_security_broker "--command-config")
+
+  container=$(echo "$ret" | cut -d "@" -f 1)
+  security=$(echo "$ret" | cut -d "@" -f 2)
+
+  environment=`get_environment_used`
+
+  if [ "$environment" == "error" ]
+  then
+    logerror "File containing restart command /tmp/playground-command does not exist!"
+    exit 1
+
+  fi
+
+  log "🆕 Creating topic $topic"
+  if [[ "$environment" == "environment" ]]
+  then
+      if [ -f /tmp/delta_configs/env.delta ]
+      then
+          source /tmp/delta_configs/env.delta
+      else
+          logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
+          exit 1
+      fi
+      if [ ! -f /tmp/delta_configs/ak-tools-ccloud.delta ]
+      then
+          logerror "ERROR: /tmp/delta_configs/ak-tools-ccloud.delta has not been generated"
+          exit 1
+      fi
+
+      DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+      dir1=$(echo ${DIR_CLI%/*})
+      root_folder=$(echo ${dir1%/*})
+      IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
+      source $root_folder/scripts/utils.sh
+
+      docker run --rm -v /tmp/delta_configs/ak-tools-ccloud.delta:/tmp/configuration/ccloud.properties ${CP_CONNECT_IMAGE}:${CONNECT_TAG} kafka-topics --create --topic $topic --bootstrap-server $BOOTSTRAP_SERVERS --command-config /tmp/configuration/ccloud.properties --partitions $nb_partitions ${other_args[*]}
+  else
+      docker exec $container kafka-topics --create --topic $topic --bootstrap-server broker:9092 --partitions $nb_partitions $security ${other_args[*]}
+  fi
+}
+
+# :command.function
+playground_topic_delete_command() {
+  # src/topic_delete_command.sh
+  topic="${args[--topic]}"
+
+  ret=$(get_security_broker "--command-config")
+
+  container=$(echo "$ret" | cut -d "@" -f 1)
+  security=$(echo "$ret" | cut -d "@" -f 2)
+
+  environment=`get_environment_used`
+
+  if [ "$environment" == "error" ]
+  then
+    logerror "File containing restart command /tmp/playground-command does not exist!"
+    exit 1
+
+  fi
+
+  log "❌ Deleting topic $topic"
+  if [[ "$environment" == "environment" ]]
+  then
+      if [ -f /tmp/delta_configs/env.delta ]
+      then
+          source /tmp/delta_configs/env.delta
+      else
+          logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
+          exit 1
+      fi
+      if [ ! -f /tmp/delta_configs/ak-tools-ccloud.delta ]
+      then
+          logerror "ERROR: /tmp/delta_configs/ak-tools-ccloud.delta has not been generated"
+          exit 1
+      fi
+
+      DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+      dir1=$(echo ${DIR_CLI%/*})
+      root_folder=$(echo ${dir1%/*})
+      IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
+      source $root_folder/scripts/utils.sh
+
+      docker run --rm -v /tmp/delta_configs/ak-tools-ccloud.delta:/tmp/configuration/ccloud.properties ${CP_CONNECT_IMAGE}:${CONNECT_TAG} kafka-topics --delete --topic $topic --bootstrap-server $BOOTSTRAP_SERVERS --command-config /tmp/configuration/ccloud.properties
+  else
+      docker exec $container kafka-topics --delete --topic $topic --bootstrap-server broker:9092 $security
+  fi
 }
 
 # :command.function
@@ -14331,6 +14524,20 @@ playground_topic_parse_requirements() {
       shift $#
       ;;
 
+    create)
+      action="create"
+      shift
+      playground_topic_create_parse_requirements "$@"
+      shift $#
+      ;;
+
+    delete)
+      action="delete"
+      shift
+      playground_topic_delete_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_topic_usage >&2
@@ -14755,6 +14962,26 @@ playground_topic_produce_parse_requirements() {
         fi
         ;;
 
+      # :flag.case
+      --nb-partitions)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--nb-partitions NB-PARTITIONS" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--nb-partitions']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--nb-partitions requires an argument: --nb-partitions NB-PARTITIONS" >&2
+          exit 1
+        fi
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -14780,6 +15007,7 @@ playground_topic_produce_parse_requirements() {
   # :command.default_assignments
   [[ -n ${args['--input']:-} ]] || args['--input']="-"
   [[ -n ${args['--nb-messages']:-} ]] || args['--nb-messages']="3"
+  [[ -n ${args['--nb-partitions']:-} ]] || args['--nb-partitions']="1"
 
   # :command.user_filter
   filter_error=$(filter_schema_registry_running)
@@ -14937,6 +15165,163 @@ playground_topic_display_schema_id_statistics_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_topic_create_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_topic_create_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="topic create"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --topic | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--topic']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--topic requires an argument: --topic, -t TOPIC" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --nb-partitions)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--nb-partitions NB-PARTITIONS" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--nb-partitions']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--nb-partitions requires an argument: --nb-partitions NB-PARTITIONS" >&2
+          exit 1
+        fi
+        ;;
+
+      --)
+        shift
+        other_args+=("$@")
+        break
+        ;;
+
+      -?*)
+        other_args+=("$1")
+        shift
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_catch_all
+        other_args+=("$1")
+        shift
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--topic']+x} ]]; then
+    printf "missing required flag: --topic, -t TOPIC\n" >&2
+    exit 1
+  fi
+
+  # :command.default_assignments
+  [[ -n ${args['--nb-partitions']:-} ]] || args['--nb-partitions']="1"
+
+}
+
+# :command.parse_requirements
+playground_topic_delete_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_topic_delete_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="topic delete"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --topic | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--topic']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--topic requires an argument: --topic, -t TOPIC" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--topic']+x} ]]; then
+    printf "missing required flag: --topic, -t TOPIC\n" >&2
+    exit 1
+  fi
 
 }
 
@@ -16265,6 +16650,8 @@ run() {
     "topic produce") playground_topic_produce_command ;;
     "topic set-schema-compatibility") playground_topic_set_schema_compatibility_command ;;
     "topic display-schema-id-statistics") playground_topic_display_schema_id_statistics_command ;;
+    "topic create") playground_topic_create_command ;;
+    "topic delete") playground_topic_delete_command ;;
     "ccloud-connector") playground_ccloud_connector_command ;;
     "ccloud-connector status") playground_ccloud_connector_status_command ;;
     "ccloud-connector plugins") playground_ccloud_connector_plugins_command ;;
