wip delete

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -62,6 +62,7 @@ playground_usage() {
   printf "  %s   🔰 Schema commands\n" "$(green "schema")                                 "
   [[ -n $long_usage ]] && printf "  %s   🔰 Get all schemas versions for specified subject (if --subject is not specified, all subjects will be used)\n" "$(green "schema get")                             "
   [[ -n $long_usage ]] && printf "  %s   ⏺️ Register a schema in specified subject\n" "$(green "schema register")                        "
+  [[ -n $long_usage ]] && printf "  %s   🧟 Delete schema\n" "$(green "schema delete")                          "
   echo
   printf "%s\n" "$(bold "Debug commands:")"
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                                  "
@@ -1412,6 +1413,7 @@ playground_schema_usage() {
   printf "%s\n" "$(bold "Schema commands:")"
   printf "  %s   🔰 Get all schemas versions for specified subject (if --subject is not specified, all subjects will be used)\n" "$(green "get")     "
   printf "  %s   ⏺️ Register a schema in specified subject\n" "$(green "register")"
+  printf "  %s   🧟 Delete schema\n" "$(green "delete")  "
   echo
 
   # :command.long_usage
@@ -1513,6 +1515,56 @@ playground_schema_register_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground schema register --subject test-protobuf << 'EOF'\n  syntax = \"proto3\";\n  \n  package com.github.vdesabou;\n  \n  message Customer {\n      int64 count = 1;\n      string first_name = 2;\n      string last_name = 3;\n      string address = 4;\n  }\n  EOF\n  \n  playground schema register --subject test-avro << 'EOF'\n  {\n      \"type\": \"record\",\n      \"namespace\": \"com.github.vdesabou\",\n      \"name\": \"Customer\",\n      \"fields\": [\n          {\n              \"name\": \"count\",\n              \"type\": \"long\",\n              \"doc\": \"count\"\n          },\n          {\n              \"name\": \"first_name\",\n              \"type\": \"string\",\n              \"doc\": \"First Name of Customer\"\n          },\n          {\n              \"name\": \"last_name\",\n              \"type\": \"string\",\n              \"doc\": \"Last Name of Customer\"\n          },\n          {\n              \"name\": \"address\",\n              \"type\": \"string\",\n              \"doc\": \"Address of Customer\"\n          }\n      ]\n  }\n  EOF\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_schema_delete_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground schema delete - 🧟 Delete schema\n"
+    echo
+
+  else
+    printf "playground schema delete - 🧟 Delete schema\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground schema delete [OPTIONS]\n"
+  printf "  playground schema delete --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--subject SUBJECT")"
+    printf "    📛 Subject name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--id ID")"
+    printf "    1️⃣ schema id\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--version VERSION")"
+    printf "    🔢 schema version\n    \n    Can only be used when --subject is provided\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--permanent")"
+    printf "    💀 Hard delete for a specific version of the subject, which removes all\n    associated metadata including the schema ID.\n    \n    default is soft delete\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -7395,7 +7447,7 @@ function ccloud::create_ccloud_stack() {
 
   SCHEMA_REGISTRY_GEO="${SCHEMA_REGISTRY_GEO:-us}"
   SCHEMA_REGISTRY=$(ccloud::enable_schema_registry $CLUSTER_CLOUD $SCHEMA_REGISTRY_GEO)
-  SCHEMA_REGISTRY_ENDPOINT=$(confluent schema-registry cluster describe -o json | jq -r ".endpoint_url")
+
   # VINC: added
   if [[ -z "$SCHEMA_REGISTRY_CREDS" ]]
   then
@@ -7407,6 +7459,8 @@ function ccloud::create_ccloud_stack() {
     fi
     SCHEMA_REGISTRY_CREDS=$(ccloud::maybe_create_credentials_resource $SERVICE_ACCOUNT_ID $SCHEMA_REGISTRY)
   fi
+
+  SCHEMA_REGISTRY_ENDPOINT=$(confluent schema-registry cluster describe -o json | jq -r ".endpoint_url")
 
   if [[ $NEED_ACLS -eq 1 ]]
   then
@@ -10697,6 +10751,83 @@ playground_schema_register_command() {
       --header 'Content-Type: application/vnd.schemaregistry.v1+json' \
       --data "$json_new" | jq .
 
+}
+
+# :command.function
+playground_schema_delete_command() {
+  # src/schema_delete_command.sh
+  subject="${args[--subject]}"
+  version="${args[--version]}"
+  id="${args[--id]}"
+  permanent="${args[--permanent]}"
+
+  ret=$(get_sr_url_and_security)
+
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
+
+  if [[ -n "$version" ]]
+  then
+      if [[ ! -n "$subject" ]]
+      then
+          logerror "❌ --version is set without --subject being set"
+          exit 1
+      fi
+  fi
+
+  # https://docs.confluent.io/platform/current/schema-registry/develop/api.html#delete--subjects-(string-%20subject)-versions-(versionId-%20version)
+  if [[ -n "$subject" ]]
+  then
+      if [[ -n "$version" ]]
+      then
+          log "🧟 Soft deleting 💯 version ${version} from subject 🔰 ${subject}"
+          curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${version}" | jq .
+          if [[ -n "$permanent" ]]
+          then
+              log "💀 Hard deleting 💯 version ${version} from subject 🔰 ${subject}"
+              curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${version}?permanent=true" | jq .
+          fi
+      else
+          logwarn "--version is not set, deleting all versions !"
+          versions=$(curl $sr_security -s "${sr_url}/subjects/${subject}/versions")
+          ret=$?
+          set -e
+          if [ $ret -eq 0 ]
+          then
+              if echo "$versions" | jq -r .error_code >/dev/null 2>&1
+              then
+                  error_code=$(echo "$versions" | jq -r .error_code)
+                  if [ "$error_code" != "null" ]
+                  then
+                      message=$(echo "$versions" | jq -r .message)
+                      logerror "Command failed with error code $error_code"
+                      logerror "$message"
+                      exit 1
+                  fi
+              else
+                  for version in $(echo "${versions}" | jq -r '.[]')
+                  do
+                      if test "$version" -eq "$version" 2>/dev/null
+                      then
+                          log "🧟 Soft deleting 💯 version ${version} from subject 🔰 ${subject}"
+                          curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${version}" | jq .
+                          if [[ -n "$permanent" ]]
+                          then
+                              log "💀 Hard deleting 💯 version ${version} from subject 🔰 ${subject}"
+                              curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${version}?permanent=true" | jq .
+                          fi
+                      else
+                          logerror "$version is not a number"
+                          exit 1
+                      fi
+                  done
+              fi
+          else
+              logerror "❌ curl request failed with error code $ret!"
+              exit 1
+          fi
+      fi
+  fi
 }
 
 # :command.function
@@ -17059,6 +17190,13 @@ playground_schema_parse_requirements() {
       shift $#
       ;;
 
+    delete)
+      action="delete"
+      shift
+      playground_schema_delete_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_schema_usage >&2
@@ -17266,6 +17404,119 @@ playground_schema_register_parse_requirements() {
     echo "$filter_error" >&2
     exit 1
   fi
+
+}
+
+# :command.parse_requirements
+playground_schema_delete_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_schema_delete_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="schema delete"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --subject)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--subject']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--subject requires an argument: --subject SUBJECT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --id)
+        # :flag.conflicts
+        for conflict in --subject --version; do
+          if [[ -n "${args[$conflict]:-}" ]]; then
+            printf "conflicting options: %s cannot be used with %s\n" "$key" "$conflict" >&2
+            exit 1
+          fi
+        done
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--id ID" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--id requires an argument: --id ID" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --version)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--version VERSION" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--version']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--version requires an argument: --version VERSION" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --permanent)
+
+        # :flag.case_no_arg
+        args['--permanent']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
 
 }
 
@@ -22041,6 +22292,7 @@ run() {
     "schema") playground_schema_command ;;
     "schema get") playground_schema_get_command ;;
     "schema register") playground_schema_register_command ;;
+    "schema delete") playground_schema_delete_command ;;
     "debug") playground_debug_command ;;
     "debug install-vscode-extension") playground_debug_install_vscode_extension_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
