added start-environment

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -43,6 +43,7 @@ playground_usage() {
   printf "%s\n" "$(bold "Run commands:")"
   printf "  %s   🕹️ Run any example, except for Confluent Cloud (in this case use run-ccloud command)\n" "$(green "run")                                    "
   printf "  %s   ⚡ Simply re-run last example you ran with <playground run> or <playground run-ccloud>\n" "$(green "re-run")                                 "
+  printf "  %s   🔐 Simply start an environment listed in https://kafka-docker-playground.io/#/content?id=%f0%9f%94%90-environments:\n" "$(green "start-environment")                      "
   printf "  %s   ⛅ Run any Confluent Cloud (ccloud) example\n" "$(green "run-ccloud")                             "
   printf "  %s   ✨ Update current confluent platform or connector(s) with new version(s)\n" "$(green "update-version")                         "
   printf "  %s   👐 When --file is not provided, simply open last example you ran with <playground run> or <playground run-ccloud>\n" "$(green "open")                                   "
@@ -835,7 +836,105 @@ playground_re_run_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground re-run\n"
-    printf "  playground re-run --tag=6.2.1\n"
+    printf "  playground re-run --tag 6.2.1\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_start_environment_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground start-environment\n"
+    echo
+
+    printf "  🔐 Simply start an environment listed in\n  https://kafka-docker-playground.io/#/content?id=%f0%9f%94%90-environments:\n  \n  - ccloud\n  - 2way-ssl\n  - kerberos\n  - kraft-external-plaintext\n  - kraft-plaintext\n  - ldap-authorizer-sasl-plain\n  - ldap-sasl-plain\n  - mdc-kerberos\n  - mdc-plaintext\n  - mdc-sasl-plain\n  - plaintext\n  - rbac-sasl-plain\n  - sasl-plain\n  - sasl-scram\n  - sasl-ssl\n  - ssl_kerberos\n  \n  Note: when running an example with <playground run> or <playground\n  run-ccloud>, it is already automatically done\n"
+    echo
+
+  else
+    printf "playground start-environment - 🔐 Simply start an environment listed in https://kafka-docker-playground.io/#/content?id=%f0%9f%94%90-environments:\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground start-environment [OPTIONS] [ARGUMENTS...]\n"
+  printf "  playground start-environment --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--environment ENVIRONMENT")"
+    printf "    🔐 The environment to start . \n    \n    - ccloud\n    - 2way-ssl\n    - kerberos\n    - kraft-external-plaintext\n    - kraft-plaintext\n    - ldap-authorizer-sasl-plain\n    - ldap-sasl-plain\n    - mdc-kerberos\n    - mdc-plaintext\n    - mdc-sasl-plain\n    - plaintext\n    - rbac-sasl-plain\n    - sasl-plain\n    - sasl-scram\n    - sasl-ssl\n    - ssl_kerberos\n    \n    Default is plaintext\n"
+    printf "    Allowed: ccloud, 2way-ssl, kerberos, kraft-external-plaintext, kraft-plaintext, ldap-authorizer-sasl-plain, ldap-sasl-plain, mdc-kerberos, mdc-plaintext, mdc-sasl-plain, plaintext, rbac-sasl-plain, sasl-plain, sasl-scram, sasl-ssl, ssl_kerberos\n"
+    printf "    Default: plaintext\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--tag TAG")"
+    printf "    🎯 Confluent Platform (CP) version to use\n    \n    Must be greater or equal to 5.0.0\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--enable-ksqldb")"
+    printf "    🚀 Enable ksqlDB\n    \n    By default, ksqldb-server and ksqldb-cli containers are not started for\n    every test\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--enable-control-center")"
+    printf "    💠 Enable Control Center\n    \n    By default, control-center container is not started for every test\n    \n    Control Center is reachable at http://127.0.0.1:9021\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--enable-conduktor")"
+    printf "    🐺 Enable Conduktor Platform\n    \n    By default, Conduktor Platform container is not started for every test\n    \n    Conduktor is reachable at http://127.0.0.1:8080/console (admin/admin)\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--enable-multiple-brokers")"
+    printf "    3️⃣ Enable multiple brokers\n    \n    By default, there is only one broker node enabled\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--enable-multiple-connect-workers")"
+    printf "    🥉 Enable multiple connect node\n    \n    By default, there is only one connect node enabled\n    \n    It only works when plaintext environment is used\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--enable-jmx-grafana")"
+    printf "    Enable Grafana, Prometheus and Pyroscope\n    \n    📊 Grafana is reachable at http://127.0.0.1:3000 (login/password is\n    admin/password)\n    \n    🛡️ Prometheus is reachable at http://127.0.0.1:9090\n    \n    📛 Pyroscope is reachable at http://127.0.0.1:4040\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--enable-kcat")"
+    printf "    🐈‍⬛ Enable kcat\n    \n    You can use it with:\n    \n    $ docker exec kcat kcat -b broker:9092 -L\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--enable-sr-maven-plugin-app")"
+    printf "    🔰 Enable Schema Registry Maven plugin App\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    echo "  ARGUMENTS..."
+    printf "    Arguments to use by script\n    \n    Most of examples support to get required options either by using arguments\n    or environment variables.\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground start-environment\n"
+    printf "  playground start-environment --environment rbac-sasl-plain\n"
     echo
 
   fi
@@ -9396,6 +9495,82 @@ playground_re_run_command() {
 }
 
 # :command.function
+playground_start_environment_command() {
+  # src/start_environment_command.sh
+  IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
+
+  DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+  dir1=$(echo ${DIR_CLI%/*})
+  root_folder=$(echo ${dir1%/*})
+
+  environment="${args[--environment]}"
+  tag="${args[--tag]}"
+  enable_ksqldb="${args[--enable-ksqldb]}"
+  enable_c3="${args[--enable-control-center]}"
+  enable_conduktor="${args[--enable-conduktor]}"
+  enable_multiple_brokers="${args[--enable-multiple-brokers]}"
+  enable_multiple_connect_workers="${args[--enable-multiple-connect-workers]}"
+  enable_jmx_grafana="${args[--enable-jmx-grafana]}"
+  enable_kcat="${args[--enable-kcat]}"
+  enable_sr_maven_plugin_app="${args[--enable-sr-maven-plugin-app]}"
+
+  flag_list=""
+  if [[ -n "$tag" ]]
+  then
+    flag_list="--tag=$tag"
+  fi
+
+  if [[ -n "$enable_ksqldb" ]]
+  then
+    flag_list="$flag_list --enable-ksqldb"
+  fi
+
+  if [[ -n "$enable_c3" ]]
+  then
+    flag_list="$flag_list --enable-control-center"
+  fi
+
+  if [[ -n "$enable_conduktor" ]]
+  then
+    flag_list="$flag_list --enable-conduktor"
+  fi
+
+  if [[ -n "$enable_multiple_brokers" ]]
+  then
+    flag_list="$flag_list --enable-multiple-broker"
+  fi
+
+  if [[ -n "$enable_multiple_connect_workers" ]]
+  then
+    flag_list="$flag_list --enable-multiple-connect-workers"
+  fi
+
+  if [[ -n "$enable_jmx_grafana" ]]
+  then
+    flag_list="$flag_list --enable-jmx-grafana"
+  fi
+
+  if [[ -n "$enable_kcat" ]]
+  then
+    flag_list="$flag_list --enable-kcat"
+  fi
+
+  if [[ -n "$enable_sr_maven_plugin_app" ]]
+  then
+    flag_list="$flag_list --enable-sr-maven-plugin-app"
+  fi
+
+  if [ "$environment" = "ccloud" ]
+  then
+    test_file="$root_folder/ccloud/environment/start.sh"
+  else
+    test_file="$root_folder/environment/$environment/start.sh"
+  fi
+
+  playground run -f $test_file $flag_list ${other_args[*]}
+}
+
+# :command.function
 playground_run_ccloud_command() {
   # src/run_ccloud_command.sh
   DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
@@ -15727,6 +15902,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    start-environment)
+      action="start-environment"
+      shift
+      playground_start_environment_parse_requirements "$@"
+      shift $#
+      ;;
+
     run-ccloud)
       action="run-ccloud"
       shift
@@ -17036,6 +17218,163 @@ playground_re_run_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_start_environment_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_start_environment_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="start-environment"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --environment)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--environment']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--environment requires an argument: --environment ENVIRONMENT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --tag)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_minimal_cp_version "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--tag TAG" "$(validate_minimal_cp_version "$2")" >&2
+            exit 1
+          fi
+
+          args['--tag']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--tag requires an argument: --tag TAG" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --enable-ksqldb)
+
+        # :flag.case_no_arg
+        args['--enable-ksqldb']=1
+        shift
+        ;;
+
+      # :flag.case
+      --enable-control-center)
+
+        # :flag.case_no_arg
+        args['--enable-control-center']=1
+        shift
+        ;;
+
+      # :flag.case
+      --enable-conduktor)
+
+        # :flag.case_no_arg
+        args['--enable-conduktor']=1
+        shift
+        ;;
+
+      # :flag.case
+      --enable-multiple-brokers)
+
+        # :flag.case_no_arg
+        args['--enable-multiple-brokers']=1
+        shift
+        ;;
+
+      # :flag.case
+      --enable-multiple-connect-workers)
+
+        # :flag.case_no_arg
+        args['--enable-multiple-connect-workers']=1
+        shift
+        ;;
+
+      # :flag.case
+      --enable-jmx-grafana)
+
+        # :flag.case_no_arg
+        args['--enable-jmx-grafana']=1
+        shift
+        ;;
+
+      # :flag.case
+      --enable-kcat)
+
+        # :flag.case_no_arg
+        args['--enable-kcat']=1
+        shift
+        ;;
+
+      # :flag.case
+      --enable-sr-maven-plugin-app)
+
+        # :flag.case_no_arg
+        args['--enable-sr-maven-plugin-app']=1
+        shift
+        ;;
+
+      --)
+        shift
+        other_args+=("$@")
+        break
+        ;;
+
+      -?*)
+        other_args+=("$1")
+        shift
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_catch_all
+        other_args+=("$1")
+        shift
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--environment']:-} ]] || args['--environment']="plaintext"
+
+  # :command.whitelist_filter
+  if [[ ${args['--environment']} ]] && [[ ! ${args['--environment']} =~ ^(ccloud|2way-ssl|kerberos|kraft-external-plaintext|kraft-plaintext|ldap-authorizer-sasl-plain|ldap-sasl-plain|mdc-kerberos|mdc-plaintext|mdc-sasl-plain|plaintext|rbac-sasl-plain|sasl-plain|sasl-scram|sasl-ssl|ssl_kerberos)$ ]]; then
+    printf "%s\n" "--environment must be one of: ccloud, 2way-ssl, kerberos, kraft-external-plaintext, kraft-plaintext, ldap-authorizer-sasl-plain, ldap-sasl-plain, mdc-kerberos, mdc-plaintext, mdc-sasl-plain, plaintext, rbac-sasl-plain, sasl-plain, sasl-scram, sasl-ssl, ssl_kerberos" >&2
+    exit 1
+  fi
 
 }
 
@@ -24122,6 +24461,7 @@ run() {
     "bashly-reload") playground_bashly_reload_command ;;
     "run") playground_run_command ;;
     "re-run") playground_re_run_command ;;
+    "start-environment") playground_start_environment_command ;;
     "run-ccloud") playground_run_ccloud_command ;;
     "update-version") playground_update_version_command ;;
     "open") playground_open_command ;;
