Added playground open

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -36,6 +36,7 @@ playground_usage() {
   printf "%s\n" "$(bold "Run commands:")"
   printf "  %s   🚀 Run example\n" "$(green "run")                           "
   printf "  %s   ⚡ Simply re-run last example you ran with <playground run>\n" "$(green "re-run")                        "
+  printf "  %s   👐 Simply open last example you ran with <playground run>\n" "$(green "open")                          "
   echo
   printf "%s\n" "$(bold "Bootstrap commands:")"
   printf "  %s   🛠  Bootstrap reproduction model\n" "$(green "bootstrap-reproduction-model")  "
@@ -452,6 +453,43 @@ playground_re_run_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground re-run\n"
   printf "  playground re-run --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_environment_variables
+    printf "%s\n" "$(bold "Environment Variables:")"
+
+    # :environment_variable.usage
+    printf "  %s\n" "$(cyan "EDITOR")"
+    printf "    🔖 Editor to use to open the example file\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_open_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground open - 👐 Simply open last example you ran with <playground run>\n"
+    echo
+
+  else
+    printf "playground open - 👐 Simply open last example you ran with <playground run>\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground open\n"
+  printf "  playground open --help | -h\n"
   echo
 
   # :command.long_usage
@@ -6171,13 +6209,49 @@ playground_re_run_command() {
   if [ ! -f /tmp/playground-run ]
   then
     logerror "File containing re-run command /tmp/playground-run does not exist!"
-    logerror "Make sure to run playground run command !"
+    logerror "Make sure to use <playground run> command !"
     exit 1
   fi
 
   log "Run command again:"
   cat /tmp/playground-run
   bash /tmp/playground-run
+}
+
+# :command.function
+playground_open_command() {
+  # src/open_command.sh
+  if [ ! -f /tmp/playground-run ]
+  then
+    logerror "File containing re-run command /tmp/playground-run does not exist!"
+    logerror "Make sure to use <playground run> command !"
+    exit 1
+  fi
+
+  test_file=$(cat /tmp/playground-run | awk '{ print $4}')
+
+  if [ ! -f $test_file ]
+  then
+
+    logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
+    logerror "Make sure to use <playground run> command !"
+    exit 1
+  fi
+
+  if [ ! -z $EDITOR ]
+  then
+      log "📖 Opening ${test_file} using EDITOR environment variable"
+      $EDITOR ${test_file}
+  else
+      if [[ $(type code 2>&1) =~ "not found" ]]
+      then
+          logerror "Could not determine an editor to use, you can set EDITOR environment variable with your preferred choice"
+          exit 1
+      else
+          log "📖 Opening ${test_file} with code (you can change editor by setting EDITOR environment variable)"
+          code ${test_file}
+      fi
+  fi
 }
 
 # :command.function
@@ -7484,7 +7558,7 @@ playground_topic_consume_command() {
   if [ ! -f /tmp/playground-run ]
   then
     logerror "File containing re-run command /tmp/playground-run does not exist!"
-    logerror "Make sure to run playground run command !"
+    logerror "Make sure to use <playground run> command !"
     exit 1
   fi
 
@@ -8015,6 +8089,13 @@ parse_requirements() {
       action="re-run"
       shift
       playground_re_run_parse_requirements "$@"
+      shift $#
+      ;;
+
+    open)
+      action="open"
+      shift
+      playground_open_parse_requirements "$@"
       shift $#
       ;;
 
@@ -8717,6 +8798,52 @@ playground_re_run_parse_requirements() {
 
   # :command.command_filter
   action="re-run"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_open_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_open_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+
+  # :command.command_filter
+  action="open"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -11456,6 +11583,15 @@ run() {
         playground_re_run_usage
       else
         playground_re_run_command
+      fi
+      ;;
+
+    "open")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        playground_open_usage
+      else
+        playground_open_command
       fi
       ;;
 
