wip #5730

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -165,6 +165,10 @@ playground_usage() {
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "connector create-or-update")               "
   printf "  %s   🛠️ Update connector configuration by opening current connector config in text editor set with playground config editor <editor> (default is code). Once file is saved, the new configuration is updated.\n" "$(green "connector update")                         "
   echo
+  printf "%s\n" "$(bold "ec2 commands:")"
+  printf "  %s   😶‍🌫️ AWS EC2 instance (using Cloud Formation)\n" "$(green "ec2")                                      "
+  printf "  %s   🏭 Create an EC2 instance using Cloud Formation\n" "$(green "ec2 create")                               "
+  echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
@@ -6578,6 +6582,107 @@ playground_connector_update_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground connector update -c filestream-sink\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ec2_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground ec2\n"
+    echo
+
+    printf "  😶‍🌫️ AWS EC2 instance (using Cloud Formation)\n  \n  ✨ Create and manage AWS EC2 instances to run kafka-docker-playground\n  \n  🪄 Open EC2 instances directly in Visual Studio code using Remote Development\n  (over SSH)\n"
+    echo
+
+  else
+    printf "playground ec2 - 😶‍🌫️ AWS EC2 instance (using Cloud Formation)\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ec2 COMMAND\n"
+  printf "  playground ec2 [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "$(bold "== Commands ==")"
+  printf "  %s   🏭 Create an EC2 instance using Cloud Formation\n" "$(green "create")"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ec2_create_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground ec2 create - 🏭 Create an EC2 instance using Cloud Formation\n"
+    echo
+
+  else
+    printf "playground ec2 create - 🏭 Create an EC2 instance using Cloud Formation\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ec2 create [OPTIONS]\n"
+  printf "  playground ec2 create --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--pem-file PEM-FILE")"
+    printf "    🔐 AWS EC2 pem file\n    \n    ❕ It must be absolute full path\n    \n    You can also specify it with EC2_CLOUD_FORMATION_PEM_FILE environment\n    variable\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--cloud-formation-yml-file CLOUD-FORMATION-YML-FILE")"
+    printf "    🌀 Cloud Formation yml file\n    \n    ❕ It must be absolute full path\n    \n    If not set default is used\n    https://github.com/vdesabou/kafka-docker-playground/blob/master/cloudformation/alfred-aws-vscode-workflow/kafka-docker-playground.yml\n    \n    You can also specify it with EC2_CLOUD_FORMATION_YML_FILE environment\n    variable\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--instance-type INSTANCE-TYPE")"
+    printf "    🧑‍💻 instance type. default is t3.2xlarge\n"
+    printf "    Allowed: c1.medium, c1.xlarge, c3.2xlarge, c3.4xlarge, c3.8xlarge, c3.large, c3.xlarge, c4.2xlarge, c4.4xlarge, c4.large, c4.xlarge, m1.large, m1.medium, m1.small, m1.xlarge, m2.2xlarge, m2.4xlarge, m2.xlarge, m3.2xlarge, m3.large, m3.medium, m3.xlarge, m4.10xlarge, m4.2xlarge, m4.4xlarge, m4.large, m4.xlarge, t1.micro, t2.large, t2.medium, t2.micro, t2.nano, t2.small, t3.2xlarge\n"
+    printf "    Default: t3.2xlarge\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--region REGION")"
+    printf "    🌍 instance region. default is eu-west-3\n"
+    printf "    Allowed: ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, cn-north-1, cn-northwest-1, eu-central-1, eu-north-1, eu-west-1, eu-west-2, eu-west-3, sa-east-1, us-east-1, us-east-2, us-west-1, us-west-2\n"
+    printf "    Default: eu-west-3\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--size SIZE")"
+    printf "    💾 instance size in Gb. default is 1000 Gb\n"
+    printf "    Default: 1000\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--suffix SUFFIX")"
+    printf "    📮 suffix to add to instance name\n    kafka-docker-playground-${username}-${suffix}\n    \n    If not set, default is kafka-docker-playground-${username}-${current-date}\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -24636,6 +24741,105 @@ playground_connector_update_command() {
 
 }
 
+# :command.function
+playground_ec2_create_command() {
+  # src/commands/ec2/create.sh
+  pem_file="${args[--pem-file]}"
+  cloud_formation_yml_file="${args[--cloud-formation-yml-file]}"
+  suffix="${args[--suffix]}"
+  aws_region="${args[--region]}"
+  instance_type="${args[--instance-type]}"
+  ec2_size="${args[--size]}"
+
+  if [[ -n "$pem_file" ]]
+  then
+      if [[ $pem_file == *"@"* ]]
+      then
+          pem_file=$(echo "$pem_file" | cut -d "@" -f 2)
+      fi
+  elif [[ -n "$EC2_CLOUD_FORMATION_PEM_FILE" ]]
+  then
+      pem_file="$EC2_CLOUD_FORMATION_PEM_FILE"
+      if [ ! -f "$EC2_CLOUD_FORMATION_PEM_FILE" ]
+      then
+          logerror "❌ EC2_CLOUD_FORMATION_PEM_FILE is set with $EC2_CLOUD_FORMATION_PEM_FILE but the file does not exist"
+          exit 1
+      fi
+  else
+      logerror "❌ --pem-file or EC2_CLOUD_FORMATION_PEM_FILE is required"
+      exit 1
+  fi
+
+  if [[ -n "$cloud_formation_yml_file" ]]
+  then
+      if [[ $cloud_formation_yml_file == *"@"* ]]
+      then
+          cloud_formation_yml_file=$(echo "$cloud_formation_yml_file" | cut -d "@" -f 2)
+      fi
+  elif [[ -n "$EC2_CLOUD_FORMATION_YML_FILE" ]]
+  then
+      cloud_formation_yml_file="$EC2_CLOUD_FORMATION_YML_FILE"
+      if [ ! -f "$cloud_formation_yml_file" ]
+      then
+          logerror "❌ EC2_CLOUD_FORMATION_YML_FILE is set with $EC2_CLOUD_FORMATION_YML_FILE but the file does not exist"
+          exit 1
+      fi
+  else
+      cloud_formation_yml_file="$root_folder/cloudformation/alfred-aws-vscode-workflow/kafka-docker-playground.yml"
+      if [ ! -f "$cloud_formation_yml_file" ]
+      then
+          logerror "❌ cloud_formation_yml_file is set with $cloud_formation_yml_file but the file does not exist"
+          exit 1
+      fi
+  fi
+
+  username=$(whoami)
+  if [[ -n "$suffix" ]]
+  then
+      suffix_kebab="${suffix// /-}"
+      suffix_kebab=$(echo "$suffix_kebab" | tr '[:upper:]' '[:lower:]')
+  else
+      suffix_kebab=$(date +%F)
+  fi
+  name="kafka-docker-playground-${username}-${suffix_kebab}"
+  myip=$(dig @resolver4.opendns.com myip.opendns.com +short)
+  key_name=$(basename $pem_file .pem)
+
+  cd /tmp
+  cp "$cloud_formation_yml_file" tmp.yml
+
+  log "🏭 creating ${instance_type} instance $name in $aws_region region (${ec2_size} Gb)"
+  log "🌀 cloud formation file used: $cloud_formation_yml_file"
+  log "🔐 ec2 pem file used: $pem_file"
+  log "aws cloudformation create-stack --stack-name $name --template-body "file://tmp.yml" --region ${aws_region} --parameters ParameterKey=InstanceType,ParameterValue=${instance_type} ParameterKey=Ec2RootVolumeSize,ParameterValue=${ec2_size} ParameterKey=KeyName,ParameterValue=${key_name} ParameterKey=InstanceName,ParameterValue=$name ParameterKey=IPAddressRange,ParameterValue=${myip}/32 ParameterKey=SecretsEncryptionPassword,ParameterValue="${SECRETS_ENCRYPTION_PASSWORD}" ParameterKey=LinuxUserName,ParameterValue="${username}""
+  cd -
+
+  # ParameterKey=GithubSshKeyFile,ParameterValue="${github_ssh_key_file_content}"
+
+  log "Sleeping 4 minutes"
+  sleep 240
+
+  for row in $(aws ec2 describe-instances | jq '[.Reservations | .[] | .Instances | .[] | {KeyName: .KeyName, LaunchTime: .LaunchTime, PublicDnsName: .PublicDnsName, InstanceId: .InstanceId, InstanceType: .InstanceType,State: .State.Name, Name: (.Tags[]|select(.Key=="Name")|.Value)}]' | jq -r '.[] | @base64'); do
+      _jq() {
+       echo ${row} | base64 --decode | jq -r ${1}
+      }
+
+      KeyName=$(echo $(_jq '.KeyName'))
+      LaunchTime=$(echo $(_jq '.LaunchTime'))
+      PublicDnsName=$(echo $(_jq '.PublicDnsName'))
+      Name=$(echo $(_jq '.Name'))
+      InstanceId=$(echo $(_jq '.InstanceId'))
+      InstanceType=$(echo $(_jq '.InstanceType'))
+      State=$(echo $(_jq '.State'))
+
+      if [ "$Name" == "$name" ]
+      then
+          log "Starting $Name ($InstanceId)"
+          #ksh ./ec2openec2.ksh "$PublicDnsName|$Name|$InstanceId|$State"
+      fi
+  done
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
@@ -25043,6 +25247,13 @@ parse_requirements() {
       action="connector"
       shift
       playground_connector_parse_requirements "$@"
+      shift $#
+      ;;
+
+    ec2)
+      action="ec2"
+      shift
+      playground_ec2_parse_requirements "$@"
       shift $#
       ;;
 
@@ -36888,6 +37099,234 @@ playground_connector_update_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+playground_ec2_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ec2_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    create)
+      action="create"
+      shift
+      playground_ec2_create_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      playground_ec2_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_ec2_create_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ec2_create_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="ec2 create"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --pem-file)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--pem-file']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--pem-file requires an argument: --pem-file PEM-FILE" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --cloud-formation-yml-file)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--cloud-formation-yml-file']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--cloud-formation-yml-file requires an argument: --cloud-formation-yml-file CLOUD-FORMATION-YML-FILE" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --instance-type)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--instance-type']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--instance-type requires an argument: --instance-type INSTANCE-TYPE" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --region)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--region']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--region requires an argument: --region REGION" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --size)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--size']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--size requires an argument: --size SIZE" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --suffix)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--suffix']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--suffix requires an argument: --suffix SUFFIX" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--instance-type']:-} ]] || args['--instance-type']="t3.2xlarge"
+  [[ -n ${args['--region']:-} ]] || args['--region']="eu-west-3"
+  [[ -n ${args['--size']:-} ]] || args['--size']="1000"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--pem-file'] && -n $(validate_file_exists_with_trick "${args['--pem-file']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--pem-file PEM-FILE" "$(validate_file_exists_with_trick "${args['--pem-file']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--cloud-formation-yml-file'] && -n $(validate_file_exists_with_trick "${args['--cloud-formation-yml-file']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--cloud-formation-yml-file CLOUD-FORMATION-YML-FILE" "$(validate_file_exists_with_trick "${args['--cloud-formation-yml-file']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--size'] && -n $(validate_integer "${args['--size']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--size SIZE" "$(validate_integer "${args['--size']:-}")" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ ${args['--instance-type']:-} ]] && [[ ! ${args['--instance-type']:-} =~ ^(c1.medium|c1.xlarge|c3.2xlarge|c3.4xlarge|c3.8xlarge|c3.large|c3.xlarge|c4.2xlarge|c4.4xlarge|c4.large|c4.xlarge|m1.large|m1.medium|m1.small|m1.xlarge|m2.2xlarge|m2.4xlarge|m2.xlarge|m3.2xlarge|m3.large|m3.medium|m3.xlarge|m4.10xlarge|m4.2xlarge|m4.4xlarge|m4.large|m4.xlarge|t1.micro|t2.large|t2.medium|t2.micro|t2.nano|t2.small|t3.2xlarge)$ ]]; then
+    printf "%s\n" "--instance-type must be one of: c1.medium, c1.xlarge, c3.2xlarge, c3.4xlarge, c3.8xlarge, c3.large, c3.xlarge, c4.2xlarge, c4.4xlarge, c4.large, c4.xlarge, m1.large, m1.medium, m1.small, m1.xlarge, m2.2xlarge, m2.4xlarge, m2.xlarge, m3.2xlarge, m3.large, m3.medium, m3.xlarge, m4.10xlarge, m4.2xlarge, m4.4xlarge, m4.large, m4.xlarge, t1.micro, t2.large, t2.medium, t2.micro, t2.nano, t2.small, t3.2xlarge" >&2
+    exit 1
+  fi
+  if [[ ${args['--region']:-} ]] && [[ ! ${args['--region']:-} =~ ^(ap-northeast-1|ap-northeast-2|ap-northeast-3|ap-south-1|ap-southeast-1|ap-southeast-2|ca-central-1|cn-north-1|cn-northwest-1|eu-central-1|eu-north-1|eu-west-1|eu-west-2|eu-west-3|sa-east-1|us-east-1|us-east-2|us-west-1|us-west-2)$ ]]; then
+    printf "%s\n" "--region must be one of: ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, cn-north-1, cn-northwest-1, eu-central-1, eu-north-1, eu-west-1, eu-west-2, eu-west-3, sa-east-1, us-east-1, us-east-2, us-west-1, us-west-2" >&2
+    exit 1
+  fi
+
+}
+
 # :command.user_hooks
 before_hook() {
   # src/before.sh
@@ -37083,6 +37522,8 @@ run() {
     "connector open-in-confluent-cloud") playground_connector_open_in_confluent_cloud_command ;;
     "connector create-or-update") playground_connector_create_or_update_command ;;
     "connector update") playground_connector_update_command ;;
+    "ec2") playground_ec2_command ;;
+    "ec2 create") playground_ec2_create_command ;;
   esac
 }
 
