wip 👾 Add playground connector-plugin sourcecode commands Fixes #7214

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -165,6 +165,7 @@ playground_usage() {
   printf "  %s   🎨 Show all connector plugins installed. You can also display transforms, converters and predicates using --all flag\n" "$(green "connector plugins")                         "
   printf "  %s   ⏸️  Pause connector\n" "$(green "connector pause")                           "
   printf "  %s   🧞 Get current and latest versions available on Confluent Hub for connector(s) used in example\n" "$(green "connector versions")                        "
+  printf "  %s   🧑‍💻 open source code url for connector(s) used in example\n" "$(green "connector sourcecode")                      "
   printf "  %s   ♻️  Restart connector\n" "$(green "connector restart")                         "
   printf "  %s   🛑 Stop connector (only available if CP > 7.5)\n" "$(green "connector stop")                            "
   printf "  %s   ⏯️  Resume connector\n" "$(green "connector resume")                          "
@@ -5610,7 +5611,7 @@ playground_connector_plugin_display_last_updated_usage() {
 
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
-    printf "  playground connector-plugin display-last-updated --days 7\n  playground connector-plugin display-last-updated --days 7 --vendor\n  confluentinc\n"
+    printf "  playground connector-plugin display-last-updated --days 7\n"
     echo
 
   fi
@@ -5669,6 +5670,7 @@ playground_connector_usage() {
   printf "  %s   🎨 Show all connector plugins installed. You can also display transforms, converters and predicates using --all flag\n" "$(green "plugins")                         "
   printf "  %s   ⏸️  Pause connector\n" "$(green "pause")                           "
   printf "  %s   🧞 Get current and latest versions available on Confluent Hub for connector(s) used in example\n" "$(green "versions")                        "
+  printf "  %s   🧑‍💻 open source code url for connector(s) used in example\n" "$(green "sourcecode")                      "
   printf "  %s   ♻️  Restart connector\n" "$(green "restart")                         "
   printf "  %s   🛑 Stop connector (only available if CP > 7.5)\n" "$(green "stop")                            "
   printf "  %s   ⏯️  Resume connector\n" "$(green "resume")                          "
@@ -6087,6 +6089,38 @@ playground_connector_versions_usage() {
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_sourcecode_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector sourcecode\n\n"
+    printf "  🧑‍💻 open source code url for connector(s) used in example\n  \n  You can compare different sourcecode versions by specifying --connector-tag\n  two times, in such case it will open github in comparison mode\n\n"
+  else
+    printf "playground connector sourcecode - 🧑‍💻 open source code url for connector(s) used in example\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector sourcecode [OPTIONS]\n"
+  printf "  playground connector sourcecode --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector-tag CONNECTOR_TAG (repeatable)")"
+    printf "    🔗 Connector version to use\n    \n    By default, for each connector, the current version is used\n    \n    🎓 Tip: set to \" \" in order to select the version dynamically\n    \n    🎓 Tip: you can compare different sourcecode versions by specifying\n    --connector-tag two times, in such case it will open github in comparison\n    mode\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -25805,6 +25839,114 @@ playground_connector_versions_command() {
 }
 
 # :command.function
+playground_connector_sourcecode_command() {
+
+  # src/commands/connector/sourcecode.sh
+  connector_tags="${args[--connector-tag]}"
+
+  # Convert space-separated string to array
+  IFS=' ' read -ra connector_tag_array <<< "$connector_tags"
+
+  test_file=$(playground state get run.test_file)
+
+  connector_type=$(playground state get run.connector_type)
+  if [ "$connector_type" == "$CONNECTOR_TYPE_CUSTOM" ]
+  then
+      log "connector versions command is not supported with $connector_type connector"
+      exit 0
+  fi
+
+  if [ ! -f $test_file ]
+  then
+
+      logerror "File $test_file retrieved from $root_folder/playground.ini does not exist!"
+      exit 1
+  fi
+
+  if [ "$connector_type" == "$CONNECTOR_TYPE_FULLY_MANAGED" ]
+  then
+      owner="confluentinc"
+      name=$(grep "connector.class" $test_file | head -1 | cut -d '"' -f4)
+
+      length=${#connector_tag_array[@]}
+      if ((length > 1))
+      then
+          if ((length > 2))
+          then
+              logerror "❌ --connector-tag can only be set 2 times"
+              exit 1
+          fi
+          connector_tag1="${connector_tag_array[0]}"
+          connector_tag2="${connector_tag_array[1]}"
+          playground connector-plugin sourcecode --connector-plugin "$owner/$name" --connector-tag "$connector_tag1" --connector-tag "$connector_tag2"
+      else
+          if ((length == 1))
+          then
+              connector_tag="${connector_tag_array[0]}"
+              playground connector-plugin sourcecode --connector-plugin "$owner/$name" --connector-tag "$connector_tag"
+          else
+              playground connector-plugin sourcecode --connector-plugin "$owner/$name"
+          fi
+      fi
+      exit 0
+  fi
+
+  get_connector_paths
+  if [ "$connector_paths" == "" ]
+  then
+      logwarn "❌ skipping as it is not an example with connector, but --connector-tag is set"
+      exit 1
+  else
+      for connector_path in ${connector_paths//,/ }
+      do
+          full_connector_name=$(basename "$connector_path")
+          owner=$(echo "$full_connector_name" | cut -d'-' -f1)
+          name=$(echo "$full_connector_name" | cut -d'-' -f2-)
+
+          if [ "$owner" == "java" ] || [ "$name" == "hub-components" ] || [ "$owner" == "filestream" ]
+          then
+              # happens when plugin is not coming from confluent hub
+              # logwarn "skipping as plugin $owner/$name does not appear to be coming from confluent hub"
+              continue
+          fi
+
+          # # latest
+          # latest=$(playground connector-plugin versions --connector-plugin $owner/$name --last 1)
+          # latest_to_compare=$(echo "$latest" | head -n 1 | sed 's/ ([0-9]* days ago)//')
+
+          length=${#connector_tag_array[@]}
+          if ((length > 1))
+          then
+              if ((length > 2))
+              then
+                  logerror "❌ --connector-tag can only be set 2 times"
+                  exit 1
+              fi
+              connector_tag1="${connector_tag_array[0]}"
+              connector_tag2="${connector_tag_array[1]}"
+              playground connector-plugin sourcecode --connector-plugin "$owner/$name" --connector-tag "$connector_tag1" --connector-tag "$connector_tag2"
+          else
+              if ((length == 1))
+              then
+                  connector_tag="${connector_tag_array[0]}"
+                  playground connector-plugin sourcecode --connector-plugin "$owner/$name" --connector-tag "$connector_tag"
+              else
+                  manifest_file="$root_folder/confluent-hub/$full_connector_name/manifest.json"
+                  if [ -f $manifest_file ]
+                  then
+                      version=$(cat $manifest_file | jq -r '.version')
+                      playground connector-plugin sourcecode --connector-plugin "$owner/$name" --connector-tag "$version"
+                  else
+                      logwarn "file $manifest_file does not exist, could not retrieve version"
+                      exit 0
+                  fi
+              fi
+          fi
+      done
+  fi
+}
+
+# :command.function
 playground_connector_restart_command() {
 
   # src/commands/connector/restart.sh
@@ -41540,6 +41682,13 @@ playground_connector_parse_requirements() {
       shift $#
       ;;
 
+    sourcecode)
+      action="sourcecode"
+      shift
+      playground_connector_sourcecode_parse_requirements "$@"
+      shift $#
+      ;;
+
     restart)
       action="restart"
       shift
@@ -42438,6 +42587,69 @@ playground_connector_versions_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_connector_sourcecode_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_sourcecode_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector sourcecode"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connector-tag)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          escaped="$(printf '%q' "$2")"
+          if [[ -z ${args['--connector-tag']+x} ]]; then
+            args['--connector-tag']="$escaped"
+          else
+            args['--connector-tag']="${args['--connector-tag']} $escaped"
+          fi
+          shift
+          shift
+        else
+          printf "%s\n" "--connector-tag requires an argument: --connector-tag CONNECTOR_TAG" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -45134,6 +45346,7 @@ run() {
     "connector plugins") playground_connector_plugins_command ;;
     "connector pause") playground_connector_pause_command ;;
     "connector versions") playground_connector_versions_command ;;
+    "connector sourcecode") playground_connector_sourcecode_command ;;
     "connector restart") playground_connector_restart_command ;;
     "connector stop") playground_connector_stop_command ;;
     "connector resume") playground_connector_resume_command ;;
