fix 🐛 connect/connect-ftps-sink/ftps-sink.sh should return 111 exit code #7226

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -9332,13 +9332,13 @@ function verbose_begin () {
 }
 
 function verbose_end () {
-  ret="$?"
+  return_code="$?"
   # If set -x was initially active, re-enable it
   if [[ $was_x_set -eq 1 ]]
   then
     set -x
   fi
-  return $ret
+  return $return_code
 }
 
 function log() {
@@ -16718,6 +16718,9 @@ playground_run_command() {
   SECONDS=0
   cd $test_file_directory
   function cleanup {
+    # 💡 Capture the original exit status immediately!
+    local original_exit_status=$?
+    set +e
     if [[ -n "$enable_multiple_connect_workers" ]]
     then
       if [ -f /tmp/playground-backup-docker-compose.yml ]
@@ -16728,14 +16731,12 @@ playground_run_command() {
     rm /tmp/playground-run-command-used
     echo ""
     sleep 3
-    set +e
 
     connector_type=$(playground state get run.connector_type)
 
     if [ "$connector_type" == "$CONNECTOR_TYPE_ONPREM" ] || [ "$connector_type" == "$CONNECTOR_TYPE_SELF_MANAGED" ]
     then
         # playground connector-plugin display-last-updated
-      set +e
       if ! pgrep -f "playground connector-plugin display-last-updated" > /dev/null
       then
         if [ -f ${connector_plugin_display_last_updated_file} ]
@@ -16745,7 +16746,6 @@ playground_run_command() {
       fi
 
       playground connector versions
-      set -e
     fi
 
     if [ "$connector_type" == "$CONNECTOR_TYPE_FULLY_MANAGED" ] || [ "$connector_type" == "$CONNECTOR_TYPE_CUSTOM" ]
@@ -16774,7 +16774,8 @@ playground_run_command() {
     then
       playground connector open-docs --only-show-url
     fi
-    set -e
+    # 💡 Exit the function (and the script) with the captured status
+    exit "$original_exit_status"
   }
   trap cleanup EXIT
 
@@ -16820,7 +16821,7 @@ playground_run_command() {
       log "🧑‍🚒 open full logs with '<playground container logs --open --container <container>', example:"
       echo "playground container logs --open --container connect"
     fi
-    exit 1
+    exit $ret
   fi
   check_for_ec2_instance_running
 
