add -f option for open command

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -333,6 +333,43 @@ playground_get_schema_with_fzf_usage() {
 }
 
 # :command.usage
+playground_get_any_file_with_fzf_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground get-any-file-with-fzf - Return some completion for any files\n"
+    echo
+
+  else
+    printf "playground get-any-file-with-fzf - Return some completion for any files\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground get-any-file-with-fzf [CUR]\n"
+  printf "  playground get-any-file-with-fzf --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "CUR")"
+    printf "    correspond to completion $cur\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 playground_bashly_reload_usage() {
   if [[ -n $long_usage ]]; then
     printf "playground bashly-reload\n"
@@ -721,13 +758,19 @@ playground_open_usage() {
   fi
 
   printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground open\n"
+  printf "  playground open [OPTIONS]\n"
   printf "  playground open --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--file, -f FILE (required)")"
+    printf "    🔎 Search any file and open it.\n    \n    ❕ It must be absolute full path\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -2677,6 +2720,28 @@ function get_schema_with_fzf() {
   folder_producer_schema=${folder_producer_schema//,/ }
 
   res=$(find $folder_producer_schema $PWD -type f \( -name "*.avsc" -o -name "*.json" -o -name "*.proto" -o -name "*.proto3" \) ! -path '*/\.*' | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🍺" --header="ctrl-c or esc to quit" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+}
+
+function get_any_files_with_fzf() {
+  DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+  dir1=$(echo ${DIR_CLI%/*})
+  dir2=$(echo ${dir1%/*})
+
+  cur="$1"
+
+  fzf_version=$(get_fzf_version)
+  if version_gt $fzf_version "0.38"
+  then
+    fzf_option_wrap="--preview-window=40%,wrap"
+    fzf_option_pointer="--pointer=👉"
+    fzf_option_rounded="--border=rounded"
+  else
+    fzf_options=""
+    fzf_option_pointer=""
+    fzf_option_rounded=""
+  fi
+
+  res=$(find $dir2 -type f ! -path '*/\.*' | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🍺" --header="ctrl-c or esc to quit" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
 }
 
 function filter_not_mdc_environment() {
@@ -6528,6 +6593,14 @@ playground_get_schema_with_fzf_command() {
 }
 
 # :command.function
+playground_get_any_file_with_fzf_command() {
+  # src/get_any_file_with_fzf_command.sh
+  cur="${args[cur]}"
+
+  get_any_files_with_fzf "$cur"
+}
+
+# :command.function
 playground_bashly_reload_command() {
   # src/bashly_reload_command.sh
   DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
@@ -7069,21 +7142,31 @@ playground_run_ccloud_command() {
 # :command.function
 playground_open_command() {
   # src/open_command.sh
-  if [ ! -f /tmp/playground-run ]
+  test_file="${args[--file]}"
+
+  if [[ -n "$test_file" ]]
   then
-    logerror "File containing run command /tmp/playground-run does not exist!"
-    logerror "Make sure to use <playground run> command !"
-    exit 1
-  fi
+    if [[ $test_file == *"@"* ]]
+    then
+      test_file=$(echo "$test_file" | cut -d "@" -f 2)
+    fi
+  else
+    if [ ! -f /tmp/playground-run ]
+    then
+      logerror "File containing run command /tmp/playground-run does not exist!"
+      logerror "Make sure to use <playground run> command !"
+      exit 1
+    fi
 
-  test_file=$(cat /tmp/playground-run | awk '{ print $4}')
+    test_file=$(cat /tmp/playground-run | awk '{ print $4}')
 
-  if [ ! -f $test_file ]
-  then
+    if [ ! -f $test_file ]
+    then
 
-    logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
-    logerror "Make sure to use <playground run> command !"
-    exit 1
+      logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
+      logerror "Make sure to use <playground run> command !"
+      exit 1
+    fi
   fi
 
   if config_has_key "editor"
@@ -9257,6 +9340,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    get-any-file-with-fzf)
+      action="get-any-file-with-fzf"
+      shift
+      playground_get_any_file_with_fzf_parse_requirements "$@"
+      shift $#
+      ;;
+
     bashly-reload)
       action="bashly-reload"
       shift
@@ -9716,6 +9806,56 @@ playground_get_schema_with_fzf_parse_requirements() {
 
   # :command.command_filter
   action="get-schema-with-fzf"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['cur']+x} ]]; then
+
+          args['cur']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_get_any_file_with_fzf_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_get_any_file_with_fzf_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="get-any-file-with-fzf"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -10622,6 +10762,25 @@ playground_open_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --file | -f)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_file_exists_with_trick "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--file, -f FILE" "$(validate_file_exists_with_trick "$2")" >&2
+            exit 1
+          fi
+
+          args['--file']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--file requires an argument: --file, -f FILE" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -10638,6 +10797,12 @@ playground_open_parse_requirements() {
 
     esac
   done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--file']+x} ]]; then
+    printf "missing required flag: --file, -f FILE\n" >&2
+    exit 1
+  fi
 
 }
 
@@ -13708,6 +13873,7 @@ run() {
     "get-examples-list-with-fzf") playground_get_examples_list_with_fzf_command ;;
     "get-zip-or-jar-with-fzf") playground_get_zip_or_jar_with_fzf_command ;;
     "get-schema-with-fzf") playground_get_schema_with_fzf_command ;;
+    "get-any-file-with-fzf") playground_get_any_file_with_fzf_command ;;
     "bashly-reload") playground_bashly_reload_command ;;
     "run") playground_run_command ;;
     "re-run") playground_re_run_command ;;
