fix

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -8753,7 +8753,7 @@ function bootstrap_ccloud_environment () {
         unset SCHEMA_REGISTRY_CREDS
       fi
     fi
-    log "🔋  CLUSTER_TYPE is set with $CLUSTER_TYPE"
+    log "🔋 CLUSTER_TYPE is set with $CLUSTER_TYPE"
     log "🌤  CLUSTER_CLOUD is set with $CLUSTER_CLOUD"
     log "🗺  CLUSTER_REGION is set with $CLUSTER_REGION"
 
@@ -10871,14 +10871,17 @@ function handle_ccloud_connect_rest_api () {
           code=$(echo "$curl_output" | jq -r .error_code)
           message=$(echo "$curl_output" | jq -r .message)
         fi
+        logerror "Command failed with error code $code"
+        logerror "$message"
+        exit 1
       elif echo "$curl_output" | jq 'has("errors")' 2> /dev/null | grep -q true
       then
         code=$(echo "$curl_output" | jq -r '.errors[0].status')
         message=$(echo "$curl_output" | jq -r '.errors[0].detail')
+        logerror "Command failed with error code $code"
+        logerror "$message"
+        exit 1
       fi
-      logerror "Command failed with error code $code"
-      logerror "$message"
-      exit 1
   else
     logerror "❌ curl request failed with error code $ret!"
     exit 1
