Document that bash version 4 is now mandatory to run examples #3918

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1895,7 +1895,7 @@ playground_topic_consume_usage() {
     echo
 
     # :flag.usage
-    printf "  %s\n" "$(magenta "--min-expected-messages  --timeout 60MIN-EXPECTED-MESSAGES")"
+    printf "  %s\n" "$(magenta "--min-expected-messages MIN-EXPECTED-MESSAGES")"
     printf "    Minimum expected number of messages to be present in topic, returns an error\n    if this is not the case\n    \n    Note: --topic should be specified in this case.\n"
     printf "    Default: \n"
     echo
@@ -3446,7 +3446,23 @@ function check_docker_compose_version() {
   DOCKER_COMPOSE_VER=$(get_docker_compose_version)
 
   if version_gt $REQUIRED_DOCKER_COMPOSE_VER $DOCKER_COMPOSE_VER; then
-    log "docker-compose version ${REQUIRED_DOCKER_COMPOSE_VER} or greater is required.  Current reported version: ${DOCKER_COMPOSE_VER}"
+    logerror "docker-compose version ${REQUIRED_DOCKER_COMPOSE_VER} or greater is required. Current reported version: ${DOCKER_COMPOSE_VER}"
+    exit 1
+  fi
+}
+
+function get_bash_version() {
+  bash_major_version=$(bash --version | head -n1 | awk '{print $4}')
+  major_version="${bash_major_version%%.*}"
+  echo "$major_version"
+}
+
+function check_bash_version() {
+  REQUIRED_BASH_VER=${1:-"6"}
+  BASH_VER=$(get_bash_version)
+
+  if version_gt $REQUIRED_BASH_VER $BASH_VER; then
+    logerror "bash version ${REQUIRED_BASH_VER} or greater is required. Current reported version: ${BASH_VER}"
     exit 1
   fi
 }
@@ -13160,7 +13176,7 @@ playground_topic_consume_parse_requirements() {
         if [[ -n ${2+x} ]]; then
           # :flag.validations
           if [[ -n $(validate_integer "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--min-expected-messages  --timeout 60MIN-EXPECTED-MESSAGES" "$(validate_integer "$2")" >&2
+            printf "validation error in %s:\n%s\n" "--min-expected-messages MIN-EXPECTED-MESSAGES" "$(validate_integer "$2")" >&2
             exit 1
           fi
 
@@ -13168,7 +13184,7 @@ playground_topic_consume_parse_requirements() {
           shift
           shift
         else
-          printf "%s\n" "--min-expected-messages  --timeout 60requires an argument: --min-expected-messages  --timeout 60MIN-EXPECTED-MESSAGES" >&2
+          printf "%s\n" "--min-expected-messages requires an argument: --min-expected-messages MIN-EXPECTED-MESSAGES" >&2
           exit 1
         fi
         ;;
