🧠 flink_connectors variable warnings during playground stop #6205

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -12103,7 +12103,16 @@ function playground() {
   verbose_begin
   if [[ $(type -f playground 2>&1) =~ "not found" ]]
   then
-    ../../scripts/cli/playground "$@"
+    if [ -f ../../scripts/cli/playground ]
+    then
+      ../../scripts/cli/playground "$@"
+    elif [ -f ../../../scripts/cli/playground ]
+    then
+      ../../../scripts/cli/playground "$@"
+    else
+      logerror "🔍 playground command not found, add it to your PATH https://kafka-docker-playground.io/#/cli?id=🦶-setup-path"
+      exit 1
+    fi
   else
     $(which playground) "$@"
   fi
@@ -15956,6 +15965,7 @@ playground_stop_command() {
       logerror "File $test_file retrieved from $root_folder/playground.ini does not exist!"
       exit 1
   fi
+  export flink_connectors=""
   filename=$(basename -- "$test_file")
   test_file_directory="$(dirname "${test_file}")"
 
