check for pem valid

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -7486,11 +7486,11 @@ function wait_for_ec2_instance_to_be_running () {
   max_wait=${2:-300}
   cur_wait=0
   log "⌛ waiting up to $max_wait seconds for ec2 instance $instance to be running"
-  playground ec2 status --instance $instance > /tmp/out.txt 2>&1
+  playground ec2 status --instance "$instance" > /tmp/out.txt 2>&1
   while ! grep "running" /tmp/out.txt > /dev/null;
   do
     sleep 10
-    playground ec2 status --instance $instance > /tmp/out.txt 2>&1
+    playground ec2 status --instance "$instance" > /tmp/out.txt 2>&1
     status=$(cat /tmp/out.txt)
     log "⌛ current status: $status"
     cur_wait=$(( cur_wait+10 ))
@@ -24266,6 +24266,13 @@ playground_ec2_create_command() {
 
   log "🔐 creating pem file $pem_file (make sure to create backup)"
   aws ec2 create-key-pair --key-name "$name" --key-type rsa --key-format pem --query "KeyMaterial" --output text > $pem_file
+
+  if ! grep "BEGIN RSA PRIVATE KEY" $pem_file > /dev/null
+  then
+      logerror "❌ failed to create pem file $pem_file"
+      cat $pem_file
+      exit 1
+  fi
   chmod 400 $pem_file
 
   cloud_formation_yml_file="$root_folder/cloudformation/kafka-docker-playground.yml"
