🧠 add playground schema set-alias and get-alias commands #7824

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -89,6 +89,8 @@ playground_usage() {
   printf "  %s   🩺 Validate new schemas (default is true since CP 8.2.0)\n" "$(green "schema validate-new-schemas")               "
   printf "  %s   🧟 Delete schema\n" "$(green "schema delete")                             "
   printf "  %s   🪄 Derive a schema based on payload\n" "$(green "schema derive-schema")                      "
+  printf "  %s   🔯 Set a subject alias (see https://docs.confluent.io/platform/8.2/schema-registry/fundamentals/index.html#subject-aliases)\n" "$(green "schema set-alias")                          "
+  printf "  %s   🔯 Get subject alias\n" "$(green "schema get-alias")                          "
   echo
   printf "%s\n" "$(bold "TCP Proxy commands:")"
   printf "  %s   🏚 Zazkia TCP Proxy commands\n" "$(green "tcp-proxy")                                 "
@@ -3141,6 +3143,8 @@ playground_schema_usage() {
   printf "  %s   🩺 Validate new schemas (default is true since CP 8.2.0)\n" "$(green "validate-new-schemas")"
   printf "  %s   🧟 Delete schema\n" "$(green "delete")              "
   printf "  %s   🪄 Derive a schema based on payload\n" "$(green "derive-schema")       "
+  printf "  %s   🔯 Set a subject alias (see https://docs.confluent.io/platform/8.2/schema-registry/fundamentals/index.html#subject-aliases)\n" "$(green "set-alias")           "
+  printf "  %s   🔯 Get subject alias\n" "$(green "get-alias")           "
   echo
 
   # :command.long_usage
@@ -3572,6 +3576,87 @@ playground_schema_derive_schema_usage() {
 echo
 
 fi
+}
+
+# :command.usage
+playground_schema_set_alias_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground schema set-alias\n\n"
+    printf "  🔯 Set a subject alias (see\n  https://docs.confluent.io/platform/8.2/schema-registry/fundamentals/index.html#subject-aliases)\n  \n  CP 7.4.1 or higher is required to have this feature\n\n"
+  else
+    printf "playground schema set-alias - 🔯 Set a subject alias (see https://docs.confluent.io/platform/8.2/schema-registry/fundamentals/index.html#subject-aliases)\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground schema set-alias [OPTIONS]\n"
+  printf "  playground schema set-alias --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--subject SUBJECT (required)")"
+    printf "    📛 Subject name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--alias ALIAS (required)")"
+    printf "    🔯 Alias name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--verbose, -v")"
+    printf "    🐞 Show command being ran.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_schema_get_alias_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground schema get-alias\n\n"
+    printf "  🔯 Get subject alias\n  \n  CP 7.4.1 or higher is required to have this feature\n\n"
+  else
+    printf "playground schema get-alias - 🔯 Get subject alias\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground schema get-alias [OPTIONS]\n"
+  printf "  playground schema get-alias --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--alias ALIAS (required)")"
+    printf "    🔯 Alias name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--verbose, -v")"
+    printf "    🐞 Show command being ran.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
 }
 
 # :command.usage
@@ -22584,6 +22669,103 @@ EOF
 }
 
 # :command.function
+playground_schema_set_alias_command() {
+
+  # src/commands/schema/set-alias.sh
+  subject="${args[--subject]}"
+  alias="${args[--alias]}"
+  verbose="${args[--verbose]}"
+
+  get_environment_used
+  if [[ "$environment" != "ccloud" ]]
+  then
+      get_connect_image
+
+      if ! version_gt $CP_CONNECT_TAG "7.4.1"
+      then
+          logerror "❌ subject aliases are available since CP 7.4.1 only"
+          exit 1
+      fi
+  fi
+
+  get_sr_url_and_security
+
+  log "🔯 Set alias for subject ${subject} with alias ${alias}"
+  if [[ -n "$verbose" ]]
+  then
+      log "🐞 curl command used"
+      echo "curl $sr_security -s -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data "{\"alias\": \"$subject\"}" "${sr_url}/config/${alias}""
+  fi
+  curl_output=$(curl $sr_security -s -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data "{\"alias\": \"$subject\"}" "${sr_url}/config/${alias}" | jq .)
+  ret=$?
+  if [ $ret -eq 0 ]
+  then
+      error_code=$(echo "$curl_output" | jq -r .error_code)
+      if [ "$error_code" != "null" ]
+      then
+          message=$(echo "$curl_output" | jq -r .message)
+          logerror "Command failed with error code $error_code"
+          logerror "$message"
+          exit 1
+      else
+          alias=$(echo "$curl_output" | jq -r .alias)
+          echo "$alias"
+      fi
+  else
+      logerror "❌ curl request failed with error code $ret!"
+      exit 1
+  fi
+}
+
+# :command.function
+playground_schema_get_alias_command() {
+
+  # src/commands/schema/get-alias.sh
+  alias="${args[--alias]}"
+  verbose="${args[--verbose]}"
+
+  if [[ "$environment" != "ccloud" ]]
+  then
+      get_connect_image
+
+      if ! version_gt $CP_CONNECT_TAG "7.4.1"
+      then
+          logerror "❌ subject aliases are available since CP 7.4.1 only"
+          exit 1
+      fi
+  fi
+
+  get_sr_url_and_security
+
+  log "🔯 Get alias for alias ${alias}"
+  if [[ -n "$verbose" ]]
+  then
+      log "🐞 curl command used"
+      echo "curl $sr_security -s -H "Content-Type: application/vnd.schemaregistry.v1+json" "${sr_url}/config/${alias}""
+  fi
+  curl_output=$(curl $sr_security -s -H "Content-Type: application/vnd.schemaregistry.v1+json" "${sr_url}/config/${alias}")
+  ret=$?
+  if [ $ret -eq 0 ]
+  then
+      if echo "$curl_output" | jq '. | has("error_code")' 2> /dev/null | grep -q true
+
+      then
+          error_code=$(echo "$curl_output" | jq -r .error_code)
+          message=$(echo "$curl_output" | jq -r .message)
+          logerror "Command failed with error code $error_code"
+          logerror "$message"
+          exit 1
+      else
+          alias=$(echo "$curl_output" | jq -r .alias)
+          echo "$alias"
+      fi
+  else
+      logerror "❌ curl request failed with error code $ret!"
+      exit 1
+  fi
+}
+
+# :command.function
 playground_tcp_proxy_start_command() {
 
   # src/commands/tcp-proxy/start.sh
@@ -39790,6 +39972,20 @@ playground_schema_parse_requirements() {
       shift $#
       ;;
 
+    set-alias)
+      action="set-alias"
+      shift
+      playground_schema_set_alias_parse_requirements "$@"
+      shift $#
+      ;;
+
+    get-alias)
+      action="get-alias"
+      shift
+      playground_schema_get_alias_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_schema_usage >&2
@@ -40891,6 +41087,198 @@ playground_schema_derive_schema_parse_requirements() {
   # :command.whitelist_filter
   if [[ ${args['--schema-type']:-} ]] && [[ ! ${args['--schema-type']:-} =~ ^(AVRO|JSON|PROTOBUF)$ ]]; then
     printf "%s\n" "--schema-type must be one of: AVRO, JSON, PROTOBUF" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_schema_set_alias_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_schema_set_alias_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="schema set-alias"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --subject)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--subject']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--subject requires an argument: --subject SUBJECT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --alias)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--alias']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--alias requires an argument: --alias ALIAS" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --verbose | -v)
+
+        # :flag.case_no_arg
+        args['--verbose']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--subject']+x} ]]; then
+    printf "missing required flag: --subject SUBJECT\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['--alias']+x} ]]; then
+    printf "missing required flag: --alias ALIAS\n" >&2
+    exit 1
+  fi
+
+  # :command.user_filter
+  filter_error=$(filter_not_mdc_environment)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+  filter_error=$(filter_schema_registry_running)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_schema_get_alias_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_schema_get_alias_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="schema get-alias"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --alias)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--alias']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--alias requires an argument: --alias ALIAS" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --verbose | -v)
+
+        # :flag.case_no_arg
+        args['--verbose']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--alias']+x} ]]; then
+    printf "missing required flag: --alias ALIAS\n" >&2
+    exit 1
+  fi
+
+  # :command.user_filter
+  filter_error=$(filter_not_mdc_environment)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+  filter_error=$(filter_schema_registry_running)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
     exit 1
   fi
 
@@ -52142,6 +52530,8 @@ run() {
     "schema validate-new-schemas") playground_schema_validate_new_schemas_command ;;
     "schema delete") playground_schema_delete_command ;;
     "schema derive-schema") playground_schema_derive_schema_command ;;
+    "schema set-alias") playground_schema_set_alias_command ;;
+    "schema get-alias") playground_schema_get_alias_command ;;
     "tcp-proxy") playground_tcp_proxy_command ;;
     "tcp-proxy start") playground_tcp_proxy_start_command ;;
     "tcp-proxy get-connections") playground_tcp_proxy_get_connections_command ;;
