wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -84,6 +84,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   ⏸️  Pause connector\n" "$(green "ccloud-connector pause")            "
   [[ -n $long_usage ]] && printf "  %s   ⏯️  Resume connector\n" "$(green "ccloud-connector resume")           "
   [[ -n $long_usage ]] && printf "  %s   🗑️  Delete connector\n" "$(green "ccloud-connector delete")           "
+  [[ -n $long_usage ]] && printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "ccloud-connector create-or-update") "
   printf "  %s   🔗 Connector commands\n" "$(green "connector")                         "
   [[ -n $long_usage ]] && printf "  %s   🧩 Show status of all connectors\n" "$(green "connector status")                  "
   [[ -n $long_usage ]] && printf "  %s   🎨 Show all plugins installed\n" "$(green "connector plugins")                 "
@@ -2058,11 +2059,12 @@ playground_ccloud_connector_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
-  printf "  %s   🧩 Show status of all connectors\n" "$(green "status") "
-  printf "  %s   🎨 Show all plugins installed\n" "$(green "plugins")"
-  printf "  %s   ⏸️  Pause connector\n" "$(green "pause")  "
-  printf "  %s   ⏯️  Resume connector\n" "$(green "resume") "
-  printf "  %s   🗑️  Delete connector\n" "$(green "delete") "
+  printf "  %s   🧩 Show status of all connectors\n" "$(green "status")          "
+  printf "  %s   🎨 Show all plugins installed\n" "$(green "plugins")         "
+  printf "  %s   ⏸️  Pause connector\n" "$(green "pause")           "
+  printf "  %s   ⏯️  Resume connector\n" "$(green "resume")          "
+  printf "  %s   🗑️  Delete connector\n" "$(green "delete")          "
+  printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")"
   echo
 
   # :command.long_usage
@@ -2248,6 +2250,55 @@ playground_ccloud_connector_delete_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ccloud_connector_create_or_update_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground ccloud-connector create-or-update - 🧑‍🎨  Create or update connector\n"
+    echo
+
+  else
+    printf "playground ccloud-connector create-or-update - 🧑‍🎨  Create or update connector\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ccloud-connector create-or-update [JSON] [OPTIONS]\n"
+  printf "  playground ccloud-connector create-or-update --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector, -c CONNECTOR (required)")"
+    printf "    🔗 Connector name\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "JSON")"
+    printf "    json (reads from stdin if empty)\n"
+    printf "    Default: -\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground ccloud-connector create-or-update -c filestream-sink << EOF\n  {\n      \"tasks.max\": \"1\",\n      \"connector.class\":\n  \"org.apache.kafka.connect.file.FileStreamSinkConnector\",\n      \"topics\": \"filestream\",\n      \"file\": \"/tmp/output.json\",\n      \"key.converter\": \"org.apache.kafka.connect.storage.StringConverter\",\n      \"value.converter\": \"org.apache.kafka.connect.json.JsonConverter\",\n      \"value.converter.schemas.enable\": \"false\"\n  }\n  EOF\n"
     echo
 
   fi
@@ -4944,10 +4995,9 @@ function ccloud::retry() {
 }
 
 function wait_for_ccloud_connector_up() {
-  filename=$1
+  connectorName=$1
   maxWait=$2
 
-  connectorName=$(cat $filename | jq -r .name)
   connectorId=$(get_ccloud_connector_lcc $connectorName)
   log "Waiting up to $maxWait seconds for connector $connectorName ($connectorId) to be RUNNING"
   ccloud::retry $maxWait validate_ccloud_connector_up $connectorName || exit 1
@@ -4957,8 +5007,7 @@ function wait_for_ccloud_connector_up() {
 }
 
 function delete_ccloud_connector() {
-  filename=$1
-  connectorName=$(cat $filename | jq -r .name)
+  connectorName=$1
   connectorId=$(get_ccloud_connector_lcc $connectorName)
 
   log "Deleting connector $connectorName ($connectorId)"
@@ -5585,10 +5634,9 @@ function ccloud::validate_connector_up() {
 }
 
 function ccloud::wait_for_connector_up() {
-  filename=$1
+  connectorName=$1
   maxWait=$2
 
-  connectorName=$(cat $filename | jq -r .name)
   echo "Waiting up to $maxWait seconds for connector $filename ($connectorName) to be RUNNING"
   ccloud::retry $maxWait ccloud::validate_connector_up $connectorName || exit 1
   echo "Connector $filename ($connectorName) is RUNNING"
@@ -9621,6 +9669,102 @@ playground_ccloud_connector_delete_command() {
   done
   sleep 3
   playground ccloud-connector status
+}
+
+# :command.function
+playground_ccloud_connector_create_or_update_command() {
+  # src/ccloud_connector_create_or_update_command.sh
+  json=${args[json]}
+
+  if [ "$json" = "-" ]
+  then
+      # stdin
+      json_content=$(cat "$json")
+  else
+      json_content=$json
+  fi
+
+  json_file=/tmp/json
+  echo "$json_content" > $json_file
+
+  # JSON is invalid
+  if ! echo "$json_content" | jq -e .
+
+  then
+      set +e
+      jq_output=$(jq . "$json_file" 2>&1)
+      error_line=$(echo "$jq_output" | grep -oE 'parse error.*at line [0-9]+' | grep -oE '[0-9]+')
+
+      if [[ -n "$error_line" ]]; then
+          logerror "Invalid JSON at line $error_line"
+      fi
+      set -e
+
+      if [[ $(type -f bat 2>&1) =~ "not found" ]]
+      then
+          cat $json_file
+      else
+          bat $json_file --highlight-line $error_line
+      fi
+
+      exit 1
+  fi
+
+  ret=$(get_ccloud_connect)
+
+  environment=$(echo "$ret" | cut -d "@" -f 1)
+  cluster=$(echo "$ret" | cut -d "@" -f 2)
+  authorization=$(echo "$ret" | cut -d "@" -f 3)
+
+  connector="${args[--connector]}"
+
+  is_create=1
+  connectors=$(playground get-ccloud-connector-list)
+  items=($connectors)
+  for con in ${items[@]}
+  do
+      if [[ "$con" == "$connector" ]]
+      then
+          is_create=0
+      fi
+  done
+
+  if [ $is_create == 1 ]
+  then
+      log "Creating connector $connector"
+  else
+      log "Updating connector $connector"
+  fi
+
+  curl_output=$(curl $security -s -X PUT \
+       -H "Content-Type: application/json" \
+       -H "authorization: Basic $authorization" \
+       --data @$json_file \
+       https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector/config)
+
+  if [ $? -eq 0 ]
+  then
+      error_code=$(echo "$curl_output" | jq -r .error_code)
+      if [ $error_code != "null" ]
+      then
+          message=$(echo "$curl_output" | jq -r .message)
+          logerror "Command failed with error code $error_code"
+          logerror "$message"
+      else
+          if [ $is_create == 1 ]
+          then
+              log "Connector $connector was successfully created"
+          else
+              log "Connector $connector was successfully updated"
+          fi
+          sleep 3
+          playground connector status
+      fi
+  else
+      logerror "curl request failed !"
+      echo "$curl_output"
+      exit 1
+  fi
 }
 
 # :command.function
@@ -14147,6 +14291,13 @@ playground_ccloud_connector_parse_requirements() {
       shift $#
       ;;
 
+    create-or-update)
+      action="create-or-update"
+      shift
+      playground_ccloud_connector_create_or_update_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_ccloud_connector_usage >&2
@@ -14449,6 +14600,79 @@ playground_ccloud_connector_delete_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_ccloud_connector_create_or_update_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ccloud_connector_create_or_update_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="ccloud-connector create-or-update"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connector | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--connector']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector requires an argument: --connector, -c CONNECTOR" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['json']+x} ]]; then
+
+          args['json']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--connector']+x} ]]; then
+    printf "missing required flag: --connector, -c CONNECTOR\n" >&2
+    exit 1
+  fi
+
+  # :command.default_assignments
+  [[ -n ${args['json']:-} ]] || args['json']="-"
 
 }
 
@@ -15240,6 +15464,7 @@ run() {
     "ccloud-connector pause") playground_ccloud_connector_pause_command ;;
     "ccloud-connector resume") playground_ccloud_connector_resume_command ;;
     "ccloud-connector delete") playground_ccloud_connector_delete_command ;;
+    "ccloud-connector create-or-update") playground_ccloud_connector_create_or_update_command ;;
     "connector") playground_connector_command ;;
     "connector status") playground_connector_status_command ;;
     "connector plugins") playground_connector_plugins_command ;;
