handle export when repro folder not managed by git

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -9102,7 +9102,7 @@ playground_repro_export_command() {
   set +e
   if [[ -n "$all" ]]
   then
-      if git rev-parse --git-dir > /dev/null 2>&1
+      if [ -d .git ]
       then
           new_files=$(git status --porcelain 2>/dev/null  | grep "^?? " | cut -d " " -f2-)
           if [[ -n "$new_files" ]]
@@ -9122,8 +9122,15 @@ playground_repro_export_command() {
               exit 1
           fi
       else
-          logerror "❌ output folder is not managed by git, please clone repository using git clone"
-          exit 1
+          logwarn "output folder is not managed by git, creating a full tgz of $output_folder"
+          tar cvfz "$output_filename" * > /dev/null 2>&1
+          if [ -f $final_archive ]
+          then
+              log "📤 Exported archive is available: $final_archive"
+          else
+              logerror "❌ export failed as archive could not be created !"
+              exit 1
+          fi
       fi
   else
       # copy only current example
@@ -9138,7 +9145,6 @@ playground_repro_export_command() {
 
       if [ ! -f $test_file ]
       then
-
           logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
           logerror "Make sure to use <playground run> command !"
           exit 1
@@ -9155,7 +9161,7 @@ playground_repro_export_command() {
           exit 1
       fi
 
-      if git rev-parse --git-dir > /dev/null 2>&1
+      if [ -d .git ]
       then
           cd $test_file_directory
 
@@ -9178,8 +9184,15 @@ playground_repro_export_command() {
               exit 1
           fi
       else
-          logerror "❌ output folder is not managed by git, please clone repository using git clone"
-          exit 1
+          logwarn "output folder is not managed by git, creating a full tgz of $test_file_directory"
+          tar cvfz "$output_filename" $test_file_directory > /dev/null 2>&1
+          if [ -f $final_archive ]
+          then
+              log "📤 Exported archive is available: $final_archive"
+          else
+              logerror "❌ export failed as archive could not be created !"
+              exit 1
+          fi
       fi
   fi
 
