topic command

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -56,10 +56,11 @@ playground_usage() {
   printf "  %s   🔫 Kill a container.\n" "$(green "kill")                          "
   echo
   printf "%s\n" "$(bold "Topic Commands:")"
-  printf "  %s   💯 Get number of records in a topic.\n" "$(green "get-number-records-topic")      "
-  printf "  %s   🔺 Display content of connect offsets topic.\n" "$(green "display-connect-offsets-topic") "
-  printf "  %s   🔻 Display content of __consumer_offsets topic.\n" "$(green "display-consumer-offsets-topic")"
-  printf "  %s   🔎 Describe topic.\n" "$(green "describe-topic")                "
+  printf "  %s   📁 Topic commands.\n" "$(green "topic")                         "
+  [[ -n $long_usage ]] && printf "  %s   💯 Get number of records in a topic.\n" "$(green "topic get-number-records")      "
+  [[ -n $long_usage ]] && printf "  %s   🔺 Display content of connect offsets topic.\n" "$(green "topic display-connect-offsets") "
+  [[ -n $long_usage ]] && printf "  %s   🔻 Display content of __consumer_offsets topic.\n" "$(green "topic display-consumer-offsets")"
+  [[ -n $long_usage ]] && printf "  %s   🔎 Describe topic.\n" "$(green "topic describe")                "
   echo
   printf "%s\n" "$(bold "Connector Commands:")"
   printf "  %s   🔗 Connector commands.\n" "$(green "connector")                     "
@@ -464,20 +465,56 @@ playground_kill_all_containers_usage() {
 }
 
 # :command.usage
-playground_get_number_records_topic_usage() {
+playground_topic_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground get-number-records-topic - 💯 Get number of records in a topic.\n"
+    printf "playground topic - 📁 Topic commands.\n"
     echo
 
   else
-    printf "playground get-number-records-topic - 💯 Get number of records in a topic.\n"
+    printf "playground topic - 📁 Topic commands.\n"
     echo
 
   fi
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  playground get-number-records-topic [OPTIONS]\n"
-  printf "  playground get-number-records-topic --help | -h\n"
+  printf "  playground topic COMMAND\n"
+  printf "  playground topic [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "$(bold "Topic Commands:")"
+  printf "  %s   💯 Get number of records in a topic.\n" "$(green "get-number-records")      "
+  printf "  %s   🔺 Display content of connect offsets topic.\n" "$(green "display-connect-offsets") "
+  printf "  %s   🔻 Display content of __consumer_offsets topic.\n" "$(green "display-consumer-offsets")"
+  printf "  %s   🔎 Describe topic.\n" "$(green "describe")                "
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_topic_get_number_records_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground topic get-number-records - 💯 Get number of records in a topic.\n"
+    echo
+
+  else
+    printf "playground topic get-number-records - 💯 Get number of records in a topic.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  playground topic get-number-records [OPTIONS]\n"
+  printf "  playground topic get-number-records --help | -h\n"
   echo
 
   # :command.long_usage
@@ -497,28 +534,28 @@ playground_get_number_records_topic_usage() {
 
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples:")"
-    printf "  playground get-number-records-topic --topic a-topic\n"
-    printf "  playground get-number-records-topic -t a-topic\n"
+    printf "  playground get-number-records --topic a-topic\n"
+    printf "  playground get-number-records -t a-topic\n"
     echo
 
   fi
 }
 
 # :command.usage
-playground_display_connect_offsets_topic_usage() {
+playground_topic_display_connect_offsets_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground display-connect-offsets-topic - 🔺 Display content of connect offsets topic.\n"
+    printf "playground topic display-connect-offsets - 🔺 Display content of connect offsets topic.\n"
     echo
 
   else
-    printf "playground display-connect-offsets-topic - 🔺 Display content of connect offsets topic.\n"
+    printf "playground topic display-connect-offsets - 🔺 Display content of connect offsets topic.\n"
     echo
 
   fi
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  playground display-connect-offsets-topic\n"
-  printf "  playground display-connect-offsets-topic --help | -h\n"
+  printf "  playground topic display-connect-offsets\n"
+  printf "  playground topic display-connect-offsets --help | -h\n"
   echo
 
   # :command.long_usage
@@ -534,20 +571,20 @@ playground_display_connect_offsets_topic_usage() {
 }
 
 # :command.usage
-playground_display_consumer_offsets_topic_usage() {
+playground_topic_display_consumer_offsets_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground display-consumer-offsets-topic - 🔻 Display content of __consumer_offsets topic.\n"
+    printf "playground topic display-consumer-offsets - 🔻 Display content of __consumer_offsets topic.\n"
     echo
 
   else
-    printf "playground display-consumer-offsets-topic - 🔻 Display content of __consumer_offsets topic.\n"
+    printf "playground topic display-consumer-offsets - 🔻 Display content of __consumer_offsets topic.\n"
     echo
 
   fi
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  playground display-consumer-offsets-topic\n"
-  printf "  playground display-consumer-offsets-topic --help | -h\n"
+  printf "  playground topic display-consumer-offsets\n"
+  printf "  playground topic display-consumer-offsets --help | -h\n"
   echo
 
   # :command.long_usage
@@ -563,20 +600,20 @@ playground_display_consumer_offsets_topic_usage() {
 }
 
 # :command.usage
-playground_describe_topic_usage() {
+playground_topic_describe_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground describe-topic - 🔎 Describe topic.\n"
+    printf "playground topic describe - 🔎 Describe topic.\n"
     echo
 
   else
-    printf "playground describe-topic - 🔎 Describe topic.\n"
+    printf "playground topic describe - 🔎 Describe topic.\n"
     echo
 
   fi
 
   printf "%s\n" "$(bold "Usage:")"
-  printf "  playground describe-topic [OPTIONS]\n"
-  printf "  playground describe-topic --help | -h\n"
+  printf "  playground topic describe [OPTIONS]\n"
+  printf "  playground topic describe --help | -h\n"
   echo
 
   # :command.long_usage
@@ -5480,8 +5517,8 @@ playground_kill_all_containers_command() {
 }
 
 # :command.function
-playground_get_number_records_topic_command() {
-  # src/get_number_records_topic_command.sh
+playground_topic_get_number_records_command() {
+  # src/topic_get_number_records_command.sh
   topic="${args[--topic]}"
 
   log "Get number of records in a topic $topic"
@@ -5490,26 +5527,24 @@ playground_get_number_records_topic_command() {
 }
 
 # :command.function
-playground_display_connect_offsets_topic_command() {
-  # src/display_connect_offsets_topic_command.sh
+playground_topic_display_connect_offsets_command() {
+  # src/topic_display_connect_offsets_command.sh
   log "Display content of connect offsets topic, press crtl-c to stop..."
   docker exec connect kafka-console-consumer -bootstrap-server broker:9092 --topic connect-offsets --from-beginning --property print.key=true --property print.timestamp=true
 }
 
 # :command.function
-playground_display_consumer_offsets_topic_command() {
-  # src/display_consumer_offsets_topic_command.sh
+playground_topic_display_consumer_offsets_command() {
+  # src/topic_display_consumer_offsets_command.sh
   log "Display content of __consumer_offsets topic, press crtl-c to stop..."
   docker exec -i broker bash -c 'kafka-console-consumer --bootstrap-server broker:9092 --topic __consumer_offsets --from-beginning --formatter "kafka.coordinator.group.GroupMetadataManager\$OffsetsMessageFormatter" | grep -v "_confluent-controlcenter"'
 }
 
 # :command.function
-playground_describe_topic_command() {
-  # src/describe_topic_command.sh
-  topic="${args[--topic]}"
-
-  log "Description of topic $topic"
-  docker exec broker kafka-topics --describe --topic $topic --bootstrap-server broker:9092
+playground_topic_describe_command() {
+  # src/topic_describe_command.sh
+  log "Display content of connect offsets topic, press crtl-c to stop..."
+  docker exec connect kafka-console-consumer -bootstrap-server broker:9092 --topic connect-offsets --from-beginning --property print.key=true --property print.timestamp=true
 }
 
 # :command.function
@@ -5943,31 +5978,10 @@ parse_requirements() {
       shift $#
       ;;
 
-    get-number-records-topic)
-      action="get-number-records-topic"
+    topic)
+      action="topic"
       shift
-      playground_get_number_records_topic_parse_requirements "$@"
-      shift $#
-      ;;
-
-    display-connect-offsets-topic)
-      action="display-connect-offsets-topic"
-      shift
-      playground_display_connect_offsets_topic_parse_requirements "$@"
-      shift $#
-      ;;
-
-    display-consumer-offsets-topic)
-      action="display-consumer-offsets-topic"
-      shift
-      playground_display_consumer_offsets_topic_parse_requirements "$@"
-      shift $#
-      ;;
-
-    describe-topic)
-      action="describe-topic"
-      shift
-      playground_describe_topic_parse_requirements "$@"
+      playground_topic_parse_requirements "$@"
       shift $#
       ;;
 
@@ -6656,13 +6670,13 @@ playground_kill_all_containers_parse_requirements() {
 }
 
 # :command.parse_requirements
-playground_get_number_records_topic_parse_requirements() {
+playground_topic_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        playground_get_number_records_topic_usage
+        playground_topic_usage
         exit
         ;;
 
@@ -6676,7 +6690,97 @@ playground_get_number_records_topic_parse_requirements() {
   # :command.dependencies_filter
 
   # :command.command_filter
-  action="get-number-records-topic"
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    get-number-records)
+      action="get-number-records"
+      shift
+      playground_topic_get_number_records_parse_requirements "$@"
+      shift $#
+      ;;
+
+    display-connect-offsets)
+      action="display-connect-offsets"
+      shift
+      playground_topic_display_connect_offsets_parse_requirements "$@"
+      shift $#
+      ;;
+
+    display-consumer-offsets)
+      action="display-consumer-offsets"
+      shift
+      playground_topic_display_consumer_offsets_parse_requirements "$@"
+      shift $#
+      ;;
+
+    describe)
+      action="describe"
+      shift
+      playground_topic_describe_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      playground_topic_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_topic_get_number_records_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_topic_get_number_records_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+
+  # :command.command_filter
+  action="topic get-number-records"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -6722,13 +6826,13 @@ playground_get_number_records_topic_parse_requirements() {
 }
 
 # :command.parse_requirements
-playground_display_connect_offsets_topic_parse_requirements() {
+playground_topic_display_connect_offsets_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        playground_display_connect_offsets_topic_usage
+        playground_topic_display_connect_offsets_usage
         exit
         ;;
 
@@ -6742,7 +6846,7 @@ playground_display_connect_offsets_topic_parse_requirements() {
   # :command.dependencies_filter
 
   # :command.command_filter
-  action="display-connect-offsets-topic"
+  action="topic display-connect-offsets"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -6768,13 +6872,13 @@ playground_display_connect_offsets_topic_parse_requirements() {
 }
 
 # :command.parse_requirements
-playground_display_consumer_offsets_topic_parse_requirements() {
+playground_topic_display_consumer_offsets_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        playground_display_consumer_offsets_topic_usage
+        playground_topic_display_consumer_offsets_usage
         exit
         ;;
 
@@ -6788,7 +6892,7 @@ playground_display_consumer_offsets_topic_parse_requirements() {
   # :command.dependencies_filter
 
   # :command.command_filter
-  action="display-consumer-offsets-topic"
+  action="topic display-consumer-offsets"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -6814,13 +6918,13 @@ playground_display_consumer_offsets_topic_parse_requirements() {
 }
 
 # :command.parse_requirements
-playground_describe_topic_parse_requirements() {
+playground_topic_describe_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        playground_describe_topic_usage
+        playground_topic_describe_usage
         exit
         ;;
 
@@ -6834,7 +6938,7 @@ playground_describe_topic_parse_requirements() {
   # :command.dependencies_filter
 
   # :command.command_filter
-  action="describe-topic"
+  action="topic describe"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -8286,39 +8390,48 @@ run() {
       fi
       ;;
 
-    "get-number-records-topic")
+    "topic")
       if [[ ${args['--help']:-} ]]; then
         long_usage=yes
-        playground_get_number_records_topic_usage
+        playground_topic_usage
       else
-        playground_get_number_records_topic_command
+        playground_topic_command
       fi
       ;;
 
-    "display-connect-offsets-topic")
+    "topic get-number-records")
       if [[ ${args['--help']:-} ]]; then
         long_usage=yes
-        playground_display_connect_offsets_topic_usage
+        playground_topic_get_number_records_usage
       else
-        playground_display_connect_offsets_topic_command
+        playground_topic_get_number_records_command
       fi
       ;;
 
-    "display-consumer-offsets-topic")
+    "topic display-connect-offsets")
       if [[ ${args['--help']:-} ]]; then
         long_usage=yes
-        playground_display_consumer_offsets_topic_usage
+        playground_topic_display_connect_offsets_usage
       else
-        playground_display_consumer_offsets_topic_command
+        playground_topic_display_connect_offsets_command
       fi
       ;;
 
-    "describe-topic")
+    "topic display-consumer-offsets")
       if [[ ${args['--help']:-} ]]; then
         long_usage=yes
-        playground_describe_topic_usage
+        playground_topic_display_consumer_offsets_usage
       else
-        playground_describe_topic_command
+        playground_topic_display_consumer_offsets_command
+      fi
+      ;;
+
+    "topic describe")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        playground_topic_describe_usage
+      else
+        playground_topic_describe_command
       fi
       ;;
 
