ccloud-connector show-config

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -96,6 +96,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   ⏯️  Resume connector\n" "$(green "ccloud-connector resume")          "
   [[ -n $long_usage ]] && printf "  %s   🗑️  Delete connector\n" "$(green "ccloud-connector delete")          "
   [[ -n $long_usage ]] && printf "  %s   🐢 Show lag of sink connector\n" "$(green "ccloud-connector show-lag")        "
+  [[ -n $long_usage ]] && printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "ccloud-connector show-config")     "
   [[ -n $long_usage ]] && printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "ccloud-connector create-or-update")"
   printf "  %s   🔗 Connector commands\n" "$(green "connector")                        "
   [[ -n $long_usage ]] && printf "  %s   🧩 Show status of all connectors\n" "$(green "connector status")                 "
@@ -2676,6 +2677,7 @@ playground_ccloud_connector_usage() {
   printf "  %s   ⏯️  Resume connector\n" "$(green "resume")          "
   printf "  %s   🗑️  Delete connector\n" "$(green "delete")          "
   printf "  %s   🐢 Show lag of sink connector\n" "$(green "show-lag")        "
+  printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "show-config")     "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")"
   echo
 
@@ -2897,6 +2899,51 @@ playground_ccloud_connector_show_lag_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--wait-for-zero-lag")"
     printf "    😴 Wait until lag becomes 0\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ccloud_connector_show_config_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground ccloud-connector show-config - 🔩 Show all possible configuration parameters of connector\n"
+    echo
+
+  else
+    printf "playground ccloud-connector show-config - 🔩 Show all possible configuration parameters of connector\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ccloud-connector show-config [OPTIONS]\n"
+  printf "  playground ccloud-connector show-config --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector, -c CONNECTOR")"
+    printf "    🔗 Connector name\n    \n    🎓 Tip: If not specified, the command will apply to all connectors\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--open, -o")"
+    printf "    🔖 Save output to a file and open with text editor set with config.ini\n    (default is code)\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--force-refresh")"
+    printf "    ☢️ Force refresh.\n"
     echo
 
     # :command.usage_fixed_flags
@@ -8341,6 +8388,12 @@ playground_run_ccloud_command() {
   ret=$?
   ELAPSED="took: $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
   let ELAPSED_TOTAL+=$SECONDS
+  set +e
+  # just run it in background in case it is called later, the
+
+  # file will be present and it will be much faster to display config
+  playground ccloud-connector show-config > /dev/null 2>&1 &
+  set -e
   if [ $ret -eq 0 ]
   then
       log "####################################################"
@@ -11738,6 +11791,196 @@ playground_ccloud_connector_show_lag_command() {
       fi
   done
 
+}
+
+# :command.function
+playground_ccloud_connector_show_config_command() {
+  # src/ccloud_connector_show_config_command.sh
+  ret=$(get_ccloud_connect)
+
+  environment=$(echo "$ret" | cut -d "@" -f 1)
+  cluster=$(echo "$ret" | cut -d "@" -f 2)
+  authorization=$(echo "$ret" | cut -d "@" -f 3)
+
+  connector="${args[--connector]}"
+  open="${args[--open]}"
+  force_refresh="${args[--force-refresh]}"
+
+  if [[ ! -n "$connector" ]]
+  then
+      log "✨ --connector flag was not provided, applying command to all ccloud connectors"
+      connector=$(playground get-ccloud-connector-list)
+      if [ "$connector" == "" ]
+      then
+          logerror "💤 No ccloud connector is running !"
+          exit 1
+      fi
+  fi
+
+  if [ -f /tmp/delta_configs/env.delta ]
+  then
+      source /tmp/delta_configs/env.delta
+  else
+      logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
+      exit 1
+  fi
+  if [ ! -f /tmp/delta_configs/ak-tools-ccloud.delta ]
+  then
+      logerror "ERROR: /tmp/delta_configs/ak-tools-ccloud.delta has not been generated"
+      exit 1
+  fi
+
+  DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+  dir1=$(echo ${DIR_CLI%/*})
+  root_folder=$(echo ${dir1%/*})
+  IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
+  source $root_folder/scripts/utils.sh
+
+  items=($connector)
+  for connector in ${items[@]}
+  do
+      json_config=$(curl -s --request GET "https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector/config" --header "authorization: Basic $authorization")
+      connector_class=$(echo "$json_config" | jq -r '."connector.class"')
+      set +e
+      curl_output=$(curl -s --request GET "https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connector-plugins" --header "authorization: Basic $authorization")
+      ret=$?
+      set -e
+      if [ $ret -eq 0 ]
+      then
+          current_group=""
+          rows=()
+          for row in $(echo "$curl_output" | jq -r '.[] | @base64'); do
+              _jq() {
+                  echo ${row} | base64 --decode | jq -r ${1}
+              }
+
+              class=$(_jq '.class')
+          done
+      else
+          logerror "❌ curl request failed with error code $ret!"
+          exit 1
+      fi
+
+      filename="/tmp/config-$connector_class.txt"
+
+      class=$(echo $connector_class | rev | cut -d '.' -f 1 | rev)
+      log "🔩 getting parameters for connector $connector ($class)"
+
+      if [[ -n "$force_refresh" ]]
+      then
+          if [ -f $filename ]
+          then
+              rm -f $filename
+          fi
+      fi
+      if [ ! -f $filename ]
+      then
+          set +e
+          curl_output=$(curl -s --request PUT -H "Content-Type: application/json" --data "$json_config" "https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connector-plugins/$connector_class/config/validate" --header "authorization: Basic $authorization")
+          ret=$?
+          set -e
+          if [ $ret -eq 0 ]
+          then
+              error_code=$(echo "$curl_output" | jq -r .error_code)
+              if [ "$error_code" != "null" ]
+              then
+                  message=$(echo "$curl_output" | jq -r .message)
+                  logerror "Command failed with error code $error_code"
+                  logerror "$message"
+              else
+                  if ! echo "$curl_output" | jq -e .  > /dev/null 2>&1
+                  then
+                      set +e
+                      json_file=/tmp/json
+                      echo "$curl_output" > $json_file
+                      jq_output=$(jq . "$json_file" 2>&1)
+                      error_line=$(echo "$jq_output" | grep -oE 'parse error.*at line [0-9]+' | grep -oE '[0-9]+')
+
+                      if [[ -n "$error_line" ]]; then
+                          logerror "❌ Invalid JSON at line $error_line"
+                      fi
+                      set -e
+
+                      if [[ $(type -f bat 2>&1) =~ "not found" ]]
+                      then
+                          cat -n $json_file
+                      else
+                          bat $json_file --highlight-line $error_line
+                      fi
+
+                      exit 1
+                  fi
+
+                  current_group=""
+                  rows=()
+                  for row in $(echo "$curl_output" | jq -r '.configs[] | @base64'); do
+                      _jq() {
+                          echo ${row} | base64 --decode | jq -r ${1}
+                      }
+
+                      group=$(_jq '.definition.group')
+                      if [[ "$group" == "Common" || "$group" == "Transforms" || "$group" == "Error Handling" || "$group" == "Topic Creation" || "$group" == "offsets.topic" || "$group" == "Exactly Once Support" || "$group" == "Predicates" || "$group" == "Confluent Licensing" ]] ; then
+                          continue
+                      fi
+
+                      if [ "$group" != "$current_group" ]
+                      then
+                          echo -e "==========================" >> $filename
+                          echo -e "$group"                     >> $filename
+                          echo -e "==========================" >> $filename
+                          current_group=$group
+                      fi
+
+                      param=$(_jq '.definition.name')
+                      default=$(_jq '.definition.default_value')
+                      type=$(_jq '.definition.type')
+                      required=$(_jq '.definition.required')
+                      importance=$(_jq '.definition.importance')
+                      description=$(_jq '.definition.documentation')
+
+                      echo -e "🔘 $param" >> $filename
+                      echo -e "" >> $filename
+                      echo -e "$description" >> $filename
+                      echo -e "" >> $filename
+                      echo -e "\t - Type: $type" >> $filename
+                      echo -e "\t - Default: $default" >> $filename
+                      echo -e "\t - Importance: $importance" >> $filename
+                      echo -e "\t - Required: $required" >> $filename
+                      echo -e "" >> $filename
+                  done
+              fi
+          else
+              logerror "❌ curl request failed with error code $ret!"
+              exit 1
+          fi
+      fi
+
+      if [[ -n "$open" ]]
+      then
+          if config_has_key "editor"
+          then
+              editor=$(config_get "editor")
+          log "📖 Opening ${filename} using configured editor $editor"
+          $editor $filename
+          else
+              if [[ $(type code 2>&1) =~ "not found" ]]
+              then
+              logerror "Could not determine an editor to use as default code is not found - you can change editor by updating config.ini"
+              exit 1
+              else
+              log "📖 Opening ${filename} with code (default) - you can change editor by updating config.ini"
+              code $filename
+              fi
+          fi
+      else
+          # if [[ $(type -f bat 2>&1) =~ "not found" ]]
+          # then
+              cat $filename
+          # else
+          #     bat $filename
+          # fi
+      fi
+  done
 }
 
 # :command.function
@@ -17734,6 +17977,13 @@ playground_ccloud_connector_parse_requirements() {
       shift $#
       ;;
 
+    show-config)
+      action="show-config"
+      shift
+      playground_ccloud_connector_show_config_parse_requirements "$@"
+      shift $#
+      ;;
+
     create-or-update)
       action="create-or-update"
       shift
@@ -18091,6 +18341,80 @@ playground_ccloud_connector_show_lag_parse_requirements() {
 
         # :flag.case_no_arg
         args['--wait-for-zero-lag']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_ccloud_connector_show_config_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ccloud_connector_show_config_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="ccloud-connector show-config"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connector | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--connector']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector requires an argument: --connector, -c CONNECTOR" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --open | -o)
+
+        # :flag.case_no_arg
+        args['--open']=1
+        shift
+        ;;
+
+      # :flag.case
+      --force-refresh)
+
+        # :flag.case_no_arg
+        args['--force-refresh']=1
         shift
         ;;
 
@@ -19108,6 +19432,7 @@ run() {
     "ccloud-connector resume") playground_ccloud_connector_resume_command ;;
     "ccloud-connector delete") playground_ccloud_connector_delete_command ;;
     "ccloud-connector show-lag") playground_ccloud_connector_show_lag_command ;;
+    "ccloud-connector show-config") playground_ccloud_connector_show_config_command ;;
     "ccloud-connector create-or-update") playground_ccloud_connector_create_or_update_command ;;
     "connector") playground_connector_command ;;
     "connector status") playground_connector_status_command ;;
