wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -10884,23 +10884,26 @@ playground_switch_ccloud_command() {
   # src/switch_ccloud_command.sh
   log "🌩️ switch to ccloud environment"
 
+  for item in {ENVIRONMENT,CLUSTER_NAME,CLUSTER_CLOUD,CLUSTER_REGION,CLUSTER_CREDS,SCHEMA_REGISTRY_CREDS}
+  do
+  set +e
+  playground state get "ccloud.${item}" > /dev/null 2>&1
+  if [ $? != 0 ]
+  then
+      logerror "ccloud.${item} is missing"
+      logerror "a ccloud example was probably not executed before"
+      exit 1
+  fi
+  done
+
+  set +e
   ENVIRONMENT=$(playground state get ccloud.ENVIRONMENT)
   CLUSTER_NAME=$(playground state get ccloud.CLUSTER_NAME)
   CLUSTER_CLOUD=$(playground state get ccloud.CLUSTER_CLOUD)
   CLUSTER_REGION=$(playground state get ccloud.CLUSTER_REGION)
   CLUSTER_CREDS=$(playground state get ccloud.CLUSTER_CREDS)
   SCHEMA_REGISTRY_CREDS=$(playground state get ccloud.SCHEMA_REGISTRY_CREDS)
-
-  if [ -z $ENVIRONMENT ] || [ -z $CLUSTER_CLOUD ] || [ -z $CLUSTER_CLOUD ] || [ -z $CLUSTER_REGION ] || [ -z $CLUSTER_CREDS ]
-  then
-      logerror "One mandatory environment variable to use your cluster is missing:"
-      logerror "ENVIRONMENT=$ENVIRONMENT"
-      logerror "CLUSTER_NAME=$CLUSTER_NAME"
-      logerror "CLUSTER_CLOUD=$CLUSTER_CLOUD"
-      logerror "CLUSTER_REGION=$CLUSTER_REGION"
-      logerror "CLUSTER_CREDS=$CLUSTER_CREDS"
-      exit 1
-  fi
+  set -e
 
   playground state set run.environment_before_switch "$(playground state get run.environment)"
 
