added remove-all-docker-images command

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -52,6 +52,7 @@ playground_usage() {
   printf "  %s   ✨ Update current confluent platform or connector(s) with new version(s)\n" "$(green "update-version")                                "
   printf "  %s   👐 When --file is not provided, simply open last example you ran with <playground run> or <playground run-ccloud>\n" "$(green "open")                                          "
   printf "  %s   🛑 Stop currently running example\n" "$(green "stop")                                          "
+  printf "  %s   🧨 Remove all docker images (including docker volumes)\n" "$(green "remove-all-docker-images")                      "
   printf "  %s   🧑‍🎓 Open Confluent documentation of currently running example\n" "$(green "open-docs")                                     "
   echo
   printf "%s\n" "$(bold "Repro commands:")"
@@ -1919,6 +1920,35 @@ playground_stop_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground stop\n"
   printf "  playground stop --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_remove_all_docker_images_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground remove-all-docker-images - 🧨 Remove all docker images (including docker volumes)\n"
+    echo
+
+  else
+    printf "playground remove-all-docker-images - 🧨 Remove all docker images (including docker volumes)\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground remove-all-docker-images\n"
+  printf "  playground remove-all-docker-images --help | -h\n"
   echo
 
   # :command.long_usage
@@ -12311,6 +12341,17 @@ playground_stop_command() {
 }
 
 # :command.function
+playground_remove_all_docker_images_command() {
+  # src/remove_all_docker_images_command.sh
+  log "🧨 Remove all docker images (including docker volumes)"
+  check_if_continue
+
+  docker image rm $(docker image list | grep -v "oracle/database"  | grep -v "db-prebuilt" | awk 'NR>1 {print $3}') -f
+  docker system prune -a -f
+  docker volume rm $(docker volume ls -qf dangling=true)
+}
+
+# :command.function
 playground_open_docs_command() {
   # src/open_docs_command.sh
   only_show_url="${args[--only-show-url]}"
@@ -19530,6 +19571,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    remove-all-docker-images)
+      action="remove-all-docker-images"
+      shift
+      playground_remove_all_docker_images_parse_requirements "$@"
+      shift $#
+      ;;
+
     open-docs)
       action="open-docs"
       shift
@@ -22693,6 +22741,50 @@ playground_stop_parse_requirements() {
 
   # :command.command_filter
   action="stop"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_remove_all_docker_images_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_remove_all_docker_images_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="remove-all-docker-images"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -30122,6 +30214,7 @@ run() {
     "update-version") playground_update_version_command ;;
     "open") playground_open_command ;;
     "stop") playground_stop_command ;;
+    "remove-all-docker-images") playground_remove_all_docker_images_command ;;
     "open-docs") playground_open_docs_command ;;
     "repro") playground_repro_command ;;
     "repro export") playground_repro_export_command ;;
