wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -164,6 +164,7 @@ playground_usage() {
   printf "  %s   👷 Create kafka-docker-playground EC2 instance using AWS Cloud Formation\n" "$(green "ec2 create")                               "
   printf "  %s   ❌ Delete an EC2 instance created with Cloud Formation\n" "$(green "ec2 delete")                               "
   printf "  %s   👨‍💻 Open an EC2 instance using Visual Studio code\n" "$(green "ec2 open")                                 "
+  printf "  %s   🛂 Allow your current ip to connect to ec2 instance via ssh\n" "$(green "ec2 allow-my-ip")                          "
   printf "  %s   🔘 List all EC2 instance\n" "$(green "ec2 list")                                 "
   printf "  %s   🔴 Stop an EC2 instance\n" "$(green "ec2 stop")                                 "
   printf "  %s   🟢 Start an EC2 instance\n" "$(green "ec2 start")                                "
@@ -5583,6 +5584,7 @@ playground_ec2_usage() {
   printf "  %s   👷 Create kafka-docker-playground EC2 instance using AWS Cloud Formation\n" "$(green "create")                  "
   printf "  %s   ❌ Delete an EC2 instance created with Cloud Formation\n" "$(green "delete")                  "
   printf "  %s   👨‍💻 Open an EC2 instance using Visual Studio code\n" "$(green "open")                    "
+  printf "  %s   🛂 Allow your current ip to connect to ec2 instance via ssh\n" "$(green "allow-my-ip")             "
   printf "  %s   🔘 List all EC2 instance\n" "$(green "list")                    "
   printf "  %s   🔴 Stop an EC2 instance\n" "$(green "stop")                    "
   printf "  %s   🟢 Start an EC2 instance\n" "$(green "start")                   "
@@ -5712,6 +5714,33 @@ playground_ec2_open_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground ec2 open [OPTIONS]\n"
   printf "  playground ec2 open --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--instance, -i INSTANCE (required)")"
+    printf "    🖥️ EC2 instance (need to use completion to get all required details)\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ec2_allow_my_ip_usage() {
+  printf "playground ec2 allow-my-ip - 🛂 Allow your current ip to connect to ec2 instance via ssh\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ec2 allow-my-ip [OPTIONS]\n"
+  printf "  playground ec2 allow-my-ip --help | -h\n"
   echo
 
   # :command.long_usage
@@ -7454,7 +7483,7 @@ function wait_for_ec2_instance_to_be_running () {
   instance="$1"
   max_wait=${2:-300}
   cur_wait=0
-  log "⌛ Waiting up to $max_wait seconds for ec2 instance $instance to be running"
+  log "⌛ waiting up to $max_wait seconds for ec2 instance $instance to be running"
   playground ec2 status --instance $instance > /tmp/out.txt 2>&1
   while ! grep "running" /tmp/out.txt > /dev/null;
   do
@@ -7476,8 +7505,8 @@ function wait_for_ec2_cloudformation_to_be_completed () {
   stack_name="$1"
   max_wait=${2:-900}
   cur_wait=0
-  log "⌛ Waiting up to $max_wait seconds for ec2 cloudformation stack $stack_name to be in status CREATE_COMPLETE"
-  log "⌛ You can check progress by checking log file output.log in root folder of ec2 instance"
+  log "⌛ waiting up to $max_wait seconds for ec2 cloudformation stack $stack_name to be in status CREATE_COMPLETE"
+  log "⌛ you can check progress by checking log file output.log in root folder of ec2 instance"
 
   aws cloudformation describe-stacks --output text --query "Stacks[?StackName==\`$stack_name\`].StackStatus" > /tmp/out.txt 2>&1
   while ! grep "CREATE_COMPLETE" /tmp/out.txt > /dev/null;
@@ -24276,6 +24305,24 @@ playground_ec2_open_command() {
       instance=$(echo "$instance" | cut -d "@" -f 2)
   fi
   name=$(echo "${instance}" | cut -d "/" -f 1)
+  username=$(whoami)
+
+  playground ec2 allow-my-ip --instance "$instance"
+
+  log "👨‍💻 Open EC2 instance $name using Visual Studio code"
+  code --folder-uri "vscode-remote://ssh-remote+$name/home/$username"
+}
+
+# :command.function
+playground_ec2_allow_my_ip_command() {
+  # src/commands/ec2/allow-my-ip.sh
+  instance="${args[--instance]}"
+
+  if [[ $instance == *"@"* ]]
+  then
+      instance=$(echo "$instance" | cut -d "@" -f 2)
+  fi
+  name=$(echo "${instance}" | cut -d "/" -f 1)
   state=$(echo "${instance}" | cut -d "/" -f 2)
   ip=$(echo "${instance}" | cut -d "/" -f 3)
   id=$(echo "${instance}" | cut -d "/" -f 4)
@@ -24284,19 +24331,19 @@ playground_ec2_open_command() {
 
   if [ ! -f "$pem_file" ]
   then
-      logerror "❌ AWS EC2 pem file $pem_file file does not exist"
+      logerror "❌ aws ec2 pem file $pem_file file does not exist"
       exit 1
   fi
 
-  group=$(aws ec2 describe-instances --instance-id $id --output=json | jq '.Reservations[] | .Instances[] | {SecurityGroups: .SecurityGroups}' | jq -r '.SecurityGroups[0] | .GroupName')
+  group=$(aws ec2 describe-instances --instance-id "$id" --output=json | jq '.Reservations[] | .Instances[] | {SecurityGroups: .SecurityGroups}' | jq -r '.SecurityGroups[0] | .GroupName')
 
   # delete all rules
-  aws ec2 revoke-security-group-ingress --group-name $group \
+  aws ec2 revoke-security-group-ingress --group-name "$group" \
     --ip-permissions \
-    "$(aws ec2 describe-security-groups --output json --group-name $group --query "SecurityGroups[0].IpPermissions")"
+    "$(aws ec2 describe-security-groups --output json --group-name "$group" --query "SecurityGroups[0].IpPermissions")" > /dev/null
 
   myip=$(dig @resolver4.opendns.com myip.opendns.com +short)
-  aws ec2 authorize-security-group-ingress --group-name "$group" --protocol tcp --port 22 --cidr $myip/32 > /dev/null 2>&1 &
+  aws ec2 authorize-security-group-ingress --group-name "$group" --protocol tcp --port 22 --cidr "$myip/32" > /dev/null 2>&1 &
   if [ "$state" = "$EC2_INSTANCE_STATE_STOPPED" ]
   then
       log "🚀 starting the ec2 instance $name with id $id"
@@ -24306,18 +24353,27 @@ playground_ec2_open_command() {
   fi
 
   mkdir -p $HOME/.ssh
-  SSH_CONFIG_FILE=$HOME/.ssh/config
   username=$(whoami)
+  ssh_config_file=$HOME/.ssh/config
+
+  if [ -f "$ssh_config_file" ]
+  then
+      if grep "Host $name" -A 1 "$ssh_config_file" | grep "$ip" > /dev/null
+      then
+          log "🛂 ip $myip is now allowed to connect to ec2 instance $name"
+          exit 0
+      fi
+  fi
 
   set +e
-  grep "$name" $SSH_CONFIG_FILE > /dev/null
+  grep "$name" "$ssh_config_file" > /dev/null
   if [ $? = 0 ]
   then
-      OLDIP=$(grep -w $name -A 1 ${SSH_CONFIG_FILE} | awk '/HostName/ {print $2}')
-      sed -e "s/$OLDIP/$ip/g" ${SSH_CONFIG_FILE} > /tmp/tmp_file
-      mv /tmp/tmp_file ${SSH_CONFIG_FILE}
+      old_ip=$(grep -w $name -A 1 ${ssh_config_file} | awk '/HostName/ {print $2}')
+      sed -e "s/$old_ip/$ip/g" ${ssh_config_file} > /tmp/tmp_file
+      mv /tmp/tmp_file "${ssh_config_file}"
   else
-  cat << EOF >> ${SSH_CONFIG_FILE}
+  cat << EOF >> "${ssh_config_file}"
 
 Host $name
   HostName $ip
@@ -24329,8 +24385,7 @@ EOF
   fi
   set -e
 
-  log "👨‍💻 Open EC2 instance $name using Visual Studio code (only your ip $myip is allowed to connect)"
-  code --folder-uri "vscode-remote://ssh-remote+$name/home/$username"
+  log "🛂 ip $myip is now allowed to connect to ec2 instance $name"
 }
 
 # :command.function
@@ -36937,6 +36992,13 @@ playground_ec2_parse_requirements() {
       shift $#
       ;;
 
+    allow-my-ip)
+      action="allow-my-ip"
+      shift
+      playground_ec2_allow_my_ip_parse_requirements "$@"
+      shift $#
+      ;;
+
     list)
       action="list"
       shift
@@ -37264,6 +37326,76 @@ playground_ec2_open_parse_requirements() {
 
   # :command.command_filter
   action="ec2 open"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --instance | -i)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--instance']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--instance requires an argument: --instance, -i INSTANCE" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--instance']+x} ]]; then
+    printf "missing required flag: --instance, -i INSTANCE\n" >&2
+    exit 1
+  fi
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--instance'] && -n $(validate_not_empty "${args['--instance']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--instance, -i INSTANCE" "$(validate_not_empty "${args['--instance']:-}")" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_ec2_allow_my_ip_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ec2_allow_my_ip_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="ec2 allow-my-ip"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -37944,6 +38076,7 @@ run() {
     "ec2 create") playground_ec2_create_command ;;
     "ec2 delete") playground_ec2_delete_command ;;
     "ec2 open") playground_ec2_open_command ;;
+    "ec2 allow-my-ip") playground_ec2_allow_my_ip_command ;;
     "ec2 list") playground_ec2_list_command ;;
     "ec2 stop") playground_ec2_stop_command ;;
     "ec2 start") playground_ec2_start_command ;;
