added debug generate-diagnostics

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -63,6 +63,7 @@ playground_usage() {
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                                  "
   [[ -n $long_usage ]] && printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "debug enable-remote-debugging")          "
   [[ -n $long_usage ]] && printf "  %s   🔐 Testing TLS/SSL encryption using https://testssl.sh/\n" "$(green "debug testssl")                          "
+  [[ -n $long_usage ]] && printf "  %s   ⛑️ Generate a diagnostic bundle with Diagnostics Bundle Tool\n" "$(green "debug generate-diagnostics")             "
   [[ -n $long_usage ]] && printf "  %s   🎯 Take a java thread dump\n" "$(green "debug thread-dump")                      "
   [[ -n $long_usage ]] && printf "  %s   👻 Take a heap dump\n" "$(green "debug heap-dump")                        "
   [[ -n $long_usage ]] && printf "  %s   🕵️‍♂️ Take a tcp dump (sniffing network)\n" "$(green "debug tcp-dump")                         "
@@ -1417,6 +1418,7 @@ playground_debug_usage() {
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "enable-remote-debugging")"
   printf "  %s   🔐 Testing TLS/SSL encryption using https://testssl.sh/\n" "$(green "testssl")                "
+  printf "  %s   ⛑️ Generate a diagnostic bundle with Diagnostics Bundle Tool\n" "$(green "generate-diagnostics")   "
   printf "  %s   🎯 Take a java thread dump\n" "$(green "thread-dump")            "
   printf "  %s   👻 Take a heap dump\n" "$(green "heap-dump")              "
   printf "  %s   🕵️‍♂️ Take a tcp dump (sniffing network)\n" "$(green "tcp-dump")               "
@@ -1524,6 +1526,51 @@ playground_debug_testssl_usage() {
     printf "%s\n" "$(bold "Examples")"
     printf "  playground debug testssl https://google.com\n"
     printf "  playground debug testssl pkc-xxxx.us-west-2.aws.confluent.cloud:9092\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_debug_generate_diagnostics_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground debug generate-diagnostics\n"
+    echo
+
+    printf "  ⛑️ Generate a diagnostic bundle with Diagnostics Bundle Tool\n  \n  ⚠️ only connect and broker containers are supported for now\n  \n  see\n  https://docs.confluent.io/platform/current/tools/diagnostics-tool.html#collect-diagnostics\n"
+    echo
+
+  else
+    printf "playground debug generate-diagnostics - ⛑️ Generate a diagnostic bundle with Diagnostics Bundle Tool\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground debug generate-diagnostics [OPTIONS]\n"
+  printf "  playground debug generate-diagnostics --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    🐳 Container name\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground debug generate-diagnostics\n"
+    printf "  playground debug generate-diagnostics --container broker\n"
     echo
 
   fi
@@ -10487,6 +10534,51 @@ playground_debug_testssl_command() {
 }
 
 # :command.function
+playground_debug_generate_diagnostics_command() {
+  # src/debug_generate_diagnostics_command.sh
+  container="${args[--container]}"
+  tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
+  trap 'rm -rf $tmp_dir' EXIT
+
+  if [[ "$container" == "connect" ]] || [[ "$container" == "broker" ]]
+  then
+      log "⛑️ Creating diagnostics bundle for container ${container}"
+      log "⏳ please wait..."
+  else
+      logerror "❌ only connect and broker containers are supported"
+      exit 1
+  fi
+
+  docker exec $container curl -L https://packages.confluent.io/tools/diagnostics-bundle/diagnostics-bundle-1.0.0.jar -o /tmp/diagnostics-bundle-1.0.0.jar > /dev/null 2>&1
+
+  fifo_path="$tmp_dir/collect_fifo"
+  mkfifo "$fifo_path"
+
+  set +e
+  docker exec $container java -jar /tmp/diagnostics-bundle-1.0.0.jar collect > "$fifo_path" 2>&1 &
+
+  # Loop through each line in the named pipe
+  while read -r line
+  do
+      echo "$line"
+      echo "$line" >> $tmp_dir/result.log
+
+  done < "$fifo_path"
+
+  nb=$(grep -c "Diagnostics output has been zipped and written to" $tmp_dir/result.log)
+  if [ $nb -eq 0 ]
+  then
+      logerror "❌ Failed to generate bundle"
+      cat $tmp_dir/result.log
+      exit 1
+  fi
+  bundle_file=$(cat $tmp_dir/result.log | grep "Diagnostics output has been zipped and written to" | cut -d ":" -f 4 | sed 's/ //g')
+  bundle_file_filename=$(basename -- "$bundle_file")
+  log "⛑️ diagnostics bundle is available at ${bundle_file_filename}"
+  docker cp ${container}:${bundle_file} ${bundle_file_filename}
+}
+
+# :command.function
 playground_debug_thread_dump_command() {
   # src/debug_thread_dump_command.sh
   container="${args[--container]}"
@@ -16668,6 +16760,13 @@ playground_debug_parse_requirements() {
       shift $#
       ;;
 
+    generate-diagnostics)
+      action="generate-diagnostics"
+      shift
+      playground_debug_generate_diagnostics_parse_requirements "$@"
+      shift $#
+      ;;
+
     thread-dump)
       action="thread-dump"
       shift
@@ -16854,6 +16953,67 @@ playground_debug_testssl_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_debug_generate_diagnostics_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_debug_generate_diagnostics_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="debug generate-diagnostics"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
 
 }
 
@@ -21259,6 +21419,7 @@ run() {
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
     "debug testssl") playground_debug_testssl_command ;;
+    "debug generate-diagnostics") playground_debug_generate_diagnostics_command ;;
     "debug thread-dump") playground_debug_thread_dump_command ;;
     "debug heap-dump") playground_debug_heap_dump_command ;;
     "debug tcp-dump") playground_debug_tcp_dump_command ;;
