wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -46,6 +46,7 @@ playground_usage() {
   echo
   printf "%s\n" "$(bold "Repro commands:")"
   printf "  %s   👷‍♂️ Reproduction model commands\n" "$(green "repro")                                  "
+  [[ -n $long_usage ]] && printf "  %s   ↗️ Export your reproduction models to easily share.\n" "$(green "repro export")                           "
   [[ -n $long_usage ]] && printf "  %s   🛠  Bootstrap reproduction model\n" "$(green "repro bootstrap")                        "
   echo
   printf "%s\n" "$(bold "Kafka commands:")"
@@ -924,12 +925,57 @@ playground_repro_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
+  printf "  %s   ↗️ Export your reproduction models to easily share.\n" "$(green "export")   "
   printf "  %s   🛠  Bootstrap reproduction model\n" "$(green "bootstrap")"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_environment_variables
+    printf "%s\n" "$(bold "Environment Variables:")"
+
+    # :environment_variable.usage
+    printf "  %s\n" "$(cyan "OUTPUT_FOLDER")"
+    printf "    📁 Output folder where to generate bootstrapped files\n"
+    printf "    Default: reproduction-models\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_repro_export_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground repro export - ↗️ Export your reproduction models to easily share.\n"
+    echo
+
+  else
+    printf "playground repro export - ↗️ Export your reproduction models to easily share.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground repro export [OPTIONS]\n"
+  printf "  playground repro export --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--all")"
+    printf "    Export all uncommitted reproduction models\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -1107,15 +1153,6 @@ playground_repro_bootstrap_usage() {
 
     echo "  ARGUMENTS..."
     printf "    Arguments to use by example script\n    \n    Most of examples support to get required options either by using arguments\n    or environment variables.\n    \n    Example with Zendesk:\n    \n    playground run -f zendesk-source<tab> <ZENDESK_URL> <ZENDESK_USERNAME>\n    <ZENDESK_PASSWORD>\n"
-    echo
-
-    # :command.usage_environment_variables
-    printf "%s\n" "$(bold "Environment Variables:")"
-
-    # :environment_variable.usage
-    printf "  %s\n" "$(cyan "OUTPUT_FOLDER")"
-    printf "    📁 Output folder where to generate bootstrapped files\n"
-    printf "    Default: reproduction-models\n"
     echo
 
     # :command.usage_examples
@@ -8739,6 +8776,123 @@ playground_open_docs_command() {
 }
 
 # :command.function
+playground_repro_export_command() {
+  # src/repro_export_command.sh
+  all="${args[--all]}"
+
+  DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+  dir1=$(echo ${DIR_CLI%/*})
+  root_folder=$(echo ${dir1%/*})
+
+  if [ ! -z "$OUTPUT_FOLDER" ]
+  then
+    output_folder="$OUTPUT_FOLDER"
+  else
+    output_folder="reproduction-models"
+  fi
+
+  if [ "$output_folder" != "reproduction-models" ]
+  then
+      logerror "❌ OUTPUT_FOLDER $output_folder is not set with reproduction-models, this is the only supported value !"
+      exit 1
+  fi
+
+  repro_dir=$root_folder/$output_folder
+  cd $repro_dir
+
+  output_filename="playground_repro_export.tgz"
+  final_archive=$repro_dir/$output_filename
+  if [ -f $final_archive ]
+  then
+      rm -rf $final_archive
+  fi
+  set +e
+  if [[ -n "$all" ]]
+  then
+      if git rev-parse --git-dir > /dev/null 2>&1
+      then
+          new_files=$(git status --porcelain 2>/dev/null  | grep "^?? " | cut -d " " -f2-)
+          if [[ -n "$new_files" ]]
+          then
+              log "💫 detected new files:"
+              echo "$new_files"
+              tar cvfz "$output_filename" $new_files > /dev/null 2>&1
+              if [ -f $final_archive ]
+              then
+                  log "✅ Exported archive is available: $final_archive"
+              else
+                  logerror "❌ export failed as archive could not be created !"
+                  exit 1
+              fi
+          else
+              logerror "❌ No new files found !"
+              exit 1
+          fi
+      else
+          logerror "❌ output folder is not managed by git, please clone repository using git clone"
+          exit 1
+      fi
+  else
+      # copy only current example
+      if [ ! -f /tmp/playground-run ]
+      then
+          logerror "File containing re-run command /tmp/playground-run does not exist!"
+          logerror "Make sure to use <playground run> command !"
+          exit 1
+      fi
+
+      test_file=$(cat /tmp/playground-run | awk '{ print $4}')
+
+      if [ ! -f $test_file ]
+      then
+
+          logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
+          logerror "Make sure to use <playground run> command !"
+          exit 1
+      fi
+
+      test_file_directory="$(dirname "${test_file}")"
+      base1="${test_file_directory##*/}" # connect-connect-aws-s3-sink
+      dir1="${test_file_directory%/*}" # reproduction-models
+      dir2="${dir1##*/}/$base1" # reproduction-models/connect-connect-aws-s3-sink
+
+      if [[ "$dir2" != ${output_folder}* ]]
+      then
+          logerror "example <$dir2> is not from OUTPUT_FOLDER ${output_folder} folder, only examples in there can be exported"
+          exit 1
+      fi
+
+      if git rev-parse --git-dir > /dev/null 2>&1
+      then
+          cd $test_file_directory
+
+          new_files=$(git status --porcelain . 2>/dev/null  | grep "^?? " | cut -d " " -f2-)
+          if [[ -n "$new_files" ]]
+          then
+              log "💫 detected new files:"
+              echo "$new_files"
+              cd - >/dev/null
+              tar cvfz "$output_filename" $new_files > /dev/null 2>&1
+              if [ -f $final_archive ]
+              then
+                  log "✅ Exported archive is available: $final_archive"
+              else
+                  logerror "❌ export failed as archive could not be created !"
+                  exit 1
+              fi
+          else
+              logerror "❌ No new files found !"
+              exit 1
+          fi
+      else
+          logerror "❌ output folder is not managed by git, please clone repository using git clone"
+          exit 1
+      fi
+  fi
+
+}
+
+# :command.function
 playground_repro_bootstrap_command() {
   # src/repro_bootstrap_command.sh
   IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
@@ -14961,11 +15115,31 @@ playground_repro_parse_requirements() {
     esac
   done
 
+  # :command.environment_variables_filter
+  # :command.environment_variables_default
+  export OUTPUT_FOLDER="${OUTPUT_FOLDER:-reproduction-models}"
+
+  # :command.dependencies_filter
+  if command -v fzf >/dev/null 2>&1; then
+    deps['fzf']="$(command -v fzf | head -n1)"
+  else
+    printf "missing dependency: fzf\n" >&2
+    printf "%s\n" "visit $(blue_underlined https://github.com/junegunn/fzf#installation) to install" >&2
+    exit 1
+  fi
+
   # :command.command_filter
   action=${1:-}
 
   case $action in
     -*) ;;
+
+    export)
+      action="export"
+      shift
+      playground_repro_export_parse_requirements "$@"
+      shift $#
+      ;;
 
     bootstrap)
       action="bootstrap"
@@ -15011,6 +15185,66 @@ playground_repro_parse_requirements() {
 }
 
 # :command.parse_requirements
+playground_repro_export_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_repro_export_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  if command -v git >/dev/null 2>&1; then
+    deps['git']="$(command -v git | head -n1)"
+  else
+    printf "missing dependency: git\n" >&2
+    printf "%s\n" "visit $(blue_underlined https://git-scm.com/downloads) to install" >&2
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="repro export"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --all)
+
+        # :flag.case_no_arg
+        args['--all']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 playground_repro_bootstrap_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -15027,19 +15261,6 @@ playground_repro_bootstrap_parse_requirements() {
 
     esac
   done
-
-  # :command.environment_variables_filter
-  # :command.environment_variables_default
-  export OUTPUT_FOLDER="${OUTPUT_FOLDER:-reproduction-models}"
-
-  # :command.dependencies_filter
-  if command -v fzf >/dev/null 2>&1; then
-    deps['fzf']="$(command -v fzf | head -n1)"
-  else
-    printf "missing dependency: fzf\n" >&2
-    printf "%s\n" "visit $(blue_underlined https://github.com/junegunn/fzf#installation) to install" >&2
-    exit 1
-  fi
 
   # :command.command_filter
   action="repro bootstrap"
@@ -20109,6 +20330,7 @@ run() {
     "stop") playground_stop_command ;;
     "open-docs") playground_open_docs_command ;;
     "repro") playground_repro_command ;;
+    "repro export") playground_repro_export_command ;;
     "repro bootstrap") playground_repro_bootstrap_command ;;
     "get-docker-compose") playground_get_docker_compose_command ;;
     "get-properties") playground_get_properties_command ;;
