do not show json

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -4991,7 +4991,7 @@ function bootstrap_ccloud_environment () {
 function create_ccloud_connector() {
   file=$1
 
-  log "Creating connector from $file"
+  log "🛠️ Creating connector from $file"
   confluent connect cluster create --config-file $file
   if [[ $? != 0 ]]
   then
@@ -9785,15 +9785,14 @@ playground_ccloud_connector_create_or_update_command() {
   echo "$json_content" > $json_file
 
   # JSON is invalid
-  if ! echo "$json_content" | jq -e .
-
+  if ! echo "$json_content" | jq -e . > /dev/null 2>&1
   then
       set +e
       jq_output=$(jq . "$json_file" 2>&1)
       error_line=$(echo "$jq_output" | grep -oE 'parse error.*at line [0-9]+' | grep -oE '[0-9]+')
 
       if [[ -n "$error_line" ]]; then
-          logerror "Invalid JSON at line $error_line"
+          logerror "❌ Invalid JSON at line $error_line"
       fi
       set -e
 
@@ -9828,9 +9827,9 @@ playground_ccloud_connector_create_or_update_command() {
 
   if [ $is_create == 1 ]
   then
-      log "Creating connector $connector"
+      log "🛠️ Creating connector $connector"
   else
-      log "Updating connector $connector"
+      log "🔄 Updating connector $connector"
   fi
 
   curl_output=$(curl $security -s -X PUT \
@@ -9850,15 +9849,15 @@ playground_ccloud_connector_create_or_update_command() {
       else
           if [ $is_create == 1 ]
           then
-              log "Connector $connector was successfully created"
+              log "✅ Connector $connector was successfully created"
           else
-              log "Connector $connector was successfully updated"
+              log "✅ Connector $connector was successfully updated"
           fi
           sleep 3
           playground ccloud-connector status
       fi
   else
-      logerror "curl request failed !"
+      logerror "❌ curl request failed !"
       echo "$curl_output"
       exit 1
   fi
@@ -10274,15 +10273,14 @@ playground_connector_create_or_update_command() {
   echo "$json_content" > $json_file
 
   # JSON is invalid
-  if ! echo "$json_content" | jq -e .
-
+  if ! echo "$json_content" | jq -e .  > /dev/null 2>&1
   then
       set +e
       jq_output=$(jq . "$json_file" 2>&1)
       error_line=$(echo "$jq_output" | grep -oE 'parse error.*at line [0-9]+' | grep -oE '[0-9]+')
 
       if [[ -n "$error_line" ]]; then
-          logerror "Invalid JSON at line $error_line"
+          logerror "❌ Invalid JSON at line $error_line"
       fi
       set -e
 
@@ -10316,9 +10314,9 @@ playground_connector_create_or_update_command() {
 
   if [ $is_create == 1 ]
   then
-      log "Creating connector $connector"
+      log "🛠️ Creating connector $connector"
   else
-      log "Updating connector $connector"
+      log "🔄 Updating connector $connector"
   fi
 
   curl_output=$(curl $security -s -X PUT \
@@ -10337,15 +10335,15 @@ playground_connector_create_or_update_command() {
       else
           if [ $is_create == 1 ]
           then
-              log "Connector $connector was successfully created"
+              log "✅ Connector $connector was successfully created"
           else
-              log "Connector $connector was successfully updated"
+              log "✅ Connector $connector was successfully updated"
           fi
           sleep 3
           playground connector status
       fi
   else
-      logerror "curl request failed !"
+      logerror "❌ curl request failed !"
       echo "$curl_output"
       exit 1
   fi
