add --grep command to topic consume

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1894,6 +1894,12 @@ playground_topic_consume_usage() {
     printf "    Default: \n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--grep GREP")"
+    printf "    Verify that topic content contains record which contains specified string\n"
+    printf "    Default: \n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -8568,6 +8574,7 @@ playground_topic_consume_command() {
   # src/topic_consume_command.sh
   topic="${args[--topic]}"
   max_messages="${args[--max-messages]}"
+  grep_string="${args[--grep]}"
 
   environment=`get_environment_used`
 
@@ -8685,13 +8692,13 @@ playground_topic_consume_command() {
       avro|protobuf|json-schema)
           if [ "$key_type" == "avro" ] || [ "$key_type" == "protobuf" ] || [ "$key_type" == "json-schema" ]
           then
-              docker exec -e SCHEMA_REGISTRY_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties" $container kafka-$value_type-console-consumer -bootstrap-server broker:9092 --property schema.registry.url=$sr_url_cli --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" --skip-message-on-error $security --from-beginning --max-messages $nb_messages > "$fifo_path" &
+              docker exec -e SCHEMA_REGISTRY_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties" $container kafka-$value_type-console-consumer -bootstrap-server broker:9092 --property schema.registry.url=$sr_url_cli --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" --skip-message-on-error $security --from-beginning --max-messages $nb_messages > "$fifo_path" 2>&1 &
           else
-              docker exec -e SCHEMA_REGISTRY_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties" $container kafka-$value_type-console-consumer --bootstrap-server broker:9092 --property schema.registry.url=$sr_url_cli --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" --property key.deserializer=org.apache.kafka.common.serialization.StringDeserializer --skip-message-on-error $security --from-beginning --max-messages $nb_messages > "$fifo_path" &
+              docker exec -e SCHEMA_REGISTRY_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties" $container kafka-$value_type-console-consumer --bootstrap-server broker:9092 --property schema.registry.url=$sr_url_cli --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" --property key.deserializer=org.apache.kafka.common.serialization.StringDeserializer --skip-message-on-error $security --from-beginning --max-messages $nb_messages > "$fifo_path" 2>&1 &
           fi
           ;;
       *)
-          docker exec $container kafka-console-consumer --bootstrap-server broker:9092 --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" $security --from-beginning --max-messages $nb_messages > "$fifo_path" &
+          docker exec $container kafka-console-consumer --bootstrap-server broker:9092 --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" $security --from-beginning --max-messages $nb_messages > "$fifo_path" 2>&1  &
       ;;
     esac
 
@@ -8704,6 +8711,7 @@ playground_topic_consume_command() {
       date_command="date -d @"
     fi
 
+    found=0
     # Loop through each line in the named pipe
     while read -r line
     do
@@ -8717,10 +8725,30 @@ playground_topic_consume_command() {
         readable_date="$(${date_command}${timestamp_sec} "+%Y-%m-%d %H:%M:%S.${milliseconds}")"
         line_with_date=$(echo "$line" | sed -E "s/CreateTime:[0-9]{13}/CreateTime: ${readable_date}/")
         echo "$line_with_date"
+      elif [[ $line =~ "Processed a total of" ]]
+      then
+        continue
       else
         echo "$line"
       fi
+      if [[ -n "$grep_string" ]]
+      then
+        if [[ $line =~ "$grep_string" ]]
+        then
+          log "✅ found $grep_string in topic $topic"
+          found=1
+        fi
+      fi
     done < "$fifo_path"
+
+    if [[ -n "$grep_string" ]]
+    then
+      if [ $found != 1 ]
+      then
+        logerror "❌ could not find $grep_string in topic $topic"
+        exit 1
+      fi
+    fi
   done
 }
 
@@ -12822,6 +12850,21 @@ playground_topic_consume_parse_requirements() {
         fi
         ;;
 
+      # :flag.case
+      --grep)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--grep']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--grep requires an argument: --grep GREP" >&2
+          exit 1
+        fi
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -12840,6 +12883,7 @@ playground_topic_consume_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['--max-messages']:-} ]] || args['--max-messages']=""
+  [[ -n ${args['--grep']:-} ]] || args['--grep']=""
 
   # :command.user_filter
   filter_error=$(filter_schema_registry_running)
