show method signatures

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -134,7 +134,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   🐢 Show lag of sink connector\n" "$(green "connector show-lag")                     "
   [[ -n $long_usage ]] && printf "  %s   🧰 Show current connector config\n" "$(green "connector show-config")                  "
   [[ -n $long_usage ]] && printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "connector show-config-parameters")       "
-  [[ -n $long_usage ]] && printf "  %s   🔌 Connector plugin from confluent hub https://www.confluent.io/hub/\n" "$(green "connector search-jar")                   "
+  [[ -n $long_usage ]] && printf "  %s   🔌 List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "connector search-jar")                   "
   [[ -n $long_usage ]] && printf "  %s   🧬 Set connect log level\n" "$(green "connector log-level")                    "
   [[ -n $long_usage ]] && printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "connector create-or-update")             "
   echo
@@ -4179,7 +4179,7 @@ playground_connector_usage() {
   printf "  %s   🐢 Show lag of sink connector\n" "$(green "show-lag")              "
   printf "  %s   🧰 Show current connector config\n" "$(green "show-config")           "
   printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "show-config-parameters")"
-  printf "  %s   🔌 Connector plugin from confluent hub https://www.confluent.io/hub/\n" "$(green "search-jar")            "
+  printf "  %s   🔌 List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "search-jar")            "
   printf "  %s   🧬 Set connect log level\n" "$(green "log-level")             "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")      "
   echo
@@ -4604,11 +4604,11 @@ playground_connector_show_config_parameters_usage() {
 # :command.usage
 playground_connector_search_jar_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground connector search-jar - 🔌 Connector plugin from confluent hub https://www.confluent.io/hub/\n"
+    printf "playground connector search-jar - 🔌 List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n"
     echo
 
   else
-    printf "playground connector search-jar - 🔌 Connector plugin from confluent hub https://www.confluent.io/hub/\n"
+    printf "playground connector search-jar - 🔌 List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n"
     echo
 
   fi
@@ -5650,13 +5650,13 @@ send_completions() {
 function log() {
   YELLOW='\033[0;33m'
   NC='\033[0m' # No Color
-  echo -e "$YELLOW`date +"%H:%M:%S"` ℹ️ $@$NC"
+  echo -e "$YELLOW$(date +"%H:%M:%S") ℹ️ $@$NC"
 }
 
 function logerror() {
   RED='\033[0;31m'
   NC='\033[0m' # No Color
-  echo -e "$RED`date +"%H:%M:%S"` 🔥 $@$NC"
+  echo -e "$RED$(date +"%H:%M:%S") 🔥 $@$NC"
 }
 
 function logwarn() {
@@ -16173,7 +16173,23 @@ playground_connector_search_jar_command() {
   if [[ -n "$class" ]]
   then
     log "Searching for java class $class in all jars"
-    find . -name '*.jar' -print | while read i; do jar -tvf "$i" | grep -Hsi ${class} && log "👉 $i"; done
+    find . -name '*.jar' -print | while read i;
+
+    do
+
+      set +e
+      jar -tvf "$i" | grep -Hsi ${class} | awk '{print $10}' | sed 's/\.class$//' | tr '/' '.' | while read j
+      do
+        if [ $? -eq 0 ]
+        then
+          if [ "$j" != "" ]
+          then
+            log "👉 method signatures from $i jar for class $j"
+            javap -classpath $i $j
+          fi
+        fi
+      done
+    done
   fi
 }
 
@@ -25217,6 +25233,15 @@ playground_connector_search_jar_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
+  if command -v javap >/dev/null 2>&1; then
+    deps['javap']="$(command -v javap | head -n1)"
+  else
+    printf "missing dependency: javap\n" >&2
+    printf "%s\n" "visit https://openjdk.org/install/ to install" >&2
+    exit 1
+  fi
 
   # :command.command_filter
   action="connector search-jar"
