renaming to avoid clash

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -653,13 +653,11 @@ playground_run_ccloud_usage() {
     printf "  %s\n" "$(magenta "--cluster-cloud CLUSTER-CLOUD")"
     printf "    🌤 The cloud provider: aws, gcp or azure. Default is aws\n    \n    🎓 Tip: you can also use CLUSTER_CLOUD environment variable\n"
     printf "    Allowed: aws, gcp, azure\n"
-    printf "    Default: aws\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "$(magenta "--cluster-region CLUSTER-REGION")"
     printf "    🗺 The Cloud region. \n    \n    🎓 Tip: you can also use CLUSTER_REGION environment variable\n"
-    printf "    Default: eu-west-2\n"
     echo
 
     # :flag.usage
@@ -853,7 +851,6 @@ playground_bootstrap_reproduction_model_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--cluster-region CLUSTER-REGION")"
     printf "    🗺 The Cloud region. \n    \n    🎓 Tip: you can also use CLUSTER_REGION environment variable\n"
-    printf "    Default: eu-west-2\n"
     echo
 
     # :flag.usage
@@ -4412,12 +4409,12 @@ function bootstrap_ccloud_environment () {
   ccloud::create_ccloud_stack false  \
     && print_code_pass -c "ccloud::create_ccloud_stack false"
 
-  CONFIG_FILE=/tmp/tmp.config
-  export CONFIG_FILE=$CONFIG_FILE
-  ccloud::validate_ccloud_config $CONFIG_FILE || exit 1
+  CCLOUD_CONFIG_FILE=/tmp/tmp.config
+  export CCLOUD_CONFIG_FILE=$CCLOUD_CONFIG_FILE
+  ccloud::validate_ccloud_config $CCLOUD_CONFIG_FILE || exit 1
 
-  ccloud::generate_configs $CONFIG_FILE \
-    && print_code_pass -c "ccloud::generate_configs $CONFIG_FILE"
+  ccloud::generate_configs $CCLOUD_CONFIG_FILE \
+    && print_code_pass -c "ccloud::generate_configs $CCLOUD_CONFIG_FILE"
 
   if [ -f $DELTA_CONFIGS_ENV ]
   then
@@ -5276,7 +5273,7 @@ function ccloud::create_acls_connect_topics() {
 
 function ccloud::validate_ccloud_stack_up() {
   CLOUD_KEY=$1
-  CONFIG_FILE=$2
+  CCLOUD_CONFIG_FILE=$2
   enable_ksqldb=$3
 
   if [ -z "$enable_ksqldb" ]; then
@@ -5288,7 +5285,7 @@ function ccloud::validate_ccloud_stack_up() {
   ccloud::validate_schema_registry_up "$SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO" "$SCHEMA_REGISTRY_URL" || exit 1
   if $enable_ksqldb ; then
     ccloud::validate_ksqldb_up "$KSQLDB_ENDPOINT" || exit 1
-    ccloud::validate_credentials_ksqldb "$KSQLDB_ENDPOINT" "$CONFIG_FILE" "$KSQLDB_BASIC_AUTH_USER_INFO" || exit 1
+    ccloud::validate_credentials_ksqldb "$KSQLDB_ENDPOINT" "$CCLOUD_CONFIG_FILE" "$KSQLDB_BASIC_AUTH_USER_INFO" || exit 1
   fi
 }
 
@@ -5450,11 +5447,11 @@ function ccloud::create_ccloud_stack() {
   confluent api-key use $CLOUD_API_KEY --resource ${CLUSTER}
 
   if [[ -z "$SKIP_CONFIG_FILE_WRITE" ]]; then
-    if [[ -z "$CONFIG_FILE" ]]; then
-      CONFIG_FILE="/tmp/tmp.config"
+    if [[ -z "$CCLOUD_CONFIG_FILE" ]]; then
+      CCLOUD_CONFIG_FILE="/tmp/tmp.config"
     fi
 
-    cat <<EOF > $CONFIG_FILE
+    cat <<EOF > $CCLOUD_CONFIG_FILE
 # --------------------------------------
 # Confluent Cloud connection information
 # --------------------------------------
@@ -5464,11 +5461,11 @@ function ccloud::create_ccloud_stack() {
 # SCHEMA REGISTRY CLUSTER ID: ${SCHEMA_REGISTRY}
 EOF
     if $enable_ksqldb ; then
-      cat <<EOF >> $CONFIG_FILE
+      cat <<EOF >> $CCLOUD_CONFIG_FILE
 # KSQLDB APP ID: ${KSQLDB}
 EOF
     fi
-    cat <<EOF >> $CONFIG_FILE
+    cat <<EOF >> $CCLOUD_CONFIG_FILE
 # --------------------------------------
 sasl.mechanism=PLAIN
 security.protocol=SASL_SSL
@@ -5480,14 +5477,14 @@ basic.auth.user.info=`echo $SCHEMA_REGISTRY_CREDS | awk -F: '{print $1}'`:`echo 
 replication.factor=${REPLICATION_FACTOR}
 EOF
     if $enable_ksqldb ; then
-      cat <<EOF >> $CONFIG_FILE
+      cat <<EOF >> $CCLOUD_CONFIG_FILE
 ksql.endpoint=${KSQLDB_ENDPOINT}
 ksql.basic.auth.user.info=`echo $KSQLDB_CREDS | awk -F: '{print $1}'`:`echo $KSQLDB_CREDS | awk -F: '{print $2}'`
 EOF
     fi
 
     echo
-    echo "Client configuration file saved to: $CONFIG_FILE"
+    echo "Client configuration file saved to: $CCLOUD_CONFIG_FILE"
   fi
 
   return 0
@@ -5508,7 +5505,7 @@ function ccloud::destroy_ccloud_stack() {
 
   ENVIRONMENT_NAME_PREFIX=${ENVIRONMENT_NAME_PREFIX:-"pg-$SERVICE_ACCOUNT_ID"}
   CLUSTER_NAME=${CLUSTER_NAME:-"pg-cluster-$SERVICE_ACCOUNT_ID"}
-  CONFIG_FILE=${CONFIG_FILE:-"/tmp/tmp.config"}
+  CCLOUD_CONFIG_FILE=${CCLOUD_CONFIG_FILE:-"/tmp/tmp.config"}
   KSQLDB_NAME=${KSQLDB_NAME:-"demo-ksqldb-$SERVICE_ACCOUNT_ID"}
 
   # Setting default QUIET=false to surface potential errors
@@ -5552,7 +5549,7 @@ function ccloud::destroy_ccloud_stack() {
     fi
   fi
 
-  rm -f $CONFIG_FILE
+  rm -f $CCLOUD_CONFIG_FILE
 
   return 0
 }
@@ -5591,9 +5588,9 @@ function ccloud::destroy_ccloud_stack() {
 #
 # Arguments:
 #
-#   CONFIG_FILE, defaults to ~/.ccloud/config
+#   CCLOUD_CONFIG_FILE, defaults to ~/.ccloud/config
 #
-# Example CONFIG_FILE at ~/.ccloud/config
+# Example CCLOUD_CONFIG_FILE at ~/.ccloud/config
 #
 #   $ cat $HOME/.ccloud/config
 #
@@ -5614,27 +5611,27 @@ function ccloud::destroy_ccloud_stack() {
 #   ksql.basic.auth.user.info=<ksqlDB API KEY>:<ksqlDB API SECRET>
 #
 function ccloud::generate_configs() {
-  CONFIG_FILE=$1
-  if [[ -z "$CONFIG_FILE" ]]; then
-    CONFIG_FILE=~/.ccloud/config
+  CCLOUD_CONFIG_FILE=$1
+  if [[ -z "$CCLOUD_CONFIG_FILE" ]]; then
+    CCLOUD_CONFIG_FILE=~/.ccloud/config
   fi
-  if [[ ! -f "$CONFIG_FILE" ]]; then
-    echo "File $CONFIG_FILE is not found.  Please create this properties file to connect to your Confluent Cloud cluster and then try again"
+  if [[ ! -f "$CCLOUD_CONFIG_FILE" ]]; then
+    echo "File $CCLOUD_CONFIG_FILE is not found.  Please create this properties file to connect to your Confluent Cloud cluster and then try again"
     echo "See https://docs.confluent.io/current/cloud/connect/auto-generate-configs.html for more information"
     return 1
   fi
 
-  echo -e "\nGenerating component configurations from $CONFIG_FILE"
+  echo -e "\nGenerating component configurations from $CCLOUD_CONFIG_FILE"
   echo -e "\n(If you want to run any of these components to talk to Confluent Cloud, these are the configurations to add to the properties file for each component)"
 
   # Set permissions
   PERM=600
   if ls --version 2>/dev/null | grep -q 'coreutils' ; then
     # GNU binutils
-    PERM=$(stat -c "%a" $CONFIG_FILE)
+    PERM=$(stat -c "%a" $CCLOUD_CONFIG_FILE)
   else
     # BSD
-    PERM=$(stat -f "%OLp" $CONFIG_FILE)
+    PERM=$(stat -f "%OLp" $CCLOUD_CONFIG_FILE)
   fi
 
   # Make destination
@@ -5644,28 +5641,28 @@ function ccloud::generate_configs() {
   # Glean parameters from the Confluent Cloud configuration file
 
   # Kafka cluster
-  BOOTSTRAP_SERVERS=$( grep "^bootstrap.server" $CONFIG_FILE | awk -F'=' '{print $2;}' )
+  BOOTSTRAP_SERVERS=$( grep "^bootstrap.server" $CCLOUD_CONFIG_FILE | awk -F'=' '{print $2;}' )
   BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS/\\/}
-  SASL_JAAS_CONFIG=$( grep "^sasl.jaas.config" $CONFIG_FILE | cut -d'=' -f2- )
+  SASL_JAAS_CONFIG=$( grep "^sasl.jaas.config" $CCLOUD_CONFIG_FILE | cut -d'=' -f2- )
   SASL_JAAS_CONFIG_PROPERTY_FORMAT=${SASL_JAAS_CONFIG/username\\=/username=}
   SASL_JAAS_CONFIG_PROPERTY_FORMAT=${SASL_JAAS_CONFIG_PROPERTY_FORMAT/password\\=/password=}
   CLOUD_KEY=$( echo $SASL_JAAS_CONFIG | awk '{print $3}' | awk -F"'" '$0=$2' )
   CLOUD_SECRET=$( echo $SASL_JAAS_CONFIG | awk '{print $4}' | awk -F"'" '$0=$2' )
 
   # Schema Registry
-  BASIC_AUTH_CREDENTIALS_SOURCE=$( grep "^basic.auth.credentials.source" $CONFIG_FILE | awk -F'=' '{print $2;}' )
-  SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO=$( grep "^basic.auth.user.info" $CONFIG_FILE | awk -F'=' '{print $2;}' )
-  SCHEMA_REGISTRY_URL=$( grep "^schema.registry.url" $CONFIG_FILE | awk -F'=' '{print $2;}' )
+  BASIC_AUTH_CREDENTIALS_SOURCE=$( grep "^basic.auth.credentials.source" $CCLOUD_CONFIG_FILE | awk -F'=' '{print $2;}' )
+  SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO=$( grep "^basic.auth.user.info" $CCLOUD_CONFIG_FILE | awk -F'=' '{print $2;}' )
+  SCHEMA_REGISTRY_URL=$( grep "^schema.registry.url" $CCLOUD_CONFIG_FILE | awk -F'=' '{print $2;}' )
 
   # ksqlDB
-  KSQLDB_ENDPOINT=$( grep "^ksql.endpoint" $CONFIG_FILE | awk -F'=' '{print $2;}' )
-  KSQLDB_BASIC_AUTH_USER_INFO=$( grep "^ksql.basic.auth.user.info" $CONFIG_FILE | awk -F'=' '{print $2;}' )
+  KSQLDB_ENDPOINT=$( grep "^ksql.endpoint" $CCLOUD_CONFIG_FILE | awk -F'=' '{print $2;}' )
+  KSQLDB_BASIC_AUTH_USER_INFO=$( grep "^ksql.basic.auth.user.info" $CCLOUD_CONFIG_FILE | awk -F'=' '{print $2;}' )
 
   # Build configuration file with Confluent Cloud connection parameters and
   # Confluent Monitoring Interceptors for Streams Monitoring in Confluent Control Center
   INTERCEPTORS_CONFIG_FILE=$DEST/interceptors-ccloud.config
   rm -f $INTERCEPTORS_CONFIG_FILE
-  echo "# Configuration derived from $CONFIG_FILE" > $INTERCEPTORS_CONFIG_FILE
+  echo "# Configuration derived from $CCLOUD_CONFIG_FILE" > $INTERCEPTORS_CONFIG_FILE
   while read -r line
   do
     # Skip lines that are commented out
@@ -5680,7 +5677,7 @@ function ccloud::generate_configs() {
       line=${line/\\/}
     fi
     echo $line >> $INTERCEPTORS_CONFIG_FILE
-  done < "$CONFIG_FILE"
+  done < "$CCLOUD_CONFIG_FILE"
   echo -e "\n# Confluent Monitoring Interceptor specific configuration" >> $INTERCEPTORS_CONFIG_FILE
   while read -r line
   do
@@ -5701,7 +5698,7 @@ function ccloud::generate_configs() {
           ${line:0:9} == 'bootstrap' ]]; then
       echo "confluent.monitoring.interceptor.$line" >> $INTERCEPTORS_CONFIG_FILE
     fi
-  done < "$CONFIG_FILE"
+  done < "$CCLOUD_CONFIG_FILE"
   chmod $PERM $INTERCEPTORS_CONFIG_FILE
 
   echo -e "\nConfluent Platform Components:"
@@ -5717,7 +5714,7 @@ function ccloud::generate_configs() {
         echo "kafkastore.$line" >> $SR_CONFIG_DELTA
       fi
     fi
-  done < "$CONFIG_FILE"
+  done < "$CCLOUD_CONFIG_FILE"
   chmod $PERM $SR_CONFIG_DELTA
 
   # Confluent Replicator (executable) for Confluent Cloud
@@ -5755,7 +5752,7 @@ function ccloud::generate_configs() {
     elif [[ ${line:0:15} == 'schema.registry' ]]; then
       echo "ksql.$line" >> $KSQLDB_SERVER_DELTA
     fi
-  done < $CONFIG_FILE
+  done < $CCLOUD_CONFIG_FILE
   chmod $PERM $KSQLDB_SERVER_DELTA
 
   # KSQL DataGen for Confluent Cloud
@@ -5773,7 +5770,7 @@ function ccloud::generate_configs() {
     elif [[ ${line:0:15} == 'schema.registry' ]]; then
       echo "ksql.$line" >> $KSQL_DATAGEN_DELTA
     fi
-  done < $CONFIG_FILE
+  done < $CCLOUD_CONFIG_FILE
   chmod $PERM $KSQL_DATAGEN_DELTA
 
   # Confluent Control Center runs locally, monitors Confluent Cloud, and uses Confluent Cloud cluster as the backstore
@@ -5792,7 +5789,7 @@ function ccloud::generate_configs() {
         echo "confluent.controlcenter.streams.$line" >> $C3_DELTA
       fi
     fi
-  done < "$CONFIG_FILE"
+  done < "$CCLOUD_CONFIG_FILE"
   # max.message.bytes is enforced to 8MB in Confluent Cloud
   echo "confluent.metrics.topic.max.message.bytes=8388608" >> $C3_DELTA
   echo -e "\n# Confluent Schema Registry configuration for Confluent Control Center" >> $C3_DELTA
@@ -5803,7 +5800,7 @@ function ccloud::generate_configs() {
     elif [[ ${line:0:15} == 'schema.registry' ]]; then
       echo "confluent.controlcenter.$line" >> $C3_DELTA
     fi
-  done < $CONFIG_FILE
+  done < $CCLOUD_CONFIG_FILE
   chmod $PERM $C3_DELTA
 
   # Confluent Metrics Reporter to Confluent Cloud
@@ -5819,7 +5816,7 @@ function ccloud::generate_configs() {
         echo "confluent.metrics.reporter.$line" >> $METRICS_REPORTER_DELTA
       fi
     fi
-  done < "$CONFIG_FILE"
+  done < "$CCLOUD_CONFIG_FILE"
   chmod $PERM $METRICS_REPORTER_DELTA
 
   # Confluent REST Proxy to Confluent Cloud
@@ -5834,7 +5831,7 @@ function ccloud::generate_configs() {
         echo "client.$line" >> $REST_PROXY_DELTA
       fi
     fi
-  done < "$CONFIG_FILE"
+  done < "$CCLOUD_CONFIG_FILE"
   echo -e "\n# Confluent Schema Registry configuration for REST Proxy" >> $REST_PROXY_DELTA
   while read -r line
   do
@@ -5843,7 +5840,7 @@ function ccloud::generate_configs() {
     elif [[ ${line:0:19} == 'schema.registry.url' ]]; then
       echo "$line" >> $REST_PROXY_DELTA
     fi
-  done < $CONFIG_FILE
+  done < $CCLOUD_CONFIG_FILE
   chmod $PERM $REST_PROXY_DELTA
 
   # Kafka Connect runs locally and connects to Confluent Cloud
@@ -5869,7 +5866,7 @@ EOF
         echo "$line" >> $CONNECT_DELTA
       fi
     fi
-  done < "$CONFIG_FILE"
+  done < "$CCLOUD_CONFIG_FILE"
 
   for prefix in "producer" "consumer" "producer.confluent.monitoring.interceptor" "consumer.confluent.monitoring.interceptor" ; do
 
@@ -5884,7 +5881,7 @@ EOF
         echo "${prefix}.$line" >> $CONNECT_DELTA
       fi
     fi
-  done < "$CONFIG_FILE"
+  done < "$CCLOUD_CONFIG_FILE"
 
   done
 
@@ -5915,7 +5912,7 @@ EOF
   AK_TOOLS_DELTA=$DEST/ak-tools-ccloud.delta
   echo "$AK_TOOLS_DELTA"
   rm -f $AK_TOOLS_DELTA
-  cp $CONFIG_FILE $AK_TOOLS_DELTA
+  cp $CCLOUD_CONFIG_FILE $AK_TOOLS_DELTA
   chmod $PERM $AK_TOOLS_DELTA
 
   echo -e "\nKafka Clients:"
@@ -6878,12 +6875,22 @@ playground_run_ccloud_command() {
   then
     flag_list="$flag_list --cluster-cloud $cluster_cloud"
     export CLUSTER_CLOUD=$cluster_cloud
+  else
+    if [ -z "$CLUSTER_CLOUD" ]
+    then
+      export CLUSTER_CLOUD="aws"
+    fi
   fi
 
   if [[ -n "$cluster_region" ]]
   then
     flag_list="$flag_list --cluster-region $cluster_region"
     export CLUSTER_REGION=$cluster_region
+  else
+    if [ -z "$CLUSTER_REGION" ]
+    then
+      export CLUSTER_REGION="eu-west-2"
+    fi
   fi
 
   if [[ -n "$cluster_environment" ]]
@@ -10309,10 +10316,6 @@ playground_run_ccloud_parse_requirements() {
     exit 1
   fi
 
-  # :command.default_assignments
-  [[ -n ${args['--cluster-cloud']:-} ]] || args['--cluster-cloud']="aws"
-  [[ -n ${args['--cluster-region']:-} ]] || args['--cluster-region']="eu-west-2"
-
   # :command.whitelist_filter
   if [[ ${args['--cluster-cloud']} ]] && [[ ! ${args['--cluster-cloud']} =~ ^(aws|gcp|azure)$ ]]; then
     printf "%s\n" "--cluster-cloud must be one of: aws, gcp, azure" >&2
@@ -10892,7 +10895,6 @@ playground_bootstrap_reproduction_model_parse_requirements() {
   fi
 
   # :command.default_assignments
-  [[ -n ${args['--cluster-region']:-} ]] || args['--cluster-region']="eu-west-2"
   [[ -n ${args['--producer']:-} ]] || args['--producer']="none"
   [[ -n ${args['--nb-producers']:-} ]] || args['--nb-producers']=""
 
