added help command

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -36,6 +36,9 @@ playground_usage() {
   printf "  playground --version | -v\n"
   echo
   # :command.usage_commands
+  printf "%s\n" "$(bold "== Commands ==")"
+  printf "  %s   Show help about a command\n" "$(green "help")                                   "
+  echo
   printf "%s\n" "$(bold "Run commands:")"
   printf "  %s   🕹️ Run any example, except for Confluent Cloud (in this case use run-ccloud command)\n" "$(green "run")                                    "
   printf "  %s   ⚡ Simply re-run last example you ran with <playground run> or <playground run-ccloud>\n" "$(green "re-run")                                 "
@@ -127,6 +130,43 @@ playground_usage() {
     echo
     printf "  %s\n" "$(magenta "--version, -v")"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_help_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground help - Show help about a command\n"
+    echo
+
+  else
+    printf "playground help - Show help about a command\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground help [COMMAND]\n"
+  printf "  playground help --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "COMMAND")"
+    printf "    🆘 Help command\n"
     echo
 
   fi
@@ -2713,7 +2753,7 @@ playground_topic_produce_usage() {
 
     # :flag.usage
     printf "  %s\n" "$(magenta "--validate")"
-    printf "    ☑️ Validate schema according to connect converter used\n"
+    printf "    ☑️ Validate schema according to connect sink converter used\n"
     echo
 
     # :flag.usage
@@ -8056,6 +8096,30 @@ validate_not_empty() {
 }
 
 # :command.command_functions
+# :command.function
+playground_help_command() {
+  # src/help_command.sh
+  command="${args[command]}"
+  long_usage=yes
+
+  if [[ -z "$command" ]]; then
+    # No command argument, show the global help
+    help_function=playground_usage
+  else
+    # Show the help for the requested command
+    help_function="playground_${command}_usage"
+  fi
+
+  # Call the help function if it exists
+  if [[ $(type -t "$help_function") ]]; then
+    "$help_function"
+  else
+    echo "No help available for this command"
+    exit 1
+  fi
+
+}
+
 # :command.function
 playground_get_connector_list_command() {
   # src/get_connector_list_command.sh
@@ -13685,6 +13749,13 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    help)
+      action="help"
+      shift
+      playground_help_parse_requirements "$@"
+      shift $#
+      ;;
+
     get-connector-list)
       action="get-connector-list"
       shift
@@ -13907,6 +13978,56 @@ parse_requirements() {
     echo "$filter_error" >&2
     exit 1
   fi
+
+}
+
+# :command.parse_requirements
+playground_help_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_help_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="help"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['command']+x} ]]; then
+
+          args['command']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
 
 }
 
@@ -20742,6 +20863,7 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "help") playground_help_command ;;
     "get-connector-list") playground_get_connector_list_command ;;
     "get-ccloud-connector-list") playground_get_ccloud_connector_list_command ;;
     "get-kafka-region-list") playground_get_kafka_region_list_command ;;
