Take a tcp dump (sniffing network)

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -55,6 +55,7 @@ playground_usage() {
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                             "
   [[ -n $long_usage ]] && printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "debug enable-remote-debugging")     "
   [[ -n $long_usage ]] && printf "  %s   🎯 Take a java thread dump\n" "$(green "debug thread-dump")                 "
+  [[ -n $long_usage ]] && printf "  %s   🕵️‍♂️ Take a tcp dump\n" "$(green "debug tcp-dump")                    "
   [[ -n $long_usage ]] && printf "  %s   🧬 Set log level for any package\n" "$(green "debug log-level")                   "
   echo
   printf "%s\n" "$(bold "Container commands:")"
@@ -1152,6 +1153,7 @@ playground_debug_usage() {
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "enable-remote-debugging")"
   printf "  %s   🎯 Take a java thread dump\n" "$(green "thread-dump")            "
+  printf "  %s   🕵️‍♂️ Take a tcp dump\n" "$(green "tcp-dump")               "
   printf "  %s   🧬 Set log level for any package\n" "$(green "log-level")              "
   echo
 
@@ -1253,6 +1255,59 @@ playground_debug_thread_dump_usage() {
     printf "%s\n" "$(bold "Examples")"
     printf "  playground debug thread-dump\n"
     printf "  playground debug thread-dump --container broker\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_debug_tcp_dump_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground debug tcp-dump - 🕵️‍♂️ Take a tcp dump\n"
+    echo
+
+  else
+    printf "playground debug tcp-dump - 🕵️‍♂️ Take a tcp dump\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground debug tcp-dump [OPTIONS]\n"
+  printf "  playground debug tcp-dump --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    🐳 Container name\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--port PORT (required)")"
+    printf "    Port on which tcp dump should be done\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--duration DURATION")"
+    printf "    Duration of the dump (default is 30 seconds).\n"
+    printf "    Default: 30\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground debug tcp-dump\n"
+    printf "  playground debug tcp-dump --container broker\n"
     echo
 
   fi
@@ -9226,6 +9281,77 @@ playground_debug_thread_dump_command() {
 }
 
 # :command.function
+playground_debug_tcp_dump_command() {
+  # src/debug_tcp_dump_command.sh
+  container="${args[--container]}"
+  port="${args[--port]}"
+  duration="${args[--duration]}"
+  filename="/tmp/tcp-dump-$container-$port-`date '+%Y-%m-%d-%H-%M-%S'`.pcap"
+
+  set +e
+  docker exec $container type tcpdump > /dev/null 2>&1
+  if [ $? != 0 ]
+  then
+      logwarn "tcpdump is not installed on container $container, attempting to install it"
+
+      DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+      dir1=$(echo ${DIR_CLI%/*})
+      root_folder=$(echo ${dir1%/*})
+      IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
+      source $root_folder/scripts/utils.sh
+      if [[ "$TAG" == *ubi8 ]] || version_gt $TAG_BASE "5.9.0"
+      then
+        export CONNECT_USER="appuser"
+        if [ `uname -m` = "arm64" ]
+        then
+          docker exec --privileged --user root $container bash -c "rpm -i --nosignature https://rpmfind.net/linux/centos/8-stream/AppStream/aarch64/os/Packages/tcpdump-4.9.3-2.el8.aarch64.rpm"
+        else
+          docker exec --privileged --user root $container bash -c "wget http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iproute-tc-4.18.0-15.el8.x86_64.rpm && rpm -i --nodeps --nosignature http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iproute-tc-4.18.0-15.el8.x86_64.rpm && curl http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/tcpdump-4.9.3-1.el8.x86_64.rpm -o tcpdump-4.9.3-1.el8.x86_64.rpm && rpm -Uvh tcpdump-4.9.3-1.el8.x86_64.rpm && yum -y install --disablerepo='Confluent*' bind-utils openssl unzip findutils net-tools nc jq which iptables libmnl && yum clean all && rm -rf /var/cache/yum"
+        fi
+      else
+        export CONNECT_USER="root"
+        docker exec --privileged --user root $container bash -c "apt-get update && echo bind-utils openssl unzip findutils net-tools nc jq which iptables iproute tree | xargs -n 1 apt-get install --force-yes -y && rm -rf /var/lib/apt/lists/*"
+      fi
+  fi
+  docker exec $container type tcpdump > /dev/null 2>&1
+  if [ $? != 0 ]
+  then
+      logerror "❌ tcpdump could not be installed"
+      exit 1
+  fi
+  set -e
+
+  set +e
+  docker exec --privileged --user root ${container} bash -c "killall tcpdump" > /dev/null 2>&1
+  set -e
+
+  log "🕵️‍♂️ Taking tcp dump on container ${container} and port ${port} for ${duration} seconds..."
+  docker exec -d --privileged --user root ${container} bash -c "tcpdump -w ${filename} port ${port}"
+  if [ $? -eq 0 ]
+  then
+      playground container get-ip-addresses
+      sleep $duration
+      set +e
+      docker exec --privileged --user root ${container} bash -c "killall tcpdump" > /dev/null 2>&1
+      set -e
+      log "🌶️ tcp dump is available at ${filename}"
+      docker cp ${container}:${filename} ${filename}
+      if [[ $(type -f wireshark 2>&1) =~ "not found" ]]
+      then
+          logwarn "🦈 wireshark is not installed, grab it at https://www.wireshark.org/"
+          exit 0
+      else
+          log "🦈 Opening ${filename} with wireshark"
+          wireshark ${filename}
+      fi
+
+  else
+      logerror "❌ Failed to take tcp dump"
+  fi
+
+}
+
+# :command.function
 playground_debug_log_level_get_command() {
   # src/debug_log_level_get_command.sh
   ret=$(get_connect_url_and_security)
@@ -13523,6 +13649,13 @@ playground_debug_parse_requirements() {
       shift $#
       ;;
 
+    tcp-dump)
+      action="tcp-dump"
+      shift
+      playground_debug_tcp_dump_parse_requirements "$@"
+      shift $#
+      ;;
+
     log-level)
       action="log-level"
       shift
@@ -13685,6 +13818,114 @@ playground_debug_thread_dump_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+}
+
+# :command.parse_requirements
+playground_debug_tcp_dump_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_debug_tcp_dump_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="debug tcp-dump"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --port)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--port PORT" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--port']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--port requires an argument: --port PORT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --duration)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--duration DURATION" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--duration']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--duration requires an argument: --duration DURATION" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--port']+x} ]]; then
+    printf "missing required flag: --port PORT\n" >&2
+    exit 1
+  fi
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+  [[ -n ${args['--duration']:-} ]] || args['--duration']="30"
 
 }
 
@@ -17072,6 +17313,7 @@ run() {
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
     "debug thread-dump") playground_debug_thread_dump_command ;;
+    "debug tcp-dump") playground_debug_tcp_dump_command ;;
     "debug log-level") playground_debug_log_level_command ;;
     "debug log-level get") playground_debug_log_level_get_command ;;
     "debug log-level set") playground_debug_log_level_set_command ;;
