predefined schemas !

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -74,7 +74,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "topic display-consumer-offsets")    "
   [[ -n $long_usage ]] && printf "  %s   🔬 Describe topic\n" "$(green "topic describe")                    "
   [[ -n $long_usage ]] && printf "  %s   📥 Consume topic from beginning\n" "$(green "topic consume")                     "
-  [[ -n $long_usage ]] && printf "  %s   Produce to a topic\n" "$(green "topic produce")                     "
+  [[ -n $long_usage ]] && printf "  %s   📤 Produce to a topic\n" "$(green "topic produce")                     "
   [[ -n $long_usage ]] && printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "topic set-schema-compatibility")    "
   [[ -n $long_usage ]] && printf "  %s   🧞 Easily identify the usage of different schema versions within a topic.\n" "$(green "topic display-schema-id-statistics")"
   echo
@@ -349,6 +349,43 @@ playground_get_any_file_with_fzf_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground get-any-file-with-fzf [CUR]\n"
   printf "  playground get-any-file-with-fzf --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "CUR")"
+    printf "    correspond to completion $cur\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_get_predefined_schemas_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground get-predefined-schemas - Return some completion for predefined schemas\n"
+    echo
+
+  else
+    printf "playground get-predefined-schemas - Return some completion for predefined schemas\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground get-predefined-schemas [CUR]\n"
+  printf "  playground get-predefined-schemas --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1784,7 +1821,7 @@ playground_topic_usage() {
   printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "display-consumer-offsets")    "
   printf "  %s   🔬 Describe topic\n" "$(green "describe")                    "
   printf "  %s   📥 Consume topic from beginning\n" "$(green "consume")                     "
-  printf "  %s   Produce to a topic\n" "$(green "produce")                     "
+  printf "  %s   📤 Produce to a topic\n" "$(green "produce")                     "
   printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "set-schema-compatibility")    "
   printf "  %s   🧞 Easily identify the usage of different schema versions within a topic.\n" "$(green "display-schema-id-statistics")"
   echo
@@ -1968,11 +2005,11 @@ playground_topic_consume_usage() {
 # :command.usage
 playground_topic_produce_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground topic produce - Produce to a topic\n"
+    printf "playground topic produce - 📤 Produce to a topic\n"
     echo
 
   else
-    printf "playground topic produce - Produce to a topic\n"
+    printf "playground topic produce - 📤 Produce to a topic\n"
     echo
 
   fi
@@ -1994,8 +2031,8 @@ playground_topic_produce_usage() {
 
     # :flag.usage
     printf "  %s\n" "$(magenta "--nb-messages NB-MESSAGES")"
-    printf "    Number of messages to produce\n"
-    printf "    Default: 1\n"
+    printf "    Number of messages to produce (default is 3)\n"
+    printf "    Default: 3\n"
     echo
 
     # :command.usage_fixed_flags
@@ -2008,7 +2045,7 @@ playground_topic_produce_usage() {
 
     # :argument.usage
     printf "  %s\n" "$(blue "SCHEMA")"
-    printf "    schema (reads from stdin if empty)\n"
+    printf "    You can either:\n    \n    * Set your own schema with stdin (see example section)\n    \n    * Or use completion to select predefined schemas\n    \n    * Or select your own schema file (if file is present in current folder)\n"
     printf "    Default: -\n"
     echo
 
@@ -3161,6 +3198,34 @@ function get_any_files_with_fzf() {
   fi
 
   res=$(find $dir2 -type f ! -path '*/\.*' | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🍺" --header="ctrl-c or esc to quit" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+}
+
+function get_predefined_schemas_with_fzf() {
+  DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+  dir1=$(echo ${DIR_CLI%/*})
+  dir2=$(echo ${dir1%/*})
+  predefined_folder=$dir2/scripts/cli/src/predefined-schemas
+
+  cur="$1"
+
+  fzf_version=$(get_fzf_version)
+  if version_gt $fzf_version "0.38"
+  then
+    fzf_option_wrap="--preview-window=70%,wrap"
+    fzf_option_pointer="--pointer=👉"
+    fzf_option_rounded="--border=rounded"
+  else
+    fzf_options=""
+    fzf_option_pointer=""
+    fzf_option_rounded=""
+  fi
+
+  if [[ $(type -f bat 2>&1) =~ "not found" ]]
+  then
+    res=$(find $predefined_folder $PWD \( -name "*.json" -o -name "*.avsc" -o -name "*.proto" -o -name "*.proto5" \) | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🍺" --header="ctrl-c or esc to quit" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" --delimiter / --with-nth "-2,-1" $fzf_option_wrap $fzf_option_pointer --preview 'cat {}');echo "$cur@$res"
+  else
+    res=$(find $predefined_folder $PWD \( -name "*.json" -o -name "*.avsc" -o -name "*.proto" -o -name "*.proto5" \) | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🍺" --header="ctrl-c or esc to quit" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" --delimiter / --with-nth "-2,-1" $fzf_option_wrap $fzf_option_pointer --preview 'bat --style=plain --color=always --line-range :500 {}');echo "$cur@$res"
+  fi
 }
 
 function filter_not_mdc_environment() {
@@ -7105,6 +7170,14 @@ playground_get_any_file_with_fzf_command() {
 }
 
 # :command.function
+playground_get_predefined_schemas_command() {
+  # src/get_predefined_schemas_command.sh
+  cur="${args[cur]}"
+
+  get_predefined_schemas_with_fzf "$cur"
+}
+
+# :command.function
 playground_bashly_reload_command() {
   # src/bashly_reload_command.sh
   DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
@@ -9555,16 +9628,28 @@ playground_topic_produce_command() {
 
   schema=${args[schema]}
 
+  tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
+  schema_file=$tmp_dir/value_schema
+
   if [ "$schema" = "-" ]
   then
       # stdin
       schema_content=$(cat "$schema")
+      echo "$schema_content" > $schema_file
   else
-      schema_content=$schema
+      if [[ $schema == @* ]]
+      then
+          # this is a schema file
+          argument_schema_file=$(echo "$schema" | cut -d "@" -f 2)
+          cp $argument_schema_file $schema_file
+      elif [ -f $schema ]
+      then
+          cp $schema $schema_file
+      else
+          schema_content=$schema
+          echo "$schema_content" > $schema_file
+      fi
   fi
-  tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
-  schema_file=$tmp_dir/value_schema
-  echo "$schema_content" > $schema_file
 
   environment=`get_environment_used`
 
@@ -9637,7 +9722,7 @@ playground_topic_produce_command() {
       log "🔮 schema was identified as avro"
       value_type=avro
   else
-      logerror "❌ Could not detect schema type for $schema_file"
+      logerror "❌ Could not recognize the type of schema in provided schema:"
       cat $schema_file
       exit 1
   fi
@@ -9661,8 +9746,8 @@ playground_topic_produce_command() {
       ;;
 
       avro)
-          docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools random /tmp/out.avro --schema-file /tmp/value_schema --count $nb_messages
-          docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools tojson /tmp/out.avro > $tmp_dir/out.json
+          docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools random /tmp/out.avro --schema-file /tmp/value_schema --count $nb_messages > /dev/null 2>&1
+          docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools tojson /tmp/out.avro > $tmp_dir/out.json 2>/dev/null
       ;;
       avro-with-key)
 
@@ -10698,6 +10783,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    get-predefined-schemas)
+      action="get-predefined-schemas"
+      shift
+      playground_get_predefined_schemas_parse_requirements "$@"
+      shift $#
+      ;;
+
     bashly-reload)
       action="bashly-reload"
       shift
@@ -11217,6 +11309,56 @@ playground_get_any_file_with_fzf_parse_requirements() {
 
   # :command.command_filter
   action="get-any-file-with-fzf"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['cur']+x} ]]; then
+
+          args['cur']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_get_predefined_schemas_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_get_predefined_schemas_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="get-predefined-schemas"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -14534,7 +14676,7 @@ playground_topic_produce_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['schema']:-} ]] || args['schema']="-"
-  [[ -n ${args['--nb-messages']:-} ]] || args['--nb-messages']="1"
+  [[ -n ${args['--nb-messages']:-} ]] || args['--nb-messages']="3"
 
   # :command.user_filter
   filter_error=$(filter_schema_registry_running)
@@ -15986,6 +16128,7 @@ run() {
     "get-examples-list-with-fzf") playground_get_examples_list_with_fzf_command ;;
     "get-zip-or-jar-with-fzf") playground_get_zip_or_jar_with_fzf_command ;;
     "get-any-file-with-fzf") playground_get_any_file_with_fzf_command ;;
+    "get-predefined-schemas") playground_get_predefined_schemas_command ;;
     "bashly-reload") playground_bashly_reload_command ;;
     "run") playground_run_command ;;
     "re-run") playground_re_run_command ;;
