improve consume topic command

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -71,10 +71,9 @@ playground_usage() {
   printf "%s\n" "$(bold "Topic commands:")"
   printf "  %s   🗳 Topic commands\n" "$(green "topic")                         "
   [[ -n $long_usage ]] && printf "  %s   💯 Get number of records in a topic\n" "$(green "topic get-number-records")      "
-  [[ -n $long_usage ]] && printf "  %s   📬 Display content of connect offsets topic\n" "$(green "topic display-connect-offsets") "
   [[ -n $long_usage ]] && printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "topic display-consumer-offsets")"
   [[ -n $long_usage ]] && printf "  %s   🔬 Describe topic\n" "$(green "topic describe")                "
-  [[ -n $long_usage ]] && printf "  %s   📥 Consume topic(s) from running example\n" "$(green "topic consume")                 "
+  [[ -n $long_usage ]] && printf "  %s   📥 Consume topic from beginning\n" "$(green "topic consume")                 "
   echo
   printf "%s\n" "$(bold "Connector commands:")"
   printf "  %s   🔗 Connector commands\n" "$(green "connector")                     "
@@ -1732,10 +1731,9 @@ playground_topic_usage() {
   # :command.usage_commands
   printf "%s\n" "$(bold "Topic commands:")"
   printf "  %s   💯 Get number of records in a topic\n" "$(green "get-number-records")      "
-  printf "  %s   📬 Display content of connect offsets topic\n" "$(green "display-connect-offsets") "
   printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "display-consumer-offsets")"
   printf "  %s   🔬 Describe topic\n" "$(green "describe")                "
-  printf "  %s   📥 Consume topic(s) from running example\n" "$(green "consume")                 "
+  printf "  %s   📥 Consume topic from beginning\n" "$(green "consume")                 "
   echo
 
   # :command.long_usage
@@ -1786,35 +1784,6 @@ playground_topic_get_number_records_usage() {
     printf "%s\n" "$(bold "Examples")"
     printf "  playground get-number-records --topic a-topic\n"
     printf "  playground get-number-records -t a-topic\n"
-    echo
-
-  fi
-}
-
-# :command.usage
-playground_topic_display_connect_offsets_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "playground topic display-connect-offsets - 📬 Display content of connect offsets topic\n"
-    echo
-
-  else
-    printf "playground topic display-connect-offsets - 📬 Display content of connect offsets topic\n"
-    echo
-
-  fi
-
-  printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground topic display-connect-offsets\n"
-  printf "  playground topic display-connect-offsets --help | -h\n"
-  echo
-
-  # :command.long_usage
-  if [[ -n $long_usage ]]; then
-    printf "%s\n" "$(bold "== Options ==")"
-
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
     echo
 
   fi
@@ -1887,23 +1856,29 @@ playground_topic_describe_usage() {
 # :command.usage
 playground_topic_consume_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground topic consume - 📥 Consume topic(s) from running example\n"
+    printf "playground topic consume - 📥 Consume topic from beginning\n"
     echo
 
   else
-    printf "playground topic consume - 📥 Consume topic(s) from running example\n"
+    printf "playground topic consume - 📥 Consume topic from beginning\n"
     echo
 
   fi
 
   printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground topic consume\n"
+  printf "  playground topic consume [OPTIONS]\n"
   printf "  playground topic consume --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--topic, -t TOPIC (required)")"
+    printf "    🗳 Topic name\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -8378,18 +8353,6 @@ playground_topic_get_number_records_command() {
 }
 
 # :command.function
-playground_topic_display_connect_offsets_command() {
-  # src/topic_display_connect_offsets_command.sh
-  ret=$(get_security_broker "--consumer.config")
-
-  container=$(echo "$ret" | cut -d "@" -f 1)
-  security=$(echo "$ret" | cut -d "@" -f 2)
-
-  log "Display content of connect offsets topic, press crtl-c to stop..."
-  docker exec $container kafka-console-consumer -bootstrap-server broker:9092 --topic connect-offsets --from-beginning --property print.key=true --property print.timestamp=true $security
-}
-
-# :command.function
 playground_topic_display_consumer_offsets_command() {
   # src/topic_display_consumer_offsets_command.sh
   ret=$(get_security_broker "--consumer.config")
@@ -8418,20 +8381,7 @@ playground_topic_describe_command() {
 # :command.function
 playground_topic_consume_command() {
   # src/topic_consume_command.sh
-  if [ ! -f /tmp/playground-run ]
-  then
-    logerror "File containing re-run command /tmp/playground-run does not exist!"
-    logerror "Make sure to use <playground run> command !"
-    exit 1
-  fi
-
-  test_file=$(cat /tmp/playground-run |tr '\t' ' ' |cut -d' ' -f4)
-  if [ ! -f $test_file ]
-  then
-    logerror "Could not find test file in /tmp/playground-run"
-    cat /tmp/playground-run
-    exit 1
-  fi
+  topic="${args[--topic]}"
 
   environment=`get_environment_used`
 
@@ -8440,6 +8390,61 @@ playground_topic_consume_command() {
     logerror "File containing restart command /tmp/playground-command does not exist!"
     exit 1
 
+  fi
+
+  ret=$(get_sr_url_and_security)
+
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
+
+  key_type=""
+  version=$(curl $sr_security -s "${sr_url}/subjects/${topic}-key/versions/1" | jq -r .version)
+  if [ "$version" != "null" ]
+  then
+    schema_type=$(curl $sr_security -s "${sr_url}/subjects/${topic}-key/versions/1"  | jq -r .schemaType)
+    case "${schema_type}" in
+      JSON)
+        key_type="json-schema"
+      ;;
+      PROTOBUF)
+        key_type="protobuf"
+      ;;
+      null)
+        key_type="avro"
+      ;;
+    esac
+  fi
+
+  if [ "$key_type" != "" ]
+  then
+    log "🔮🔰 topic is using $key_type for key"
+  else
+    log "🔮🙅 topic is not using any schema for key"
+  fi
+
+  value_type=""
+  version=$(curl $sr_security -s "${sr_url}/subjects/${topic}-value/versions/1" | jq -r .version)
+  if [ "$version" != "null" ]
+  then
+    schema_type=$(curl $sr_security -s "${sr_url}/subjects/${topic}-value/versions/1"  | jq -r .schemaType)
+    case "${schema_type}" in
+      JSON)
+        value_type="json-schema"
+      ;;
+      PROTOBUF)
+        value_type="protobuf"
+      ;;
+      null)
+        value_type="avro"
+      ;;
+    esac
+  fi
+
+  if [ "$value_type" != "" ]
+  then
+    log "🔮🔰 topic is using $value_type for value"
+  else
+    log "🔮🙅 topic is not using any schema for value"
   fi
 
   container="connect"
@@ -8462,91 +8467,49 @@ playground_topic_consume_command() {
       docker exec -i client kinit -k -t /var/lib/secret/kafka-connect.key connect
   fi
 
+  log "✨ Display content of topic $topic, press crtl-c to stop..."
+  type=""
   tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
-  awk -F'--topic ' '{print $2}' $test_file > $tmp_dir/tmp
-  sed '/^$/d' $tmp_dir/tmp > $tmp_dir/tmp2
-  topic_name=$(head -1 $tmp_dir/tmp2 | cut -d " " -f1)
+  fifo_path="$tmp_dir/kafka_output_fifo"
+  mkfifo "$fifo_path"
+  case "${value_type}" in
+    avro|protobuf|json-schema)
+        if [ "$key_type" == "avro" ] || [ "$key_type" == "protobuf" ] || [ "$key_type" == "json-schema" ]
+        then
+            docker exec $container kafka-$value_type-console-consumer -bootstrap-server broker:9092 --property schema.registry.url=$sr_url --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" $security --from-beginning > "$fifo_path" &
+        else
+            docker exec $container kafka-$value_type-console-consumer --bootstrap-server broker:9092 --property schema.registry.url=$sr_url --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" --property key.deserializer=org.apache.kafka.common.serialization.StringDeserializer $security --from-beginning > "$fifo_path" &
+        fi
+        ;;
+    *)
+        docker exec $container kafka-console-consumer --bootstrap-server broker:9092 --topic $topic --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" $security --from-beginning > "$fifo_path" &
+    ;;
+  esac
 
-  if [ "$topic_name" != "" ]
-  then
-    key_converter=$(grep "\"key.converter\"" $test_file | cut -d '"' -f 4)
-    if [ "$key_converter" == "" ]
-    then
-      log "🔮 connector is using default key.converter, i.e org.apache.kafka.connect.storage.StringConverter"
-      key_converter="io.confluent.connect.avro.AvroConverter"
-    else
-      log "🔮 connector is using key.converter $key_converter"
-    fi
-
-    value_converter=$(grep "\"value.converter\"" $test_file | cut -d '"' -f 4)
-    if [ "$value_converter" == "" ]
-    then
-      log "🔮 connector is using default value.converter, i.e io.confluent.connect.avro.AvroConverter"
-      value_converter="io.confluent.connect.avro.AvroConverter"
-    else
-      log "🔮 connector is using value.converter $value_converter"
-    fi
-    log "✨ Display content of topic $topic_name, press crtl-c to stop..."
-    type=""
-    case "${value_converter}" in
-      io.confluent.connect.json.JsonSchemaConverter)
-          type="json-schema"
-      ;;
-      io.confluent.connect.protobuf.ProtobufConverter)
-          type="protobuf"
-      ;;
-      io.confluent.connect.avro.AvroConverter)
-          type="avro"
-          ;;
-      *)
-      ;;
-    esac
-
-    fifo_path="$tmp_dir/kafka_output_fifo"
-    mkfifo "$fifo_path"
-    case "${type}" in
-      avro|protobuf|json-schema)
-          if [ "$key_converter" == "io.confluent.connect.avro.AvroConverter" ]
-          then
-              docker exec $container kafka-$type-console-consumer -bootstrap-server broker:9092 --property schema.registry.url=$sr_url --topic $topic_name --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" $security --from-beginning > "$fifo_path" &
-          else
-              docker exec $container kafka-$type-console-consumer --bootstrap-server broker:9092 --property schema.registry.url=$sr_url --topic $topic_name --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" --property key.deserializer=org.apache.kafka.common.serialization.StringDeserializer $security --from-beginning > "$fifo_path" &
-          fi
-          ;;
-      *)
-          docker exec $container kafka-console-consumer --bootstrap-server broker:9092 --topic $topic_name --property print.partition=true --property print.offset=true --property print.headers=true --property print.timestamp=true --property print.key=true --property key.separator="|" $security --from-beginning > "$fifo_path" &
-      ;;
-    esac
-
-    # Detect the platform (macOS or Linux) and set the date command accordingly
-    if [[ "$(uname)" == "Darwin" ]]; then
-      # macOS
-      date_command="date -r "
-    else
-      # Linux
-      date_command="date -d @"
-    fi
-
-    # Loop through each line in the named pipe
-    while read -r line; do
-      # Extract the timestamp from the line
-      timestamp_ms=$(echo "$line" | cut -d ":" -f 2 | cut -d "|" -f 1)
-
-      # Convert milliseconds to seconds
-      timestamp_sec=$((timestamp_ms / 1000))
-      milliseconds=$((timestamp_ms % 1000))
-
-      readable_date="$(${date_command}${timestamp_sec} "+%Y-%m-%d %H:%M:%S.${milliseconds}")"
-
-      line_with_date=$(echo "$line" | sed -E "s/CreateTime:[0-9]{13}/CreateTime: ${readable_date}/")
-
-      echo "$line_with_date"
-    done < "$fifo_path"
+  # Detect the platform (macOS or Linux) and set the date command accordingly
+  if [[ "$(uname)" == "Darwin" ]]; then
+    # macOS
+    date_command="date -r "
   else
-
-    logwarn "Could not find topic name !"
-    exit 1
+    # Linux
+    date_command="date -d @"
   fi
+
+  # Loop through each line in the named pipe
+  while read -r line; do
+    # Extract the timestamp from the line
+    timestamp_ms=$(echo "$line" | cut -d ":" -f 2 | cut -d "|" -f 1)
+
+    # Convert milliseconds to seconds
+    timestamp_sec=$((timestamp_ms / 1000))
+    milliseconds=$((timestamp_ms % 1000))
+
+    readable_date="$(${date_command}${timestamp_sec} "+%Y-%m-%d %H:%M:%S.${milliseconds}")"
+
+    line_with_date=$(echo "$line" | sed -E "s/CreateTime:[0-9]{13}/CreateTime: ${readable_date}/")
+
+    echo "$line_with_date"
+  done < "$fifo_path"
 }
 
 # :command.function
@@ -12201,13 +12164,6 @@ playground_topic_parse_requirements() {
       shift $#
       ;;
 
-    display-connect-offsets)
-      action="display-connect-offsets"
-      shift
-      playground_topic_display_connect_offsets_parse_requirements "$@"
-      shift $#
-      ;;
-
     display-consumer-offsets)
       action="display-consumer-offsets"
       shift
@@ -12333,50 +12289,6 @@ playground_topic_get_number_records_parse_requirements() {
     printf "missing required flag: --topic, -t TOPIC\n" >&2
     exit 1
   fi
-
-}
-
-# :command.parse_requirements
-playground_topic_display_connect_offsets_parse_requirements() {
-  # :command.fixed_flags_filter
-  while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
-      --help | -h)
-        long_usage=yes
-        playground_topic_display_connect_offsets_usage
-        exit
-        ;;
-
-      *)
-        break
-        ;;
-
-    esac
-  done
-
-  # :command.command_filter
-  action="topic display-connect-offsets"
-
-  # :command.parse_requirements_while
-  while [[ $# -gt 0 ]]; do
-    key="$1"
-    case "$key" in
-
-      -?*)
-        printf "invalid option: %s\n" "$key" >&2
-        exit 1
-        ;;
-
-      *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
-
-        ;;
-
-    esac
-  done
 
 }
 
@@ -12513,6 +12425,20 @@ playground_topic_consume_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --topic | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--topic']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--topic requires an argument: --topic, -t TOPIC" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -12529,6 +12455,12 @@ playground_topic_consume_parse_requirements() {
 
     esac
   done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--topic']+x} ]]; then
+    printf "missing required flag: --topic, -t TOPIC\n" >&2
+    exit 1
+  fi
 
 }
 
@@ -13236,7 +13168,6 @@ run() {
     "container kill") playground_container_kill_command ;;
     "topic") playground_topic_command ;;
     "topic get-number-records") playground_topic_get_number_records_command ;;
-    "topic display-connect-offsets") playground_topic_display_connect_offsets_command ;;
     "topic display-consumer-offsets") playground_topic_display_consumer_offsets_command ;;
     "topic describe") playground_topic_describe_command ;;
     "topic consume") playground_topic_consume_command ;;
