wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -3203,6 +3203,11 @@ playground_connector_config_usage() {
     printf "    🔗 Connector name\n    \n    🎓 Tip: If not specified, the command will apply to all connectors\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--open, -o")"
+    printf "    🔖 Save output to a file and open with text editor set with config.ini\n    (default is code)\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -11914,6 +11919,8 @@ playground_connector_show_lag_command() {
 # :command.function
 playground_connector_config_command() {
   # src/connector_config_command.sh
+  open="${args[--open]}"
+
   ret=$(get_connect_url_and_security)
 
   connect_url=$(echo "$ret" | cut -d "@" -f 1)
@@ -11935,10 +11942,10 @@ playground_connector_config_command() {
   items=($connector)
   for connector in ${items[@]}
   do
-      log "⏸️ Config connector $connector"
       json_config=$(curl $security -s -X GET -H "Content-Type: application/json" "$connect_url/connectors/$connector/config")
       connector_class=$(echo "$json_config" | jq -r '."connector.class"')
 
+      log "⚙️ Config for connector $connector ($connector_class)"
       set +e
       curl_output=$(curl $security -s -X PUT \
           -H "Content-Type: application/json" \
@@ -11955,7 +11962,6 @@ playground_connector_config_command() {
               logerror "Command failed with error code $error_code"
               logerror "$message"
           else
-
               if ! echo "$curl_output" | jq -e .  > /dev/null 2>&1
               then
                   set +e
@@ -11979,9 +11985,11 @@ playground_connector_config_command() {
                   exit 1
               fi
 
-              header="| Parameter  | Group | Default Value | Required | Importance | Description |"
-              divider=$(printf "| --%s-- | --%s-- | --%s-- | --%s-- | --%s-- | --%s-- |\n" $(printf '%.0s-' {1..9}))
-
+              if [[ -n "$open" ]]
+              then
+                  filename="/tmp/config-$connector.txt"
+              fi
+              current_group=""
               rows=()
               for row in $(echo "$curl_output" | jq -r '.configs[] | @base64'); do
                   _jq() {
@@ -11993,22 +12001,76 @@ playground_connector_config_command() {
                       continue
                   fi
 
+                  if [ "$group" != "$current_group" ]
+                  then
+                      if [[ -n "$open" ]]
+                      then
+                          echo -e "==========================" > $filename
+                          echo -e "$group"                     >> $filename
+                          echo -e "==========================" >> $filename
+                      else
+                          echo -e "=========================="
+                          echo -e "$group"
+                          echo -e "=========================="
+                      fi
+                      current_group=$group
+                  fi
+
                   param=$(_jq '.definition.name')
                   default=$(_jq '.definition.default_value')
+                  type=$(_jq '.definition.type')
                   required=$(_jq '.definition.required')
                   importance=$(_jq '.definition.importance')
                   description=$(_jq '.definition.documentation')
 
-                  rows+=("| $param | $group | $default | $required | $importance | $description |\n")
+                  if [[ -n "$open" ]]
+                  then
+                      echo -e "🔘 $param" >> $filename
+                      echo -e "" >> $filename
+                      echo -e "$description" >> $filename
+                      echo -e "" >> $filename
+                      echo -e "\t - Type: $type" >> $filename
+                      echo -e "\t - Default: $default" >> $filename
+                      echo -e "\t - Importance: $importance" >> $filename
+                      echo -e "\t - Required: $required" >> $filename
+                      echo -e "" >> $filename
+                  else
+                      echo -e "🔘 $param"
+                      echo -e ""
+                      echo -e "$description"
+                      echo -e ""
+                      echo -e "\t - Type: $type"
+                      echo -e "\t - Default: $default"
+                      echo -e "\t - Importance: $importance"
+                      echo -e "\t - Required: $required"
+                      echo -e ""
+                  fi
               done
-
-              echo -e "$header\n$divider\n${rows[*]}$divider"
           fi
       else
           logerror "❌ curl request failed with error code $ret!"
           exit 1
       fi
 
+      if [[ -n "$open" ]]
+      then
+          filename="/tmp/config-$connector.txt"
+          if config_has_key "editor"
+          then
+              editor=$(config_get "editor")
+          log "📖 Opening ${filename} using configured editor $editor"
+          $editor $filename
+          else
+              if [[ $(type code 2>&1) =~ "not found" ]]
+              then
+              logerror "Could not determine an editor to use as default code is not found - you can change editor by updating config.ini"
+              exit 1
+              else
+              log "📖 Opening ${filename} with code (default) - you can change editor by updating config.ini"
+              code $filename
+              fi
+          fi
+      fi
   done
 
 }
@@ -18231,6 +18293,14 @@ playground_connector_config_parse_requirements() {
           printf "%s\n" "--connector requires an argument: --connector, -c CONNECTOR" >&2
           exit 1
         fi
+        ;;
+
+      # :flag.case
+      --open | -o)
+
+        # :flag.case_no_arg
+        args['--open']=1
+        shift
         ;;
 
       -?*)
