schema get

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -56,8 +56,11 @@ playground_usage() {
   printf "%s\n" "$(bold "Kafka commands:")"
   printf "  %s   🐋 Get docker-compose\n" "$(green "get-docker-compose")                     "
   printf "  %s   📝 Get properties file from a container\n" "$(green "get-properties")                         "
-  printf "  %s   🔰 Get all schemas versions for all subjects\n" "$(green "get-all-schemas")                        "
   printf "  %s   🔢 Get JMX metrics from a component\n" "$(green "get-jmx-metrics")                        "
+  echo
+  printf "%s\n" "$(bold "Schema commands:")"
+  printf "  %s   🔰 Schema commands\n" "$(green "schema")                                 "
+  [[ -n $long_usage ]] && printf "  %s   🔰 Get all schemas versions for all subjects\n" "$(green "schema get")                             "
   echo
   printf "%s\n" "$(bold "Debug commands:")"
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                                  "
@@ -1389,20 +1392,53 @@ playground_get_properties_usage() {
 }
 
 # :command.usage
-playground_get_all_schemas_usage() {
+playground_schema_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground get-all-schemas - 🔰 Get all schemas versions for all subjects\n"
+    printf "playground schema - 🔰 Schema commands\n"
     echo
 
   else
-    printf "playground get-all-schemas - 🔰 Get all schemas versions for all subjects\n"
+    printf "playground schema - 🔰 Schema commands\n"
     echo
 
   fi
 
   printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground get-all-schemas [OPTIONS]\n"
-  printf "  playground get-all-schemas --help | -h\n"
+  printf "  playground schema COMMAND\n"
+  printf "  playground schema [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "$(bold "Kafka commands:")"
+  printf "  %s   🔰 Get all schemas versions for all subjects\n" "$(green "get")"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_schema_get_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground schema get - 🔰 Get all schemas versions for all subjects\n"
+    echo
+
+  else
+    printf "playground schema get - 🔰 Get all schemas versions for all subjects\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground schema get [OPTIONS]\n"
+  printf "  playground schema get --help | -h\n"
   echo
 
   # :command.long_usage
@@ -1411,8 +1447,8 @@ playground_get_all_schemas_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "$(magenta "--open, -o")"
-    printf "    🔖 Save output to a file and open with text editor set with config.ini\n    (default is code)\n"
+    printf "  %s\n" "$(magenta "--subject SUBJECT")"
+    printf "    📛 Subject\n"
     echo
 
     # :command.usage_fixed_flags
@@ -1422,7 +1458,8 @@ playground_get_all_schemas_usage() {
 
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
-    printf "  playground get-all-schemas\n"
+    printf "  playground schema get\n"
+    printf "  playground schema get --subject <SUBJECT>\n"
     echo
 
   fi
@@ -5976,9 +6013,12 @@ function create_or_get_oracle_image() {
     if [ $? -eq 0 ]
     then
         log "Downloading <s3://kafka-docker-playground/3rdparty/$ORACLE_IMAGE.tar> from S3 bucket"
+        pwd
+        df
         aws s3 cp --only-show-errors "s3://kafka-docker-playground/3rdparty/$ORACLE_IMAGE.tar" .
         if [ $? -eq 0 ]
         then
+          df
           log "📄 <s3://kafka-docker-playground/3rdparty/$ORACLE_IMAGE.tar> was downloaded from S3 bucket"
           docker load -i $ORACLE_IMAGE.tar
           if [ $? -eq 0 ]
@@ -10493,79 +10533,48 @@ playground_get_properties_command() {
 }
 
 # :command.function
-playground_get_all_schemas_command() {
-  # src/get_all_schemas_command.sh
-  open="${args[--open]}"
+playground_schema_get_command() {
+  # src/schema_get_command.sh
+  subject="${args[--subject]}"
 
-  function get_all_schemas() {
-    ret=$(get_sr_url_and_security)
+  ret=$(get_sr_url_and_security)
 
-    sr_url=$(echo "$ret" | cut -d "@" -f 1)
-    sr_security=$(echo "$ret" | cut -d "@" -f 2)
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
 
-    # Get a list of all subjects in the schema registry
-    subjects=$(curl $sr_security -s "${sr_url}/subjects")
+  if [[ ! -n "$subject" ]]
+  then
+      log "✨ --subject flag was not provided, applying command to all subjects"
+      subject=$(playground get-subject-list)
+      if [ "$subject" == "" ]
+      then
+          logerror "❌ No subject found !"
+          exit 1
+      fi
+  fi
 
-    if [[ -n "$open" ]]
-    then
-      echo "Displaying all subjects 🔰 and versions 💯"
-    else
-      log "Displaying all subjects 🔰 and versions 💯"
-    fi
-    for subject in $(echo "${subjects}" | jq -r '.[]'); do
+  items=($subject)
+  for subject in ${items[@]}
+  do
       versions=$(curl $sr_security -s "${sr_url}/subjects/${subject}/versions")
 
       for version in $(echo "${versions}" | jq -r '.[]')
       do
-        schema_type=$(curl $sr_security -s "${sr_url}/subjects/${subject}/versions/${version}"  | jq -r .schemaType)
-        case "${schema_type}" in
+          schema_type=$(curl $sr_security -s "${sr_url}/subjects/${subject}/versions/${version}"  | jq -r .schemaType)
+          case "${schema_type}" in
           JSON|null)
-            schema=$(curl $sr_security -s "${sr_url}/subjects/${subject}/versions/${version}/schema" | jq .)
+              schema=$(curl $sr_security -s "${sr_url}/subjects/${subject}/versions/${version}/schema" | jq .)
           ;;
           PROTOBUF)
-            schema=$(curl $sr_security -s "${sr_url}/subjects/${subject}/versions/${version}/schema")
+              schema=$(curl $sr_security -s "${sr_url}/subjects/${subject}/versions/${version}/schema")
           ;;
-        esac
+          esac
 
-        if [[ -n "$open" ]]
-        then
-          echo "🔰 ${subject} 💯 ${version}"
-        else
-          log "🔰 ${subject} 💯 ${version}"
-        fi
-        echo "${schema}"
+          log "🔰 subject ${subject} 💯 version ${version}"
+
+          echo "${schema}"
       done
-    done
-  }
-
-  if [[ -n "$open" ]]
-  then
-    filename="/tmp/get-all-schemas-`date '+%Y-%m-%d-%H-%M-%S'`.log"
-    get_all_schemas > "$filename" 2>&1
-    if [ $? -eq 0 ]
-    then
-      if config_has_key "editor"
-      then
-        editor=$(config_get "editor")
-        log "📖 Opening ${filename} using configured editor $editor"
-        $editor $filename
-      else
-        if [[ $(type code 2>&1) =~ "not found" ]]
-        then
-          logerror "Could not determine an editor to use as default code is not found - you can change editor by updating config.ini"
-          exit 1
-        else
-          log "📖 Opening ${filename} with code (default) - you can change editor by updating config.ini"
-          code $filename
-        fi
-      fi
-    else
-      logerror "Failed to get schemas"
-    fi
-  else
-
-    get_all_schemas
-  fi
+  done
 }
 
 # :command.function
@@ -14421,10 +14430,10 @@ parse_requirements() {
       shift $#
       ;;
 
-    get-all-schemas)
-      action="get-all-schemas"
+    schema)
+      action="schema"
       shift
-      playground_get_all_schemas_parse_requirements "$@"
+      playground_schema_parse_requirements "$@"
       shift $#
       ;;
 
@@ -16891,13 +16900,13 @@ playground_get_properties_parse_requirements() {
 }
 
 # :command.parse_requirements
-playground_get_all_schemas_parse_requirements() {
+playground_schema_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        playground_get_all_schemas_usage
+        playground_schema_usage
         exit
         ;;
 
@@ -16909,18 +16918,92 @@ playground_get_all_schemas_parse_requirements() {
   done
 
   # :command.command_filter
-  action="get-all-schemas"
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    get)
+      action="get"
+      shift
+      playground_schema_get_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      playground_schema_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_schema_get_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_schema_get_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="schema get"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       # :flag.case
-      --open | -o)
+      --subject)
 
-        # :flag.case_no_arg
-        args['--open']=1
-        shift
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--subject']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--subject requires an argument: --subject SUBJECT" >&2
+          exit 1
+        fi
         ;;
 
       -?*)
@@ -21723,7 +21806,8 @@ run() {
     "repro bootstrap") playground_repro_bootstrap_command ;;
     "get-docker-compose") playground_get_docker_compose_command ;;
     "get-properties") playground_get_properties_command ;;
-    "get-all-schemas") playground_get_all_schemas_command ;;
+    "schema") playground_schema_command ;;
+    "schema get") playground_schema_get_command ;;
     "debug") playground_debug_command ;;
     "debug install-vscode-extension") playground_debug_install_vscode_extension_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
