fix

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -17406,21 +17406,21 @@ playground_fully_managed_connector_create_or_update_command() {
       set -e
       if [ $ret -eq 0 ]
       then
-        if echo "$curl_output" | jq 'if .error then .error | has("error_code") else has("error_code") end' 2> /dev/null | grep -q true
+          if echo "$curl_output" | jq 'if .error then .error | has("error_code") else has("error_code") end' 2> /dev/null | grep -q true
 
-        then
-            if echo "$curl_output" | jq '.error | has("error_code")' 2> /dev/null | grep -q true
+          then
+              if echo "$curl_output" | jq '.error | has("error_code")' 2> /dev/null | grep -q true
 
-            then
-                code=$(echo "$curl_output" | jq -r .error.code)
-                message=$(echo "$curl_output" | jq -r .error.message)
-            else
-                code=$(echo "$curl_output" | jq -r .error_code)
-                message=$(echo "$curl_output" | jq -r .message)
-            fi
-            logerror "Command failed with error code $code"
-            logerror "$message"
-            exit 1
+              then
+                  code=$(echo "$curl_output" | jq -r .error.code)
+                  message=$(echo "$curl_output" | jq -r .error.message)
+              else
+                  code=$(echo "$curl_output" | jq -r .error_code)
+                  message=$(echo "$curl_output" | jq -r .message)
+              fi
+              logerror "Command failed with error code $code"
+              logerror "$message"
+              exit 1
           else
               if ! echo "$curl_output" | jq -e .  > /dev/null 2>&1
               then
@@ -17502,11 +17502,18 @@ playground_fully_managed_connector_create_or_update_command() {
   set -e
   if [ $ret -eq 0 ]
   then
-      if echo "$curl_output" | jq '.error | has("error_code")' 2> /dev/null | grep -q true
+      if echo "$curl_output" | jq 'if .error then .error | has("error_code") else has("error_code") end' 2> /dev/null | grep -q true
 
       then
-          code=$(echo "$curl_output" | jq -r .error.code)
-          message=$(echo "$curl_output" | jq -r .error.message)
+          if echo "$curl_output" | jq '.error | has("error_code")' 2> /dev/null | grep -q true
+
+          then
+              code=$(echo "$curl_output" | jq -r .error.code)
+              message=$(echo "$curl_output" | jq -r .error.message)
+          else
+              code=$(echo "$curl_output" | jq -r .error_code)
+              message=$(echo "$curl_output" | jq -r .message)
+          fi
           logerror "Command failed with error code $code"
           logerror "$message"
           exit 1
