--cluster-environment completion

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -410,6 +410,43 @@ playground_get_connector_plugin_usage() {
 }
 
 # :command.usage
+playground_get_ccloud_environment_list_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground get-ccloud-environment-list - Return some completion for ccloud environment\n"
+    echo
+
+  else
+    printf "playground get-ccloud-environment-list - Return some completion for ccloud environment\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground get-ccloud-environment-list [CUR]\n"
+  printf "  playground get-ccloud-environment-list --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "CUR")"
+    printf "    correspond to completion $cur\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 playground_get_tag_list_usage() {
   if [[ -n $long_usage ]]; then
     printf "playground get-tag-list - Return some completion for confluent platform tag\n"
@@ -1427,12 +1464,12 @@ playground_run_usage() {
 
     # :flag.usage
     printf "  %s\n" "$(magenta "--cluster-region CLUSTER-REGION")"
-    printf "    🗺 The Cloud region. \n    \n    🎓 Tip: you can also use CLUSTER_REGION environment variable\n"
+    printf "    🗺 The Cloud region. \n    \n    🎓 Tip: you can also use CLUSTER_REGION environment variable\n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "$(magenta "--cluster-environment CLUSTER-ENVIRONMENT")"
-    printf "    🌐 The environment id where want your new cluster (example: env-xxxxx)\n    \n    ℹ️ Optional, if not set, new environment will be created\n    \n    🎓 Tip: you can also use ENVIRONMENT environment variable\n"
+    printf "    🌐 The environment id where want your new cluster (example: env-xxxxx)\n    \n    ℹ️ Optional, if not set, new environment will be created\n    \n    🎓 Tip: you can also use ENVIRONMENT environment variable\n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
     echo
 
     # :flag.usage
@@ -2177,12 +2214,12 @@ playground_repro_bootstrap_usage() {
 
     # :flag.usage
     printf "  %s\n" "$(magenta "--cluster-region CLUSTER-REGION")"
-    printf "    🗺 The Cloud region. \n    \n    🎓 Tip: you can also use CLUSTER_REGION environment variable\n"
+    printf "    🗺 The Cloud region. \n    \n    🎓 Tip: you can also use CLUSTER_REGION environment variable\n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "$(magenta "--cluster-environment CLUSTER-ENVIRONMENT")"
-    printf "    🌐 The environment id where want your new cluster (example: env-xxxxx)\n    \n    ℹ️ Optional, if not set, new environment will be created\n    \n    🎓 Tip: you can also use ENVIRONMENT environment variable\n"
+    printf "    🌐 The environment id where want your new cluster (example: env-xxxxx)\n    \n    ℹ️ Optional, if not set, new environment will be created\n    \n    🎓 Tip: you can also use ENVIRONMENT environment variable\n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
     echo
 
     # :flag.usage
@@ -5786,6 +5823,24 @@ function get_playground_repro_export_with_fzf() {
   folder_zip_or_jar=${folder_zip_or_jar//,/ }
 
   res=$(find $folder_zip_or_jar $PWD -name playground_repro_export.tgz ! -path '*/\.*' | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🍺" --header="ctrl-c or esc to quit" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+}
+
+function get_ccloud_environment_list_with_fzf() {
+  cur="$1"
+
+  fzf_version=$(get_fzf_version)
+  if version_gt $fzf_version "0.38"
+  then
+    fzf_option_wrap="--preview-window=40%,wrap"
+    fzf_option_pointer="--pointer=👉"
+    fzf_option_rounded="--border=rounded"
+  else
+    fzf_options=""
+    fzf_option_pointer=""
+    fzf_option_rounded=""
+  fi
+
+  res=$(confluent environment list | awk -F'|' '{print $2"/"$3}' | sed 's/[[:blank:]]//g' | grep -v "ID" | grep -v "\-\-\-" | grep -v '^/' | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🌐" --header="select ccloud environment (ctrl-c or esc to quit)" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
 }
 
 function get_confluent_kafka_region_list_with_fzf() {
@@ -10819,6 +10874,14 @@ playground_get_connector_plugin_command() {
 }
 
 # :command.function
+playground_get_ccloud_environment_list_command() {
+  # src/commands/get-ccloud-environment-list.sh
+  cur="${args[cur]}"
+
+  get_ccloud_environment_list_with_fzf "$cur"
+}
+
+# :command.function
 playground_get_tag_list_command() {
   # src/commands/get-tag-list.sh
   cur="${args[cur]}"
@@ -11600,6 +11663,14 @@ playground_run_command() {
 
   if [[ -n "$cluster_environment" ]]
   then
+    if [[ $cluster_environment == *"@"* ]]
+    then
+      cluster_environment=$(echo "$cluster_environment" | cut -d "@" -f 2)
+    fi
+    if [[ $cluster_environment == *"/"* ]]
+    then
+      cluster_environment=$(echo "$cluster_environment" | sed 's/[[:blank:]]//g' | cut -d "/" -f 2)
+    fi
     flag_list="$flag_list --cluster-environment $cluster_environment"
     export ENVIRONMENT=$cluster_environment
   fi
@@ -11840,8 +11911,6 @@ playground_run_command() {
         export CONNECTOR_JAR=$connector_jar
       fi
 
-      # readonly MENU_CLUSTER_ENVIRONMENT="🌐 The environment id where want your new cluster (example: env-xxxxx)"
-
       # readonly MENU_CLUSTER_NAME="🎰 The cluster name" #17
       # readonly MENU_CLUSTER_CREDS="🔒 The Kafka api key and secret to use, it should be separated with colon (example: <API_KEY>:<API_KEY_SECRET>)"
       # readonly MENU_CLUSTER_SR_CREDS="🔒 The Schema Registry api key and secret to use, it should be separated with colon (example: <SR_API_KEY>:<SR_API_KEY_SECRET>)"
@@ -11864,6 +11933,22 @@ playground_run_command() {
           cluster_region=$(echo "$cluster_region" | cut -d "@" -f 2)
         fi
         cluster_region=$(echo "$cluster_region" | sed 's/[[:blank:]]//g' | cut -d "/" -f 2)
+      fi
+
+      if [[ $res == *"$MENU_CLUSTER_REGION"* ]]
+      then
+        cluster_environment=$(playground get-ccloud-environment-list)
+
+        if [[ $cluster_environment == *"@"* ]]
+        then
+          cluster_environment=$(echo "$cluster_environment" | cut -d "@" -f 2)
+        fi
+        if [[ $cluster_environment == *"/"* ]]
+        then
+          cluster_environment=$(echo "$cluster_environment" | sed 's/[[:blank:]]//g' | cut -d "/" -f 2)
+        fi
+        flag_list="$flag_list --cluster-environment $cluster_environment"
+        export ENVIRONMENT=$cluster_environment
       fi
     fi # end of interactive_mode
   fi
@@ -19175,6 +19260,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    get-ccloud-environment-list)
+      action="get-ccloud-environment-list"
+      shift
+      playground_get_ccloud_environment_list_parse_requirements "$@"
+      shift $#
+      ;;
+
     get-tag-list)
       action="get-tag-list"
       shift
@@ -19785,6 +19877,56 @@ playground_get_connector_plugin_parse_requirements() {
 
   # :command.command_filter
   action="get-connector-plugin"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['cur']+x} ]]; then
+
+          args['cur']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_get_ccloud_environment_list_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_get_ccloud_environment_list_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="get-ccloud-environment-list"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -29165,6 +29307,7 @@ run() {
     "generate-connector-plugin-list") playground_generate_connector_plugin_list_command ;;
     "generate-kafka-region-list") playground_generate_kafka_region_list_command ;;
     "get-connector-plugin") playground_get_connector_plugin_command ;;
+    "get-ccloud-environment-list") playground_get_ccloud_environment_list_command ;;
     "get-tag-list") playground_get_tag_list_command ;;
     "get-kafka-region-list") playground_get_kafka_region_list_command ;;
     "get-topic-list") playground_get_topic_list_command ;;
