playground container recreate doesn't take env variables into account #4567

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -5761,6 +5761,117 @@ function check_bash_version() {
   fi
 }
 
+function set_profiles() {
+
+  rm -f /tmp/playground-command
+  touch /tmp/playground-command
+  # https://docs.docker.com/compose/profiles/
+  profile_control_center_command=""
+  if [ -z "$ENABLE_CONTROL_CENTER" ]
+  then
+    log "🛑 control-center is disabled"
+  else
+    log "💠 control-center is enabled"
+    log "Use http://localhost:9021 to login"
+    profile_control_center_command="--profile control-center"
+    echo "export ENABLE_CONTROL_CENTER=1" >> /tmp/playground-command
+  fi
+
+  profile_ksqldb_command=""
+  if [ -z "$ENABLE_KSQLDB" ]
+  then
+    log "🛑 ksqldb is disabled"
+  else
+    log "🚀 ksqldb is enabled"
+    log "🔧 You can use ksqlDB with CLI using:"
+    log "docker exec -i ksqldb-cli ksql http://ksqldb-server:8088"
+    profile_ksqldb_command="--profile ksqldb"
+    echo "export ENABLE_KSQLDB=1" >> /tmp/playground-command
+  fi
+
+  # defined grafana variable and when profile is included/excluded
+  profile_grafana_command=""
+  if [ -z "$ENABLE_JMX_GRAFANA" ]
+  then
+    log "🛑 Grafana is disabled"
+  else
+    log "📊 Grafana is enabled"
+    profile_grafana_command="--profile grafana"
+    echo "export ENABLE_JMX_GRAFANA=1" >> /tmp/playground-command
+  fi
+  profile_kcat_command=""
+  if [ -z "$ENABLE_KCAT" ]
+  then
+    log "🛑 kcat is disabled"
+  else
+    log "🧰 kcat is enabled"
+    profile_kcat_command="--profile kcat"
+    echo "export ENABLE_KCAT=1" >> /tmp/playground-command
+  fi
+  profile_conduktor_command=""
+  if [ -z "$ENABLE_CONDUKTOR" ]
+  then
+    log "🛑 conduktor is disabled"
+  else
+    log "🐺 conduktor is enabled"
+    log "Use http://localhost:8080/console (admin/admin) to login"
+    profile_conduktor_command="--profile conduktor"
+    echo "export ENABLE_CONDUKTOR=1" >> /tmp/playground-command
+  fi
+  profile_sql_datagen_command=""
+  if [ ! -z "$SQL_DATAGEN" ]
+  then
+    profile_sql_datagen_command="--profile sql_datagen"
+    echo "export SQL_DATAGEN=1" >> /tmp/playground-command
+  fi
+
+  #define kafka_nodes variable and when profile is included/excluded
+  profile_kafka_nodes_command=""
+  if [ -z "$ENABLE_KAFKA_NODES" ]
+  then
+    profile_kafka_nodes_command=""
+  else
+    log "3️⃣  Multi broker nodes enabled"
+    profile_kafka_nodes_command="--profile kafka_nodes"
+    echo "export ENABLE_KAFKA_NODES=1" >> /tmp/playground-command
+  fi
+
+  # Adding Schema Registry plugin profile
+  profile_schema_registry_command=""
+  if [ -z "$ENABLE_SR_MAVEN_PLUGIN_NODE" ]
+  then
+    profile_schema_registry_command=""
+  else
+    log " Starting Schema Registry plugin profile"
+    profile_schema_registry_command="--profile sr_plugin_app"
+    echo "export ENABLE_SR_MAVEN_PLUGIN_NODE=1" >> /tmp/playground-command
+  fi
+
+  # defined 3 Connect variable and when profile is included/excluded
+  profile_connect_nodes_command=""
+  if [ -z "$ENABLE_CONNECT_NODES" ]
+  then
+    :
+  elif [ ${nb_connect_services} -gt 1 ]
+  then
+
+    log "🥉 Multiple Connect nodes mode is enabled, connect2 and connect 3 containers will be started"
+    profile_connect_nodes_command="--profile connect_nodes"
+    export CONNECT_NODES_PROFILES="connect_nodes"
+    echo "export CONNECT_NODES_PROFILES=connect_nodes" >> /tmp/playground-command
+  else
+    if [ ! -f "${DOCKER_COMPOSE_FILE_OVERRIDE}" ]
+    then
+      log "🥉 Multiple connect nodes mode is enabled, connect2 and connect 3 containers will be started"
+      profile_connect_nodes_command="--profile connect_nodes"
+      echo "export CONNECT_NODES_PROFILES=connect_nodes" >> /tmp/playground-command
+    else
+      logerror "🛑 Could not find connect2 and connect3 in ${DOCKER_COMPOSE_FILE_OVERRIDE}. Update the yaml files to contain the connect2 && connect3 in ${DOCKER_COMPOSE_FILE_OVERRIDE}"
+      exit 1
+    fi
+  fi
+}
+
 function get_confluent_version() {
   confluent version | grep "^Version:" | cut -d':' -f2 | cut -d'v' -f2
 }
