get-properties change

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -62,7 +62,6 @@ playground_usage() {
   echo
   printf "%s\n" "$(bold "Kafka commands:")"
   printf "  %s   🐋 Get docker-compose\n" "$(green "get-docker-compose")                            "
-  printf "  %s   📝 Get properties file from a container\n" "$(green "get-properties")                                "
   printf "  %s   🔢 Get JMX metrics from a component\n" "$(green "get-jmx-metrics")                               "
   echo
   printf "%s\n" "$(bold "Schema commands:")"
@@ -90,6 +89,7 @@ playground_usage() {
   echo
   printf "%s\n" "$(bold "Container commands:")"
   printf "  %s   🐳 Container commands\n" "$(green "container")                                     "
+  printf "  %s   📝 Get properties file from a container\n" "$(green "container get-properties")                      "
   printf "  %s   💫 Recreate container(s)\n" "$(green "container recreate")                            "
   printf "  %s   🖥️  Get ip address of running containers\n" "$(green "container get-ip-addresses")                    "
   printf "  %s   💀 Kill all containers\n" "$(green "container kill-all")                            "
@@ -2256,52 +2256,6 @@ playground_get_docker_compose_usage() {
 }
 
 # :command.usage
-playground_get_properties_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "playground get-properties\n"
-    echo
-
-    printf "  📝 Get properties file from a container\n  \n  👉 Check documentation\n  https://kafka-docker-playground.io/#/how-to-use?id=%f0%9f%93%9d-see-properties-file\n"
-    echo
-
-  else
-    printf "playground get-properties - 📝 Get properties file from a container\n"
-    echo
-
-  fi
-
-  printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground get-properties [OPTIONS]\n"
-  printf "  playground get-properties --help | -h\n"
-  echo
-
-  # :command.long_usage
-  if [[ -n $long_usage ]]; then
-    printf "%s\n" "$(bold "== Options ==")"
-
-    # :command.usage_flags
-    # :flag.usage
-    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
-    printf "    🐳 Container name\n"
-    printf "    Default: connect\n"
-    echo
-
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
-    # :command.usage_examples
-    printf "%s\n" "$(bold "Examples")"
-    printf "  playground get-properties\n"
-    printf "  playground get-properties --container broker\n"
-    printf "  playground get-properties -c broker\n"
-    echo
-
-  fi
-}
-
-# :command.usage
 playground_schema_usage() {
   if [[ -n $long_usage ]]; then
     printf "playground schema - 🔰 Schema commands\n"
@@ -3327,6 +3281,9 @@ playground_container_usage() {
   printf "  playground container [COMMAND] --help | -h\n"
   echo
   # :command.usage_commands
+  printf "%s\n" "$(bold "== Commands ==")"
+  printf "  %s   📝 Get properties file from a container\n" "$(green "get-properties")  "
+  echo
   printf "%s\n" "$(bold "Container commands:")"
   printf "  %s   💫 Recreate container(s)\n" "$(green "recreate")        "
   printf "  %s   🖥️  Get ip address of running containers\n" "$(green "get-ip-addresses")"
@@ -3347,6 +3304,52 @@ playground_container_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_container_get_properties_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground container get-properties\n"
+    echo
+
+    printf "  📝 Get properties file from a container\n  \n  👉 Check documentation\n  https://kafka-docker-playground.io/#/how-to-use?id=%f0%9f%93%9d-see-properties-file\n"
+    echo
+
+  else
+    printf "playground container get-properties - 📝 Get properties file from a container\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground container get-properties [OPTIONS]\n"
+  printf "  playground container get-properties --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    🐳 Container name\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground get-properties\n"
+    printf "  playground get-properties --container broker\n"
+    printf "  playground get-properties -c broker\n"
     echo
 
   fi
@@ -13453,16 +13456,6 @@ playground_get_docker_compose_command() {
 }
 
 # :command.function
-playground_get_properties_command() {
-  # src/get_properties_command.sh
-  container="${args[--container]}"
-
-  log "Displaying properties file for $container"
-  # see heredocs.sh
-  get_properties_command_heredoc "$container"
-}
-
-# :command.function
 playground_schema_get_command() {
   # src/schema_get_command.sh
   subject="${args[--subject]}"
@@ -14433,6 +14426,16 @@ playground_get_jmx_metrics_command() {
   esac
 
   get_jmx_metrics "$component" "$domain" "$open"
+}
+
+# :command.function
+playground_container_get_properties_command() {
+  # src/container_get_properties_command.sh
+  container="${args[--container]}"
+
+  log "Displaying properties file for $container"
+  # see heredocs.sh
+  get_properties_command_heredoc "$container"
 }
 
 # :command.function
@@ -18590,13 +18593,6 @@ parse_requirements() {
       shift $#
       ;;
 
-    get-properties)
-      action="get-properties"
-      shift
-      playground_get_properties_parse_requirements "$@"
-      shift $#
-      ;;
-
     schema)
       action="schema"
       shift
@@ -22494,67 +22490,6 @@ playground_get_docker_compose_parse_requirements() {
 }
 
 # :command.parse_requirements
-playground_get_properties_parse_requirements() {
-  # :command.fixed_flags_filter
-  while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
-      --help | -h)
-        long_usage=yes
-        playground_get_properties_usage
-        exit
-        ;;
-
-      *)
-        break
-        ;;
-
-    esac
-  done
-
-  # :command.command_filter
-  action="get-properties"
-
-  # :command.parse_requirements_while
-  while [[ $# -gt 0 ]]; do
-    key="$1"
-    case "$key" in
-      # :flag.case
-      --container | -c)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-
-          args['--container']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
-          exit 1
-        fi
-        ;;
-
-      -?*)
-        printf "invalid option: %s\n" "$key" >&2
-        exit 1
-        ;;
-
-      *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
-
-        ;;
-
-    esac
-  done
-
-  # :command.default_assignments
-  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
-
-}
-
-# :command.parse_requirements
 playground_schema_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -24505,6 +24440,13 @@ playground_container_parse_requirements() {
   case $action in
     -*) ;;
 
+    get-properties)
+      action="get-properties"
+      shift
+      playground_container_get_properties_parse_requirements "$@"
+      shift $#
+      ;;
+
     recreate)
       action="recreate"
       shift
@@ -24608,6 +24550,67 @@ playground_container_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_container_get_properties_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_container_get_properties_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="container get-properties"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
 
 }
 
@@ -28773,7 +28776,6 @@ run() {
     "repro import") playground_repro_import_command ;;
     "repro bootstrap") playground_repro_bootstrap_command ;;
     "get-docker-compose") playground_get_docker_compose_command ;;
-    "get-properties") playground_get_properties_command ;;
     "schema") playground_schema_command ;;
     "schema get") playground_schema_get_command ;;
     "schema register") playground_schema_register_command ;;
@@ -28797,6 +28799,7 @@ run() {
     "debug log-level set") playground_debug_log_level_set_command ;;
     "get-jmx-metrics") playground_get_jmx_metrics_command ;;
     "container") playground_container_command ;;
+    "container get-properties") playground_container_get_properties_command ;;
     "container recreate") playground_container_recreate_command ;;
     "container get-ip-addresses") playground_container_get_ip_addresses_command ;;
     "container kill-all") playground_container_kill_all_command ;;
