Add cli for AWS EC2 instance (using Cloud Formation) #5730

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -168,6 +168,7 @@ playground_usage() {
   printf "%s\n" "$(bold "ec2 commands:")"
   printf "  %s   😶‍🌫️ AWS EC2 instance (using Cloud Formation)\n" "$(green "ec2")                                      "
   printf "  %s   🏭 Create an EC2 instance using Cloud Formation\n" "$(green "ec2 create")                               "
+  printf "  %s   👨‍💻 Open an EC2 instance using Visual Studio code\n" "$(green "ec2 open")                                 "
   echo
 
   # :command.long_usage
@@ -316,6 +317,43 @@ playground_get_connector_list_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_get_ec2_instance_list_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground get-ec2-instance-list - Return some completion for ec2 instance list\n"
+    echo
+
+  else
+    printf "playground get-ec2-instance-list - Return some completion for ec2 instance list\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground get-ec2-instance-list [CUR]\n"
+  printf "  playground get-ec2-instance-list --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "CUR")"
+    printf "    correspond to completion $cur\n"
     echo
 
   fi
@@ -6609,6 +6647,7 @@ playground_ec2_usage() {
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   🏭 Create an EC2 instance using Cloud Formation\n" "$(green "create")"
+  printf "  %s   👨‍💻 Open an EC2 instance using Visual Studio code\n" "$(green "open")  "
   echo
 
   # :command.long_usage
@@ -6678,6 +6717,46 @@ playground_ec2_create_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--suffix SUFFIX")"
     printf "    📮 suffix to add to instance name\n    kafka-docker-playground-${username}-${suffix}\n    \n    If not set, default is kafka-docker-playground-${username}-${current-date}\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ec2_open_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground ec2 open - 👨‍💻 Open an EC2 instance using Visual Studio code\n"
+    echo
+
+  else
+    printf "playground ec2 open - 👨‍💻 Open an EC2 instance using Visual Studio code\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ec2 open [OPTIONS]\n"
+  printf "  playground ec2 open --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--pem-file PEM-FILE")"
+    printf "    🔐 AWS EC2 pem file\n    \n    ❕ It must be absolute full path\n    \n    You can also specify it with EC2_CLOUD_FORMATION_PEM_FILE environment\n    variable\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--instance, -i INSTANCE (required)")"
+    printf "    🖥️ EC2 instance (need to use completion to get all required details)\n"
     echo
 
     # :command.usage_fixed_flags
@@ -7270,6 +7349,60 @@ function get_confluent_kafka_region_list_with_fzf() {
   fi
 
   res=$(cat $root_folder/scripts/cli/confluent-kafka-region-list.txt | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🌍" --header="select region" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+}
+
+function ec2_instance_list() {
+  username=$(whoami)
+  name="kafka-docker-playground-${username}"
+
+  for row in $(aws ec2 describe-instances | jq '[.Reservations | .[] | .Instances | .[] | select(.State.Name!="terminated") | {KeyName: .KeyName, LaunchTime: .LaunchTime, PublicDnsName: .PublicDnsName, InstanceId: .InstanceId, InstanceType: .InstanceType,State: .State.Name, Name: (.Tags[]|select(.Key=="Name")|.Value)}]' | jq -r '.[] | @base64'); do
+      _jq() {
+      echo ${row} | base64 -d | jq -r ${1}
+      }
+
+      Name=$(echo $(_jq '.Name'))
+      if [[ $Name != $name* ]]
+      then
+          continue
+      fi
+    # KeyName=$(echo $(_jq '.KeyName'))
+    # LaunchTime=$(echo $(_jq '.LaunchTime'))
+      PublicDnsName=$(echo $(_jq '.PublicDnsName'))
+      InstanceId=$(echo $(_jq '.InstanceId'))
+    # InstanceType=$(echo $(_jq '.InstanceType'))
+      State=$(echo $(_jq '.State'))
+
+      if [ "$State" = "stopped" ]
+      then
+          echo -n "$Name|$EC2_INSTANCE_STATE_STOPPED|$PublicDnsName|$InstanceId"
+      elif [ "$State" = "stopping" ]
+      then
+          echo -n "$Name|$EC2_INSTANCE_STATE_STOPPING"
+      elif [ "$State" = "pending" ]
+      then
+          echo -n "$Name|$EC2_INSTANCE_STATE_PENDING"
+      else
+          echo -n "$Name|$EC2_INSTANCE_STATE_RUNNING|$PublicDnsName|$InstanceId"
+      fi
+  done
+}
+
+function get_ec2_instance_list_with_fzf() {
+  cur="$1"
+
+  fzf_version=$(get_fzf_version)
+  if version_gt $fzf_version "0.38"
+  then
+    fzf_option_wrap="--preview-window=40%,wrap"
+    fzf_option_pointer="--pointer=👉"
+    fzf_option_rounded="--border=rounded"
+  else
+    fzf_option_wrap=""
+    fzf_option_pointer=""
+    fzf_option_rounded=""
+  fi
+
+  res=$(ec2_instance_list | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🖥️" --header="select ec2 instance (wait for it)" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
 }
 
 function get_tag_list_with_fzf() {
@@ -12291,6 +12424,11 @@ readonly CONNECTOR_TYPE_CUSTOM="🌤️🛃custom"
 readonly CONNECTOR_TYPE_SELF_MANAGED="⛈️👷self managed"
 readonly CONNECTOR_TYPE_ONPREM="🌎onprem"
 
+readonly EC2_INSTANCE_STATE_STOPPED="🛑stopped"
+readonly EC2_INSTANCE_STATE_RUNNING="✅running"
+readonly EC2_INSTANCE_STATE_STOPPING="⌛stopping"
+readonly EC2_INSTANCE_STATE_PENDING="⌛pending"
+
 function get_connector_type () {
   get_connector_paths
   if [ "$connector_paths" == "" ]
@@ -12692,6 +12830,14 @@ playground_get_connector_list_command() {
   fi
 
   echo "$curl_output" | jq -r '.[]' | tr '\n' ' ' | sed -e 's/[[:space:]]*$//'
+}
+
+# :command.function
+playground_get_ec2_instance_list_command() {
+  # src/commands/get-ec2-instance-list.sh
+  cur="${args[cur]}"
+
+  get_ec2_instance_list_with_fzf "$cur"
 }
 
 # :command.function
@@ -24816,7 +24962,7 @@ playground_ec2_create_command() {
 
   # ParameterKey=GithubSshKeyFile,ParameterValue="${github_ssh_key_file_content}"
 
-  log "Sleeping 4 minutes"
+  log "sleeping 4 minutes to let the instance start..."
   sleep 240
 
   for row in $(aws ec2 describe-instances | jq '[.Reservations | .[] | .Instances | .[] | {KeyName: .KeyName, LaunchTime: .LaunchTime, PublicDnsName: .PublicDnsName, InstanceId: .InstanceId, InstanceType: .InstanceType,State: .State.Name, Name: (.Tags[]|select(.Key=="Name")|.Value)}]' | jq -r '.[] | @base64'); do
@@ -24834,10 +24980,95 @@ playground_ec2_create_command() {
 
       if [ "$Name" == "$name" ]
       then
-          log "Starting $Name ($InstanceId)"
+          log "starting $Name ($InstanceId)"
           #ksh ./ec2openec2.ksh "$PublicDnsName|$Name|$InstanceId|$State"
       fi
   done
+}
+
+# :command.function
+playground_ec2_open_command() {
+  # src/commands/ec2/open.sh
+  instance="${args[--instance]}"
+  pem_file="${args[--pem-file]}"
+
+  if [[ $(type code 2>&1) =~ "not found" ]]
+  then
+      logerror "❌ code command is not found - this command requires vscode to be installed"
+      exit 1
+  fi
+
+  if [[ -n "$pem_file" ]]
+  then
+      if [[ $pem_file == *"@"* ]]
+      then
+          pem_file=$(echo "$pem_file" | cut -d "@" -f 2)
+      fi
+  elif [[ -n "$EC2_CLOUD_FORMATION_PEM_FILE" ]]
+  then
+      pem_file="$EC2_CLOUD_FORMATION_PEM_FILE"
+      if [ ! -f "$EC2_CLOUD_FORMATION_PEM_FILE" ]
+      then
+          logerror "❌ EC2_CLOUD_FORMATION_PEM_FILE is set with $EC2_CLOUD_FORMATION_PEM_FILE but the file does not exist"
+          exit 1
+      fi
+  else
+      logerror "❌ --pem-file or EC2_CLOUD_FORMATION_PEM_FILE is required"
+      exit 1
+  fi
+
+  if [[ $instance == *"@"* ]]
+  then
+      instance=$(echo "$instance" | cut -d "@" -f 2)
+  fi
+  name=$(echo "${instance}" | cut -d "|" -f 1)
+  state=$(echo "${instance}" | cut -d "|" -f 2)
+  ip=$(echo "${instance}" | cut -d "|" -f 3)
+  id=$(echo "${instance}" | cut -d "|" -f 4)
+
+  group=$(aws ec2 describe-instances --instance-id $id --output=json | jq '.Reservations[] | .Instances[] | {SecurityGroups: .SecurityGroups}' | jq -r '.SecurityGroups[0] | .GroupName')
+
+  # delete all rules
+  aws ec2 revoke-security-group-ingress --group-name $group \
+    --ip-permissions \
+    "$(aws ec2 describe-security-groups --output json --group-name $group --query "SecurityGroups[0].IpPermissions")"
+
+  myip=$(dig @resolver4.opendns.com myip.opendns.com +short)
+  aws ec2 authorize-security-group-ingress --group-name "$group" --protocol tcp --port 22 --cidr $myip/32 > /dev/null 2>&1 &
+  if [ "$state" = "$EC2_INSTANCE_STATE_STOPPED" ]
+  then
+      log "🚀 starting the ec2 instance $name with id $id"
+      aws ec2 start-instances --instance-ids "$id"
+      sleep 15
+      ip=$(aws ec2 describe-instances --instance-ids "$id" | jq ".Reservations[0].Instances[0].PublicDnsName" | tr -d '"')
+  fi
+
+  mkdir -p $HOME/.ssh
+  SSH_CONFIG_FILE=$HOME/.ssh/config
+
+  username=$(whoami)
+
+  set +e
+  grep "$name" $SSH_CONFIG_FILE > /dev/null
+  if [ $? = 0 ]
+  then
+      OLDIP=$(grep -w $name -A 1 ${SSH_CONFIG_FILE} | awk '/HostName/ {print $2}')
+      sed -e "s/$OLDIP/$ip/g" ${SSH_CONFIG_FILE} > /tmp/tmp_file
+      mv /tmp/tmp_file ${SSH_CONFIG_FILE}
+  else
+  cat << EOF >> ${SSH_CONFIG_FILE}
+
+Host $name
+  HostName $ip
+  IdentityFile $pem_file
+  User $username
+  StrictHostKeyChecking no
+EOF
+
+  fi
+  set -e
+  code --folder-uri "vscode-remote://ssh-remote+$name/home/$username"
+
 }
 
 # :command.parse_requirements
@@ -24925,6 +25156,13 @@ parse_requirements() {
       action="get-connector-list"
       shift
       playground_get_connector_list_parse_requirements "$@"
+      shift $#
+      ;;
+
+    get-ec2-instance-list)
+      action="get-ec2-instance-list"
+      shift
+      playground_get_ec2_instance_list_parse_requirements "$@"
       shift $#
       ;;
 
@@ -25480,6 +25718,56 @@ playground_get_connector_list_parse_requirements() {
         # :command.parse_requirements_case_simple
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_get_ec2_instance_list_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_get_ec2_instance_list_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="get-ec2-instance-list"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        # :argument.case
+        if [[ -z ${args['cur']+x} ]]; then
+          args['cur']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
@@ -37130,6 +37418,13 @@ playground_ec2_parse_requirements() {
       shift $#
       ;;
 
+    open)
+      action="open"
+      shift
+      playground_ec2_open_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_ec2_usage >&2
@@ -37327,6 +37622,96 @@ playground_ec2_create_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+playground_ec2_open_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ec2_open_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="ec2 open"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --pem-file)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--pem-file']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--pem-file requires an argument: --pem-file PEM-FILE" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --instance | -i)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--instance']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--instance requires an argument: --instance, -i INSTANCE" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--instance']+x} ]]; then
+    printf "missing required flag: --instance, -i INSTANCE\n" >&2
+    exit 1
+  fi
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--pem-file'] && -n $(validate_file_exists_with_trick "${args['--pem-file']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--pem-file PEM-FILE" "$(validate_file_exists_with_trick "${args['--pem-file']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--instance'] && -n $(validate_not_empty "${args['--instance']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--instance, -i INSTANCE" "$(validate_not_empty "${args['--instance']:-}")" >&2
+    exit 1
+  fi
+
+}
+
 # :command.user_hooks
 before_hook() {
   # src/before.sh
@@ -37381,6 +37766,7 @@ run() {
     "status") playground_status_command ;;
     "get-docker-ports") playground_get_docker_ports_command ;;
     "get-connector-list") playground_get_connector_list_command ;;
+    "get-ec2-instance-list") playground_get_ec2_instance_list_command ;;
     "get-zazkia-connection-list") playground_get_zazkia_connection_list_command ;;
     "generate-fzf-find-files") playground_generate_fzf_find_files_command ;;
     "generate-tag-list") playground_generate_tag_list_command ;;
@@ -37524,6 +37910,7 @@ run() {
     "connector update") playground_connector_update_command ;;
     "ec2") playground_ec2_command ;;
     "ec2 create") playground_ec2_create_command ;;
+    "ec2 open") playground_ec2_open_command ;;
   esac
 }
 
