Remove requirement to move java producer manually in boostrap-reproduction-model CLI #3499

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 0.9.5 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.0.rc1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -156,11 +156,6 @@ playground_bootstrap_reproduction_model_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--file, -f FILE (required)")"
@@ -183,6 +178,11 @@ playground_bootstrap_reproduction_model_usage() {
     printf "  %s\n" "$(magenta "--nb-producers, -n NB-PRODUCERS")"
     printf "    Number of java producers to generate.\n"
     printf "    Default: \n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_environment_variables
@@ -229,16 +229,16 @@ playground_get_properties_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
     printf "    Container name.\n"
     printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_examples
@@ -275,16 +275,16 @@ playground_enable_remote_debugging_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
     printf "    Container name.\n"
     printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_examples
@@ -321,11 +321,6 @@ playground_get_jmx_metrics_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--component, -c COMPONENT")"
@@ -337,6 +332,11 @@ playground_get_jmx_metrics_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--domain, -d DOMAIN")"
     printf "    Domain name.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_examples
@@ -465,15 +465,15 @@ playground_get_number_records_topic_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--topic, -t TOPIC (required)")"
     printf "    Topic name.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_examples
@@ -506,11 +506,6 @@ playground_logs_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
@@ -532,6 +527,11 @@ playground_logs_usage() {
     printf "  %s\n" "$(magenta "--max-wait, -m MAX_WAIT")"
     printf "    Max time in seconds to wait when using --wait-for-log (default 600s).\n"
     printf "    Default: 600\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_examples
@@ -565,11 +565,6 @@ playground_ssh_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
@@ -582,6 +577,11 @@ playground_ssh_usage() {
     printf "    Shell to use (default is bash).\n"
     printf "    Allowed: bash, sh, ksh, zsh\n"
     printf "    Default: bash\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_examples
@@ -615,11 +615,6 @@ playground_exec_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
@@ -642,6 +637,11 @@ playground_exec_usage() {
     printf "    Shell to use (default is bash).\n"
     printf "    Allowed: bash, sh, ksh, zsh\n"
     printf "    Default: bash\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_examples
@@ -721,15 +721,15 @@ playground_connector_status_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--json")"
     printf "    Show output as JSON.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -785,15 +785,15 @@ playground_connector_pause_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--connector, -c CONNECTOR (required)")"
     printf "    Connector name.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -820,15 +820,15 @@ playground_connector_resume_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--connector, -c CONNECTOR (required)")"
     printf "    Connector name.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -855,15 +855,15 @@ playground_connector_delete_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--connector, -c CONNECTOR (required)")"
     printf "    Connector name.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -935,15 +935,15 @@ playground_connect_log_level_get_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--package, -p PACKAGE")"
     printf "    Package name.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -970,11 +970,6 @@ playground_connect_log_level_set_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "Options:")"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "$(magenta "--package, -p PACKAGE (required)")"
@@ -985,6 +980,11 @@ playground_connect_log_level_set_usage() {
     printf "  %s\n" "$(magenta "--level, -l LEVEL (required)")"
     printf "    Log level.\n"
     printf "    Allowed: INFO, WARN, DEBUG, TRACE\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -4887,7 +4887,33 @@ playground_bootstrap_reproduction_model_command() {
     line=$(grep -n '${DIR}/../../environment' $repro_test_file | cut -d ":" -f 1 | tail -n1)
 
     { head -n $(($line-1)) $tmp_dir/tmp_file; cat $tmp_dir/build_producer; tail -n +$line $tmp_dir/tmp_file; } > $repro_test_file
+
+    line_kafka_cli_producer=$(egrep -n "kafka-console-producer|kafka-avro-console-producer|kafka-json-schema-console-producer|kafka-protobuf-console-producer" $repro_test_file | cut -d ":" -f 1 | tail -n1)
+    kafka_cli_producer_error=0
+    kafka_cli_producer_eof=0
+    set +e
+    egrep "kafka-console-producer|kafka-avro-console-producer|kafka-json-schema-console-producer|kafka-protobuf-console-producer" $repro_test_file | grep EOF > /dev/null
+    if [ $? = 0 ]
+    then
+        kafka_cli_producer_eof=1
+
+        sed -n "$line_kafka_cli_producer,$(($line_kafka_cli_producer + 10))p" $repro_test_file > /tmp/tmp
+        tmp=$(grep -n "^EOF" /tmp/tmp | cut -d ":" -f 1 | tail -n1)
+        if [ $tmp == "" ]
+        then
+          logwarn "Could not determine EOF for kafka cli producer!"
+          kafka_cli_producer_error=1
+        fi
+        line_kafka_cli_producer_end=$(($line_kafka_cli_producer + $tmp))
+    else
+        logwarn "Could not find kafka cli producer!"
+        kafka_cli_producer_error=1
+    fi
+    set -e
+    if [ $kafka_cli_producer_error = 1 ]
+    then
       get_producer_fixthis_heredoc
+    fi
 
     for((i=1;i<=$nb_producers;i++)); do
       producer_hostname=""
@@ -4902,10 +4928,25 @@ playground_bootstrap_reproduction_model_command() {
       fi
       get_producer_run_heredoc
     done
+    if [ $kafka_cli_producer_error = 1 ]
+    then
       get_producer_fixthis_heredoc
+    fi
     # log "✨ Adding command to run producer to $repro_test_file"
     cp $repro_test_file $tmp_dir/tmp_file
-    { head -n $(($line-1)) $tmp_dir/tmp_file; cat $tmp_dir/java_producer; tail -n +$line $tmp_dir/tmp_file; } > $repro_test_file
+
+    if [ $kafka_cli_producer_error == 1 ]
+    then
+        { head -n $(($line-1)) $tmp_dir/tmp_file; cat $tmp_dir/java_producer; tail -n +$line $tmp_dir/tmp_file; } > $repro_test_file
+    else
+      if [ $kafka_cli_producer_eof == 0 ]
+      then
+        line_kafka_cli_producer_end=$(($line_kafka_cli_producer + 1))
+      fi
+      { head -n $(($line_kafka_cli_producer - 2)) $tmp_dir/tmp_file; cat $tmp_dir/java_producer; tail -n +$line_kafka_cli_producer_end $tmp_dir/tmp_file; } > $repro_test_file
+    fi
+    set +x
+
   fi
 
   chmod u+x $repro_test_file
