Add CI results when using run command #5527

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -963,6 +963,27 @@ playground_update_docs_usage() {
 }
 
 # :command.usage
+playground_get_ci_result_usage() {
+  printf "playground get-ci-result - get ci result for current test\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground get-ci-result\n"
+  printf "  playground get-ci-result --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 playground_bashly_reload_usage() {
   printf "playground bashly-reload\n\n"
 
@@ -13391,6 +13412,52 @@ playground_update_docs_command() {
 }
 
 # :command.function
+playground_get_ci_result_command() {
+  # src/commands/get-ci-result.sh
+  test_file=$(playground state get run.test_file)
+
+  if [ ! -f $test_file ]
+  then
+
+      logerror "File $test_file retrieved from $root_folder/playground.ini does not exist!"
+      exit 1
+  fi
+
+  test_file_directory="$(dirname "${test_file}")"
+  base1="${test_file_directory##*/}" # connect-cdc-oracle12-source
+  dir1="${test_file_directory%/*}" #connect
+  dir2="${dir1##*/}/$base1" # connect/connect-cdc-oracle12-source
+
+  tmp_dir=$(mktemp -d -t pg-XXXXXXXXXX)
+  if [ -z "$PG_VERBOSE_MODE" ]
+  then
+      trap 'rm -rf $tmp_dir' EXIT
+  else
+      log "🐛📂 not deleting tmp dir $tmp_dir"
+  fi
+
+  content_file="$tmp_dir/content.md"
+  curl -s -o $content_file  https://raw.githubusercontent.com/vdesabou/kafka-docker-playground-docs/main/docs/content.md
+
+  result_ok="$(grep "$dir2" $content_file | sed -n 's/.*\[CI \(ok\)\].*(\(https[^)]*\)).*/🤖CI status: 🟢 ok\n🔗test url: \2/p')"
+  result_fail="$(grep "$dir2" $content_file | sed -n 's/.*\[CI \(fail\)\].*(\(https[^)]*\)).*/🤖CI status: 🔴 fail\n🐛 github issue: \2/p')"
+  result_not_tested="$(grep "$dir2" $content_file | sed -n 's/.*\[not tested\].*/🤖CI status: 🤷‍♂️ not tested/p')"
+
+  # print only result not empty
+  if [ -n "$result_ok" ]; then
+      log "$result_ok"
+  fi
+
+  if [ -n "$result_fail" ]; then
+      logwarn "$result_fail"
+  fi
+
+  if [ -n "$result_not_tested" ]; then
+      log "$result_not_tested"
+  fi
+}
+
+# :command.function
 playground_bashly_reload_command() {
   # src/commands/bashly-reload.sh
   cd $root_folder/scripts/cli
@@ -15129,7 +15196,7 @@ playground_run_command() {
 
   increment_cli_metric nb_runs
   log "🚀 Number of examples ran so far: $(get_cli_metric nb_runs)"
-
+  playground get-ci-result
   log "####################################################"
   log "🚀 Executing $filename in dir $test_file_directory"
   log "####################################################"
@@ -25710,6 +25777,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    get-ci-result)
+      action="get-ci-result"
+      shift
+      playground_get_ci_result_parse_requirements "$@"
+      shift $#
+      ;;
+
     bashly-reload)
       action="bashly-reload"
       shift
@@ -27376,6 +27450,51 @@ playground_update_docs_parse_requirements() {
 
   # :command.command_filter
   action="update-docs"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_get_ci_result_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_get_ci_result_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="get-ci-result"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -39685,6 +39804,7 @@ run() {
     "get-predefined-schemas") playground_get_predefined_schemas_command ;;
     "update-readme") playground_update_readme_command ;;
     "update-docs") playground_update_docs_command ;;
+    "get-ci-result") playground_get_ci_result_command ;;
     "bashly-reload") playground_bashly_reload_command ;;
     "state") playground_state_command ;;
     "state show") playground_state_show_command ;;
