wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1520,6 +1520,11 @@ playground_schema_register_usage() {
     printf "    Default: -\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--replace")"
+    printf "    💪 Force replace existing schema\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -10764,6 +10769,7 @@ playground_schema_register_command() {
   subject="${args[--subject]}"
   schema="${args[--input]}"
   verbose="${args[--verbose]}"
+  replace="${args[--replace]}"
 
   ret=$(get_sr_url_and_security)
 
@@ -10816,6 +10822,37 @@ playground_schema_register_command() {
   content=$(cat $schema_file | tr -d '\n' | tr -s ' ')
   json_new=$(echo $json | jq --arg content "$content" '. + { "schema": $content }')
 
+  # check if schema already exists
+  # https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)
+  curl_output=$(curl $sr_security --request POST -s "${sr_url}/subjects/${subject}" \
+  --header 'Content-Type: application/vnd.schemaregistry.v1+json' \
+  --data "$json_new" | jq .)
+  ret=$?
+  set -e
+  if [ $ret -eq 0 ]
+  then
+      error_code=$(echo "$curl_output" | jq -r .error_code)
+      if [ "$error_code" != "null" ]
+      then
+          if [ "$error_code" != "40403" ]
+          then
+              message=$(echo "$curl_output" | jq -r .message)
+              logerror "Command failed with error code $error_code"
+              logerror "$message"
+              exit 1
+          fi
+      else
+          id=$(echo "$curl_output" | jq -r .id)
+          version=$(echo "$curl_output" | jq -r .version)
+
+          log "🚪 Skipping as schema already exists with id $id (version $version)"
+          exit 0
+      fi
+  else
+      logerror "❌ curl request failed with error code $ret!"
+      exit 1
+  fi
+
   log "⏺️ Registering schema to subject ${subject}"
   if [[ -n "$verbose" ]]
   then
@@ -10825,6 +10862,37 @@ playground_schema_register_command() {
       --header 'Content-Type: application/vnd.schemaregistry.v1+json' \
       --data "$json_new" | jq .
 
+  # # trying workaround
+
+  # log "Hard delete schema id 1"
+  # curl -X DELETE -H "Content-Type: application/json" http://localhost:8081/subjects/customer_avro-value/versions/1
+  # curl -X DELETE -H "Content-Type: application/json" http://localhost:8081/subjects/customer_avro-value/versions/1?permanent=true
+
+  # # https://docs.confluent.io/platform/6.2.4/schema-registry/develop/api.html#put--mode-(string-%20subject)
+  # log "Set the subject to IMPORT mode"
+  # curl --request PUT \
+  #   --url http://localhost:8081/mode/customer_avro-value \
+  #   --header 'Content-Type: application/vnd.schemaregistry.v1+json' \
+  #   --data '{
+  #     "mode": "IMPORT"
+  # }'
+
+  # log "Re-register schema with id 1 and removing "default": {}"
+  # escaped_json=$(jq -c -Rs '.' producer-repro-120245/src/main/resources/avro/customer-without-default.avsc)
+  # cat << EOF > /tmp/final.json
+  # {"schema":$escaped_json,"version": "1","id":"1"}
+  # EOF
+  # curl -X POST http://localhost:8081/subjects/customer_avro-value/versions \
+  # --header 'Content-Type: application/vnd.schemaregistry.v1+json' \
+  # --data @/tmp/final.json
+
+  # log "Set back the subject to READWRITE"
+  # curl --request PUT \
+  #   --url http://localhost:8081/mode/customer_avro-value \
+  #   --header 'Content-Type: application/vnd.schemaregistry.v1+json' \
+  #   --data '{
+  #     "mode": "READWRITE"
+  # }'
 }
 
 # :command.function
@@ -17432,6 +17500,14 @@ playground_schema_register_parse_requirements() {
           printf "%s\n" "--input requires an argument: --input INPUT" >&2
           exit 1
         fi
+        ;;
+
+      # :flag.case
+      --replace)
+
+        # :flag.case_no_arg
+        args['--replace']=1
+        shift
         ;;
 
       -?*)
