added --validate to playground connector create-or-update

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -4093,6 +4093,11 @@ playground_ccloud_connector_create_or_update_usage() {
     printf "    🔗 Connector name\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--validate")"
+    printf "    ✅ Validate config using PUT\n    https://api.confluent.cloud/connect/v1/environments/{environment_id}/clusters/{kafka_cluster_id}/connector-plugins/{plugin_name}/config/validate\n    (https://docs.confluent.io/cloud/current/api.html#tag/Managed-Connector-Plugins-(connectv1)/operation/validateConnectv1ConnectorPlugin)\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -4697,6 +4702,11 @@ playground_connector_create_or_update_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--package, -p PACKAGE")"
     printf "    Package name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--validate")"
+    printf "    ✅ Validate config using PUT /connector-plugins/(string:name)/config/validate\n    (https://docs.confluent.io/platform/current/connect/references/restapi.html#put--connector-plugins-(string-name)-config-validate)\n"
     echo
 
     # :command.usage_fixed_flags
@@ -15316,6 +15326,7 @@ playground_ccloud_connector_show_config_parameters_command() {
 playground_ccloud_connector_create_or_update_command() {
   # src/ccloud_connector_create_or_update_command.sh
   json=${args[json]}
+  validate=${args[--validate]}
 
   if [ "$json" = "-" ]
   then
@@ -15369,6 +15380,87 @@ playground_ccloud_connector_create_or_update_command() {
           is_create=0
       fi
   done
+
+  if [[ -n "$validate" ]]
+  then
+      log "✅ --validate is set"
+      set +e
+      connector_class=$(echo "$json_content" | jq -r '."connector.class"')
+      curl_output=$(curl $security -s -X PUT \
+          -H "Content-Type: application/json" \
+          -H "authorization: Basic $authorization" \
+          --data @$json_file \
+          https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connector-plugins/$connector_class/config/validate)
+
+      ret=$?
+      set -e
+      if [ $ret -eq 0 ]
+      then
+          if echo "$curl_output" | jq '. | has("error_code")' 2> /dev/null | grep -q true
+
+          then
+              error_code=$(echo "$curl_output" | jq -r .error_code)
+              message=$(echo "$curl_output" | jq -r .message)
+              logerror "Command failed with error code $error_code"
+              logerror "$message"
+              exit 1
+          else
+              if ! echo "$curl_output" | jq -e .  > /dev/null 2>&1
+              then
+                  set +e
+                  json_file=/tmp/json
+                  echo "$curl_output" > $json_file
+                  jq_output=$(jq . "$json_file" 2>&1)
+                  error_line=$(echo "$jq_output" | grep -oE 'parse error.*at line [0-9]+' | grep -oE '[0-9]+')
+
+                  if [[ -n "$error_line" ]]; then
+                      logerror "❌ Invalid JSON at line $error_line"
+                  fi
+                  set -e
+
+                  if [[ $(type -f bat 2>&1) =~ "not found" ]]
+                  then
+                      cat -n $json_file
+                  else
+                      bat $json_file --highlight-line $error_line
+                  fi
+
+                  exit 1
+              fi
+
+              is_valid=1
+              rows=()
+              for row in $(echo "$curl_output" | jq -r '.configs[] | @base64'); do
+                  _jq() {
+                      echo ${row} | base64 --decode | jq -r ${1}
+                  }
+
+                  name=$(_jq '.value.name')
+                  value=$(_jq '.value.value')
+                  errors=$(_jq '.value.errors')
+
+                  if [ "$(echo "$errors" | jq 'length')" -gt 0 ]
+                  then
+                      is_valid=0
+                      logerror "❌ validation error for config <$name=$value>"
+
+                      echo "$errors" | jq .
+                  fi
+              done
+
+              if [ $is_valid -eq 1 ]
+              then
+                  log "✅ connector config is valid !"
+
+              else
+                  exit 1
+              fi
+          fi
+      else
+          logerror "❌ curl request failed with error code $ret!"
+          exit 1
+      fi
+  fi
 
   if [ $is_create == 1 ]
   then
@@ -16023,7 +16115,7 @@ playground_connector_show_config_parameters_command() {
           set +e
           curl_output=$(curl $security -s -X PUT \
               -H "Content-Type: application/json" \
-              --data "$json_config" \
+              --data "$json_content" \
               $connect_url/connector-plugins/$connector_class/config/validate)
           ret=$?
           set -e
@@ -16215,6 +16307,7 @@ playground_connector_create_or_update_command() {
   json=${args[json]}
   level=${args[--level]}
   package=${args[--package]}
+  validate=${args[--validate]}
 
   if [ "$json" = "-" ]
   then
@@ -16267,6 +16360,87 @@ playground_connector_create_or_update_command() {
           is_create=0
       fi
   done
+
+  if [[ -n "$validate" ]]
+  then
+      log "✅ --validate is set"
+      set +e
+      connector_class=$(echo "$json_content" | jq -r '."connector.class"')
+      # add mandator name field
+      new_json_content=$(echo $json_content | jq '. + {"name": "validate_connector"}')
+      curl_output=$(curl $security -s -X PUT \
+          -H "Content-Type: application/json" \
+          --data "$new_json_content" \
+          $connect_url/connector-plugins/$connector_class/config/validate)
+      ret=$?
+      set -e
+      if [ $ret -eq 0 ]
+      then
+          if echo "$curl_output" | jq '. | has("error_code")' 2> /dev/null | grep -q true
+
+          then
+              error_code=$(echo "$curl_output" | jq -r .error_code)
+              message=$(echo "$curl_output" | jq -r .message)
+              logerror "Command failed with error code $error_code"
+              logerror "$message"
+              exit 1
+          else
+              if ! echo "$curl_output" | jq -e .  > /dev/null 2>&1
+              then
+                  set +e
+                  json_file=/tmp/json
+                  echo "$curl_output" > $json_file
+                  jq_output=$(jq . "$json_file" 2>&1)
+                  error_line=$(echo "$jq_output" | grep -oE 'parse error.*at line [0-9]+' | grep -oE '[0-9]+')
+
+                  if [[ -n "$error_line" ]]; then
+                      logerror "❌ Invalid JSON at line $error_line"
+                  fi
+                  set -e
+
+                  if [[ $(type -f bat 2>&1) =~ "not found" ]]
+                  then
+                      cat -n $json_file
+                  else
+                      bat $json_file --highlight-line $error_line
+                  fi
+
+                  exit 1
+              fi
+
+              is_valid=1
+              rows=()
+              for row in $(echo "$curl_output" | jq -r '.configs[] | @base64'); do
+                  _jq() {
+                      echo ${row} | base64 --decode | jq -r ${1}
+                  }
+
+                  name=$(_jq '.value.name')
+                  value=$(_jq '.value.value')
+                  errors=$(_jq '.value.errors')
+
+                  if [ "$(echo "$errors" | jq 'length')" -gt 0 ]
+                  then
+                      is_valid=0
+                      logerror "❌ validation error for config <$name=$value>"
+
+                      echo "$errors" | jq .
+                  fi
+              done
+
+              if [ $is_valid -eq 1 ]
+              then
+                  log "✅ connector config is valid !"
+
+              else
+                  exit 1
+              fi
+          fi
+      else
+          logerror "❌ curl request failed with error code $ret!"
+          exit 1
+      fi
+  fi
 
   if [ $is_create == 1 ]
   then
@@ -24193,6 +24367,14 @@ playground_ccloud_connector_create_or_update_parse_requirements() {
         fi
         ;;
 
+      # :flag.case
+      --validate)
+
+        # :flag.case_no_arg
+        args['--validate']=1
+        shift
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -25294,6 +25476,14 @@ playground_connector_create_or_update_parse_requirements() {
           printf "%s\n" "--package requires an argument: --package, -p PACKAGE" >&2
           exit 1
         fi
+        ;;
+
+      # :flag.case
+      --validate)
+
+        # :flag.case_no_arg
+        args['--validate']=1
+        shift
         ;;
 
       -?*)
