add more commands

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.0.rc1 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -50,6 +50,10 @@ playground_usage() {
   printf "  %s   👨‍💻 Tail and follow container logs.\n" "$(green "logs")                        "
   printf "  %s   🚀 SSH into container.\n" "$(green "ssh")                         "
   printf "  %s   🪄 Execute command in a container.\n" "$(green "exec")                        "
+  printf "  %s   ♻️ Restart a container.\n" "$(green "restart")                     "
+  printf "  %s   ⏸️ Pause a container.\n" "$(green "pause")                       "
+  printf "  %s   ⏯️ Resume a container.\n" "$(green "resume")                      "
+  printf "  %s   🔫 Kill a container.\n" "$(green "kill")                        "
   echo
   printf "%s\n" "$(bold "Topic Commands:")"
   printf "  %s   💯 Get number of records in a topic.\n" "$(green "get-number-records-topic")    "
@@ -661,6 +665,150 @@ playground_exec_usage() {
 }
 
 # :command.usage
+playground_restart_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground restart - ♻️ Restart a container.\n"
+    echo
+
+  else
+    printf "playground restart - ♻️ Restart a container.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  playground restart [OPTIONS]\n"
+  printf "  playground restart --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    Container name.\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_pause_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground pause - ⏸️ Pause a container.\n"
+    echo
+
+  else
+    printf "playground pause - ⏸️ Pause a container.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  playground pause [OPTIONS]\n"
+  printf "  playground pause --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    Container name.\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_resume_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground resume - ⏯️ Resume a container.\n"
+    echo
+
+  else
+    printf "playground resume - ⏯️ Resume a container.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  playground resume [OPTIONS]\n"
+  printf "  playground resume --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    Container name.\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_kill_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground kill - 🔫 Kill a container.\n"
+    echo
+
+  else
+    printf "playground kill - 🔫 Kill a container.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  playground kill [OPTIONS]\n"
+  printf "  playground kill --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    Container name.\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 playground_connector_usage() {
   if [[ -n $long_usage ]]; then
     printf "playground connector - 🔗 Connector commands.\n"
@@ -1022,8 +1170,8 @@ normalize_input() {
 }
 # :command.inspect_args
 inspect_args() {
-  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
   if ((${#args[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
     for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
   else
@@ -1038,6 +1186,14 @@ inspect_args() {
       echo "- \${other_args[$i]} = ${other_args[$i]}"
     done
   fi
+
+  if ((${#deps[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
+    echo
+    echo deps:
+    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+  fi
+
 }
 
 # :command.user_lib
@@ -5176,7 +5332,6 @@ playground_get_ip_address_container_command() {
 # :command.function
 playground_kill_all_containers_command() {
   # src/kill_all_containers_command.sh
-
   log "Kill all docker containers"
   docker rm -f $(docker ps -qa)
 }
@@ -5244,6 +5399,42 @@ playground_exec_command() {
     docker exec $container $shell -c "$command"
   fi
 
+}
+
+# :command.function
+playground_restart_command() {
+  # src/restart_command.sh
+  container="${args[--container]}"
+
+  log "Restarting docker container ${container}"
+  docker restart ${container}
+}
+
+# :command.function
+playground_pause_command() {
+  # src/pause_command.sh
+  container="${args[--container]}"
+
+  log "Pausing docker container ${container}"
+  docker pause ${container}
+}
+
+# :command.function
+playground_resume_command() {
+  # src/resume_command.sh
+  container="${args[--container]}"
+
+  log "Resuming docker container ${container}"
+  docker resume ${container}
+}
+
+# :command.function
+playground_kill_command() {
+  # src/kill_command.sh
+  container="${args[--container]}"
+
+  log "Killing docker container ${container}"
+  docker kill ${container}
 }
 
 # :command.function
@@ -5476,7 +5667,9 @@ parse_requirements() {
   done
 
   # :command.dependencies_filter
-  if ! command -v docker >/dev/null 2>&1; then
+  if command -v docker >/dev/null 2>&1; then
+    deps['docker']="$(command -v docker | head -n1)"
+  else
     printf "missing dependency: docker\n" >&2
     printf "%s\n" "👉 Check documentation https://tinyurl.com/4rpcmpjj" >&2
     exit 1
@@ -5579,6 +5772,34 @@ parse_requirements() {
       shift $#
       ;;
 
+    restart)
+      action="restart"
+      shift
+      playground_restart_parse_requirements "$@"
+      shift $#
+      ;;
+
+    pause)
+      action="pause"
+      shift
+      playground_pause_parse_requirements "$@"
+      shift $#
+      ;;
+
+    resume)
+      action="resume"
+      shift
+      playground_resume_parse_requirements "$@"
+      shift $#
+      ;;
+
+    kill)
+      action="kill"
+      shift
+      playground_kill_parse_requirements "$@"
+      shift $#
+      ;;
+
     connector)
       action="connector"
       shift
@@ -5647,6 +5868,8 @@ playground_get_connector_list_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="get-connector-list"
 
@@ -5690,6 +5913,8 @@ playground_get_topic_list_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="get-topic-list"
@@ -5738,6 +5963,8 @@ playground_bootstrap_reproduction_model_parse_requirements() {
   # :command.environment_variables_filter
   # :command.environment_variables_default
   export OUTPUT_FOLDER="${OUTPUT_FOLDER:-reproduction-models}"
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="bootstrap-reproduction-model"
@@ -5885,6 +6112,8 @@ playground_get_properties_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="get-properties"
 
@@ -5946,6 +6175,8 @@ playground_enable_remote_debugging_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="enable-remote-debugging"
 
@@ -6006,6 +6237,8 @@ playground_get_jmx_metrics_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="get-jmx-metrics"
@@ -6089,6 +6322,8 @@ playground_recreate_container_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="recreate-container"
 
@@ -6132,6 +6367,8 @@ playground_get_ip_address_container_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="get-ip-address-container"
@@ -6177,6 +6414,8 @@ playground_kill_all_containers_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="kill-all-containers"
 
@@ -6220,6 +6459,8 @@ playground_get_number_records_topic_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="get-number-records-topic"
@@ -6284,6 +6525,8 @@ playground_logs_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="logs"
@@ -6422,6 +6665,8 @@ playground_ssh_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="ssh"
 
@@ -6504,6 +6749,8 @@ playground_exec_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="exec"
@@ -6605,6 +6852,258 @@ playground_exec_parse_requirements() {
 }
 
 # :command.parse_requirements
+playground_restart_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_restart_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+
+  # :command.command_filter
+  action="restart"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+}
+
+# :command.parse_requirements
+playground_pause_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_pause_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+
+  # :command.command_filter
+  action="pause"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+}
+
+# :command.parse_requirements
+playground_resume_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_resume_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+
+  # :command.command_filter
+  action="resume"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+}
+
+# :command.parse_requirements
+playground_kill_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_kill_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+
+  # :command.command_filter
+  action="kill"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+}
+
+# :command.parse_requirements
 playground_connector_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -6621,6 +7120,8 @@ playground_connector_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -6717,6 +7218,8 @@ playground_connector_status_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector status"
 
@@ -6768,6 +7271,8 @@ playground_connector_plugins_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector plugins"
 
@@ -6811,6 +7316,8 @@ playground_connector_pause_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="connector pause"
@@ -6876,6 +7383,8 @@ playground_connector_resume_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector resume"
 
@@ -6940,6 +7449,8 @@ playground_connector_delete_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector delete"
 
@@ -7003,6 +7514,8 @@ playground_connect_log_level_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -7078,6 +7591,8 @@ playground_connect_log_level_get_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connect-log-level get"
 
@@ -7140,6 +7655,8 @@ playground_connect_log_level_set_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="connect-log-level set"
@@ -7230,6 +7747,7 @@ initialize() {
 # :command.run
 run() {
   declare -A args=()
+  declare -A deps=()
   declare -a other_args=()
   declare -a input=()
   normalize_input "$@"
@@ -7350,6 +7868,42 @@ run() {
         playground_exec_usage
       else
         playground_exec_command
+      fi
+      ;;
+
+    "restart")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        playground_restart_usage
+      else
+        playground_restart_command
+      fi
+      ;;
+
+    "pause")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        playground_pause_usage
+      else
+        playground_pause_command
+      fi
+      ;;
+
+    "resume")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        playground_resume_usage
+      else
+        playground_resume_command
+      fi
+      ;;
+
+    "kill")
+      if [[ ${args['--help']:-} ]]; then
+        long_usage=yes
+        playground_kill_usage
+      else
+        playground_kill_command
       fi
       ;;
 
