handle xstreams

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.3.1 (https://bashly.dev)
+# This script was generated by bashly 1.3.3 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -21941,6 +21941,37 @@ playground_container_recreate_command() {
   bash /tmp/playground-command
 
   wait_container_ready
+
+  test_file=$(playground state get run.test_file)
+
+  if [ ! -f $test_file ]
+  then
+
+      logerror "File $test_file retrieved from $root_folder/playground.ini does not exist!"
+      exit 1
+  fi
+
+  if [[ "${test_file}" == *"xstream"* ]]
+  then
+      log "💫 xstream test detected, re-installing libraries..."
+      # https://github.com/confluentinc/common-docker/pull/743 and https://github.com/adoptium/adoptium-support/issues/1285
+      set +e
+      playground container exec --root --command "sed -i "s/packages\.adoptium\.net/adoptium\.jfrog\.io/g" /etc/yum.repos.d/adoptium.repo"
+      playground container exec --root --command "microdnf -y install libaio"
+
+      if [ "$(uname -m)" = "arm64" ]
+      then
+          :
+      else
+          if version_gt $TAG_BASE "7.9.9"
+          then
+              playground container exec --root --command "microdnf -y install libnsl2"
+              playground container exec --root --command "ln -s /usr/lib64/libnsl.so.3 /usr/lib64/libnsl.so.1"
+          else
+              playground container exec --root --command "ln -s /usr/lib64/libnsl.so.2 /usr/lib64/libnsl.so.1"
+          fi
+      fi
+  fi
 }
 
 # :command.function
@@ -22269,6 +22300,37 @@ EOF
       bash $tmp_dir/playground-command
   fi
   wait_container_ready
+
+  test_file=$(playground state get run.test_file)
+
+  if [ ! -f $test_file ]
+  then
+
+      logerror "File $test_file retrieved from $root_folder/playground.ini does not exist!"
+      exit 1
+  fi
+
+  if [[ "${test_file}" == *"xstream"* ]]
+  then
+      log "💫 xstream test detected, re-installing libraries..."
+      # https://github.com/confluentinc/common-docker/pull/743 and https://github.com/adoptium/adoptium-support/issues/1285
+      set +e
+      playground container exec --root --command "sed -i "s/packages\.adoptium\.net/adoptium\.jfrog\.io/g" /etc/yum.repos.d/adoptium.repo"
+      playground container exec --root --command "microdnf -y install libaio"
+
+      if [ "$(uname -m)" = "arm64" ]
+      then
+          :
+      else
+          if version_gt $TAG_BASE "7.9.9"
+          then
+              playground container exec --root --command "microdnf -y install libnsl2"
+              playground container exec --root --command "ln -s /usr/lib64/libnsl.so.3 /usr/lib64/libnsl.so.1"
+          else
+              playground container exec --root --command "ln -s /usr/lib64/libnsl.so.2 /usr/lib64/libnsl.so.1"
+          fi
+      fi
+  fi
 }
 
 # :command.function
@@ -32593,10 +32655,12 @@ playground_config_editor_parse_requirements() {
 
   # :command.validations
   # :argument.validations
-  validation_output="$(validate_editor_exists "${args['editor']:-}")"
-  if [[ -v args['editor'] && -n "$validation_output" ]]; then
-    printf "validation error in %s:\n%s\n" "EDITOR" "$validation_output" >&2
-    exit 1
+  if [[ -v args['editor'] ]]; then
+    validation_output="$(validate_editor_exists "${args['editor']:-}")"
+    if [[ -n "$validation_output" ]]; then
+      printf "validation error in %s:\n%s\n" "EDITOR" "$validation_output" >&2
+      exit 1
+    fi
   fi
 
 }
