Add playground connector update-version #4477

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.0 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -130,6 +130,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   🧰 Show current connector config\n" "$(green "connector show-config")                  "
   [[ -n $long_usage ]] && printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "connector show-config-parameters")       "
   [[ -n $long_usage ]] && printf "  %s   🧬 Set connect log level\n" "$(green "connector log-level")                    "
+  [[ -n $long_usage ]] && printf "  %s   ✨ Update currently running connector(s) with new version \n" "$(green "connector update-version")               "
   [[ -n $long_usage ]] && printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "connector create-or-update")             "
   echo
 
@@ -3815,6 +3816,9 @@ playground_connector_usage() {
   printf "  %s   🧬 Set connect log level\n" "$(green "log-level")             "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")      "
   echo
+  printf "%s\n" "$(bold "Run commands:")"
+  printf "  %s   ✨ Update currently running connector(s) with new version \n" "$(green "update-version")        "
+  echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
@@ -4221,6 +4225,51 @@ playground_connector_log_level_usage() {
     printf "  %s\n" "$(magenta "--level, -l LEVEL (required)")"
     printf "    ❕Log level\n"
     printf "    Allowed: INFO, WARN, DEBUG, TRACE\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_update_version_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector update-version - ✨ Update currently running connector(s) with new version \n"
+    echo
+
+  else
+    printf "playground connector update-version - ✨ Update currently running connector(s) with new version \n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector update-version [OPTIONS]\n"
+  printf "  playground connector update-version --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector-tag CONNECTOR_TAG")"
+    printf "    🔗 Connector version to use\n    \n    By default, for each connector, the latest available version on Confluent\n    Hub is used\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector-zip CONNECTOR_ZIP")"
+    printf "    🤐 Connector zip to use\n    \n    ❕ It must be absolute full path\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion \n            use folder_zip_or_jar (default: ~/Downloads) in config.ini file to\n    configure where to search the files (current folder is always used)\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector-jar CONNECTOR_JAR")"
+    printf "    ♨️ Connector jar to use\n    \n    ❕ It must be absolute full path\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion \n            use folder_zip_or_jar (default: ~/Downloads) in config.ini file to\n    configure where to search the files (current folder is always used)\n"
     echo
 
     # :command.usage_fixed_flags
@@ -5349,6 +5398,10 @@ function verify_installed()
 
 function maybe_create_image()
 {
+  if [ ! -z "$DOCKER_COMPOSE_FILE_UPDATE_VERSION" ]
+  then
+    return
+  fi
   set +e
   log "🧰 Checking if Docker image ${CP_CONNECT_IMAGE}:${CONNECT_TAG} contains additional tools"
   log "🧰 it can take a while if image is downloaded for the first time"
@@ -8822,7 +8875,6 @@ playground_run_command() {
   connector_tag="${args[--connector-tag]}"
   connector_zip="${args[--connector-zip]}"
   connector_jar="${args[--connector-jar]}"
-  connector_jar="${args[--connector-jar]}"
   enable_ksqldb="${args[--enable-ksqldb]}"
   enable_c3="${args[--enable-control-center]}"
   enable_conduktor="${args[--enable-conduktor]}"
@@ -9041,7 +9093,6 @@ playground_re_run_command() {
   connector_tag="${args[--connector-tag]}"
   connector_zip="${args[--connector-zip]}"
   connector_jar="${args[--connector-jar]}"
-  connector_jar="${args[--connector-jar]}"
   enable_ksqldb="${args[--enable-ksqldb]}"
   enable_c3="${args[--enable-control-center]}"
   enable_conduktor="${args[--enable-conduktor]}"
@@ -9177,7 +9228,6 @@ playground_run_ccloud_command() {
   tag="${args[--tag]}"
   connector_tag="${args[--connector-tag]}"
   connector_zip="${args[--connector-zip]}"
-  connector_jar="${args[--connector-jar]}"
   connector_jar="${args[--connector-jar]}"
   enable_c3="${args[--enable-control-center]}"
   enable_conduktor="${args[--enable-conduktor]}"
@@ -9705,7 +9755,6 @@ playground_repro_bootstrap_command() {
   tag="${args[--tag]}"
   connector_tag="${args[--connector-tag]}"
   connector_zip="${args[--connector-zip]}"
-  connector_jar="${args[--connector-jar]}"
   connector_jar="${args[--connector-jar]}"
   enable_ksqldb="${args[--enable-ksqldb]}"
   enable_c3="${args[--enable-control-center]}"
@@ -14768,6 +14817,81 @@ playground_connector_log_level_command() {
       # log "🧬 Set log level for connector $connector to $level"
       playground debug log-level set -p "$package" -l $level
   done
+}
+
+# :command.function
+playground_connector_update_version_command() {
+  # src/connector_update_version_command.sh
+  DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+
+  root_folder=${DIR_CLI}/../..
+
+  connector_tag="${args[--connector-tag]}"
+  connector_zip="${args[--connector-zip]}"
+  connector_jar="${args[--connector-jar]}"
+
+  if [[ -n "$connector_tag" ]]
+  then
+    export CONNECTOR_TAG=$connector_tag
+  fi
+
+  if [[ -n "$connector_zip" ]]
+  then
+    if [[ $connector_zip == *"@"* ]]
+    then
+      connector_zip=$(echo "$connector_zip" | cut -d "@" -f 2)
+    fi
+    export CONNECTOR_ZIP=$connector_zip
+  fi
+
+  if [[ -n "$connector_jar" ]]
+  then
+    if [[ $connector_jar == *"@"* ]]
+    then
+      connector_jar=$(echo "$connector_jar" | cut -d "@" -f 2)
+    fi
+    export CONNECTOR_JAR=$connector_jar
+  fi
+
+  if [ ! -f /tmp/playground-run ]
+  then
+    logerror "File containing run command /tmp/playground-run does not exist!"
+    logerror "Make sure to use <playground run> command !"
+    exit 1
+  fi
+
+  test_file=$(cat /tmp/playground-run | awk '{ print $4}')
+
+  if [ ! -f $test_file ]
+  then
+
+    logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
+    logerror "Make sure to use <playground run> command !"
+    exit 1
+  fi
+
+  # determining the docker-compose file from from test_file
+  docker_compose_file=$(grep "environment" "$test_file" | grep DIR | grep start.sh | cut -d "/" -f 7 | cut -d '"' -f 1 | tail -n1 | xargs)
+  test_file_directory="$(dirname "${test_file}")"
+  docker_compose_file="${test_file_directory}/${docker_compose_file}"
+
+  if [ "${docker_compose_file}" != "" ] && [ ! -f "${docker_compose_file}" ]
+  then
+      logwarn "Skipping as docker-compose override file could not be detemined"
+      exit 0
+  fi
+
+  filename=$(basename -- "$test_file")
+  test_file_directory="$(dirname "${test_file}")"
+  cd ${test_file_directory}
+
+  export DOCKER_COMPOSE_FILE_UPDATE_VERSION="$docker_compose_file"
+
+  log "✨ Loading new version(s)"
+  source ${DIR_CLI}/../../scripts/utils.sh
+
+  log "🎯 Now restarting connect to use new version(s)"
+  playground container restart --container connect
 }
 
 # :command.function
@@ -22187,6 +22311,13 @@ playground_connector_parse_requirements() {
       shift $#
       ;;
 
+    update-version)
+      action="update-version"
+      shift
+      playground_connector_update_version_parse_requirements "$@"
+      shift $#
+      ;;
+
     create-or-update)
       action="create-or-update"
       shift
@@ -22905,6 +23036,114 @@ playground_connector_log_level_parse_requirements() {
 }
 
 # :command.parse_requirements
+playground_connector_update_version_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_update_version_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector update-version"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connector-tag)
+        # :flag.conflicts
+        if [[ -n "${args['--connector-zip']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--connector-zip" >&2
+          exit 1
+        fi
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--connector-tag']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector-tag requires an argument: --connector-tag CONNECTOR_TAG" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --connector-zip)
+        # :flag.conflicts
+        if [[ -n "${args['--connector-tag']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--connector-tag" >&2
+          exit 1
+        fi
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_file_exists_with_trick "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--connector-zip CONNECTOR_ZIP" "$(validate_file_exists_with_trick "$2")" >&2
+            exit 1
+          fi
+
+          args['--connector-zip']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector-zip requires an argument: --connector-zip CONNECTOR_ZIP" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --connector-jar)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_file_exists_with_trick "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--connector-jar CONNECTOR_JAR" "$(validate_file_exists_with_trick "$2")" >&2
+            exit 1
+          fi
+
+          args['--connector-jar']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector-jar requires an argument: --connector-jar CONNECTOR_JAR" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 playground_connector_create_or_update_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -23140,6 +23379,7 @@ run() {
     "connector show-config") playground_connector_show_config_command ;;
     "connector show-config-parameters") playground_connector_show_config_parameters_command ;;
     "connector log-level") playground_connector_log_level_command ;;
+    "connector update-version") playground_connector_update_version_command ;;
     "connector create-or-update") playground_connector_create_or_update_command ;;
   esac
 }
