added ccloud-connector show-lag

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -84,6 +84,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   ⏸️  Pause connector\n" "$(green "ccloud-connector pause")            "
   [[ -n $long_usage ]] && printf "  %s   ⏯️  Resume connector\n" "$(green "ccloud-connector resume")           "
   [[ -n $long_usage ]] && printf "  %s   🗑️  Delete connector\n" "$(green "ccloud-connector delete")           "
+  [[ -n $long_usage ]] && printf "  %s   🐢 Show lag of sink connector\n" "$(green "ccloud-connector show-lag")         "
   [[ -n $long_usage ]] && printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "ccloud-connector create-or-update") "
   printf "  %s   🔗 Connector commands\n" "$(green "connector")                         "
   [[ -n $long_usage ]] && printf "  %s   🧩 Show status of all connectors\n" "$(green "connector status")                  "
@@ -2064,6 +2065,7 @@ playground_ccloud_connector_usage() {
   printf "  %s   ⏸️  Pause connector\n" "$(green "pause")           "
   printf "  %s   ⏯️  Resume connector\n" "$(green "resume")          "
   printf "  %s   🗑️  Delete connector\n" "$(green "delete")          "
+  printf "  %s   🐢 Show lag of sink connector\n" "$(green "show-lag")        "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")"
   echo
 
@@ -2256,6 +2258,41 @@ playground_ccloud_connector_delete_usage() {
 }
 
 # :command.usage
+playground_ccloud_connector_show_lag_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground ccloud-connector show-lag - 🐢 Show lag of sink connector\n"
+    echo
+
+  else
+    printf "playground ccloud-connector show-lag - 🐢 Show lag of sink connector\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ccloud-connector show-lag [OPTIONS]\n"
+  printf "  playground ccloud-connector show-lag --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector, -c CONNECTOR")"
+    printf "    🔗 Connector name\n    \n    🎓 Tip: If not specified, the command will apply to all connectors\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 playground_ccloud_connector_create_or_update_usage() {
   if [[ -n $long_usage ]]; then
     printf "playground ccloud-connector create-or-update - 🧑‍🎨  Create or update connector\n"
@@ -2298,7 +2335,7 @@ playground_ccloud_connector_create_or_update_usage() {
 
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
-    printf "  playground ccloud-connector create-or-update -c filestream-sink << EOF\n  {\n      \"tasks.max\": \"1\",\n      \"connector.class\":\n  \"org.apache.kafka.connect.file.FileStreamSinkConnector\",\n      \"topics\": \"filestream\",\n      \"file\": \"/tmp/output.json\",\n      \"key.converter\": \"org.apache.kafka.connect.storage.StringConverter\",\n      \"value.converter\": \"org.apache.kafka.connect.json.JsonConverter\",\n      \"value.converter.schemas.enable\": \"false\"\n  }\n  EOF\n"
+    printf "  playground ccloud-connector create-or-update --connector HttpSink << EOF\n  {\n      \"connector.class\": \"HttpSink\",\n      \"name\": \"HttpSink\",\n      \"kafka.auth.mode\": \"KAFKA_API_KEY\",\n      \"kafka.api.key\": \"$CLOUD_KEY\",\n      \"kafka.api.secret\": \"$CLOUD_SECRET\",\n      \"topics\": \"http-topic\",\n      \"input.data.format\": \"AVRO\",\n      \"http.api.url\": \"http://httpstat.us/200/\",\n      \"behavior.on.error\": \"fail\",\n      \"tasks.max\" : \"1\"\n  }\n  EOF\n"
     echo
 
   fi
@@ -9672,6 +9709,66 @@ playground_ccloud_connector_delete_command() {
 }
 
 # :command.function
+playground_ccloud_connector_show_lag_command() {
+  # src/ccloud_connector_show_lag_command.sh
+  ret=$(get_ccloud_connect)
+
+  environment=$(echo "$ret" | cut -d "@" -f 1)
+  cluster=$(echo "$ret" | cut -d "@" -f 2)
+  authorization=$(echo "$ret" | cut -d "@" -f 3)
+
+  connector="${args[--connector]}"
+
+  if [[ ! -n "$connector" ]]
+  then
+      log "✨ --connector flag was not provided, applying command to all ccloud connectors"
+      connector=$(playground get-ccloud-connector-list)
+      if [ "$connector" == "" ]
+      then
+          logerror "💤 No ccloud connector is running !"
+          exit 1
+      fi
+  fi
+
+  if [ -f /tmp/delta_configs/env.delta ]
+  then
+      source /tmp/delta_configs/env.delta
+  else
+      logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
+      exit 1
+  fi
+  if [ ! -f /tmp/delta_configs/ak-tools-ccloud.delta ]
+  then
+      logerror "ERROR: /tmp/delta_configs/ak-tools-ccloud.delta has not been generated"
+      exit 1
+  fi
+
+  DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+  dir1=$(echo ${DIR_CLI%/*})
+  root_folder=$(echo ${dir1%/*})
+  IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
+  source $root_folder/scripts/utils.sh
+
+  items=($connector)
+  for connector in ${items[@]}
+  do
+      type=$(curl -s --request GET "https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector?expand=status" --header "authorization: Basic $authorization" | jq -r '.type')
+      if [ "$type" != "sink" ]
+      then
+          logwarn "⏭️ Skipping $type connector $connector, it must be a sink to show the lag"
+          continue
+
+      fi
+      connectorId=$(get_ccloud_connector_lcc $connector)
+
+      log "🐢 Show lag for sink connector $connector ($connectorId)"
+      #docker exec $container kafka-consumer-groups --bootstrap-server broker:9092 --group connect-$connector --describe $security
+      docker run --rm -v /tmp/delta_configs/ak-tools-ccloud.delta:/tmp/configuration/ccloud.properties -e BOOTSTRAP_SERVERS="$BOOTSTRAP_SERVERS" -e SASL_JAAS_CONFIG="$SASL_JAAS_CONFIG" ${CP_CONNECT_IMAGE}:${CONNECT_TAG} kafka-consumer-groups --bootstrap-server $BOOTSTRAP_SERVERS --command-config /tmp/configuration/ccloud.properties --group connect-$connectorId --describe
+  done
+
+}
+
+# :command.function
 playground_ccloud_connector_create_or_update_command() {
   # src/ccloud_connector_create_or_update_command.sh
   json=${args[json]}
@@ -14291,6 +14388,13 @@ playground_ccloud_connector_parse_requirements() {
       shift $#
       ;;
 
+    show-lag)
+      action="show-lag"
+      shift
+      playground_ccloud_connector_show_lag_parse_requirements "$@"
+      shift $#
+      ;;
+
     create-or-update)
       action="create-or-update"
       shift
@@ -14565,6 +14669,64 @@ playground_ccloud_connector_delete_parse_requirements() {
 
   # :command.command_filter
   action="ccloud-connector delete"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connector | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--connector']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector requires an argument: --connector, -c CONNECTOR" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_ccloud_connector_show_lag_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ccloud_connector_show_lag_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="ccloud-connector show-lag"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -15464,6 +15626,7 @@ run() {
     "ccloud-connector pause") playground_ccloud_connector_pause_command ;;
     "ccloud-connector resume") playground_ccloud_connector_resume_command ;;
     "ccloud-connector delete") playground_ccloud_connector_delete_command ;;
+    "ccloud-connector show-lag") playground_ccloud_connector_show_lag_command ;;
     "ccloud-connector create-or-update") playground_ccloud_connector_create_or_update_command ;;
     "connector") playground_connector_command ;;
     "connector status") playground_connector_status_command ;;
