added topic set-schema-compatibility command

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -74,6 +74,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "topic display-consumer-offsets")"
   [[ -n $long_usage ]] && printf "  %s   🔬 Describe topic\n" "$(green "topic describe")                "
   [[ -n $long_usage ]] && printf "  %s   📥 Consume topic from beginning\n" "$(green "topic consume")                 "
+  [[ -n $long_usage ]] && printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "topic set-schema-compatibility")"
   echo
   printf "%s\n" "$(bold "Connector commands:")"
   printf "  %s   🔗 Connector commands\n" "$(green "connector")                     "
@@ -1723,6 +1724,7 @@ playground_topic_usage() {
   printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "display-consumer-offsets")"
   printf "  %s   🔬 Describe topic\n" "$(green "describe")                "
   printf "  %s   📥 Consume topic from beginning\n" "$(green "consume")                 "
+  printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "set-schema-compatibility")"
   echo
 
   # :command.long_usage
@@ -1873,6 +1875,47 @@ playground_topic_consume_usage() {
     printf "  %s\n" "$(magenta "--max-messages MAX-MESSAGES")"
     printf "    Max number of messages to consume\n"
     printf "    Default: \n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_topic_set_schema_compatibility_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground topic set-schema-compatibility - 🛡️ Change topic's schema compatibility\n"
+    echo
+
+  else
+    printf "playground topic set-schema-compatibility - 🛡️ Change topic's schema compatibility\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground topic set-schema-compatibility [OPTIONS]\n"
+  printf "  playground topic set-schema-compatibility --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--topic, -t TOPIC (required)")"
+    printf "    🗳 Topic name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--compatibility COMPATIBILITY (required)")"
+    printf "    Schema Registry compatibility rule\n"
+    printf "    Allowed: BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE\n"
     echo
 
     # :command.usage_fixed_flags
@@ -8616,6 +8659,30 @@ playground_topic_consume_command() {
 }
 
 # :command.function
+playground_topic_set_schema_compatibility_command() {
+  # src/topic_set_schema_compatibility_command.sh
+  topic="${args[--topic]}"
+  compatibility="${args[--compatibility]}"
+
+  environment=`get_environment_used`
+
+  if [ "$environment" == "error" ]
+  then
+    logerror "File containing restart command /tmp/playground-command does not exist!"
+    exit 1
+
+  fi
+
+  ret=$(get_sr_url_and_security)
+
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
+
+  log "🛡️ Set compatibility for subject ${topic}-value to $compatibility"
+  curl $sr_security -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data "{\"compatibility\": \"$compatibility\"}" "${sr_url}/config/${topic}-value"
+}
+
+# :command.function
 playground_connector_status_command() {
   # src/connector_status_command.sh
   ret=$(get_connect_url_and_security)
@@ -12303,6 +12370,13 @@ playground_topic_parse_requirements() {
       shift $#
       ;;
 
+    set-schema-compatibility)
+      action="set-schema-compatibility"
+      shift
+      playground_topic_set_schema_compatibility_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_topic_usage >&2
@@ -12602,6 +12676,102 @@ playground_topic_consume_parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['--max-messages']:-} ]] || args['--max-messages']=""
+
+  # :command.user_filter
+  filter_error=$(filter_schema_registry_running)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_topic_set_schema_compatibility_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_topic_set_schema_compatibility_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="topic set-schema-compatibility"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --topic | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--topic']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--topic requires an argument: --topic, -t TOPIC" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --compatibility)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--compatibility']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--compatibility requires an argument: --compatibility COMPATIBILITY" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--topic']+x} ]]; then
+    printf "missing required flag: --topic, -t TOPIC\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['--compatibility']+x} ]]; then
+    printf "missing required flag: --compatibility COMPATIBILITY\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ ${args['--compatibility']} ]] && [[ ! ${args['--compatibility']} =~ ^(BACKWARD|BACKWARD_TRANSITIVE|FORWARD|FORWARD_TRANSITIVE|FULL|FULL_TRANSITIVE|NONE)$ ]]; then
+    printf "%s\n" "--compatibility must be one of: BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE" >&2
+    exit 1
+  fi
 
   # :command.user_filter
   filter_error=$(filter_schema_registry_running)
@@ -13325,6 +13495,7 @@ run() {
     "topic display-consumer-offsets") playground_topic_display_consumer_offsets_command ;;
     "topic describe") playground_topic_describe_command ;;
     "topic consume") playground_topic_consume_command ;;
+    "topic set-schema-compatibility") playground_topic_set_schema_compatibility_command ;;
     "connector") playground_connector_command ;;
     "connector status") playground_connector_status_command ;;
     "connector plugins") playground_connector_plugins_command ;;
