Unify playground connector and playground fully-managed-connector #4947

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -18887,6 +18887,13 @@ playground_connector_versions_command() {
   # src/commands/connector/versions.sh
   test_file=$(playground state get run.test_file)
 
+  connector_type=$(playground state get run.connector_type)
+  if [ "$connector_type" == "$CONNECTOR_TYPE_FULLY_MANAGED" ] || [ "$connector_type" == "$CONNECTOR_TYPE_CUSTOM" ]
+  then
+      logerror "❌ versions command is not available with $connector_type connector"
+      exit 1
+  fi
+
   if [ ! -f $test_file ]
   then
 
@@ -18911,9 +18918,9 @@ playground_connector_versions_command() {
 
           if [ "$owner" == "java" ] || [ "$name" == "hub-components" ] || [ "$owner" == "filestream" ]
           then
-          # happens when plugin is not coming from confluent hub
-          logwarn "skipping as plugin $owner/$name does not appear to be coming from confluent hub"
-          continue
+              # happens when plugin is not coming from confluent hub
+              logwarn "skipping as plugin $owner/$name does not appear to be coming from confluent hub"
+              continue
           fi
 
           playground connector-plugin versions --connector-plugin $owner/$name --last 10
@@ -19015,20 +19022,14 @@ playground_connector_restart_command() {
 # :command.function
 playground_connector_stop_command() {
   # src/commands/connector/stop.sh
-  get_connect_url_and_security
-
   connector="${args[--connector]}"
   verbose="${args[--verbose]}"
 
-  tag=$(docker ps --format '{{.Image}}' | egrep 'confluentinc/cp-.*-connect-base:' | awk -F':' '{print $2}')
-  if [ $? != 0 ] || [ "$tag" == "" ]
-  then
-      logerror "Could not find current CP version from docker ps"
-      exit 1
-  fi
+  connector_type=$(playground state get run.connector_type)
 
-  if ! version_gt $tag "7.4.99"; then
-      logerror "❌ stop connector is available since CP 7.5 only"
+  if [ "$connector_type" == "$CONNECTOR_TYPE_FULLY_MANAGED" ] || [ "$connector_type" == "$CONNECTOR_TYPE_CUSTOM" ]
+  then
+      logerror "❌ stop command is not available with $connector_type connector"
       exit 1
   fi
 
@@ -19037,9 +19038,21 @@ playground_connector_stop_command() {
       connector=$(playground get-connector-list)
       if [ "$connector" == "" ]
       then
-          logerror "💤 No connector is running !"
+          logerror "💤 No $connector_type connector is running !"
           exit 1
       fi
+  fi
+
+  tag=$(docker ps --format '{{.Image}}' | egrep 'confluentinc/cp-.*-connect-base:' | awk -F':' '{print $2}')
+  if [ $? != 0 ] || [ "$tag" == "" ]
+  then
+      logerror "❌ could not find current CP version from docker ps"
+      exit 1
+  fi
+
+  if ! version_gt $tag "7.4.99"; then
+      logerror "❌ stop connector is available since CP 7.5 only"
+      exit 1
   fi
 
   items=($connector)
@@ -19050,13 +19063,11 @@ playground_connector_stop_command() {
   fi
   for connector in ${items[@]}
   do
-      log "🛑 Stopping connector $connector"
-      if [[ -n "$verbose" ]]
-      then
-          log "🐞 curl command used"
-          echo "curl $security -s -X PUT -H "Content-Type: application/json" "$connect_url/connectors/$connector/stop""
-      fi
-      curl $security -s -X PUT -H "Content-Type: application/json" "$connect_url/connectors/$connector/stop" | jq .
+      log "🛑 Stopping $connector_type connector $connector"
+      get_connect_url_and_security
+      handle_onprem_connect_rest_api "curl $security -s -X PUT -H \"Content-Type: application/json\" \"$connect_url/connectors/$connector/stop\""
+
+      echo "$curl_output" | jq .
 
       sleep 1
       playground connector status --connector $connector
@@ -19155,19 +19166,39 @@ playground_connector_show_lag_command() {
   verbose="${args[--verbose]}"
   waitforzerolaginterval="${args[--wait-for-zero-lag-interval]}"
 
-  get_connect_url_and_security
+  connector_type=$(playground state get run.connector_type)
 
   if [[ ! -n "$connector" ]]
   then
       connector=$(playground get-connector-list)
       if [ "$connector" == "" ]
       then
-          logerror "💤 No connector is running !"
+          logerror "💤 No $connector_type connector is running !"
           exit 1
       fi
   fi
 
-  get_security_broker "--command-config"
+  if [ "$connector_type" == "$CONNECTOR_TYPE_FULLY_MANAGED" ] || [ "$connector_type" == "$CONNECTOR_TYPE_CUSTOM" ]
+  then
+    get_ccloud_connect
+    get_kafka_docker_playground_dir
+    DELTA_CONFIGS_ENV=$KAFKA_DOCKER_PLAYGROUND_DIR/.ccloud/env.delta
+
+    if [ -f $DELTA_CONFIGS_ENV ]
+    then
+        source $DELTA_CONFIGS_ENV
+    else
+        logerror "ERROR: $DELTA_CONFIGS_ENV has not been generated"
+        exit 1
+    fi
+    if [ ! -f $KAFKA_DOCKER_PLAYGROUND_DIR/.ccloud/ak-tools-ccloud.delta ]
+    then
+        logerror "ERROR: $KAFKA_DOCKER_PLAYGROUND_DIR/.ccloud/ak-tools-ccloud.delta has not been generated"
+        exit 1
+    fi
+  else
+    get_security_broker "--command-config"
+  fi
 
   declare -A prev_lags
   prev_lags=()
@@ -19292,10 +19323,19 @@ playground_connector_show_lag_command() {
   fi
   for connector in ${items[@]}
   do
-    type=$(curl -s $security "$connect_url/connectors/$connector/status" | jq -r '.type')
+    if [ "$connector_type" == "$CONNECTOR_TYPE_FULLY_MANAGED" ] || [ "$connector_type" == "$CONNECTOR_TYPE_CUSTOM" ]
+    then
+        get_ccloud_connect
+        handle_ccloud_connect_rest_api "curl -s --request GET \"https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector/config\" --header \"authorization: Basic $authorization\""
+    else
+        get_connect_url_and_security
+        handle_onprem_connect_rest_api "curl -s $security \"$connect_url/connectors/$connector/status\""
+    fi
+
+    type=$(echo "$json_content" | jq -r '.type')
     if [ "$type" != "sink" ]
     then
-      logwarn "⏭️ Skipping $type connector $connector, it must be a sink to show the lag"
+      logwarn "⏭️ Skipping $type $connector_type connector $connector, it must be a sink to show the lag"
       continue
 
     fi
@@ -19312,11 +19352,16 @@ playground_connector_show_lag_command() {
 
     while [ $stop != 1 ]
     do
-      docker exec $container kafka-consumer-groups --bootstrap-server broker:9092 --group connect-$connector --describe $security | grep -v PARTITION | sed '/^$/d' &> $lag_output
+      if [ "$connector_type" == "$CONNECTOR_TYPE_FULLY_MANAGED" ] || [ "$connector_type" == "$CONNECTOR_TYPE_CUSTOM" ]
+      then
+        docker run --rm -v $KAFKA_DOCKER_PLAYGROUND_DIR/.ccloud/ak-tools-ccloud.delta:/tmp/configuration/ccloud.properties -e BOOTSTRAP_SERVERS="$BOOTSTRAP_SERVERS" -e SASL_JAAS_CONFIG="$SASL_JAAS_CONFIG" ${CP_CONNECT_IMAGE}:${CONNECT_TAG} kafka-consumer-groups --bootstrap-server $BOOTSTRAP_SERVERS --command-config /tmp/configuration/ccloud.properties --group connect-$connectorId --describe | grep -v PARTITION | sed '/^$/d' &> $lag_output
+      else
+        docker exec $container kafka-consumer-groups --bootstrap-server broker:9092 --group connect-$connector --describe $security | grep -v PARTITION | sed '/^$/d' &> $lag_output
+      fi
 
       if grep -q "Warning" $lag_output
       then
-        logwarn "🐢 consumer group for connector $connector is rebalancing"
+        logwarn "🐢 consumer group for $connector_type connector $connector is rebalancing"
         cat $lag_output
         sleep $waitforzerolaginterval
         continue
@@ -19327,7 +19372,7 @@ playground_connector_show_lag_command() {
 
       if [ ! -z "$lag_not_set" ]
       then
-        logwarn "🐢 consumer lag for connector $connector is not available"
+        logwarn "🐢 consumer lag for $connector_type connector $connector is not available"
         show_output
         if [[ ! -n "$wait_for_zero_lag" ]]
         then
@@ -19365,17 +19410,17 @@ playground_connector_show_lag_command() {
             then
               case "${compare_action}" in
                 up)
-                  log_up "🔥 total consumer lag for connector $connector has increased to $total_lag $compare (press ctrl-c to stop)"
+                  log_up "🔥 total consumer lag for $connector_type connector $connector has increased to $total_lag $compare (press ctrl-c to stop)"
                 ;;
                 down)
-                  log_down "🚀 consumer lag for connector $connector has decreased to $total_lag $compare (press ctrl-c to stop)"
+                  log_down "🚀 consumer lag for $connector_type connector $connector has decreased to $total_lag $compare (press ctrl-c to stop)"
                 ;;
                 *)
-                  log_same "🐌 consumer lag for connector $connector is still $total_lag $compare (press ctrl-c to stop)"
+                  log_same "🐌 consumer lag for $connector_type connector $connector is still $total_lag $compare (press ctrl-c to stop)"
                 ;;
               esac
             else
-              log "🐢 consumer lag for connector $connector is $total_lag"
+              log "🐢 consumer lag for $connector_type connector $connector is $total_lag"
             fi
             show_output
             if [[ ! -n "$wait_for_zero_lag" ]]
@@ -19387,11 +19432,11 @@ playground_connector_show_lag_command() {
           else
             if [[ ! -n "$wait_for_zero_lag" ]]
             then
-              log "🏁 consumer lag for connector $connector is 0 !"
+              log "🏁 consumer lag for $connector_type connector $connector is 0 !"
               stop=1
             else
               ELAPSED="took: $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
-              log "🏁 consumer lag for connector $connector is 0 ! $ELAPSED"
+              log "🏁 consumer lag for $connector_type connector $connector is 0 ! $ELAPSED"
             fi
             show_output
             break
@@ -20292,12 +20337,14 @@ playground_connector_update_command() {
   # src/commands/connector/update.sh
   connector="${args[--connector]}"
 
+  connector_type=$(playground state get run.connector_type)
+
   if [[ ! -n "$connector" ]]
   then
       connector=$(playground get-connector-list)
       if [ "$connector" == "" ]
       then
-          logerror "💤 No connector is running !"
+          logerror "💤 No $connector_type connector is running !"
           exit 1
       fi
   fi
@@ -20313,7 +20360,7 @@ playground_connector_update_command() {
   fi
   for connector in ${items[@]}
   do
-      log "🛠️ Updating connector $connector"
+      log "🛠️ Updating $connector_type connector $connector"
       file=$tmp_dir/config-$connector.sh
 
       set +e
@@ -20321,7 +20368,7 @@ playground_connector_update_command() {
       echo -e "" >> $file
       echo -e "##########################" >> $file
       echo "# this is the part to edit" >> $file
-      playground connector show-config --connector "$connector" --no-clipboard | grep -v "Current config for connector" >> $file
+      playground connector show-config --connector "$connector" --no-clipboard | grep -v "Current config for" >> $file
       if [ $? -ne 0 ]
       then
           logerror "❌ playground connector show-config --connector $connector failed with:"
