👾 Add playground connector-plugin sourcecode commands Fixes #7214 handle fm versions

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -8113,7 +8113,7 @@ function get_plugin_list() {
         exit 1
     fi
 
-  res=$(cat $root_folder/scripts/cli/confluent-hub-plugin-list.txt | cut -d "|" -f 1 | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🔌" --header="select connector plugin" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+  res=$(cat $root_folder/scripts/cli/confluent-hub-plugin-list.txt | grep -v "CONFLUENT EMPLOYEE VERSION" |cut -d "|" -f 1 | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🔌" --header="select connector plugin" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
 }
 
 function choose_connector_tag() {
@@ -13726,7 +13726,8 @@ playground_generate_connector_plugin_list_command() {
   cd - > /dev/null
   if [ -f $tmp_dir/confluent-plugin-sourcecode-mapping-list.txt ]
   then
-      grep -v confluentinc $tmp_file > $tmp_file2
+      echo "# CONFLUENT EMPLOYEE VERSION" > $tmp_file2
+      grep -v confluentinc $tmp_file >> $tmp_file2
       cat $tmp_dir/confluent-plugin-sourcecode-mapping-list.txt >> $tmp_file2
       cat $tmp_file2 | sort | uniq > $tmp_file
   fi
@@ -14044,12 +14045,28 @@ playground_get_predefined_schemas_command() {
 playground_update_cache_versions_command() {
 
   # src/commands/update-cache-versions.sh
-  echo "# This file is located at 'src/commands/update-cache-versions.sh'."
-  echo "# It contains the implementation for the 'playground update-cache-versions' command."
-  echo "# The code you write here will be wrapped by a function named 'playground_update_cache_versions_command()'."
-  echo "# Feel free to edit this file; your changes will persist when regenerating."
-  inspect_args
+  tmp_dir=$(mktemp -d -t pg-XXXXXXXXXX)
+  if [ -z "$PG_VERBOSE_MODE" ]
+  then
+      trap 'rm -rf $tmp_dir' EXIT
+  else
+      log "🐛📂 not deleting tmp dir $tmp_dir"
+  fi
 
+  curl -H "Authorization: Token $GH_TOKEN" -s "https://raw.githubusercontent.com/confluentinc/cc-docker-connect/refs/heads/master/cc-connect/cache-versions.env" -o $tmp_dir/cache-versions.env
+
+  if [ ! -f $tmp_dir/cache-versions.env ]
+  then
+      logerror "❌ could not download cache-versions.env"
+      exit 1
+  fi
+
+  aws s3 cp --only-show-errors $tmp_dir/cache-versions.env s3://kafka-docker-playground/3rdparty/cache-versions.env
+  if [ $? -ne 0 ]
+  then
+      logerror "❌ could not upload cache-versions.env to s3://kafka-docker-playground/3rdparty/cache-versions.env"
+      exit 1
+  fi
 }
 
 # :command.function
@@ -24664,19 +24681,23 @@ playground_connector_plugin_sourcecode_command() {
   fi
 
   set +e
+  is_confluent_employee=0
+  output=$(grep "CONFLUENT EMPLOYEE VERSION" $root_folder/scripts/cli/confluent-hub-plugin-list.txt)
+  if [ $ret -eq 0 ]
+  then
+      is_confluent_employee=1
+  else
+      logerror "❌ playground connector-plugin sourcecode is not working with fully managed connectors"
+      logerror "❌ if you're a Confluent employee, make sure your aws creds are set and then run <playground generate-connector-plugin-list>"
+      exit 1
+  fi
+
   output=$(grep "$connector_plugin|" $root_folder/scripts/cli/confluent-hub-plugin-list.txt)
   ret=$?
   set -e
   if [ $ret -ne 0 ]
   then
       logerror "❌ could not found $connector_plugin in $root_folder/scripts/cli/confluent-hub-plugin-list.txt"
-      logerror "❌ the file can be re-generated with <playground generate-connector-plugin-list>"
-
-      if [ $is_fully_managed -eq 1 ]
-      then
-          logerror "❌ if you're a Confluent employee, make sure your aws creds are set and then run <playground generate-connector-plugin-list>"
-          exit 1
-      fi
       exit 1
   fi
 
@@ -24686,10 +24707,62 @@ playground_connector_plugin_sourcecode_command() {
       logerror "❌ could not found sourcecode url for plugin $connector_plugin. It is probably proprietary"
       if [[ "$sourcecode_url" == *"confluentinc"* ]]
       then
-          logerror "❌ if you're a Confluent employee, make sure your aws creds are set and then run <playground generate-connector-plugin-list>"
+          if [ $is_confluent_employee -eq 1 ]
+          then
+              logerror "❌ if you're a Confluent employee, make sure your aws creds are set and then run <playground generate-connector-plugin-list>"
+              exit 1
+          fi
       fi
       exit 1
   fi
+
+  if [ $is_confluent_employee -eq 1 ] || [ $is_fully_managed -eq 1 ]
+  then
+      connector_name_cache_versions=$(echo "$output" | cut -d "|" -f 3)
+  fi
+
+  function get_latest_version_from_cc_docker_connect_cache_versions_env () {
+      tmp_dir=$(mktemp -d -t pg-XXXXXXXXXX)
+      if [ -z "$PG_VERBOSE_MODE" ]
+      then
+          trap 'rm -rf $tmp_dir' EXIT
+      else
+          log "🐛📂 not deleting tmp dir $tmp_dir"
+      fi
+      # confluent only
+      cd $tmp_dir > /dev/null
+      get_3rdparty_file "cache-versions.env"
+      cd - > /dev/null
+      if [ -f $tmp_dir/cache-versions.env ]
+      then
+          last_version=$(grep "$connector_name_cache_versions" $tmp_dir/cache-versions.env  | cut -d "=" -f 2)
+          if [ $ret -eq 0 ]
+          then
+              log "✨ --connector-tag was not set, using latest version on cc-docker-connect (cache-versions.env file https://github.com/confluentinc/cc-docker-connect/blob/master/cc-connect/cache-versions.env) which is $last_version"
+              connector_tag="$last_version"
+          else
+              logerror "❌ could not find $connector_name_cache_versions in $tmp_dir/cache-versions.env"
+              exit 1
+          fi
+      else
+          logerror "❌ file cache-versions.env could not be downloaded from s3 bucket"
+          exit 1
+      fi
+  }
+
+  function get_latest_version_from_confluent_hub () {
+      output=$(playground connector-plugin versions --connector-plugin "$connector_plugin" --last 1 | head -n 1)
+      last_version=$(echo "$output" | grep -v "<unknown>" | cut -d " " -f 2 | cut -d "v" -f 2)
+      if [[ -n "$last_version" ]]
+      then
+          log "✨ --connector-tag was not set, using latest version on hub $last_version"
+          connector_tag="$last_version"
+      else
+          logwarn "could not find latest version using <playground connector-plugin versions --connector-plugin \"$connector_plugin\" --last 1>"
+          logerror "❌ --connector-tag flag is set 2 times, but one of them is set to latest. Comparison between version can only works when providing versions"
+          exit 1
+      fi
+  }
 
   comparison_mode_versions=""
   length=${#connector_tag_array[@]}
@@ -24712,38 +24785,22 @@ playground_connector_plugin_sourcecode_command() {
       then
           if [ $is_fully_managed -eq 1 ]
           then
-              logerror "❌ --connector-tag set with \"latest\" cannot work when using fully managed connector plugin, please specify actual versions"
-              exit 1
-          fi
-          output=$(playground connector-plugin versions --connector-plugin "$connector_plugin" --last 1 | head -n 1)
-          last_version=$(echo "$output" | grep -v "<unknown>" | cut -d " " -f 2 | cut -d "v" -f 2)
-          if [[ -n "$last_version" ]]
-          then
-              log "✨ --connector-tag was not set, using latest version on hub $last_version"
-              connector_tag1="$last_version"
+              get_latest_version_from_cc_docker_connect_cache_versions_env
+              connector_tag1=$connector_tag
           else
-              logwarn "could not find latest version using <playground connector-plugin versions --connector-plugin \"$connector_plugin\" --last 1>"
-              logerror "❌ --connector-tag flag is set 2 times, but one of them is set to latest. Comparison between version can only works when providing versions"
-              exit 1
+              get_latest_version_from_confluent_hub
+              connector_tag1=$connector_tag
           fi
       fi
       if [ "$connector_tag2" == "latest" ]
       then
           if [ $is_fully_managed -eq 1 ]
           then
-              logerror "❌ --connector-tag set with \"latest\" cannot work when using fully managed connector plugin, please specify actual versions"
-              exit 1
-          fi
-          output=$(playground connector-plugin versions --connector-plugin "$connector_plugin" --last 1 | head -n 1)
-          last_version=$(echo "$output" | grep -v "<unknown>" | cut -d " " -f 2 | cut -d "v" -f 2)
-          if [[ -n "$last_version" ]]
-          then
-              log "✨ --connector-tag was not set, using latest version on hub $last_version"
-              connector_tag2="$last_version"
+              get_latest_version_from_cc_docker_connect_cache_versions_env
+              connector_tag2=$connector_tag
           else
-              logwarn "could not find latest version using <playground connector-plugin versions --connector-plugin \"$connector_plugin\" --last 1>"
-              logerror "❌ --connector-tag flag is set 2 times, but one of them is set to latest. Comparison between version can only works when providing versions"
-              exit 1
+              get_latest_version_from_confluent_hub
+              connector_tag2=$connector_tag
           fi
       fi
 
@@ -24798,7 +24855,7 @@ playground_connector_plugin_sourcecode_command() {
                   connector_tag="latest"
               fi
           else
-              connector_tag="latest"
+              get_latest_version_from_cc_docker_connect_cache_versions_env
           fi
       fi
   fi
