adding --id to playground schema delete and register

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -2476,6 +2476,11 @@ playground_schema_register_usage() {
     printf "    Default: -\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--id ID")"
+    printf "    ☢️ Force schema id\n    \n    ❗it will replace any schema which already exists at given id\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -2694,6 +2699,11 @@ playground_schema_delete_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--version VERSION")"
     printf "    🔢 Schema version of the provided subject to delete\n    \n    Can only be used when --subject is provided\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--id ID")"
+    printf "    🫵 Schema id\n    \n    Can only be used when --subject is provided\n"
     echo
 
     # :flag.usage
@@ -14442,6 +14452,7 @@ playground_schema_register_command() {
   # src/commands/schema/register.sh
   subject="${args[--subject]}"
   schema="${args[--schema]}"
+  id="${args[--id]}"
   verbose="${args[--verbose]}"
 
   get_sr_url_and_security
@@ -14491,6 +14502,90 @@ playground_schema_register_command() {
 
   content=$(cat $schema_file | tr -d '\n' | tr -s ' ')
   json_new=$(echo $json | jq --arg content "$content" '. + { "schema": $content }')
+
+  if [[ -n "$id" ]]
+  then
+      function set_back_read_write {
+          set +e
+          curl $sr_security --request PUT -s "${sr_url}/mode/${subject}" --header 'Content-Type: application/json' --data '{"mode": "READWRITE"}' > /dev/null 2>&1
+          set -e
+      }
+      trap set_back_read_write EXIT
+
+      log "Deleting 🫵 id ${id} for subject 🔰 ${subject} permanently"
+      playground schema delete --subject "${subject}" --id ${id} --permanent > /dev/null 2>&1
+
+      log "Setting mode to IMPORT"
+      curl_output=$(curl $sr_security --request PUT -s "${sr_url}/mode/${subject}" --header 'Content-Type: application/json' --data '{"mode": "IMPORT"}' | jq .)
+      ret=$?
+      if [ $ret -eq 0 ]
+      then
+          if echo "$curl_output" | jq '. | has("error_code")' 2> /dev/null | grep -q true
+
+          then
+              error_code=$(echo "$curl_output" | jq -r .error_code)
+              if [ "$error_code" != "40403" ] && [ "$error_code" != "40401" ]
+              then
+                  message=$(echo "$curl_output" | jq -r .message)
+                  logerror "Command failed with error code $error_code"
+                  logerror "$message"
+                  exit 1
+              fi
+          fi
+      else
+          logerror "❌ curl request failed with error code $ret!"
+          exit 1
+      fi
+      echo "$curl_output"
+
+      log "⏺️☢️ Registering schema to subject ${subject} with id $id"
+      json_new_force_id=$(echo $json_new | jq --arg id "$id" '. + { "id": $id }')
+      curl_output=$(curl $sr_security --request POST -s "${sr_url}/subjects/${subject}/versions" --header 'Content-Type: application/vnd.schemaregistry.v1+json' --data "$json_new_force_id" | jq .)
+      ret=$?
+      if [ $ret -eq 0 ]
+      then
+          if echo "$curl_output" | jq '. | has("error_code")' 2> /dev/null | grep -q true
+
+          then
+              error_code=$(echo "$curl_output" | jq -r .error_code)
+              if [ "$error_code" != "40403" ] && [ "$error_code" != "40401" ]
+              then
+                  message=$(echo "$curl_output" | jq -r .message)
+                  logerror "Command failed with error code $error_code"
+                  logerror "$message"
+                  exit 1
+              fi
+          fi
+      else
+          logerror "❌ curl request failed with error code $ret!"
+          exit 1
+      fi
+      echo "$curl_output"
+
+      log "Setting mode to READWRITE"
+      curl_output=$(curl $sr_security --request PUT -s "${sr_url}/mode/${subject}" --header 'Content-Type: application/json' --data '{"mode": "READWRITE"}' | jq .)
+      ret=$?
+      if [ $ret -eq 0 ]
+      then
+          if echo "$curl_output" | jq '. | has("error_code")' 2> /dev/null | grep -q true
+
+          then
+              error_code=$(echo "$curl_output" | jq -r .error_code)
+              if [ "$error_code" != "40403" ] && [ "$error_code" != "40401" ]
+              then
+                  message=$(echo "$curl_output" | jq -r .message)
+                  logerror "Command failed with error code $error_code"
+                  logerror "$message"
+                  exit 1
+              fi
+          fi
+      else
+          logerror "❌ curl request failed with error code $ret!"
+          exit 1
+      fi
+      echo "$curl_output"
+      exit 0
+  fi
 
   # check if schema already exists
   # https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)
@@ -14682,6 +14777,7 @@ playground_schema_delete_command() {
   # src/commands/schema/delete.sh
   subject="${args[--subject]}"
   version="${args[--version]}"
+  id="${args[--id]}"
   permanent="${args[--permanent]}"
   verbose="${args[--verbose]}"
 
@@ -14692,6 +14788,15 @@ playground_schema_delete_command() {
       if [[ ! -n "$subject" ]]
       then
           logerror "❌ --version is set without --subject being set"
+          exit 1
+      fi
+  fi
+
+  if [[ -n "$id" ]]
+  then
+      if [[ ! -n "$subject" ]]
+      then
+          logerror "❌ --id is set without --subject being set"
           exit 1
       fi
   fi
@@ -14719,23 +14824,44 @@ playground_schema_delete_command() {
               curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${version}?permanent=true" | jq .
           fi
       else
-          logwarn "--version is not set, deleting all versions !"
-          log "🧟 Soft deleting subject 🔰 ${subject}"
-          if [[ -n "$verbose" ]]
+          if [[ -n "$version" ]]
           then
-              log "🐞 curl command used"
-              echo "curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}""
-          fi
-          curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}" | jq .
-          if [[ -n "$permanent" ]]
-          then
-              log "💀 Hard deleting  subject 🔰 ${subject}"
+              log "🧟 Soft deleting 🫵 id ${id} for subject 🔰 ${subject}"
               if [[ -n "$verbose" ]]
               then
                   log "🐞 curl command used"
-                  echo "curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}?permanent=true""
+                  echo "curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${id}""
               fi
-              curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}?permanent=true" | jq .
+              curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${id}" | jq .
+              if [[ -n "$permanent" ]]
+              then
+                  log "💀 Hard deleting 🫵 id ${id} for subject 🔰 ${subject}"
+                  if [[ -n "$verbose" ]]
+                  then
+                      log "🐞 curl command used"
+                      echo "curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${id}?permanent=true""
+                  fi
+                  curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}/versions/${id}?permanent=true" | jq .
+              fi
+          else
+              logwarn "--version is not set, deleting all versions !"
+              log "🧟 Soft deleting subject 🔰 ${subject}"
+              if [[ -n "$verbose" ]]
+              then
+                  log "🐞 curl command used"
+                  echo "curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}""
+              fi
+              curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}" | jq .
+              if [[ -n "$permanent" ]]
+              then
+                  log "💀 Hard deleting subject 🔰 ${subject}"
+                  if [[ -n "$verbose" ]]
+                  then
+                      log "🐞 curl command used"
+                      echo "curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}?permanent=true""
+                  fi
+                  curl $sr_security -X DELETE -s "${sr_url}/subjects/${subject}?permanent=true" | jq .
+              fi
           fi
       fi
   fi
@@ -23943,6 +24069,26 @@ playground_schema_register_parse_requirements() {
         fi
         ;;
 
+      # :flag.case
+      --id)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--id ID" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--id requires an argument: --id ID" >&2
+          exit 1
+        fi
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -24415,6 +24561,11 @@ playground_schema_delete_parse_requirements() {
 
       # :flag.case
       --version)
+        # :flag.conflicts
+        if [[ -n "${args['--id']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--id" >&2
+          exit 1
+        fi
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
@@ -24429,6 +24580,31 @@ playground_schema_delete_parse_requirements() {
           shift
         else
           printf "%s\n" "--version requires an argument: --version VERSION" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --id)
+        # :flag.conflicts
+        if [[ -n "${args['--version']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--version" >&2
+          exit 1
+        fi
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--id ID" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--id requires an argument: --id ID" >&2
           exit 1
         fi
         ;;
