🧠 Add playground refresh-cp-docker-images #6831

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -48,7 +48,8 @@ playground_usage() {
   printf "  %s   👐 When --file is not provided, simply open last example you ran with <playground run>\n" "$(green "open")                                      "
   printf "  %s   🛑 Stop currently running example\n" "$(green "stop")                                      "
   printf "  %s   🧨 Remove all docker images (including docker volumes)\n" "$(green "remove-all-docker-images")                  "
-  printf "  %s   🧹 Remove all Confluent Platform docker images related to a version (a confirmation will be required for every version present)\n" "$(green "remove-cp-docker-images")                   "
+  printf "  %s   🧹 Remove all Confluent Platform docker images related to a version installed locally (a confirmation will be required for every version present)\n" "$(green "remove-cp-docker-images")                   "
+  printf "  %s   🔄 Refresh (pull from Docker) all Confluent Platform docker images related to a version installed locally\n" "$(green "refresh-cp-docker-images")                  "
   printf "  %s   🧼 playground is actively caching ccloud details (https://kafka-docker-playground.io/#/how-to-use?id=%%f0%%9f%%8c%%a4%%ef%%b8%%8f-confluent-cloud-examples)\n" "$(green "cleanup-cloud-details")                     "
   printf "  %s   🧑‍🎓 Open Confluent documentation of currently running example\n" "$(green "open-docs")                                 "
   printf "  %s   📜 Open playground changelog (https://kafka-docker-playground.io/#/changelog)\n" "$(green "open-changelog")                            "
@@ -2234,7 +2235,7 @@ playground_remove_all_docker_images_usage() {
 
 # :command.usage
 playground_remove_cp_docker_images_usage() {
-  printf "playground remove-cp-docker-images - 🧹 Remove all Confluent Platform docker images related to a version (a confirmation will be required for every version present)\n\n"
+  printf "playground remove-cp-docker-images - 🧹 Remove all Confluent Platform docker images related to a version installed locally (a confirmation will be required for every version present)\n\n"
 
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground remove-cp-docker-images [OPTIONS]\n"
@@ -2249,6 +2250,33 @@ playground_remove_cp_docker_images_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--version VERSION")"
     printf "    🔢 Specific version to remove\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_refresh_cp_docker_images_usage() {
+  printf "playground refresh-cp-docker-images - 🔄 Refresh (pull from Docker) all Confluent Platform docker images related to a version installed locally\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground refresh-cp-docker-images [OPTIONS]\n"
+  printf "  playground refresh-cp-docker-images --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--version VERSION (required)")"
+    printf "    🔢 Specific version to pull\n"
     echo
 
     # :command.usage_fixed_flags
@@ -17413,6 +17441,20 @@ playground_remove_cp_docker_images_command() {
 }
 
 # :command.function
+playground_refresh_cp_docker_images_command() {
+
+  # src/commands/refresh-cp-docker-images.sh
+  version=${args[--version]}
+
+  if [[ -n "$version" ]]
+  then
+      log "🔄 Pulling Confluent Platform docker images for $version"
+      docker image ls | grep confluentinc | grep $version | awk '{print $1":"$2}' | xargs -I {} docker pull {}
+      exit 0
+  fi
+}
+
+# :command.function
 playground_cleanup_cloud_details_command() {
 
   # src/commands/cleanup-cloud-details.sh
@@ -27713,6 +27755,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    refresh-cp-docker-images)
+      action="refresh-cp-docker-images"
+      shift
+      playground_refresh_cp_docker_images_parse_requirements "$@"
+      shift $#
+      ;;
+
     cleanup-cloud-details)
       action="cleanup-cloud-details"
       shift
@@ -32142,6 +32191,70 @@ playground_remove_cp_docker_images_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_refresh_cp_docker_images_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_refresh_cp_docker_images_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="refresh-cp-docker-images"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --version)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--version']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--version requires an argument: --version VERSION" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--version']+x} ]]; then
+    printf "missing required flag: --version VERSION\n" >&2
+    exit 1
+  fi
 
 }
 
@@ -42966,6 +43079,7 @@ run() {
     "stop") playground_stop_command ;;
     "remove-all-docker-images") playground_remove_all_docker_images_command ;;
     "remove-cp-docker-images") playground_remove_cp_docker_images_command ;;
+    "refresh-cp-docker-images") playground_refresh_cp_docker_images_command ;;
     "cleanup-cloud-details") playground_cleanup_cloud_details_command ;;
     "open-docs") playground_open_docs_command ;;
     "open-changelog") playground_open_changelog_command ;;
