added --subject option to topic consume

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -298,6 +298,35 @@ playground_get_topic_list_usage() {
 }
 
 # :command.usage
+playground_get_subject_list_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground get-subject-list - Return some completion for subject list\n"
+    echo
+
+  else
+    printf "playground get-subject-list - Return some completion for subject list\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground get-subject-list\n"
+  printf "  playground get-subject-list --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 playground_get_examples_list_with_fzf_usage() {
   if [[ -n $long_usage ]]; then
     printf "playground get-examples-list-with-fzf - Return some completion for examples list\n"
@@ -2742,6 +2771,11 @@ playground_topic_consume_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--plot-latencies-timestamp-field TIMESTAMP")"
     printf "    🗳 Timestamp field name that represents when record was created in source\n    system\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--subject SUBJECT")"
+    printf "    📛 Subject for value in schema-registry to use (useful when data was produced\n    with --value-subject-name-strategy other than TopicNameStrategy)\n    \n    Note: --topic should be specified in this case.\n"
     echo
 
     # :command.usage_fixed_flags
@@ -8329,6 +8363,17 @@ playground_get_topic_list_command() {
 }
 
 # :command.function
+playground_get_subject_list_command() {
+  # src/get_subject_list_command.sh
+  ret=$(get_sr_url_and_security)
+
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
+
+  curl $sr_security -s "${sr_url}/subjects" | jq -r '.[]'
+}
+
+# :command.function
 playground_get_examples_list_with_fzf_command() {
   # src/get_examples_list_with_fzf_command.sh
   without_repro="${args[--without-repro]}"
@@ -11505,6 +11550,7 @@ playground_topic_consume_command() {
   timeout="${args[--timeout]}"
   tail="${args[--tail]}"
   timestamp_field="${args[--plot-latencies-timestamp-field]}"
+  subject="${args[--subject]}"
 
   environment=`get_environment_used`
 
@@ -11578,6 +11624,11 @@ playground_topic_consume_command() {
       if [[ -n "$min_expected_messages" ]]
       then
         logerror "--min-expected-messages was provided without specifying --topic"
+        exit 1
+      fi
+      if [[ -n "$subject" ]]
+      then
+        logerror "--subject was provided without specifying --topic"
         exit 1
       fi
       if [[ -n "$tail" ]]
@@ -11702,11 +11753,19 @@ playground_topic_consume_command() {
       log "🔮🙅 topic is not using any schema for key"
     fi
 
+    if [[ -n "$subject" ]]
+    then
+      log "📛 subject is set with $subject"
+      value_subject="${subject}"
+    else
+      value_subject="${topic}-value"
+    fi
+
     value_type=""
-    version=$(curl $sr_security -s "${sr_url}/subjects/${topic}-value/versions/1" | jq -r .version)
+    version=$(curl $sr_security -s "${sr_url}/subjects/${value_subject}/versions/1" | jq -r .version)
     if [ "$version" != "null" ]
     then
-      schema_type=$(curl $sr_security -s "${sr_url}/subjects/${topic}-value/versions/1"  | jq -r .schemaType)
+      schema_type=$(curl $sr_security -s "${sr_url}/subjects/${value_subject}/versions/1"  | jq -r .schemaType)
       case "${schema_type}" in
         JSON)
           value_type="json-schema"
@@ -14250,6 +14309,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    get-subject-list)
+      action="get-subject-list"
+      shift
+      playground_get_subject_list_parse_requirements "$@"
+      shift $#
+      ;;
+
     get-examples-list-with-fzf)
       action="get-examples-list-with-fzf"
       shift
@@ -14679,6 +14745,50 @@ playground_get_topic_list_parse_requirements() {
         args['--skip-connect-internal-topics']=1
         shift
         ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_get_subject_list_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_get_subject_list_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="get-subject-list"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -19341,6 +19451,21 @@ playground_topic_consume_parse_requirements() {
         fi
         ;;
 
+      # :flag.case
+      --subject)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--subject']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--subject requires an argument: --subject SUBJECT" >&2
+          exit 1
+        fi
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -21579,6 +21704,7 @@ run() {
     "get-ccloud-connector-list") playground_get_ccloud_connector_list_command ;;
     "get-kafka-region-list") playground_get_kafka_region_list_command ;;
     "get-topic-list") playground_get_topic_list_command ;;
+    "get-subject-list") playground_get_subject_list_command ;;
     "get-examples-list-with-fzf") playground_get_examples_list_with_fzf_command ;;
     "get-zip-or-jar-with-fzf") playground_get_zip_or_jar_with_fzf_command ;;
     "get-any-file-with-fzf") playground_get_any_file_with_fzf_command ;;
