added playground tools certs-create

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -89,6 +89,7 @@ playground_usage() {
   printf "  %s   🪄 Install a slightly modified version of \"Shell Script Command Completion\" Visual Studio Code extension (https://marketplace.visualstudio.com/items?itemName=tetradresearch.vscode-h2o)\n" "$(green "tools install-vscode-extension")            "
   printf "  %s   🔖 Read provided avro file\n" "$(green "tools read-avro-file")                      "
   printf "  %s   🔖 Read provided parquet file\n" "$(green "tools read-parquet-file")                   "
+  printf "  %s   🔐 Generate keys and certificates used for SSL\n" "$(green "tools certs-create")                        "
   echo
   printf "%s\n" "$(bold "Debug commands:")"
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                                     "
@@ -3032,6 +3033,7 @@ playground_tools_usage() {
   printf "  %s   🪄 Install a slightly modified version of \"Shell Script Command Completion\" Visual Studio Code extension (https://marketplace.visualstudio.com/items?itemName=tetradresearch.vscode-h2o)\n" "$(green "install-vscode-extension")"
   printf "  %s   🔖 Read provided avro file\n" "$(green "read-avro-file")          "
   printf "  %s   🔖 Read provided parquet file\n" "$(green "read-parquet-file")       "
+  printf "  %s   🔐 Generate keys and certificates used for SSL\n" "$(green "certs-create")            "
   echo
 
   # :command.long_usage
@@ -3121,6 +3123,44 @@ playground_tools_read_parquet_file_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--file, -f FILE")"
     printf "    🔖 Parquet file to read\n    \n    ❕ It must be absolute full path\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_tools_certs_create_usage() {
+  printf "playground tools certs-create - 🔐 Generate keys and certificates used for SSL\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tools certs-create [OPTIONS]\n"
+  printf "  playground tools certs-create --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container CONTAINER (repeatable)")"
+    printf "    🐳 container name\n    \n    🎓 Tip: you can pass multiple containers by specifying --container multiple\n    times\n"
+    printf "    %s\n" "Default: broker, broker2, broker3, client, schema-registry, restproxy, connect, connect2, connect3, control-center, clientrestproxy, ksqldb-server, conduktor"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--verbose, -v")"
+    printf "    🐞 Show command being ran.\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--output-folder FOLDER (required)")"
+    printf "    📁 Folder where certificates are created\n"
     echo
 
     # :command.usage_fixed_flags
@@ -18818,6 +18858,39 @@ playground_tools_read_parquet_file_command() {
 }
 
 # :command.function
+playground_tools_certs_create_command() {
+  # src/commands/tools/certs-create.sh
+  output_folder="${args[--output-folder]}"
+  verbose="${args[--verbose]}"
+  # Convert the space delimited string to an array
+  eval "containers=(${args[--container]})"
+
+  function cleanup {
+      set +e
+      rm -f "${output_folder}/certs-create.sh"
+  }
+  trap cleanup EXIT
+
+  maybe_redirect_output="> /dev/null 2>&1"
+  if [[ -n "$verbose" ]]
+  then
+      maybe_redirect_output=""
+  fi
+
+  container_list="${containers[*]}"
+
+  new_open_ssl=0
+  if version_gt $CONNECT_TAG "7.7.99"
+  then
+      new_open_ssl=1
+  fi
+  cd "${output_folder}"
+  cp $root_folder/scripts/cli/src/ssl/certs-create.sh .
+  log "🔐 Generate keys and certificates in folder ${output_folder}"
+  docker run -u0 --rm -v $root_folder/scripts/cli/src/openssl.cnf:/usr/local/ssl/openssl.cnf -v $PWD:/tmp ${CP_CONNECT_IMAGE}:${CONNECT_TAG} bash -c "/tmp/certs-create.sh $maybe_redirect_output \"$container_list\" $new_open_ssl && chown -R $(id -u $USER):$(id -g $USER) /tmp/"
+}
+
+# :command.function
 playground_debug_enable_remote_debugging_command() {
   # src/commands/debug/enable-remote-debugging.sh
   container="${args[--container]}"
@@ -32093,6 +32166,13 @@ playground_tools_parse_requirements() {
       shift $#
       ;;
 
+    certs-create)
+      action="certs-create"
+      shift
+      playground_tools_certs_create_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_tools_usage >&2
@@ -32308,6 +32388,108 @@ playground_tools_read_parquet_file_parse_requirements() {
   # :flag.validations
   if [[ -v args['--file'] && -n $(validate_file_exists_and_parquet "${args['--file']:-}") ]]; then
     printf "validation error in %s:\n%s\n" "--file, -f FILE" "$(validate_file_exists_and_parquet "${args['--file']:-}")" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_tools_certs_create_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_tools_certs_create_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tools certs-create"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          escaped="$(printf '%q' "$2")"
+          if [[ -z ${args['--container']+x} ]]; then
+            args['--container']="$escaped"
+          elif [[ -z "${unique_lookup["--container:${escaped}"]:-}" ]]; then
+            args['--container']="${args['--container']} $escaped"
+          fi
+          unique_lookup["--container:${escaped}"]=1
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --verbose | -v)
+
+        # :flag.case_no_arg
+        args['--verbose']=1
+        shift
+        ;;
+
+      # :flag.case
+      --output-folder)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--output-folder']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--output-folder requires an argument: --output-folder FOLDER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--output-folder']+x} ]]; then
+    printf "missing required flag: --output-folder FOLDER\n" >&2
+    exit 1
+  fi
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="broker broker2 broker3 client schema-registry restproxy connect connect2 connect3 control-center clientrestproxy ksqldb-server conduktor"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--output-folder'] && -n $(validate_dir_exists "${args['--output-folder']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--output-folder FOLDER" "$(validate_dir_exists "${args['--output-folder']:-}")" >&2
     exit 1
   fi
 
@@ -39466,6 +39648,7 @@ run() {
     "tools install-vscode-extension") playground_tools_install_vscode_extension_command ;;
     "tools read-avro-file") playground_tools_read_avro_file_command ;;
     "tools read-parquet-file") playground_tools_read_parquet_file_command ;;
+    "tools certs-create") playground_tools_certs_create_command ;;
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
     "debug testssl") playground_debug_testssl_command ;;
