🧠 Add playground connector-plugin display-last-updated in run command output for connector examples #6827

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -144,6 +144,7 @@ playground_usage() {
   printf "  %s   🔌 Connector-plugin commands\n" "$(green "connector-plugin")                          "
   printf "  %s   ☕ List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "connector-plugin search-jar")               "
   printf "  %s   💯 List versions for a connector plugin from confluent hub https://www.confluent.io/hub/\n" "$(green "connector-plugin versions")                 "
+  printf "  %s   🆕 List last updated connector plugins from confluent hub https://www.confluent.io/hub/\n" "$(green "connector-plugin display-last-updated")     "
   echo
   printf "%s\n" "$(bold "Connector commands:")"
   printf "  %s   🔗 Connector commands\n" "$(green "connector")                                 "
@@ -5250,8 +5251,9 @@ playground_connector_plugin_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
-  printf "  %s   ☕ List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "search-jar")"
-  printf "  %s   💯 List versions for a connector plugin from confluent hub https://www.confluent.io/hub/\n" "$(green "versions")  "
+  printf "  %s   ☕ List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "search-jar")          "
+  printf "  %s   💯 List versions for a connector plugin from confluent hub https://www.confluent.io/hub/\n" "$(green "versions")            "
+  printf "  %s   🆕 List last updated connector plugins from confluent hub https://www.confluent.io/hub/\n" "$(green "display-last-updated")"
   echo
 
   # :command.long_usage
@@ -5347,6 +5349,44 @@ playground_connector_plugin_versions_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground connector-plugin versions --connector-plugin\n  confluentinc/kafka-connect-s3\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_plugin_display_last_updated_usage() {
+  printf "playground connector-plugin display-last-updated - 🆕 List last updated connector plugins from confluent hub https://www.confluent.io/hub/\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector-plugin display-last-updated [OPTIONS]\n"
+  printf "  playground connector-plugin display-last-updated --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--days DAYS")"
+    printf "    📅 Number of days to look back\n    \n    Default is 3 days\n"
+    printf "    %s\n" "Default: 3"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--vendor VENDOR")"
+    printf "    🏢 Only display results for this vendor\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground connector-plugin display-last-updated --days 7\n  playground connector-plugin display-last-updated --days 7 --vendor\n  confluentinc\n"
     echo
 
   fi
@@ -16396,6 +16436,24 @@ playground_run_command() {
     if [ "$connector_type" == "$CONNECTOR_TYPE_ONPREM" ] || [ "$connector_type" == "$CONNECTOR_TYPE_SELF_MANAGED" ]
     then
       playground connector versions
+
+      # playground connector-plugin display-last-updated
+      set +e
+      echo ""
+      # wait that process with "playground connector-plugin display-last-updated" is finished
+      set +e
+      while pgrep -f "playground connector-plugin display-last-updated" > /dev/null
+      do
+        log "⌛ wait for playground connector-plugin display-last-updated..."
+        sleep 10
+      done
+      set -e
+      if [ -f ${connector_plugin_display_last_updated_file} ]
+      then
+        cat ${connector_plugin_display_last_updated_file}
+      fi
+      set -e
+
       playground connector open-docs --only-show-url
     fi
     set -e
@@ -16404,6 +16462,18 @@ playground_run_command() {
 
   playground generate-fzf-find-files &
   generate_connector_versions > /dev/null 2>&1 &
+  set +e
+
+  connector_plugin_display_last_updated_file="/tmp/connector-plugin-display-last-updated-$(date +%Y-%m-%d).txt"
+  connector_type=$(playground state get run.connector_type)
+  if [ "$connector_type" == "$CONNECTOR_TYPE_ONPREM" ] || [ "$connector_type" == "$CONNECTOR_TYPE_SELF_MANAGED" ]
+  then
+    if [ ! -f ${connector_plugin_display_last_updated_file} ]
+    then
+      playground connector-plugin display-last-updated --days 3 --vendor confluentinc > ${connector_plugin_display_last_updated_file} &
+    fi
+  fi
+  set -e
   touch /tmp/playground-run-command-used
   set +e
   bash $filename
@@ -23852,6 +23922,50 @@ playground_connector_plugin_versions_command() {
   else
       cat $filename
   fi
+}
+
+# :command.function
+playground_connector_plugin_display_last_updated_command() {
+
+  # src/commands/connector-plugin/display-last-updated.sh
+  days="${args[--days]}"
+  vendor="${args[--vendor]}"
+
+  if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
+  then
+      logwarn "file $root_folder/scripts/cli/confluent-hub-plugin-list.txt not found. Generating it now, it may take a while..."
+      playground generate-connector-plugin-list
+  fi
+
+  if [[ -n "$vendor" ]]
+  then
+      log "🆕 Listing last updated connector plugins (within $days days) for $vendor vendor"
+  else
+      log "🆕 Listing last updated connector plugins (within $days days) for all vendors"
+  fi
+
+  for plugin in $(cat $root_folder/scripts/cli/confluent-hub-plugin-list.txt)
+  do
+      if [[ -n "$vendor" && ! "$plugin" =~ $vendor ]]
+      then
+          continue
+      fi
+      output=$(playground connector-plugin versions --connector-plugin "$plugin" --force-refresh --last 1)
+      set +e
+      if [[ -n "$days" ]]
+      then
+          last_updated=$(echo "$output" | grep -v "<unknown>" | cut -d "(" -f 2 | cut -d " " -f 1)
+          if [[ -n "$last_updated" ]]
+          then
+              last_updated_days=$(echo $last_updated | tr -d '[:space:]')
+              if [[ $last_updated_days -le $days ]]
+              then
+                  echo "🔌 $plugin - $output"
+              fi
+          fi
+      fi
+      set -e
+  done
 }
 
 # :command.function
@@ -39226,6 +39340,13 @@ playground_connector_plugin_parse_requirements() {
       shift $#
       ;;
 
+    display-last-updated)
+      action="display-last-updated"
+      shift
+      playground_connector_plugin_display_last_updated_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_connector_plugin_usage >&2
@@ -39469,6 +39590,100 @@ playground_connector_plugin_versions_parse_requirements() {
     validation_output="$(validate_integer "${args['--last']:-}")"
     if [[ -n "${validation_output}" ]]; then
       printf "validation error in %s:\n%s\n" "--last LAST" "$validation_output" >&2
+      exit 1
+    fi
+  fi
+
+}
+
+# :command.parse_requirements
+playground_connector_plugin_display_last_updated_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_plugin_display_last_updated_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector-plugin display-last-updated"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --days)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--days']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--days requires an argument: --days DAYS" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --vendor)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--vendor']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--vendor requires an argument: --vendor VENDOR" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--days']:-} ]] || args['--days']="3"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--days'] ]]; then
+    validation_output="$(validate_integer "${args['--days']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--days DAYS" "$validation_output" >&2
+      exit 1
+    fi
+  fi
+
+  # :flag.validations
+  if [[ -v args['--vendor'] ]]; then
+    validation_output="$(validate_not_empty "${args['--vendor']:-}")"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--vendor VENDOR" "$validation_output" >&2
       exit 1
     fi
   fi
@@ -42714,6 +42929,7 @@ run() {
     "connector-plugin") playground_connector_plugin_command ;;
     "connector-plugin search-jar") playground_connector_plugin_search_jar_command ;;
     "connector-plugin versions") playground_connector_plugin_versions_command ;;
+    "connector-plugin display-last-updated") playground_connector_plugin_display_last_updated_command ;;
     "connector") playground_connector_command ;;
     "connector status") playground_connector_status_command ;;
     "connector offsets") playground_connector_offsets_command ;;
