add debug heap-dump

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -55,6 +55,7 @@ playground_usage() {
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                             "
   [[ -n $long_usage ]] && printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "debug enable-remote-debugging")     "
   [[ -n $long_usage ]] && printf "  %s   🎯 Take a java thread dump\n" "$(green "debug thread-dump")                 "
+  [[ -n $long_usage ]] && printf "  %s   👻 Take a heap dump\n" "$(green "debug heap-dump")                   "
   [[ -n $long_usage ]] && printf "  %s   🕵️‍♂️ Take a tcp dump (sniffing network)\n" "$(green "debug tcp-dump")                    "
   [[ -n $long_usage ]] && printf "  %s   🧬 Set log level for any package\n" "$(green "debug log-level")                   "
   echo
@@ -1153,6 +1154,7 @@ playground_debug_usage() {
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "enable-remote-debugging")"
   printf "  %s   🎯 Take a java thread dump\n" "$(green "thread-dump")            "
+  printf "  %s   👻 Take a heap dump\n" "$(green "heap-dump")              "
   printf "  %s   🕵️‍♂️ Take a tcp dump (sniffing network)\n" "$(green "tcp-dump")               "
   printf "  %s   🧬 Set log level for any package\n" "$(green "log-level")              "
   echo
@@ -1255,6 +1257,51 @@ playground_debug_thread_dump_usage() {
     printf "%s\n" "$(bold "Examples")"
     printf "  playground debug thread-dump\n"
     printf "  playground debug thread-dump --container broker\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_debug_heap_dump_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground debug heap-dump\n"
+    echo
+
+    printf "  👻 Take a heap dump\n  \n  🔖 It will save output to a .hprof file. VisualVM (https://visualvm.github.io/)\n  or MAT (https://www.eclipse.org/mat/) can be used to read the file.\n"
+    echo
+
+  else
+    printf "playground debug heap-dump - 👻 Take a heap dump\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground debug heap-dump [OPTIONS]\n"
+  printf "  playground debug heap-dump --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    🐳 Container name\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground debug heap-dump\n"
+    printf "  playground debug heap-dump --container broker\n"
     echo
 
   fi
@@ -9299,6 +9346,41 @@ playground_debug_thread_dump_command() {
 }
 
 # :command.function
+playground_debug_heap_dump_command() {
+  # src/debug_heap_dump_command.sh
+  container="${args[--container]}"
+  filename="/tmp/heap-dump-$container-`date '+%Y-%m-%d-%H-%M-%S'`.hprof"
+
+  set +e
+  docker exec $container type jmap > /dev/null 2>&1
+  if [ $? != 0 ]
+  then
+      logerror "❌ jmap is not installed on container $container"
+      exit 1
+  fi
+  set -e
+  log "🎯 Taking heap dump on container ${container} for pid 1"
+  docker exec $container jmap -dump:live,format=b,file=${filename} 1
+  if [ $? -eq 0 ]
+  then
+      log "👻 heap dump is available at ${filename}"
+      docker cp ${container}:${filename} ${filename}
+      # if [[ $(type -f wireshark 2>&1) =~ "not found" ]]
+      # then
+      #     logwarn "🦈 wireshark is not installed, grab it at https://www.wireshark.org/"
+      #     exit 0
+      # else
+      #     log "🦈 Opening ${filename} with wireshark"
+      #     wireshark ${filename}
+      # fi
+
+  else
+      logerror "❌ Failed to take heap dump"
+  fi
+
+}
+
+# :command.function
 playground_debug_tcp_dump_command() {
   # src/debug_tcp_dump_command.sh
   container="${args[--container]}"
@@ -13726,6 +13808,13 @@ playground_debug_parse_requirements() {
       shift $#
       ;;
 
+    heap-dump)
+      action="heap-dump"
+      shift
+      playground_debug_heap_dump_parse_requirements "$@"
+      shift $#
+      ;;
+
     tcp-dump)
       action="tcp-dump"
       shift
@@ -13857,6 +13946,67 @@ playground_debug_thread_dump_parse_requirements() {
 
   # :command.command_filter
   action="debug thread-dump"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+}
+
+# :command.parse_requirements
+playground_debug_heap_dump_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_debug_heap_dump_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="debug heap-dump"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -17399,6 +17549,7 @@ run() {
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
     "debug thread-dump") playground_debug_thread_dump_command ;;
+    "debug heap-dump") playground_debug_heap_dump_command ;;
     "debug tcp-dump") playground_debug_tcp_dump_command ;;
     "debug log-level") playground_debug_log_level_command ;;
     "debug log-level get") playground_debug_log_level_get_command ;;
