🧠 Add playground tcp-proxy open-ui #6662

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -88,6 +88,7 @@ playground_usage() {
   printf "  %s   ✅ Change whether reading data from the service is enabled.\n" "$(green "tcp-proxy toggle-reads-service")            "
   printf "  %s   ✅ Change whether writing data to the client is enabled.\n" "$(green "tcp-proxy toggle-writes-client")            "
   printf "  %s   ✅ Change whether reading data to the service is enabled.\n" "$(green "tcp-proxy toggle-writes-service")           "
+  printf "  %s   🌐 Just open Zazkia UI (http://localhost:9191) in your browser\n" "$(green "tcp-proxy open-ui")                         "
   echo
   printf "%s\n" "$(bold "Tools commands:")"
   printf "  %s   🧰 Tools commands\n" "$(green "tools")                                     "
@@ -2974,6 +2975,7 @@ playground_tcp_proxy_usage() {
   printf "  %s   ✅ Change whether reading data from the service is enabled.\n" "$(green "toggle-reads-service")           "
   printf "  %s   ✅ Change whether writing data to the client is enabled.\n" "$(green "toggle-writes-client")           "
   printf "  %s   ✅ Change whether reading data to the service is enabled.\n" "$(green "toggle-writes-service")          "
+  printf "  %s   🌐 Just open Zazkia UI (http://localhost:9191) in your browser\n" "$(green "open-ui")                        "
   echo
 
   # :command.long_usage
@@ -3342,6 +3344,27 @@ playground_tcp_proxy_toggle_writes_service_usage() {
     printf "  %s\n" "$(magenta "--connection-id CONNECTION-ID")"
     printf "    🧲 Zazkia TCP connection id\n"
     echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_tcp_proxy_open_ui_usage() {
+  printf "playground tcp-proxy open-ui - 🌐 Just open Zazkia UI (http://localhost:9191) in your browser\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tcp-proxy open-ui\n"
+  printf "  playground tcp-proxy open-ui --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -20228,6 +20251,21 @@ playground_tcp_proxy_toggle_writes_service_command() {
 }
 
 # :command.function
+playground_tcp_proxy_open_ui_command() {
+
+  # src/commands/tcp-proxy/open-ui.sh
+  if [[ $(type -f open 2>&1) =~ "not found" ]]
+  then
+      log "🔗 Cannot open browser, use url:"
+      echo "http://localhost:9191"
+  else
+      log "🧲 Open Zazkia UI"
+      open "http://localhost:9191"
+  fi
+
+}
+
+# :command.function
 playground_tools_install_vscode_extension_command() {
 
   # src/commands/tools/install-vscode-extension.sh
@@ -33686,6 +33724,13 @@ playground_tcp_proxy_parse_requirements() {
       shift $#
       ;;
 
+    open-ui)
+      action="open-ui"
+      shift
+      playground_tcp_proxy_open_ui_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_tcp_proxy_usage >&2
@@ -34551,6 +34596,51 @@ playground_tcp_proxy_toggle_writes_service_parse_requirements() {
     printf "validation error in %s:\n%s\n" "--connection-id CONNECTION-ID" "$(validate_integer "${args['--connection-id']:-}")" >&2
     exit 1
   fi
+
+}
+
+# :command.parse_requirements
+playground_tcp_proxy_open_ui_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_tcp_proxy_open_ui_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tcp-proxy open-ui"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
 
 }
 
@@ -42291,6 +42381,7 @@ run() {
     "tcp-proxy toggle-reads-service") playground_tcp_proxy_toggle_reads_service_command ;;
     "tcp-proxy toggle-writes-client") playground_tcp_proxy_toggle_writes_client_command ;;
     "tcp-proxy toggle-writes-service") playground_tcp_proxy_toggle_writes_service_command ;;
+    "tcp-proxy open-ui") playground_tcp_proxy_open_ui_command ;;
     "tools") playground_tools_command ;;
     "tools install-vscode-extension") playground_tools_install_vscode_extension_command ;;
     "tools read-avro-file") playground_tools_read_avro_file_command ;;
