open file for bootstrap

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -286,7 +286,7 @@ playground_run_usage() {
 
     # :flag.usage
     printf "  %s\n" "$(magenta "--enable-jmx-grafana")"
-    printf "    Enable Grafana, Prometheus and Pyroscope\n    \n    📊 Grafana is reachable at http://127.0.0.1:3000\n    🛡️ Prometheus is reachable at http://127.0.0.1:9090\n    📛 Pyroscope is reachable at http://127.0.0.1:4040\n"
+    printf "    Enable Grafana, Prometheus and Pyroscope\n    \n    📊 Grafana is reachable at http://127.0.0.1:3000\n    🛡️  Prometheus is reachable at http://127.0.0.1:9090\n    📛 Pyroscope is reachable at http://127.0.0.1:4040\n"
     echo
 
     # :flag.usage
@@ -5811,7 +5811,7 @@ playground_run_command() {
   log "####################################################"
   SECONDS=0
   cd $test_file_directory
-  trap 'rm /tmp/playground-run-command-used;echo "";sleep 3;log "🧩 Displaying connector status";playground connector status' EXIT
+  trap 'rm /tmp/playground-run-command-used;echo "";sleep 3;playground connector status' EXIT
   touch /tmp/playground-run-command-used
   bash $filename
   ret=$?
@@ -6590,9 +6590,25 @@ playground_bootstrap_reproduction_model_command() {
   log "🌟 Command to run generated example"
   echo "playground run -f $repro_dir/$repro_test_filename"
   echo "playground run -f $repro_dir/$repro_test_filename" > /tmp/playground-run
+
+  if [ ! -z $EDITOR ]
+  then
+    log "📖 Opening ${repro_test_filename} using EDITOR environment variable"
+    $EDITOR $repro_dir/$repro_test_filename
+  else
+    if [[ $(type code 2>&1) =~ "not found" ]]
+    then
+      logerror "Could not determine an editor to use, you can set EDITOR environment variable with your preferred choice"
+      exit 1
+    else
+      log "📖 Opening ${repro_test_filename} with code (you can change editor by setting EDITOR environment variable)"
+      code $repro_dir/$repro_test_filename
+    fi
+  fi
+
   log "🕹️ Ready? Run it now ?"
   check_if_continue
-  playground run -f $repro_dir/$repro_test_filename --open
+  playground run -f $repro_dir/$repro_test_filename
 
 }
 
