🧠 Add playground connector translate command for "Translate Self Managed Connector Plugin Configurations to Fully Managed Connector Plugin Configurations" #7537

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -187,6 +187,7 @@ playground_usage() {
   printf "  %s   🧬 Set connect log level\n" "$(green "connector log-level")                       "
   printf "  %s   🕵️  Tail and follow connect logs\n" "$(green "connector logs")                            "
   printf "  %s   🤖 Open Fully Managed connector in browser (Confluent Cloud dashboard)\n" "$(green "connector open-ccloud-connector-in-browser")"
+  printf "  %s   💱 Translate Self Managed Connector Plugin Configurations to Fully Managed Connector Plugin Configuration\n" "$(green "connector translate")                       "
   printf "  %s   🧩 Run Kafka Connector Migration Utility (see https://github.com/confluentinc/connect-migration-utility/) on running connect cluster\n" "$(green "connector connect-migration-utility")       "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "connector create-or-update")                "
   printf "  %s   🛠️ Update connector configuration by opening current connector config in text editor set with playground config editor <editor> (default is code). Once file is saved, the new configuration is updated.\n" "$(green "connector update")                          "
@@ -529,7 +530,7 @@ playground_get_connector_plugin_usage() {
   printf "playground get-connector-plugin - Return some completion for connector plugin\n\n"
 
   printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground get-connector-plugin [CUR]\n"
+  printf "  playground get-connector-plugin [CUR] [TYPE]\n"
   printf "  playground get-connector-plugin --help | -h\n"
   echo
 
@@ -549,6 +550,11 @@ playground_get_connector_plugin_usage() {
     # :argument.usage
     printf "  %s\n" "$(blue "CUR")"
     printf "    correspond to completion $cur\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "TYPE")"
+    printf "    type (all, fm, onprem)\n"
     echo
 
   fi
@@ -6267,6 +6273,7 @@ playground_connector_usage() {
   printf "  %s   🔌 useful snippets\n" "$(green "snippets")                        "
   printf "  %s   🧑‍🎓 Open connector documentation of currently running conector(s)\n" "$(green "open-docs")                       "
   printf "  %s   🧬 Set connect log level\n" "$(green "log-level")                       "
+  printf "  %s   💱 Translate Self Managed Connector Plugin Configurations to Fully Managed Connector Plugin Configuration\n" "$(green "translate")                       "
   printf "  %s   🧩 Run Kafka Connector Migration Utility (see https://github.com/confluentinc/connect-migration-utility/) on running connect cluster\n" "$(green "connect-migration-utility")       "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")                "
   printf "  %s   🛠️ Update connector configuration by opening current connector config in text editor set with playground config editor <editor> (default is code). Once file is saved, the new configuration is updated.\n" "$(green "update")                          "
@@ -7280,6 +7287,49 @@ playground_connector_open_ccloud_connector_in_browser_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--browser BROWSER")"
     printf "    🌎 browser name\n    \n    Default browser from your system if not set\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_translate_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector translate\n\n"
+    printf "  💱 Translate Self Managed Connector Plugin Configurations to Fully Managed\n  Connector Plugin Configuration\n  \n  See\n  https://docs.confluent.io/cloud/current/api.html#tag/Managed-Connector-Plugins-(connectv1)/operation/translateConnectv1ConnectorPlugin\n  \n  The connector example should be ran with --environment flag set to <ccloud>\n\n"
+  else
+    printf "playground connector translate - 💱 Translate Self Managed Connector Plugin Configurations to Fully Managed Connector Plugin Configuration\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector translate [OPTIONS]\n"
+  printf "  playground connector translate --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector, -c CONNECTOR")"
+    printf "    🔗 Connector name\n    \n    🎓 Tip: If not specified, the command will apply to all connectors\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--verbose, -v")"
+    printf "    🐞 Show command being ran.\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector-plugin CONNECTOR-PLUGIN (required)")"
+    printf "    🔌 Connector plugin name\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
     echo
 
     # :command.usage_fixed_flags
@@ -8756,6 +8806,8 @@ function get_predefined_schemas_with_fzf() {
 
 function get_plugin_list() {
   cur="$1"
+  type="$2"
+
   fzf_version=$(get_fzf_version)
   if version_gt $fzf_version "0.38"
   then
@@ -8779,7 +8831,17 @@ function get_plugin_list() {
         exit 1
     fi
 
-  res=$(cat $root_folder/scripts/cli/confluent-hub-plugin-list.txt | grep -v "CONFLUENT EMPLOYEE VERSION" |cut -d "|" -f 1 | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🔌" --header="select connector plugin" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+  case "${type}" in
+    "fm")
+        res=$(cat $root_folder/scripts/cli/confluent-hub-plugin-list.txt | grep -v "CONFLUENT EMPLOYEE VERSION" | cut -d "|" -f 1 | grep "^confluentinc/" | grep -v "-" | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🔌" --header="select connector plugin" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+    ;;
+    "onprem")
+        res=$(cat $root_folder/scripts/cli/confluent-hub-plugin-list.txt | grep -v "CONFLUENT EMPLOYEE VERSION" |cut -d "|" -f 1 | grep "-" | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🔌" --header="select connector plugin" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+    ;;
+    *)
+        res=$(cat $root_folder/scripts/cli/confluent-hub-plugin-list.txt | grep -v "CONFLUENT EMPLOYEE VERSION" |cut -d "|" -f 1 | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🔌" --header="select connector plugin" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+    ;;
+  esac
 }
 
 function choose_connector_tag() {
@@ -13643,6 +13705,13 @@ function handle_ccloud_connect_rest_api () {
       elif echo "$curl_output" | jq 'has("errors")' 2> /dev/null | grep -q true
       then
         code=$(echo "$curl_output" | jq -r '.errors[0].status')
+
+        if [ "$code" == "null" ] || [ -z "$code" ]; then
+            # this happen in translate mode
+            echo "$curl_output" | jq .
+            return 0
+        fi
+
         message=$(echo "$curl_output" | jq -r '.errors[0].detail')
         logerror "Command failed with error code $code"
         logerror "$message"
@@ -14433,8 +14502,8 @@ playground_get_connector_plugin_command() {
 
   # src/commands/get-connector-plugin.sh
   cur="${args[cur]}"
-
-  get_plugin_list "$cur"
+  type="${args[type]}"
+  get_plugin_list "$cur" "$type"
 }
 
 # :command.function
@@ -29988,6 +30057,70 @@ playground_connector_open_ccloud_connector_in_browser_command() {
 }
 
 # :command.function
+playground_connector_translate_command() {
+
+  # src/commands/connector/translate.sh
+  connector="${args[--connector]}"
+  connector_plugin="${args[--connector-plugin]}"
+  verbose="${args[--verbose]}"
+
+  if [[ $connector_plugin == *"@"* ]]
+  then
+    connector_plugin=$(echo "$connector_plugin" | cut -d "@" -f 2)
+  fi
+
+  if [[ $connector_plugin == *"/"* ]]
+  then
+    connector_plugin=$(echo "$connector_plugin" | cut -d "/" -f 2)
+  fi
+
+  connector_type=$(playground state get run.connector_type)
+
+  if [[ ! -n "$connector" ]]
+  then
+      connector=$(playground get-connector-list)
+      if [ "$connector" == "" ]
+      then
+          log "💤 No $connector_type connector is running !"
+          exit 1
+      fi
+  fi
+
+  tmp_dir=$(mktemp -d -t pg-XXXXXXXXXX)
+  if [ -z "$PG_VERBOSE_MODE" ]
+  then
+      trap 'rm -rf $tmp_dir' EXIT
+  else
+      log "🐛📂 not deleting tmp dir $tmp_dir"
+  fi
+  json_file=$tmp_dir/connector.json
+
+  items=($connector)
+  length=${#items[@]}
+  if ((length > 1))
+  then
+      log "✨ --connector flag was not provided, applying command to all connectors"
+  fi
+  for connector in "${items[@]}"
+  do
+      playground --output-level WARN connector show-config --connector "$connector" --no-clipboard | grep -v "EOF" | sed 's/\\//g' >> $json_file
+      if [ $? -ne 0 ]
+      then
+          logerror "❌ playground connector show-config --connector $connector failed with:"
+          cat $file
+          exit 1
+      fi
+
+      # connector_class=$(cat "$json_file" | jq -r '."connector.class"')
+      # class=$(echo $connector_class | rev | cut -d '.' -f 1 | rev)
+
+      log "💱 Translating $connector_type connector $connector ($connector_plugin)"
+      get_ccloud_connect
+      handle_ccloud_connect_rest_api "curl -s --request PUT -H \"Content-Type: application/json\" --data @$json_file \"https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connector-plugins/$connector_plugin/config/translate\" --header \"authorization: Basic $authorization\""
+  done
+}
+
+# :command.function
 playground_connector_connect_migration_utility_discovery_command() {
 
   # src/commands/connector/connect-migration-utility/discovery.sh
@@ -32384,6 +32517,10 @@ playground_get_connector_plugin_parse_requirements() {
         # :argument.case
         if [[ -z ${args['cur']+x} ]]; then
           args['cur']=$1
+          shift
+        # :argument.case
+        elif [[ -z ${args['type']+x} ]]; then
+          args['type']=$1
           shift
         else
           printf "invalid argument: %s\n" "$key" >&2
@@ -45701,6 +45838,13 @@ playground_connector_parse_requirements() {
       shift $#
       ;;
 
+    translate)
+      action="translate"
+      shift
+      playground_connector_translate_parse_requirements "$@"
+      shift $#
+      ;;
+
     connect-migration-utility)
       action="connect-migration-utility"
       shift
@@ -47891,6 +48035,109 @@ playground_connector_open_ccloud_connector_in_browser_parse_requirements() {
 }
 
 # :command.parse_requirements
+playground_connector_translate_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_translate_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  missing_deps=
+  # :dependency.filter
+  if ! command -v confluent >/dev/null 2>&1; then
+    printf "missing dependency: confluent\n" >&2
+    printf "%s\n\n" "visit https://docs.confluent.io/confluent-cli/current/overview.html to install" >&2
+    missing_deps=1
+  else
+    deps['confluent']="$(command -v confluent | head -n1)"
+  fi
+
+  if [[ -n $missing_deps ]]; then
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="connector translate"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connector | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connector']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector requires an argument: --connector, -c CONNECTOR" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --verbose | -v)
+
+        # :flag.case_no_arg
+        args['--verbose']=1
+        shift
+        ;;
+
+      # :flag.case
+      --connector-plugin)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connector-plugin']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector-plugin requires an argument: --connector-plugin CONNECTOR-PLUGIN" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--connector-plugin']+x} ]]; then
+    printf "missing required flag: --connector-plugin CONNECTOR-PLUGIN\n" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
 playground_connector_connect_migration_utility_parse_requirements() {
   local key
 
@@ -49594,6 +49841,7 @@ run() {
     "connector log-level") playground_connector_log_level_command ;;
     "connector logs") playground_connector_logs_command ;;
     "connector open-ccloud-connector-in-browser") playground_connector_open_ccloud_connector_in_browser_command ;;
+    "connector translate") playground_connector_translate_command ;;
     "connector connect-migration-utility") playground_connector_connect_migration_utility_command ;;
     "connector connect-migration-utility discovery") playground_connector_connect_migration_utility_discovery_command ;;
     "connector connect-migration-utility migrate") playground_connector_connect_migration_utility_migrate_command ;;
