jq: error (at <stdin>:1): Cannot iterate over null (null) #4880

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -17049,30 +17049,38 @@ playground_fully_managed_connector_show_config_command() {
           log "🐞 curl command used"
           echo "curl $security -s -X GET -H "Content-Type: application/json" "https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector/config" --header "authorization: Basic $authorization""
       fi
-      json_config=$(curl $security -s -X GET -H "Content-Type: application/json" "https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector/config" --header "authorization: Basic $authorization")
-      echo "playground fully-managed-connector create-or-update --connector $connector << EOF"
-      echo "$json_config" | jq -S . | sed 's/\$/\\$/g'
-      echo "EOF"
-
-      if [[ "$OSTYPE" == "darwin"* ]]
+      curl_output=$(curl $security -s -X GET -H "Content-Type: application/json" "https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector/config" --header "authorization: Basic $authorization")
+      ret=$?
+      set -e
+      if [ $ret -eq 0 ]
       then
-          clipboard=$(playground config get clipboard)
-          if [ "$clipboard" == "" ]
-          then
-              playground config set clipboard true
-          fi
+          echo "playground fully-managed-connector create-or-update --connector $connector << EOF"
+          echo "$curl_output" | jq -S . | sed 's/\$/\\$/g'
+          echo "EOF"
 
-          if [ "$clipboard" == "true" ] || [ "$clipboard" == "" ]
+          if [[ "$OSTYPE" == "darwin"* ]]
           then
-              tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
-              trap 'rm -rf $tmp_dir' EXIT
-              echo "playground fully-managed-connector --connector $connector << EOF" > $tmp_dir/tmp
-              echo "$json_config" | jq -S . | sed 's/\$/\\$/g' >> $tmp_dir/tmp
-              echo "EOF" >> $tmp_dir/tmp
+              clipboard=$(playground config get clipboard)
+              if [ "$clipboard" == "" ]
+              then
+                  playground config set clipboard true
+              fi
 
-              cat $tmp_dir/tmp | pbcopy
-              log "📋 connector config has been copied to the clipboard (disable with 'playground config set clipboard false')"
+              if [ "$clipboard" == "true" ] || [ "$clipboard" == "" ]
+              then
+                  tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
+                  trap 'rm -rf $tmp_dir' EXIT
+                  echo "playground fully-managed-connector --connector $connector << EOF" > $tmp_dir/tmp
+                  echo "$curl_output" | jq -S . | sed 's/\$/\\$/g' >> $tmp_dir/tmp
+                  echo "EOF" >> $tmp_dir/tmp
+
+                  cat $tmp_dir/tmp | pbcopy
+                  log "📋 connector config has been copied to the clipboard (disable with 'playground config set clipboard false')"
+              fi
           fi
+      else
+          logerror "❌ curl request failed with error code $ret!"
+          exit 1
       fi
   done
 }
@@ -18074,30 +18082,48 @@ playground_connector_show_config_command() {
           log "🐞 curl command used"
           echo "curl $security -s -X GET -H "Content-Type: application/json" "$connect_url/connectors/$connector/config""
       fi
-      json_config=$(curl $security -s -X GET -H "Content-Type: application/json" "$connect_url/connectors/$connector/config")
-      echo "playground connector create-or-update --connector $connector << EOF"
-      echo "$json_config" | jq -S . | sed 's/\$/\\$/g'
-      echo "EOF"
-
-      if [[ "$OSTYPE" == "darwin"* ]]
+      curl_output=$(curl $security -s -X GET -H "Content-Type: application/json" "$connect_url/connectors/$connector/config")
+      ret=$?
+      set -e
+      if [ $ret -eq 0 ]
       then
-          clipboard=$(playground config get clipboard)
-          if [ "$clipboard" == "" ]
-          then
-              playground config set clipboard true
-          fi
+          if echo "$curl_output" | jq '. | has("error_code")' 2> /dev/null | grep -q true
 
-          if [ "$clipboard" == "true" ] || [ "$clipboard" == "" ]
           then
-              tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
-              trap 'rm -rf $tmp_dir' EXIT
-              echo "playground connector create-or-update --connector $connector << EOF" > $tmp_dir/tmp
-              echo "$json_config" | jq -S . | sed 's/\$/\\$/g' >> $tmp_dir/tmp
-              echo "EOF" >> $tmp_dir/tmp
+              error_code=$(echo "$curl_output" | jq -r .error_code)
+              message=$(echo "$curl_output" | jq -r .message)
+              logerror "Command failed with error code $error_code"
+              logerror "$message"
+              exit 1
+          else
+              echo "playground connector create-or-update --connector $connector << EOF"
+              echo "$curl_output" | jq -S . | sed 's/\$/\\$/g'
+              echo "EOF"
 
-              cat $tmp_dir/tmp | pbcopy
-              log "📋 connector config has been copied to the clipboard (disable with 'playground config set clipboard false')"
+              if [[ "$OSTYPE" == "darwin"* ]]
+              then
+                  clipboard=$(playground config get clipboard)
+                  if [ "$clipboard" == "" ]
+                  then
+                      playground config set clipboard true
+                  fi
+
+                  if [ "$clipboard" == "true" ] || [ "$clipboard" == "" ]
+                  then
+                      tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
+                      trap 'rm -rf $tmp_dir' EXIT
+                      echo "playground connector create-or-update --connector $connector << EOF" > $tmp_dir/tmp
+                      echo "$curl_output" | jq -S . | sed 's/\$/\\$/g' >> $tmp_dir/tmp
+                      echo "EOF" >> $tmp_dir/tmp
+
+                      cat $tmp_dir/tmp | pbcopy
+                      log "📋 connector config has been copied to the clipboard (disable with 'playground config set clipboard false')"
+                  fi
+              fi
           fi
+      else
+          logerror "❌ curl request failed with error code $ret!"
+          exit 1
       fi
   done
 }
