fix

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -14086,12 +14086,13 @@ playground_ccloud_connector_create_or_update_command() {
   set -e
   if [ $ret -eq 0 ]
   then
-      error_code=$(echo "$curl_output" | jq -r .error.code)
+      error_code=$(echo "$curl_output" | jq -r .error_code)
       if [ "$error_code" != "null" ]
       then
-          message=$(echo "$curl_output" | jq -r .error.message)
+          message=$(echo "$curl_output" | jq -r .message)
           logerror "Command failed with error code $error_code"
           logerror "$message"
+          exit 1
       else
           if [ $is_create == 1 ]
           then
@@ -14850,6 +14851,7 @@ playground_connector_create_or_update_command() {
           message=$(echo "$curl_output" | jq -r .message)
           logerror "Command failed with error code $error_code"
           logerror "$message"
+          exit 1
       else
           if [[ -n "$level" ]]
           then
