wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -7515,7 +7515,7 @@ function check_if_continue()
     case "$choice" in
     y|Y ) ;;
     n|N ) exit 1;;
-    * ) logerror "invalid response!";exit 1;;
+    * ) logerror "invalid response <$choice>!";exit 1;;
     esac
 }
 
@@ -18832,6 +18832,9 @@ playground_connector_show_lag_command() {
 
   get_security_broker "--command-config"
 
+  tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
+  trap 'rm -rf $tmp_dir' EXIT
+  lag_output=$tmp_dir/lag_output
   items=($connector)
   length=${#items[@]}
   if ((length > 1))
@@ -18858,26 +18861,32 @@ playground_connector_show_lag_command() {
     SECONDS=0
     while true
     do
-      lag_output=$(docker exec $container kafka-consumer-groups --bootstrap-server broker:9092 --group connect-$connector --describe $security | grep -v PARTITION | tr -d '\n')
+      docker exec $container kafka-consumer-groups --bootstrap-server broker:9092 --group connect-$connector --describe $security | grep -v PARTITION | sed '/^$/d' > $lag_output
       set +e
-      lag_not_set=$(echo "$lag_output" | awk -F" " '{ print $6 }' | grep "-")
+      lag_not_set=$(cat "$lag_output" | awk -F" " '{ print $6 }' | grep "-")
 
       if [ ! -z "$lag_not_set" ]
       then
         logwarn "🐢 consumer lag for connector $connector is not set"
-        echo "$lag_output" | awk -F" " '{ print "partition: "$3," current-offset: "$4," log-end-offset: "$5," lag: "$6 }'
+        cat "$lag_output" | awk -F" " '{ print "partition: "$3," current-offset: "$4," log-end-offset: "$5," lag: "$6 }' | sort -k2n | column -t
         sleep $CHECK_INTERVAL
       else
-        total_lag=$(echo "$lag_output" | grep -v "PARTITION" | awk -F" " '{sum+=$6;} END{print sum;}')
+        total_lag=$(cat "$lag_output" | grep -v "PARTITION" | awk -F" " '{sum+=$6;} END{print sum;}')
         if [ $total_lag -ne 0 ]
         then
-            log "🐢 consumer lag for connector $connector is $total_lag"
-            echo "$lag_output" | awk -F" " '{ print "partition: "$3," current-offset: "$4," log-end-offset: "$5," lag: "$6 }'
-            sleep $CHECK_INTERVAL
+          log "🐢 consumer lag for connector $connector is $total_lag"
+          cat "$lag_output" | awk -F" " '{ print "partition: "$3," current-offset: "$4," log-end-offset: "$5," lag: "$6 }' | sort -k2n | column -t
+          sleep $CHECK_INTERVAL
         else
+          if [[ ! -n "$wait_for_zero_lag" ]]
+          then
+            log "🏁 consumer lag for connector $connector is 0 !"
+          else
             ELAPSED="took: $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
             log "🏁 consumer lag for connector $connector is 0 ! $ELAPSED"
-            break
+          fi
+          cat "$lag_output" | awk -F" " '{ print "partition: "$3," current-offset: "$4," log-end-offset: "$5," lag: "$6 }' | sort -k2n | column -t
+          break
         fi
       fi
 
