ret

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -9832,13 +9832,16 @@ playground_ccloud_connector_create_or_update_command() {
       log "🔄 Updating connector $connector"
   fi
 
+  set +e
   curl_output=$(curl $security -s -X PUT \
        -H "Content-Type: application/json" \
        -H "authorization: Basic $authorization" \
        --data @$json_file \
        https://api.confluent.cloud/connect/v1/environments/$environment/clusters/$cluster/connectors/$connector/config)
 
-  if [ $? -eq 0 ]
+  ret=$?
+  set -e
+  if [ $ret -eq 0 ]
   then
       error_code=$(echo "$curl_output" | jq -r .error_code)
       if [ $error_code != "null" ]
@@ -9857,8 +9860,7 @@ playground_ccloud_connector_create_or_update_command() {
           playground ccloud-connector status
       fi
   else
-      logerror "❌ curl request failed !"
-      echo "$curl_output"
+      logerror "❌ curl request failed with error code $ret!"
       exit 1
   fi
 }
@@ -10319,12 +10321,14 @@ playground_connector_create_or_update_command() {
       log "🔄 Updating connector $connector"
   fi
 
+  set +e
   curl_output=$(curl $security -s -X PUT \
        -H "Content-Type: application/json" \
        --data @$json_file \
        $connect_url/connectors/$connector/config)
-
-  if [ $? -eq 0 ]
+  ret=$?
+  set -e
+  if [ $ret -eq 0 ]
   then
       error_code=$(echo "$curl_output" | jq -r .error_code)
       if [ $error_code != "null" ]
@@ -10343,8 +10347,7 @@ playground_connector_create_or_update_command() {
           playground connector status
       fi
   else
-      logerror "❌ curl request failed !"
-      echo "$curl_output"
+      logerror "❌ curl request failed with error code $ret!"
       exit 1
   fi
 }
