added playground connector logs

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -137,6 +137,7 @@ playground_usage() {
   printf "  %s   🔌 useful snippets\n" "$(green "connector snippets")              "
   printf "  %s   🧑‍🎓 Open connector documentation of currently running conector(s)\n" "$(green "connector open-docs")             "
   printf "  %s   🧬 Set connect log level\n" "$(green "connector log-level")             "
+  printf "  %s   🕵️  Tail and follow connect logs\n" "$(green "connector logs")                  "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "connector create-or-update")      "
   printf "  %s   🛠️ Update connector configuration by opening current connector config in text editor set with playground config editor <editor> (default is code). Once file is saved, the new configuration is updated.\n" "$(green "connector update")                "
   echo
@@ -4573,6 +4574,9 @@ playground_connector_usage() {
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")      "
   printf "  %s   🛠️ Update connector configuration by opening current connector config in text editor set with playground config editor <editor> (default is code). Once file is saved, the new configuration is updated.\n" "$(green "update")                "
   echo
+  printf "%s\n" "$(bold "Connect commands:")"
+  printf "  %s   🕵️  Tail and follow connect logs\n" "$(green "logs")                  "
+  echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
@@ -5382,6 +5386,60 @@ playground_connector_log_level_usage() {
     printf "  %s\n" "$(magenta "--level, -l LEVEL (required)")"
     printf "    ❕Log level\n"
     printf "    Allowed: INFO, WARN, DEBUG, TRACE\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_logs_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector logs\n"
+    echo
+
+    printf "  🕵️  Tail and follow connect logs\n  \n  This is basically a shortcut for \"playground container  logs --container\n  connect\"\n  \n  It does not work for Fully Managed conectors, except if you're a Confluent\n  employee, this will open log in our internal tools (make sure to follow this\n  first\n  https://github.com/confluentinc/kafka-docker-playground-internal#how-to-use)\n"
+    echo
+
+  else
+    printf "playground connector logs - 🕵️  Tail and follow connect logs\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector logs [OPTIONS]\n"
+  printf "  playground connector logs --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--open, -o")"
+    printf "    🔖 Save output to a file and open with text editor set with playground config\n    editor <editor> (default is code)\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--wait-for-log, -w LOG")"
+    printf "    😴 Wait until log appears\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--max-wait, -m MAX_WAIT")"
+    printf "    ⏳ Max time in seconds to wait when using --wait-for-log (default 600s)\n"
+    printf "    Default: 600\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--lcc-id LCC-ID")"
+    printf "    ☁️ Fully Managed lcc id (only for Confluent employees)\n"
     echo
 
     # :command.usage_fixed_flags
@@ -21967,6 +22025,91 @@ playground_connector_log_level_command() {
 }
 
 # :command.function
+playground_connector_logs_command() {
+  # src/commands/connector/logs.sh
+  open="${args[--open]}"
+  log="${args[--wait-for-log]}"
+  max_wait="${args[--max-wait]}"
+  lcc_id="${args[--lcc-id]}"
+
+  connector_type=$(playground state get run.connector_type)
+
+  if [ "$connector_type" == "$CONNECTOR_TYPE_CUSTOM" ]
+  then
+      logerror "🚨 This command is not supported for custom connectors"
+      exit 1
+  fi
+
+  opensearch_script="$root_folder/reproduction-models/_miscellaneous/opensearch/alfred-workflow/alfred-opensearch-connect-workflow/open-lcc-logs.ksh"
+  datadog_script="$root_folder/reproduction-models/_miscellaneous/opensearch/alfred-workflow/alfred-opensearch-connect-workflow/open-lcc-datadog.ksh"
+
+  if [[ -n "$lcc_id" ]]
+  then
+      if [ -f "$opensearch_script" ]
+      then
+          # confluent employee
+          export number_of_days=4
+          export open_audit_logs=1
+          log "🐛 Opening dashboards for $CONNECTOR_TYPE_CUSTOM connector ($lcc_id)"
+          bash "$opensearch_script" "$lcc_id"
+          bash "$datadog_script" "$lcc_id"
+          exit 0
+      else
+          logerror "🚨 This command with --lcc-id is not supported for non Confluent employees ($$root_folder/reproduction-models does not contain required scripts)"
+          exit 1
+      fi
+  fi
+
+  if [ "$connector_type" == "$CONNECTOR_TYPE_FULLY_MANAGED" ]
+  then
+      if [ -f "$opensearch_script" ]
+      then
+          # confluent employee
+          if [[ ! -n "$lcc_id" ]]
+          then
+              connector=$(playground get-connector-list)
+              if [ "$connector" == "" ]
+              then
+                  log "💤 No $connector_type connector is running !"
+                  exit 1
+              fi
+          fi
+
+          items=($connector)
+          length=${#items[@]}
+          if ((length > 1))
+          then
+              log "✨ --lcc-id flag was not provided, applying command to all $CONNECTOR_TYPE_FULLY_MANAGED connectors"
+          fi
+          export number_of_days=4
+          export open_audit_logs=1
+          for connector in ${items[@]}
+          do
+              log "🐛 Opening dashboards for $connector_type connector $connector ($connectorId)"
+              connectorId=$(get_ccloud_connector_lcc $connector)
+              bash "$opensearch_script" "$connectorId"
+              bash "$datadog_script" "$connectorId"
+          done
+
+      else
+          logerror "🚨 This command is not supported for fully managed connectors or non Confluent employees ($$root_folder/reproduction-models does not contain required scripts)"
+          exit 1
+      fi
+  else
+      if [[ -n "$open" ]]
+      then
+          playground container logs --open --container connect
+      elif [[ -n "$log" ]]
+      then
+          playground container logs --container connect --wait-for-log "$log" --max-wait "$max_wait"
+      else
+
+          playground container logs --container connect
+      fi
+  fi
+}
+
+# :command.function
 playground_connector_create_or_update_command() {
   # src/commands/connector/create-or-update.sh
   connector="${args[--connector]}"
@@ -30935,6 +31078,13 @@ playground_connector_parse_requirements() {
       shift $#
       ;;
 
+    logs)
+      action="logs"
+      shift
+      playground_connector_logs_parse_requirements "$@"
+      shift $#
+      ;;
+
     create-or-update)
       action="create-or-update"
       shift
@@ -32308,6 +32458,130 @@ playground_connector_log_level_parse_requirements() {
 }
 
 # :command.parse_requirements
+playground_connector_logs_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_logs_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector logs"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --open | -o)
+        # :flag.conflicts
+        if [[ -n "${args['--wait-for-log']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--wait-for-log" >&2
+          exit 1
+        fi
+
+        # :flag.case_no_arg
+        args['--open']=1
+        shift
+        ;;
+
+      # :flag.case
+      --wait-for-log | -w)
+        # :flag.conflicts
+        if [[ -n "${args['--open']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--open" >&2
+          exit 1
+        fi
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--wait-for-log']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--wait-for-log requires an argument: --wait-for-log, -w LOG" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --max-wait | -m)
+        # :flag.conflicts
+        if [[ -n "${args['--open']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--open" >&2
+          exit 1
+        fi
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--max-wait']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--max-wait requires an argument: --max-wait, -m MAX_WAIT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --lcc-id)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--lcc-id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--lcc-id requires an argument: --lcc-id LCC-ID" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--max-wait']:-} ]] || args['--max-wait']="600"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--wait-for-log'] && -n $(validate_not_empty "${args['--wait-for-log']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--wait-for-log, -w LOG" "$(validate_not_empty "${args['--wait-for-log']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--max-wait'] && -n $(validate_integer "${args['--max-wait']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--max-wait, -m MAX_WAIT" "$(validate_integer "${args['--max-wait']:-}")" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
 playground_connector_create_or_update_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -32677,6 +32951,7 @@ run() {
     "connector snippets") playground_connector_snippets_command ;;
     "connector open-docs") playground_connector_open_docs_command ;;
     "connector log-level") playground_connector_log_level_command ;;
+    "connector logs") playground_connector_logs_command ;;
     "connector create-or-update") playground_connector_create_or_update_command ;;
     "connector update") playground_connector_update_command ;;
   esac
