🧠 Add playground connector oracle-cdc-xstream debug command #6963

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -5648,6 +5648,7 @@ playground_connector_oracle_cdc_xstream_usage() {
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   ⚙️ Generate and open oracle cdc xstream connector diagnostics, see https://docs.confluent.io/kafka-connectors/oracle-xstream-cdc-source/current/troubleshooting.html#connector-diagnostics-script\n" "$(green "generate-report")"
+  printf "  %s   🐞 Execute various SQL commands to debug xstream components\n" "$(green "debug")          "
   echo
 
   # :command.long_usage
@@ -5674,6 +5675,32 @@ playground_connector_oracle_cdc_xstream_generate_report_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground connector oracle-cdc-xstream generate-report\n"
   printf "  playground connector oracle-cdc-xstream generate-report --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_oracle_cdc_xstream_debug_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector oracle-cdc-xstream debug\n\n"
+    printf "  🐞 Execute various SQL commands to debug xstream components\n\n"
+  else
+    printf "playground connector oracle-cdc-xstream debug - 🐞 Execute various SQL commands to debug xstream components\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector oracle-cdc-xstream debug\n"
+  printf "  playground connector oracle-cdc-xstream debug --help | -h\n"
   echo
 
   # :command.long_usage
@@ -24680,6 +24707,148 @@ EOF
 }
 
 # :command.function
+playground_connector_oracle_cdc_xstream_debug_command() {
+
+  # src/commands/connector/oracle-cdc-xstream/debug.sh
+  log "Monitoring session information about XStream Out components"
+
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    action "XStream Component",
+    sid, SERIAL#,
+    process "OS Process ID",
+    SUBSTR(program,INSTR(program,'(')+1,4) "Component Name"
+    FROM V\$SESSION
+    WHERE module ='XStream';
+EOF
+
+  log "View the status of each capture process"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    state,
+    total_messages_captured,
+    total_messages_enqueued
+    FROM V\$XSTREAM_CAPTURE;
+EOF
+
+  log "View the SCN values of each capture process"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    start_scn,captured_scn,
+    last_enqueued_scn,required_checkpoint_scn
+    FROM ALL_CAPTURE;
+EOF
+
+  log "View the latencies of each capture process"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    (capture_time - capture_message_create_time) * 86400 "Capture Latency Seconds",
+    (enqueue_time - enqueue_message_create_time) * 86400 "Enqueue Latency Seconds"
+    FROM V\$XSTREAM_CAPTURE;
+EOF
+
+  log "View redo log files required by each capture process"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    r.consumer_name "Capture Process Name",
+    r.source_database "Source Database",
+    r.sequence# "Sequence Number",
+    r.name "Archived Redo Log File Name"
+    FROM DBA_REGISTERED_ARCHIVED_LOG r,
+    ALL_CAPTURE c
+    WHERE r.consumer_name = c.capture_name AND
+    r.next_scn >= c.required_checkpoint_scn;
+EOF
+
+  log 'Important Views'
+  log 'V$XSTREAM_CAPTURE - displays information about each capture process that sends LCRs to an XStream outbound server (https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/V-XSTREAM_CAPTURE.html)'
+  log 'ALL_CAPTURE - displays information about the capture processes that enqueue the captured changes into queues accessible to the current user (https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/ALL_CAPTURE.html).'
+
+  log "View general information about outbound server"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    server_name "Outbound Server Name",
+    capture_name "Capture Process Name",
+    connect_user, capture_user,
+    queue_owner, queue_name
+    FROM ALL_XSTREAM_OUTBOUND;
+EOF
+
+  log "View information on outbound server current transaction"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    xidusn ||'.'|| xidslt ||'.'|| xidsqn "Transaction ID",
+    commitscn, commit_position,
+    last_sent_position,
+    message_sequence
+    FROM V\$XSTREAM_OUTBOUND_SERVER;
+EOF
+
+  log "View processed low position for an outbound server"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    processed_low_position,
+    TO_CHAR(processed_low_time,'HH24:MI:SS MM/DD/YY') processed_low_time
+    FROM ALL_XSTREAM_OUTBOUND_PROGRESS;
+EOF
+
+  log 'Important Views'
+  log 'V$XSTREAM_OUTBOUND_SERVER - displays statistics about an outbound server (https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/V-XSTREAM_OUTBOUND_SERVER.html)'
+  log 'ALL_XSTREAM_OUTBOUND - displays information about the XStream outbound servers (https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/ALL_XSTREAM_OUTBOUND.html)'
+  log 'ALL_XSTREAM_OUTBOUND_PROGRESS - displays information about the progress made by the XStream outbound servers (https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/ALL_XSTREAM_OUTBOUND_PROGRESS.html)'
+
+  log "View capture parameter settings"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    c.capture_name,
+    parameter, value,
+    set_by_user
+    FROM ALL_CAPTURE_PARAMETERS c,
+    ALL_XSTREAM_OUTBOUND o
+    WHERE c.capture_name = o.capture_name
+    ORDER BY parameter;
+EOF
+
+  log "View apply (outbound server) parameter settings"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    c.capture_name,
+    parameter, value,
+    set_by_user
+    FROM ALL_CAPTURE_PARAMETERS c,
+    ALL_XSTREAM_OUTBOUND o
+    WHERE c.capture_name = o.capture_name
+
+    ORDER BY parameter;
+EOF
+
+  log "View the rules used by XStream components"
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+    CONNECT sys/Admin123 AS SYSDBA
+    SELECT
+    streams_name "XStream Component Name",
+    streams_type "XStream Component Type",
+    rule_name,
+    rule_set_type,
+    streams_rule_type,
+    schema_name,
+    object_name,
+    rule_type
+    FROM ALL_XSTREAM_RULES;
+EOF
+}
+
+# :command.function
 playground_connector_offsets_get_command() {
 
   # src/commands/connector/offsets/get.sh
@@ -40885,6 +41054,13 @@ playground_connector_oracle_cdc_xstream_parse_requirements() {
       shift $#
       ;;
 
+    debug)
+      action="debug"
+      shift
+      playground_connector_oracle_cdc_xstream_debug_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_connector_oracle_cdc_xstream_usage >&2
@@ -40949,6 +41125,51 @@ playground_connector_oracle_cdc_xstream_generate_report_parse_requirements() {
 
   # :command.command_filter
   action="connector oracle-cdc-xstream generate-report"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_connector_oracle_cdc_xstream_debug_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_oracle_cdc_xstream_debug_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector oracle-cdc-xstream debug"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -43923,6 +44144,7 @@ run() {
     "connector status") playground_connector_status_command ;;
     "connector oracle-cdc-xstream") playground_connector_oracle_cdc_xstream_command ;;
     "connector oracle-cdc-xstream generate-report") playground_connector_oracle_cdc_xstream_generate_report_command ;;
+    "connector oracle-cdc-xstream debug") playground_connector_oracle_cdc_xstream_debug_command ;;
     "connector offsets") playground_connector_offsets_command ;;
     "connector offsets get") playground_connector_offsets_get_command ;;
     "connector offsets reset") playground_connector_offsets_reset_command ;;
