Better error handling for create-or-update-connector when CLOUD_API_KEY is wrong #5275

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -20305,7 +20305,16 @@ playground_connector_create_or_update_command() {
   fi
 
   is_create=1
+  set +e
   connectors=$(playground get-connector-list)
+  ret=$?
+  if [ $ret -ne 0 ]
+  then
+      logerror "❌ Failed to get list of connectors"
+      playground get-connector-list
+      exit 1
+  fi
+  set -e
   items=($connectors)
   for con in ${items[@]}
   do
