👾 Add playground connector-plugin sourcecode commands #7214

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -5671,9 +5671,8 @@ playground_connector_plugin_sourcecode_open_usage() {
     echo
 
     # :flag.usage
-    printf "  %s\n" "$(magenta "--connector-tag CONNECTOR_TAG")"
-    printf "    🔗 Connector version to use\n    \n    By default, for each connector, the latest available version on Confluent\n    Hub is used\n    \n    🎓 Tip: set to \" \" in order to select the version dynamically\n"
-    printf "    %s\n" "Conflicts: --connector-zip"
+    printf "  %s\n" "$(magenta "--connector-tag CONNECTOR_TAG (repeatable)")"
+    printf "    🔗 Connector version to use\n    \n    By default, for each connector, the latest available version on Confluent\n    Hub is used\n    \n    🎓 Tip: set to \" \" in order to select the version dynamically\n    \n    🎓 Tip: you can compare different sourcecode versions by specifying\n    --connector-tag two times, in such case it will open github in comparison\n    mode\n"
     echo
 
     # :command.usage_fixed_flags
@@ -24561,22 +24560,14 @@ playground_connector_plugin_sourcecode_open_command() {
 
   # src/commands/connector-plugin/sourcecode/open.sh
   connector_plugin="${args[--connector-plugin]}"
-  connector_tag="${args[--connector-tag]}"
+  connector_tags="${args[--connector-tag]}"
+
+  # Convert space-separated string to array
+  IFS=' ' read -ra connector_tag_array <<< "$connector_tags"
 
   if [[ $connector_plugin == *"@"* ]]
   then
     connector_plugin=$(echo "$connector_plugin" | cut -d "@" -f 2)
-  fi
-
-  if [[ -n "$connector_tag" ]]
-  then
-      if [ "$connector_tag" == " " ]
-      then
-          ret=$(choose_connector_tag "$connector_plugin")
-          connector_tag=$(echo "$ret" | cut -d ' ' -f 2 | sed 's/^v//')
-      fi
-  else
-      connector_tag="latest"
   fi
 
   if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
@@ -24587,7 +24578,7 @@ playground_connector_plugin_sourcecode_open_command() {
 
   if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
   then
-      logerror "file $root_folder/scripts/cli/confluent-hub-plugin-list.txt could not be generated"
+      logerror "❌ file $root_folder/scripts/cli/confluent-hub-plugin-list.txt could not be generated"
       exit 1
   fi
 
@@ -24598,6 +24589,7 @@ playground_connector_plugin_sourcecode_open_command() {
   if [ $ret -ne 0 ]
   then
       logerror "❌ could not found $connector_plugin in $root_folder/scripts/cli/confluent-hub-plugin-list.txt"
+      logerror "❌ the file can be re-generated with <playground generate-connector-plugin-list>"
       exit 1
   fi
 
@@ -24605,12 +24597,92 @@ playground_connector_plugin_sourcecode_open_command() {
   if [ "$sourcecode_url" == "null" ] || [ "$sourcecode_url" == "" ]
   then
       logerror "❌ could not found sourcecode url for plugin $connector_plugin. It is probably proprietary"
+      if [[ "$sourcecode_url" == *"confluentinc"* ]]
+      then
+          logerror "❌ if you're a Confluent employee, make sure your aws creds are set and then run <playground generate-connector-plugin-list>"
+      fi
       exit 1
   fi
 
-  if [ "$connector_tag" != "latest" ] && [[ "$sourcecode_url" == *"github.com"* ]]
+  comparison_mode_versions=""
+  length=${#connector_tag_array[@]}
+  if ((length > 1))
   then
-      sourcecode_url="$sourcecode_url/tree/v$connector_tag"
+      if ((length > 2))
+      then
+          logerror "❌ --connector-tag can only be set 2 times"
+          exit 1
+      fi
+      if [[ "$sourcecode_url" != *"github.com"* ]]
+      then
+          logerror "❌ --connector-tag flag is set 2 times, but sourcecode is not hosted on github, comparison between version can only works with github"
+          exit 1
+      fi
+      connector_tag1="${connector_tag_array[0]}"
+      connector_tag2="${connector_tag_array[1]}"
+      if [ "$connector_tag1" == "latest" ]
+      then
+          output=$(playground connector-plugin versions --connector-plugin "$connector_plugin" --last 1 | head -n 1)
+          last_version=$(echo "$output" | grep -v "<unknown>" | cut -d " " -f 2 | cut -d "v" -f 2)
+          if [[ -n "$last_version" ]]
+          then
+              log "✨ --connector-tag was not set, using latest version on hub $last_version"
+              connector_tag1="$last_version"
+          else
+              logwarn "could not find latest version using <playground connector-plugin versions --connector-plugin \"$connector_plugin\" --last 1>"
+              logerror "❌ --connector-tag flag is set 2 times, but one of them is set to latest. Comparison between version can only works when providing versions"
+              exit 1
+          fi
+      fi
+      if [ "$connector_tag2" == "latest" ]
+      then
+          output=$(playground connector-plugin versions --connector-plugin "$connector_plugin" --last 1 | head -n 1)
+          last_version=$(echo "$output" | grep -v "<unknown>" | cut -d " " -f 2 | cut -d "v" -f 2)
+          if [[ -n "$last_version" ]]
+          then
+              log "✨ --connector-tag was not set, using latest version on hub $last_version"
+              connector_tag2="$last_version"
+          else
+              logwarn "could not find latest version using <playground connector-plugin versions --connector-plugin \"$connector_plugin\" --last 1>"
+              logerror "❌ --connector-tag flag is set 2 times, but one of them is set to latest. Comparison between version can only works when providing versions"
+              exit 1
+          fi
+      fi
+      log "✨ --connector-tag flag is set 2 times, comparison mode will be opened with versions v$connector_tag1 and v$connector_tag2"
+      comparison_mode_versions="v$connector_tag1...v$connector_tag2"
+  else
+      connector_tag=$connector_tag1
+      if [[ -n "$connector_tag" ]]
+      then
+          if [ "$connector_tag" == " " ]
+          then
+              ret=$(choose_connector_tag "$connector_plugin")
+              connector_tag=$(echo "$ret" | cut -d ' ' -f 2 | sed 's/^v//')
+          fi
+      else
+          output=$(playground connector-plugin versions --connector-plugin "$connector_plugin" --last 1 | head -n 1)
+          last_version=$(echo "$output" | grep -v "<unknown>" | cut -d " " -f 2 | cut -d "v" -f 2)
+          if [[ -n "$last_version" ]]
+          then
+              log "✨ --connector-tag was not set, using latest version on hub $last_version"
+              connector_tag="$last_version"
+          else
+              logwarn "could not find latest version using <playground connector-plugin versions --connector-plugin \"$connector_plugin\" --last 1>, using latest"
+              connector_tag="latest"
+          fi
+      fi
+  fi
+
+  if [ "$comparison_mode_versions" != "" ]
+  then
+      additional_text=", comparing v$connector_tag1 and v$connector_tag2"
+      sourcecode_url="$sourcecode_url/compare/$comparison_mode_versions"
+  else
+      additional_text=" for $connector_tag version"
+      if [ "$connector_tag" != "latest" ] && [[ "$sourcecode_url" == *"github.com"* ]]
+      then
+          sourcecode_url="$sourcecode_url/tree/v$connector_tag"
+      fi
   fi
 
   if [[ $(type -f open 2>&1) =~ "not found" ]]
@@ -24618,7 +24690,7 @@ playground_connector_plugin_sourcecode_open_command() {
       log "🔗 Cannot open browser, use url:"
       echo "$sourcecode_url"
   else
-      log "🧑‍💻 Openening sourcecode url $sourcecode_url for plugin $connector_plugin in browser for $connector_tag version"
+      log "🧑‍💻🌐 Opening sourcecode url $sourcecode_url for plugin $connector_plugin in browser$additional_text"
       open "$sourcecode_url"
   fi
 }
@@ -41405,15 +41477,15 @@ playground_connector_plugin_sourcecode_open_parse_requirements() {
 
       # :flag.case
       --connector-tag)
-        # :flag.conflicts
-        if [[ -n "${args['--connector-zip']:-}" ]]; then
-          printf "conflicting options: %s cannot be used with %s\n" "$key" "--connector-zip" >&2
-          exit 1
-        fi
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          args['--connector-tag']="$2"
+          escaped="$(printf '%q' "$2")"
+          if [[ -z ${args['--connector-tag']+x} ]]; then
+            args['--connector-tag']="$escaped"
+          else
+            args['--connector-tag']="${args['--connector-tag']} $escaped"
+          fi
           shift
           shift
         else
