🧠 Add playground open-changelog command #6534

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -50,6 +50,7 @@ playground_usage() {
   printf "  %s   🧨 Remove all docker images (including docker volumes)\n" "$(green "remove-all-docker-images")                  "
   printf "  %s   🧼 playground is actively caching ccloud details (https://kafka-docker-playground.io/#/how-to-use?id=%%f0%%9f%%8c%%a4%%ef%%b8%%8f-confluent-cloud-examples)\n" "$(green "cleanup-cloud-details")                     "
   printf "  %s   🧑‍🎓 Open Confluent documentation of currently running example\n" "$(green "open-docs")                                 "
+  printf "  %s   📜 Open playground changelog (https://kafka-docker-playground.io/#/changelog)\n" "$(green "open-changelog")                            "
   printf "  %s   🧹 Cleanup cloud resources that were created by running examples from the playground\n" "$(green "cleanup-cloud-resources")                   "
   echo
   printf "%s\n" "$(bold "Repro commands:")"
@@ -2260,6 +2261,33 @@ playground_open_docs_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground open-docs [OPTIONS]\n"
   printf "  playground open-docs --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--only-show-url")"
+    printf "    🌐 Only show url\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_open_changelog_usage() {
+  printf "playground open-changelog - 📜 Open playground changelog (https://kafka-docker-playground.io/#/changelog)\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground open-changelog [OPTIONS]\n"
+  printf "  playground open-changelog --help | -h\n"
   echo
 
   # :command.long_usage
@@ -17182,6 +17210,22 @@ playground_open_docs_command() {
 }
 
 # :command.function
+playground_open_changelog_command() {
+
+  # src/commands/open-changelog.sh
+  only_show_url="${args[--only-show-url]}"
+
+  if [[ -n "$only_show_url" ]] || [[ $(type -f open 2>&1) =~ "not found" ]]
+  then
+      log "📜 changelog is available at:"
+      echo "https://kafka-docker-playground.io/#/changelog"
+  else
+      log "📜 opening changelog https://kafka-docker-playground.io/#/changelog"
+      open "https://kafka-docker-playground.io/#/changelog"
+  fi
+}
+
+# :command.function
 playground_cleanup_cloud_resources_command() {
 
   # src/commands/cleanup-cloud-resources.sh
@@ -27321,6 +27365,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    open-changelog)
+      action="open-changelog"
+      shift
+      playground_open_changelog_parse_requirements "$@"
+      shift $#
+      ;;
+
     cleanup-cloud-resources)
       action="cleanup-cloud-resources"
       shift
@@ -31698,6 +31749,58 @@ playground_open_docs_parse_requirements() {
 
   # :command.command_filter
   action="open-docs"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --only-show-url)
+
+        # :flag.case_no_arg
+        args['--only-show-url']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_open_changelog_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_open_changelog_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="open-changelog"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -42035,6 +42138,7 @@ run() {
     "remove-all-docker-images") playground_remove_all_docker_images_command ;;
     "cleanup-cloud-details") playground_cleanup_cloud_details_command ;;
     "open-docs") playground_open_docs_command ;;
+    "open-changelog") playground_open_changelog_command ;;
     "cleanup-cloud-resources") playground_cleanup_cloud_resources_command ;;
     "repro") playground_repro_command ;;
     "repro export") playground_repro_export_command ;;
