sync

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -170,7 +170,7 @@ playground_usage() {
   printf "  %s   🟢 Start an EC2 instance\n" "$(green "ec2 start")                                "
   printf "  %s   🔴 Stop all your EC2 instance(s)\n" "$(green "ec2 stop-all")                             "
   printf "  %s   🟢 Start all your EC2 instance(s)\n" "$(green "ec2 start-all")                            "
-  printf "  %s   🛸 Sync local reproduction-models folder to ec2 instance using rsync\n" "$(green "ec2 sync-repro-folder-to-ec2")             "
+  printf "  %s   ↔️ Synchronize reproduction-models folder bewteen local and ec2 instance\n" "$(green "ec2 sync-repro-folder")                    "
   echo
 
   # :command.long_usage
@@ -5581,16 +5581,16 @@ playground_ec2_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
-  printf "  %s   👷 Create kafka-docker-playground EC2 instance using AWS Cloud Formation\n" "$(green "create")                  "
-  printf "  %s   ❌ Delete an EC2 instance created with Cloud Formation\n" "$(green "delete")                  "
-  printf "  %s   👨‍💻 Open an EC2 instance using Visual Studio code\n" "$(green "open")                    "
-  printf "  %s   🛂 Allow your current ip to connect to ec2 instance via ssh\n" "$(green "allow-my-ip")             "
-  printf "  %s   🔘 List all EC2 instance\n" "$(green "list")                    "
-  printf "  %s   🔴 Stop an EC2 instance\n" "$(green "stop")                    "
-  printf "  %s   🟢 Start an EC2 instance\n" "$(green "start")                   "
-  printf "  %s   🔴 Stop all your EC2 instance(s)\n" "$(green "stop-all")                "
-  printf "  %s   🟢 Start all your EC2 instance(s)\n" "$(green "start-all")               "
-  printf "  %s   🛸 Sync local reproduction-models folder to ec2 instance using rsync\n" "$(green "sync-repro-folder-to-ec2")"
+  printf "  %s   👷 Create kafka-docker-playground EC2 instance using AWS Cloud Formation\n" "$(green "create")           "
+  printf "  %s   ❌ Delete an EC2 instance created with Cloud Formation\n" "$(green "delete")           "
+  printf "  %s   👨‍💻 Open an EC2 instance using Visual Studio code\n" "$(green "open")             "
+  printf "  %s   🛂 Allow your current ip to connect to ec2 instance via ssh\n" "$(green "allow-my-ip")      "
+  printf "  %s   🔘 List all EC2 instance\n" "$(green "list")             "
+  printf "  %s   🔴 Stop an EC2 instance\n" "$(green "stop")             "
+  printf "  %s   🟢 Start an EC2 instance\n" "$(green "start")            "
+  printf "  %s   🔴 Stop all your EC2 instance(s)\n" "$(green "stop-all")         "
+  printf "  %s   🟢 Start all your EC2 instance(s)\n" "$(green "start-all")        "
+  printf "  %s   ↔️ Synchronize reproduction-models folder bewteen local and ec2 instance\n" "$(green "sync-repro-folder")"
   echo
 
   # :command.long_usage
@@ -5911,12 +5911,70 @@ playground_ec2_status_usage() {
 }
 
 # :command.usage
-playground_ec2_sync_repro_folder_to_ec2_usage() {
-  printf "playground ec2 sync-repro-folder-to-ec2 - 🛸 Sync local reproduction-models folder to ec2 instance using rsync\n\n"
+playground_ec2_sync_repro_folder_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground ec2 sync-repro-folder\n\n"
+    printf "  ↔️ Synchronize reproduction-models folder bewteen local and ec2 instance\n  \n  Note: rsync needs to be installed\n\n"
+  else
+    printf "playground ec2 sync-repro-folder - ↔️ Synchronize reproduction-models folder bewteen local and ec2 instance\n\n"
+  fi
 
   printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground ec2 sync-repro-folder-to-ec2 [OPTIONS]\n"
-  printf "  playground ec2 sync-repro-folder-to-ec2 --help | -h\n"
+  printf "  playground ec2 sync-repro-folder COMMAND\n"
+  printf "  playground ec2 sync-repro-folder [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "$(bold "== Commands ==")"
+  printf "  %s   👉 Sync local reproduction-models folder to ec2 instance\n" "$(green "local-to-ec2")"
+  printf "  %s   👈 Sync ec2 instance reproduction-models folder to local\n" "$(green "ec2-to-local")"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ec2_sync_repro_folder_local_to_ec2_usage() {
+  printf "playground ec2 sync-repro-folder local-to-ec2 - 👉 Sync local reproduction-models folder to ec2 instance\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ec2 sync-repro-folder local-to-ec2 [OPTIONS]\n"
+  printf "  playground ec2 sync-repro-folder local-to-ec2 --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--instance, -i INSTANCE (required)")"
+    printf "    🖥️ EC2 instance (need to use completion to get all required details)\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ec2_sync_repro_folder_ec2_to_local_usage() {
+  printf "playground ec2 sync-repro-folder ec2-to-local - 👈 Sync ec2 instance reproduction-models folder to local\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ec2 sync-repro-folder ec2-to-local [OPTIONS]\n"
+  printf "  playground ec2 sync-repro-folder ec2-to-local --help | -h\n"
   echo
 
   # :command.long_usage
@@ -24503,8 +24561,8 @@ playground_ec2_status_command() {
 }
 
 # :command.function
-playground_ec2_sync_repro_folder_to_ec2_command() {
-  # src/commands/ec2/sync-repro-folder-to-ec2.sh
+playground_ec2_sync_repro_folder_local_to_ec2_command() {
+  # src/commands/ec2/sync-repro-folder/local-to-ec2.sh
   instance="${args[--instance]}"
 
   if [[ $instance == *"@"* ]]
@@ -24512,20 +24570,45 @@ playground_ec2_sync_repro_folder_to_ec2_command() {
       instance=$(echo "$instance" | cut -d "@" -f 2)
   fi
   name=$(echo "${instance}" | cut -d "/" -f 1)
-  state=$(echo "${instance}" | cut -d "/" -f 2)
   ip=$(echo "${instance}" | cut -d "/" -f 3)
-  id=$(echo "${instance}" | cut -d "/" -f 4)
 
   pem_file="$root_folder/$name.pem"
   username=$(whoami)
 
   if [ ! -f "$pem_file" ]
   then
-      logerror "❌ AWS EC2 pem file $pem_file file does not exist"
+      logerror "❌ aws ec2 pem file $pem_file file does not exist"
       exit 1
   fi
 
+  log "👉 Sync local reproduction-models folder to ec2 instance $name"
   rsync -cau --filter=':- .gitignore' -e "ssh -i $pem_file" "$root_folder/reproduction-models" "$username@$ip:/home/$username/kafka-docker-playground"
+}
+
+# :command.function
+playground_ec2_sync_repro_folder_ec2_to_local_command() {
+  # src/commands/ec2/sync-repro-folder/ec2-to-local.sh
+  instance="${args[--instance]}"
+
+  if [[ $instance == *"@"* ]]
+  then
+      instance=$(echo "$instance" | cut -d "@" -f 2)
+  fi
+  name=$(echo "${instance}" | cut -d "/" -f 1)
+  ip=$(echo "${instance}" | cut -d "/" -f 3)
+
+  pem_file="$root_folder/$name.pem"
+  username=$(whoami)
+
+  if [ ! -f "$pem_file" ]
+  then
+      logerror "❌ aws ec2 pem file $pem_file file does not exist"
+      exit 1
+  fi
+
+  log "👈 Sync ec2 instance $name reproduction-models folder to local"
+  rsync -cau --filter=':- .gitignore' -e "ssh -i $pem_file" "$username@$ip:/home/$username/kafka-docker-playground/reproduction-models" "$root_folder"
+
 }
 
 # :command.parse_requirements
@@ -37040,10 +37123,10 @@ playground_ec2_parse_requirements() {
       shift $#
       ;;
 
-    sync-repro-folder-to-ec2)
-      action="sync-repro-folder-to-ec2"
+    sync-repro-folder)
+      action="sync-repro-folder"
       shift
-      playground_ec2_sync_repro_folder_to_ec2_parse_requirements "$@"
+      playground_ec2_sync_repro_folder_parse_requirements "$@"
       shift $#
       ;;
 
@@ -37796,13 +37879,13 @@ playground_ec2_status_parse_requirements() {
 }
 
 # :command.parse_requirements
-playground_ec2_sync_repro_folder_to_ec2_parse_requirements() {
+playground_ec2_sync_repro_folder_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        playground_ec2_sync_repro_folder_to_ec2_usage
+        playground_ec2_sync_repro_folder_usage
         exit
         ;;
 
@@ -37823,7 +37906,151 @@ playground_ec2_sync_repro_folder_to_ec2_parse_requirements() {
   fi
 
   # :command.command_filter
-  action="ec2 sync-repro-folder-to-ec2"
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    local-to-ec2)
+      action="local-to-ec2"
+      shift
+      playground_ec2_sync_repro_folder_local_to_ec2_parse_requirements "$@"
+      shift $#
+      ;;
+
+    ec2-to-local)
+      action="ec2-to-local"
+      shift
+      playground_ec2_sync_repro_folder_ec2_to_local_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      playground_ec2_sync_repro_folder_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_ec2_sync_repro_folder_local_to_ec2_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ec2_sync_repro_folder_local_to_ec2_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="ec2 sync-repro-folder local-to-ec2"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --instance | -i)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--instance']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--instance requires an argument: --instance, -i INSTANCE" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--instance']+x} ]]; then
+    printf "missing required flag: --instance, -i INSTANCE\n" >&2
+    exit 1
+  fi
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--instance'] && -n $(validate_not_empty "${args['--instance']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--instance, -i INSTANCE" "$(validate_not_empty "${args['--instance']:-}")" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_ec2_sync_repro_folder_ec2_to_local_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_ec2_sync_repro_folder_ec2_to_local_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="ec2 sync-repro-folder ec2-to-local"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -38082,7 +38309,9 @@ run() {
     "ec2 stop-all") playground_ec2_stop_all_command ;;
     "ec2 start-all") playground_ec2_start_all_command ;;
     "ec2 status") playground_ec2_status_command ;;
-    "ec2 sync-repro-folder-to-ec2") playground_ec2_sync_repro_folder_to_ec2_command ;;
+    "ec2 sync-repro-folder") playground_ec2_sync_repro_folder_command ;;
+    "ec2 sync-repro-folder local-to-ec2") playground_ec2_sync_repro_folder_local_to_ec2_command ;;
+    "ec2 sync-repro-folder ec2-to-local") playground_ec2_sync_repro_folder_ec2_to_local_command ;;
   esac
 }
 
