wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -9622,72 +9622,97 @@ playground_topic_produce_command() {
 
   if grep -q "proto3" $schema_file
   then
-      log "schema was detected as protobuf"
+      log "🔮 schema was identified as protobuf"
       value_type=protobuf
   elif grep -q "\$schema" $schema_file
   then
-      log "schema was detected as json schema"
+      log "🔮 schema was identified as json schema"
       value_type=json-schema
   elif grep -q "_meta" $schema_file
   then
-      log "schema was detected as json"
+      log "🔮 schema was identified as json"
       value_type=json
   elif grep -q "\"type\"\s*:\s*\"record\"" $schema_file
   then
-      log "schema was detected as avro"
+      log "🔮 schema was identified as avro"
       value_type=avro
   else
-      logerror "Could not detect schema type for $schema_file"
+      logerror "❌ Could not detect schema type for $schema_file"
       cat $schema_file
       exit 1
   fi
 
   case "${value_type}" in
-  json)
-      # https://github.com/MaterializeInc/datagen
-      docker run --rm -i -v $schema_file:/app/schema.json materialize/datagen -s schema.json -n $nb_messages --dry-run | grep "Payload: " | awk '{print $2}' > $tmp_dir/out.json
-      #--record-size 104
-  ;;
+      json)
+          # https://github.com/MaterializeInc/datagen
+          set +e
+          docker run --rm -i -v $schema_file:/app/schema.json materialize/datagen -s schema.json -n $nb_messages --dry-run > $tmp_dir/result.log
 
-  avro)
-      docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools random /tmp/out.avro --schema-file /tmp/value_schema --count $nb_messages
-      docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools tojson /tmp/out.avro > $tmp_dir/out.json
-  ;;
-  avro-with-key)
+          nb=$(grep -c "Payload: " $tmp_dir/result.log)
+          if [ $nb -eq 0 ]
+          then
+              logerror "❌ materialize/datagen failed to produce json "
+              cat $tmp_dir/result.log
+              exit 1
+          fi
+          set -e
+          cat $tmp_dir/result.log | grep "Payload: " | awk '{print $2}' > $tmp_dir/out.json
+          #--record-size 104
+      ;;
 
-  ;;
-  json-schema)
-      docker run --rm -v $tmp_dir:/tmp/ -e NB_MESSAGES=$nb_messages vdesabou/json-schema-faker > $tmp_dir/out.json
-  ;;
-  json-schema-with-key)
+      avro)
+          docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools random /tmp/out.avro --schema-file /tmp/value_schema --count $nb_messages
+          docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools tojson /tmp/out.avro > $tmp_dir/out.json
+      ;;
+      avro-with-key)
 
-  ;;
-  protobuf)
-      # https://github.com/JasonkayZK/mock-protobuf.js
-      docker run --rm -v $tmp_dir:/tmp/ -v $schema_file:/app/schema.proto -e NB_MESSAGES=$nb_messages vdesabou/protobuf-faker  > $tmp_dir/out.json
-  ;;
-  protobuf-with-key)
+      ;;
+      json-schema)
+          docker run --rm -v $tmp_dir:/tmp/ -e NB_MESSAGES=$nb_messages vdesabou/json-schema-faker > $tmp_dir/out.json
+      ;;
+      json-schema-with-key)
 
-  ;;
-  none)
-  ;;
-  *)
-      logerror "value_type name not valid ! Should be one of json, avro, avro-with-key, json-schema, json-schema-with-key, protobuf or protobuf-with-key"
-      exit 1
-  ;;
+      ;;
+      protobuf)
+          # https://github.com/JasonkayZK/mock-protobuf.js
+          docker run --rm -v $tmp_dir:/tmp/ -v $schema_file:/app/schema.proto -e NB_MESSAGES=$nb_messages vdesabou/protobuf-faker  > $tmp_dir/out.json
+      ;;
+      protobuf-with-key)
+
+      ;;
+      none)
+      ;;
+      *)
+          logerror "❌ value_type name not valid ! Should be one of json, avro, avro-with-key, json-schema, json-schema-with-key, protobuf or protobuf-with-key"
+          exit 1
+      ;;
   esac
 
-  log "payload is"
-  cat $tmp_dir/out.json
+  nb_generated_messages=$(wc -l < $tmp_dir/out.json)
+  nb_generated_messages=${nb_generated_messages// /}
 
-  log "Producing data"
+  if [ "$nb_generated_messages" == "0" ]
+  then
+      logerror "❌ records could not be generated!"
+      exit 1
+  fi
+
+  log "✨ $nb_generated_messages records were generated"
+  if (( nb_generated_messages < 50 ))
+  then
+      cat $tmp_dir/out.json
+  else
+      head -n 50 "$tmp_dir/out.json"
+  fi
+
+  log "📤 producing $nb_generated_messages records to topic $topic"
   case "${value_type}" in
-  json)
-      cat $tmp_dir/out.json | docker exec -i $container kafka-console-producer --broker-list $bootstrap_server --topic $topic $security
-  ;;
-  *)
-      cat $tmp_dir/out.json | docker exec -e SCHEMA_REGISTRY_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties" -i $container kafka-$value_type-console-producer --broker-list $bootstrap_server --property schema.registry.url=$sr_url_cli --topic $topic $security --property value.schema="$(cat $schema_file)"
-  ;;
+      json)
+          cat $tmp_dir/out.json | docker exec -i $container kafka-console-producer --broker-list $bootstrap_server --topic $topic $security
+      ;;
+      *)
+          cat $tmp_dir/out.json | docker exec -e SCHEMA_REGISTRY_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties" -i $container kafka-$value_type-console-producer --broker-list $bootstrap_server --property schema.registry.url=$sr_url_cli --topic $topic $security --property value.schema="$(cat $schema_file)"
+      ;;
   esac
 }
 
