fix

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -17551,9 +17551,10 @@ playground_fully_managed_connector_select_config_command() {
       do
 
       json_file=$(playground fully-managed-connector show-config-parameters --only-show-json --only-show-json-file-path --connector $connector)
-      if [ ! -f $json_file ]
+      if [ ! -f "$json_file" ]
       then
-          logwarn "❌ file $json_file does not exist, could not retrieve json config file for connector $connector."
+          logwarn "❌ file <$json_file> does not exist, could not retrieve json config file for connector $connector."
+          exit 1
       fi
 
       fzf_version=$(get_fzf_version)
