latest bashly

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.13 (https://bashly.dev)
+# This script was generated by bashly 1.3.1 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
   printf "bash version 4 or higher is required\n" >&2
   exit 1
 fi
@@ -11127,7 +11127,6 @@ function wait_for_log () {
   log "The log is there !"
 }
 
-
 CLI_MIN_VERSION=${CLI_MIN_VERSION:-4.0.0}
 
 # --------------------------------------------------------------
@@ -12902,7 +12901,6 @@ function ccloud::retry() {
 function ccloud::version_gt() {
   test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
 }
-
 
 function check_arm64_support() {
   DIR="$1"
@@ -19254,7 +19252,6 @@ EOF
         sink_file=$(echo "$sink_file" | cut -d "@" -f 2)
       fi
       test_sink_file_directory="$(dirname "${sink_file}")"
-
       # docker-compose part
       # determining the docker-compose file from from test_file
       docker_compose_sink_file=$(grep "start-environment" "$sink_file" |  awk '{print $6}' | cut -d "/" -f 2 | cut -d '"' -f 1 | tail -n1 | xargs)
@@ -19277,7 +19274,6 @@ EOF
         yq -i ".services.connect.environment.CONNECT_PLUGIN_PATH = \"$new_connector_paths\"" /tmp/1.yml
         cp /tmp/1.yml $docker_compose_test_file
       fi
-
 
       # sh part
 
@@ -24672,7 +24668,6 @@ playground_connector_offsets_get_command() {
           fi
       else
           # SINK CONNECTOR
-
           if [[ -n "$verbose" ]]
           then
               log "🐞 CLI command used"
@@ -30578,8 +30573,9 @@ playground_config_editor_parse_requirements() {
 
   # :command.validations
   # :argument.validations
-  if [[ -v args['editor'] && -n $(validate_editor_exists "${args['editor']:-}") ]]; then
-    printf "validation error in %s:\n%s\n" "EDITOR" "$(validate_editor_exists "${args['editor']:-}")" >&2
+  validation_output="$(validate_editor_exists "${args['editor']:-}")"
+  if [[ -v args['editor'] && -n "$validation_output" ]]; then
+    printf "validation error in %s:\n%s\n" "EDITOR" "$validation_output" >&2
     exit 1
   fi
 
@@ -30654,8 +30650,9 @@ playground_config_folder_zip_or_jar_parse_requirements() {
     values=''
     eval "values=(${args['folder']})"
     for value in "${values[@]}"; do
-      if [[ -n $(validate_dir_exists "$value") ]]; then
-        printf "validation error in %s:\n%s\n" "FOLDER" "$(validate_dir_exists "$value")" >&2
+      validation_output="$(validate_dir_exists "$value")"
+      if [[ -n "$validation_output" ]]; then
+        printf "validation error in %s:\n%s\n" "FOLDER" "$validation_output" >&2
         exit 1
       fi
     done
@@ -43724,6 +43721,8 @@ run() {
 }
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  # :command.start
+  command_line_args=("$@")
   initialize
-  run "$@"
+  run "${command_line_args[@]}"
 fi
