🧠 Add playground connector oracle-cdc-xstream generate-report command #6962

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -158,6 +158,7 @@ playground_usage() {
   printf "%s\n" "$(bold "Connector commands:")"
   printf "  %s   🔗 Connector commands\n" "$(green "connector")                                 "
   printf "  %s   🧩 Show status of all connectors\n" "$(green "connector status")                          "
+  printf "  %s   🅾️ Specific Oracle CDC Xstream commands\n" "$(green "connector oracle-cdc-xstream")              "
   printf "  %s   💈 Handle source and sink connectors offsets\n" "$(green "connector offsets")                         "
   printf "  %s   🎨 Show all connector plugins installed. You can also display transforms, converters and predicates using --all flag\n" "$(green "connector plugins")                         "
   printf "  %s   ⏸️  Pause connector\n" "$(green "connector pause")                           "
@@ -5554,6 +5555,7 @@ playground_connector_usage() {
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   🧩 Show status of all connectors\n" "$(green "status")                          "
+  printf "  %s   🅾️ Specific Oracle CDC Xstream commands\n" "$(green "oracle-cdc-xstream")              "
   printf "  %s   💈 Handle source and sink connectors offsets\n" "$(green "offsets")                         "
   printf "  %s   🎨 Show all connector plugins installed. You can also display transforms, converters and predicates using --all flag\n" "$(green "plugins")                         "
   printf "  %s   ⏸️  Pause connector\n" "$(green "pause")                           "
@@ -5621,6 +5623,62 @@ playground_connector_status_usage() {
     printf "  %s\n" "$(magenta "--connector, -c CONNECTOR")"
     printf "    🔗 Connector name\n    \n    🎓 Tip: If not specified, the command will apply to all connectors\n"
     echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_oracle_cdc_xstream_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector oracle-cdc-xstream\n\n"
+    printf "  🅾️ Specific Oracle CDC Xstream commands\n\n"
+  else
+    printf "playground connector oracle-cdc-xstream - 🅾️ Specific Oracle CDC Xstream commands\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector oracle-cdc-xstream COMMAND\n"
+  printf "  playground connector oracle-cdc-xstream [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "$(bold "== Commands ==")"
+  printf "  %s   ⚙️ Generate and open oracle cdc xstream connector diagnostics, see https://docs.confluent.io/kafka-connectors/oracle-xstream-cdc-source/current/troubleshooting.html#connector-diagnostics-script\n" "$(green "generate-report")"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_oracle_cdc_xstream_generate_report_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector oracle-cdc-xstream generate-report\n\n"
+    printf "  ⚙️ Generate and open oracle cdc xstream connector diagnostics, see\n  https://docs.confluent.io/kafka-connectors/oracle-xstream-cdc-source/current/troubleshooting.html#connector-diagnostics-script\n\n"
+  else
+    printf "playground connector oracle-cdc-xstream generate-report - ⚙️ Generate and open oracle cdc xstream connector diagnostics, see https://docs.confluent.io/kafka-connectors/oracle-xstream-cdc-source/current/troubleshooting.html#connector-diagnostics-script\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector oracle-cdc-xstream generate-report\n"
+  printf "  playground connector oracle-cdc-xstream generate-report --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -7760,6 +7818,13 @@ function filter_schema_registry_running() {
 
   if [ $? != 0 ]; then
     logerror "schema registry rest api should be running to run this command"
+  fi
+}
+
+function filter_oracle_running() {
+  docker ps --filter "name=oracle" --filter "status=running" --format "{{.Names}}" | grep -q "oracle"
+  if [ $? != 0 ]; then
+    logerror "oracle docker container should be running to run this command"
   fi
 }
 
@@ -24574,6 +24639,47 @@ playground_connector_status_command() {
 }
 
 # :command.function
+playground_connector_oracle_cdc_xstream_generate_report_command() {
+
+  # src/commands/connector/oracle-cdc-xstream/generate-report.sh
+  log "⚙️ Generate and open oracle cdc xstream connector diagnostics"
+  tmp_dir=$(mktemp -d -t pg-XXXXXXXXXX)
+  if [ -z "$PG_VERBOSE_MODE" ]
+  then
+      trap 'rm -rf $tmp_dir' EXIT
+  else
+      log "🐛📂 not deleting tmp dir $tmp_dir"
+  fi
+
+  cd $tmp_dir
+  if [ ! -f orclcdc_diag.sql ]
+  then
+      wget -q https://docs.confluent.io/kafka-connectors/oracle-xstream-cdc-source/current/_downloads/6d672a473a3153a88f9c67de5e0b558f/orclcdc_diag.sql
+  fi
+  docker cp orclcdc_diag.sql oracle:/orclcdc_diag.sql > /dev/null 2>&1
+  docker exec -i oracle bash -c "ORACLE_SID=ORCLCDB;export ORACLE_SID;sqlplus /nolog" << EOF
+     CONNECT sys/Admin123 AS SYSDBA
+     @/orclcdc_diag.sql C##CFLTADMIN C##CFLTUSER XOUT ''
+END;
+/
+EOF
+  playground container exec --container oracle --command "mv /home/oracle/orclcdc_diag_*.html /home/oracle/orclcdc_diag.html"
+  docker cp oracle:/home/oracle/orclcdc_diag.html /tmp/ > /dev/null 2>&1
+  if [ -f /tmp/orclcdc_diag.html ]
+  then
+      log "⚙️ oracle cdc xstream connector diagnostics report is available at /tmp/orclcdc_diag.html"
+      if [[ $(type -f open 2>&1) =~ "not found" ]]
+      then
+          :
+      else
+          open "/tmp/orclcdc_diag.html"
+      fi
+  else
+      logwarn "❌ oracle cdc xstream connector diagnostics report is not available"
+  fi
+}
+
+# :command.function
 playground_connector_offsets_get_command() {
 
   # src/commands/connector/offsets/get.sh
@@ -40498,6 +40604,13 @@ playground_connector_parse_requirements() {
       shift $#
       ;;
 
+    oracle-cdc-xstream)
+      action="oracle-cdc-xstream"
+      shift
+      playground_connector_oracle_cdc_xstream_parse_requirements "$@"
+      shift $#
+      ;;
+
     offsets)
       action="offsets"
       shift
@@ -40721,6 +40834,126 @@ playground_connector_status_parse_requirements() {
           exit 1
         fi
         ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_connector_oracle_cdc_xstream_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_oracle_cdc_xstream_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    generate-report)
+      action="generate-report"
+      shift
+      playground_connector_oracle_cdc_xstream_generate_report_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      playground_connector_oracle_cdc_xstream_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.user_filter
+  filter_error=$(filter_oracle_running)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_connector_oracle_cdc_xstream_generate_report_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_oracle_cdc_xstream_generate_report_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector oracle-cdc-xstream generate-report"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -43688,6 +43921,8 @@ run() {
     "connector-plugin display-last-updated") playground_connector_plugin_display_last_updated_command ;;
     "connector") playground_connector_command ;;
     "connector status") playground_connector_status_command ;;
+    "connector oracle-cdc-xstream") playground_connector_oracle_cdc_xstream_command ;;
+    "connector oracle-cdc-xstream generate-report") playground_connector_oracle_cdc_xstream_generate_report_command ;;
     "connector offsets") playground_connector_offsets_command ;;
     "connector offsets get") playground_connector_offsets_get_command ;;
     "connector offsets reset") playground_connector_offsets_reset_command ;;
