open_file_with_editor

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -7981,6 +7981,19 @@ function check_for_ec2_instance_running() {
   fi
 }
 
+function open_file_with_editor() {
+  filename="$1"
+  editor=$(playground config get editor)
+  if [ "$editor" != "" ] && command -v "$editor" > /dev/null
+  then
+    log "📖 opening ${filename} using configured editor \"$editor\" (you can change editor by using \"playground config set editor <editor>\")"
+    $editor ${filename}
+  else
+    logerror "❌ editor \"$editor\" is not installed - you can change editor by using \"playground config set editor <editor>\""
+    exit 1
+  fi
+}
+
 # src/lib/colors.sh
 print_in_color() {
   local color="$1"
@@ -9335,21 +9348,7 @@ done
 
   if [[ -n "$open" ]]
   then
-    editor=$(playground config get editor)
-    if [ "$editor" != "" ]
-    then
-      log "📖 Opening /tmp/jmx_metrics.log using configured editor $editor"
-      $editor /tmp/jmx_metrics.log
-    else
-        if [[ $(type code 2>&1) =~ "not found" ]]
-        then
-            logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-            exit 1
-        else
-            log "📖 Opening /tmp/jmx_metrics.log with code (default) - you can change editor by using playground config editor <editor>"
-            code /tmp/jmx_metrics.log
-        fi
-    fi
+    open_file_with_editor "/tmp/jmx_metrics.log"
   fi
 }
 
@@ -14172,23 +14171,8 @@ playground_run_command() {
 
   if [[ -n "$open" ]]
   then
-    editor=$(playground config get editor)
-    if [ "$editor" != "" ]
-    then
-      log "📖 Opening ${test_file} using configured editor $editor"
-      $editor ${test_file}
-      check_if_continue
-    else
-        if [[ $(type code 2>&1) =~ "not found" ]]
-        then
-            logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-            exit 1
-        else
-            log "📖 Opening ${test_file} with code (default) - you can change editor by using playground config editor <editor>"
-            code ${test_file}
-            check_if_continue
-        fi
-    fi
+    open_file_with_editor "${test_file}"
+    check_if_continue
   fi
 
   if [ $interactive_mode == 1 ]
@@ -14735,21 +14719,7 @@ playground_run_command() {
 
       if [[ $res == *"$MENU_OPEN_FILE"* ]]
       then
-        editor=$(playground config get editor)
-        if [ "$editor" != "" ]
-        then
-          log "📖 Opening ${test_file} using configured editor $editor"
-          $editor ${test_file}
-        else
-            if [[ $(type code 2>&1) =~ "not found" ]]
-            then
-                logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-                exit 1
-            else
-                log "📖 Opening ${test_file} with code (default) - you can change editor by using playground config editor <editor>"
-                code ${test_file}
-            fi
-        fi
+        open_file_with_editor "${test_file}"
       fi
 
       if [[ $res == *"$MENU_OPEN_DOCS"* ]]
@@ -15848,21 +15818,7 @@ playground_update_version_command() {
 
       if [[ $res == *"$MENU_OPEN_FILE"* ]]
       then
-        editor=$(playground config get editor)
-        if [ "$editor" != "" ]
-        then
-          log "📖 Opening ${test_file} using configured editor $editor"
-          $editor ${test_file}
-        else
-            if [[ $(type code 2>&1) =~ "not found" ]]
-            then
-                logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-                exit 1
-            else
-                log "📖 Opening ${test_file} with code (default) - you can change editor by using playground config editor <editor>"
-                code ${test_file}
-            fi
-        fi
+        open_file_with_editor "${test_file}"
       fi
 
       if [[ $res == *"$MENU_OPEN_DOCS"* ]]
@@ -16061,21 +16017,7 @@ playground_open_command() {
     fi
   fi
 
-  editor=$(playground config get editor)
-  if [ "$editor" != "" ]
-  then
-    log "📖 Opening ${test_file} using configured editor $editor"
-    $editor ${test_file}
-  else
-    if [[ $(type code 2>&1) =~ "not found" ]]
-    then
-      logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-      exit 1
-    else
-      log "📖 Opening ${test_file} with code (default) - you can change editor by using playground config editor <editor>"
-      code ${test_file}
-    fi
-  fi
+  open_file_with_editor "${test_file}"
 }
 
 # :command.function
@@ -17140,7 +17082,7 @@ playground_repro_bootstrap_command() {
         else
           if [[ $(type code 2>&1) =~ "not found" ]]
           then
-            logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
+            logerror "Could not determine an editor to use as default code is not found (you can change editor by using \"playground config set editor <editor>\")"
             exit 1
           else
             log "✨ Copy and paste the schema you want to use for the key, save and close the file to continue"
@@ -17221,7 +17163,6 @@ playground_repro_bootstrap_command() {
 
       if [[ -n "$schema_file_value" ]]
       then
-
         editor=$(playground config get editor)
         if [ "$editor" != "" ]
         then
@@ -17235,7 +17176,7 @@ playground_repro_bootstrap_command() {
         else
           if [[ $(type code 2>&1) =~ "not found" ]]
           then
-            logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
+            logerror "Could not determine an editor to use as default code is not found (you can change editor by using \"playground config set editor <editor>\")"
             exit 1
           else
             log "✨ Copy and paste the schema you want to use for the value, save and close the file to continue"
@@ -17954,21 +17895,7 @@ EOF
   playground state set run.test_file "$repro_dir/$repro_test_filename"
   playground state set run.connector_type "$(get_connector_type | tr -d '\n')"
 
-  editor=$(playground config get editor)
-  if [ "$editor" != "" ]
-  then
-    log "📖 Opening ${repro_test_filename} using configured editor $editor"
-    $editor $repro_dir/$repro_test_filename
-  else
-      if [[ $(type code 2>&1) =~ "not found" ]]
-      then
-          logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-          exit 1
-      else
-          log "📖 Opening ${repro_test_filename} with code (default) - you can change editor by using playground config editor <editor>"
-          code $repro_dir/$repro_test_filename
-      fi
-  fi
+  open_file_with_editor "$repro_dir/$repro_test_filename"
 
   increment_cli_metric nb_reproduction_models
   log "👷 Number of repro models created so far: $(get_cli_metric nb_reproduction_models)"
@@ -19255,21 +19182,7 @@ playground_debug_thread_dump_command() {
   docker exec $container jstack 1 > "$filename" 2>&1
   if [ $? -eq 0 ]
   then
-      editor=$(playground config get editor)
-      if [ "$editor" != "" ]
-      then
-          log "📖 Opening ${filename} using configured editor $editor"
-          $editor ${filename}
-      else
-          if [[ $(type code 2>&1) =~ "not found" ]]
-          then
-              logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-              exit 1
-          else
-              log "📖 Opening ${filename} with code (default) - you can change editor by using playground config editor <editor>"
-              code ${filename}
-          fi
-      fi
+      open_file_with_editor "${filename}"
   else
       logerror "❌ Failed to take thread dump"
   fi
@@ -19777,23 +19690,9 @@ playground_container_logs_command() {
     docker container logs "$container" > "$filename" 2>&1
     if [ $? -eq 0 ]
     then
-      editor=$(playground config get editor)
-      if [ "$editor" != "" ]
-      then
-          log "📖 Opening ${filename} using configured editor $editor"
-          $editor ${filename}
-      else
-          if [[ $(type code 2>&1) =~ "not found" ]]
-          then
-              logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-              exit 1
-          else
-              log "📖 Opening ${filename} with code (default) - you can change editor by using playground config editor <editor>"
-              code ${filename}
-          fi
-      fi
+      open_file_with_editor "${filename}"
     else
-      logerror "Failed to get logs using container logs $container"
+      logerror "❌ failed to get logs using container logs $container"
     fi
   elif [[ -n "$log" ]]
   then
@@ -22886,7 +22785,7 @@ playground_connector_offsets_alter_command() {
           else
               if [[ $(type code 2>&1) =~ "not found" ]]
               then
-                  logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
+                  logerror "Could not determine an editor to use as default code is not found (you can change editor by using \"playground config set editor <editor>\")"
                   exit 1
               else
                   log "✨ Update the connector offsets as per your needs, save and close the file to continue"
@@ -22920,7 +22819,7 @@ playground_connector_offsets_alter_command() {
           else
               if [[ $(type code 2>&1) =~ "not found" ]]
               then
-                  logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
+                  logerror "Could not determine an editor to use as default code is not found (you can change editor by using \"playground config set editor <editor>\")"
                   exit 1
               else
                   log "✨ Update the connector offsets as per your needs, save and close the file to continue"
@@ -23041,7 +22940,7 @@ playground_connector_offsets_alter_command() {
                       else
                           if [[ $(type code 2>&1) =~ "not found" ]]
                           then
-                              logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
+                              logerror "Could not determine an editor to use as default code is not found (you can change editor by using \"playground config set editor <editor>\")"
                               exit 1
                           else
                               log "✨ Update the connector offsets as per your needs, save and close the file to continue"
@@ -24138,21 +24037,7 @@ playground_connector_show_config_parameters_command() {
               echo "🔩 list of all available parameters for connector $connector ($class) and version $version (with default value when applicable)" >> $filename
           fi
 
-          editor=$(playground config get editor)
-          if [ "$editor" != "" ]
-          then
-              log "📖 Opening ${filename} using configured editor $editor"
-              $editor ${filename}
-          else
-              if [[ $(type code 2>&1) =~ "not found" ]]
-              then
-                  logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
-                  exit 1
-              else
-                  log "📖 Opening ${filename} with code (default) - you can change editor by using playground config editor <editor>"
-                  code ${filename}
-              fi
-          fi
+          open_file_with_editor "${filename}"
       else
           if [[ -n "$only_show_json" ]] || [[ -n "$only_show_json_file_path" ]]
           then
@@ -25136,7 +25021,7 @@ playground_connector_update_command() {
       else
           if [[ $(type code 2>&1) =~ "not found" ]]
           then
-              logerror "Could not determine an editor to use as default code is not found - you can change editor by using playground config editor <editor>"
+              logerror "Could not determine an editor to use as default code is not found (you can change editor by using \"playground config set editor <editor>\")"
               exit 1
           else
               log "✨ Update the connector config as per your needs, save and close the file to continue"
