added switch-ccloud and switch-onprem commands

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.3 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.4 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -39,6 +39,8 @@ playground_usage() {
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   Show help about a command\n" "$(green "help")                                   "
   printf "  %s   🗺️ Show a status\n" "$(green "status")                                 "
+  printf "  %s   🌩️  Switch to ccloud environment.\n" "$(green "switch-ccloud")                          "
+  printf "  %s   💺  Switch back from ccloud environment to onprem environment. \n" "$(green "switch-onprem")                          "
   echo
   printf "%s\n" "$(bold "Run commands:")"
   printf "  %s   🕹️ Run any example, except for Confluent Cloud (in this case use run-ccloud command)\n" "$(green "run")                                    "
@@ -1175,6 +1177,99 @@ playground_run_ccloud_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground run-ccloud mqtt<tab> --cluster-cloud aws --cluster-region eu-west-3\n  --enable-control-center --connector-tag 1.2.3\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_switch_ccloud_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground switch-ccloud\n"
+    echo
+
+    printf "  🌩️  Switch to ccloud environment.\n  \n  It will bootstrap ccloud environment. \n  \n  Note that this is automatically done with any ccloud example.\n  \n  It will also save any onprem environment to get back to it with switch-onprem\n  command\n  \n  All you have to do is to be already logged in with confluent CLI.\n  \n  By default, a new Confluent Cloud environment with a Cluster will be created.\n  \n  You can configure the new cluster by setting:\n  \n  --cluster-type (or CLUSTER_TYPE environment variable): The type of cluster\n  (possible values: \`basic\`, \`standard\` and \`dedicated\`, default \`basic\`)\n  --cluster-cloud (or CLUSTER_CLOUD environment variable): The Cloud provider\n  (possible values: \`aws\`, \`gcp\` and \`azure\`, default \`aws\`)\n  --cluster-region (or CLUSTER_REGION environment variable): The Cloud region\n  (use \`confluent kafka region list\` to get the list, default \`eu-west-2\`)\n  --cluster-environment (or ENVIRONMENT environment variable) (optional): The\n  environment id where want your new cluster (example: \`env-xxxxx\`)\n  \n  In case you want to use your own existing cluster, you need to setup, in\n  addition to previous ones:\n  \n  --cluster-name (or CLUSTER_NAME environment variable): The cluster name\n  --cluster-creds (or CLUSTER_CREDS environment variable): The Kafka api key and\n  secret to use, it should be separated with semi-colon (example:\n  \`<API_KEY>:<API_KEY_SECRET>\`)\n  --cluster-schema-registry-creds (or SCHEMA_REGISTRY_CREDS environment\n  variable) (optional, if not set, new one will be created): The Schema Registry\n  api key and secret to use, it should be separated with semi-colon (example:\n  \`<SR_API_KEY>:<SR_API_KEY_SECRET>\`)\n"
+    echo
+
+  else
+    printf "playground switch-ccloud - 🌩️  Switch to ccloud environment.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground switch-ccloud [OPTIONS]\n"
+  printf "  playground switch-ccloud --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--cluster-type CLUSTER-TYPE")"
+    printf "    🔋 The cluster type: basic, standard or dedicated. Default is basic\n    \n    🎓 Tip: you can also use CLUSTER_TYPE environment variable\n"
+    printf "    Allowed: basic, standard, dedicated\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--cluster-region CLUSTER-REGION")"
+    printf "    🗺 The Cloud region. \n    \n    🎓 Tip: you can also use CLUSTER_REGION environment variable\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--cluster-environment CLUSTER-ENVIRONMENT")"
+    printf "    🌐 The environment id where want your new cluster (example: env-xxxxx)\n    \n    ℹ️ Optional, if not set, new environment will be created\n    \n    🎓 Tip: you can also use ENVIRONMENT environment variable\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--cluster-name CLUSTER-NAME")"
+    printf "    🎰 The cluster name. \n    \n    ❣️ Only required if you want to use your own existing cluster\n    \n    🎓 Tip: you can also use CLUSTER_NAME environment variable\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--cluster-creds CLUSTER-CREDS")"
+    printf "    🔒 The Kafka api key and secret to use, it should be separated with\n    semi-colon (example: <API_KEY>:<API_KEY_SECRET>)\n    \n    ❣️ Only required if you want to use your own existing cluster\n    \n    🎓 Tip: you can also use CLUSTER_CREDS environment variable\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--cluster-schema-registry-creds CLUSTER-SCHEMA-REGISTRY-CREDS")"
+    printf "    🔒 The Schema Registry api key and secret to use, it should be separated with\n    semi-colon (example: <SR_API_KEY>:<SR_API_KEY_SECRET>)\n    \n    ℹ️ Optional, if not set, new credentials will be created\n    \n    ❣️ Only required if you want to use your own existing cluster\n    \n    🎓 Tip: you can also use SCHEMA_REGISTRY_CREDS environment variable\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_switch_onprem_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground switch-onprem - 💺  Switch back from ccloud environment to onprem environment. \n"
+    echo
+
+  else
+    printf "playground switch-onprem - 💺  Switch back from ccloud environment to onprem environment. \n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground switch-onprem\n"
+  printf "  playground switch-onprem --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -10433,6 +10528,80 @@ playground_run_ccloud_command() {
 }
 
 # :command.function
+playground_switch_ccloud_command() {
+  # src/switch_ccloud_command.sh
+  if [ -f /tmp/switch-playground-command ] || [ -f /tmp/switch-playground-run ]
+  then
+      log "🌩️ you have already switched to ccloud environment"
+      exit 0
+  fi
+
+  if [ -f /tmp/playground-command ]
+  then
+      mv /tmp/playground-command /tmp/switch-playground-command
+  fi
+
+  if [ -f /tmp/playground-run ]
+  then
+      mv /tmp/playground-run /tmp/switch-playground-run
+  fi
+
+  log "🌩️ switch to ccloud environment"
+  bootstrap_ccloud_environment
+
+  if [ -f /tmp/delta_configs/env.delta ]
+  then
+       source /tmp/delta_configs/env.delta
+  else
+       logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
+       exit 1
+  fi
+}
+
+# :command.function
+playground_switch_onprem_command() {
+  # src/switch_onprem_command.sh
+  if [ -f /tmp/switch-playground-command ]
+  then
+      log "💺 Switch back to onprem environment"
+      mv /tmp/switch-playground-command /tmp/playground-command
+  else
+      logwarn "/tmp/switch-playground-command was not found, switch-ccloud was probably not executed before"
+  fi
+
+  if [ -f /tmp/switch-playground-run ]
+  then
+      mv /tmp/switch-playground-run /tmp/playground-run
+  else
+      logwarn "/tmp/switch-playground-run was not found, switch-ccloud was probably not executed before"
+  fi
+
+  if [ ! -f /tmp/playground-run ]
+  then
+    logerror "File containing re-run command /tmp/playground-run does not exist!"
+    logerror "Make sure to use <playground run> command !"
+    exit 1
+  fi
+
+  test_file=$(cat /tmp/playground-run | awk '{ print $4}')
+
+  if [ ! -f $test_file ]
+  then
+
+  logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
+  logerror "Make sure to use <playground run> command !"
+  exit 1
+  fi
+
+  last_two_folders=$(basename $(dirname $(dirname $test_file)))/$(basename $(dirname $test_file))
+  filename=$(basename $test_file)
+  last_folder=$(basename $(dirname $test_file))
+
+  log "🚀 Running example "
+  echo $last_two_folders/$filename
+}
+
+# :command.function
 playground_update_version_command() {
   # src/update_version_command.sh
   DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
@@ -17047,6 +17216,20 @@ parse_requirements() {
       shift $#
       ;;
 
+    switch-ccloud)
+      action="switch-ccloud"
+      shift
+      playground_switch_ccloud_parse_requirements "$@"
+      shift $#
+      ;;
+
+    switch-onprem)
+      action="switch-onprem"
+      shift
+      playground_switch_onprem_parse_requirements "$@"
+      shift $#
+      ;;
+
     update-version)
       action="update-version"
       shift
@@ -19013,6 +19196,218 @@ playground_run_ccloud_parse_requirements() {
 }
 
 # :command.parse_requirements
+playground_switch_ccloud_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_switch_ccloud_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  if command -v confluent >/dev/null 2>&1; then
+    deps['confluent']="$(command -v confluent | head -n1)"
+  else
+    printf "missing dependency: confluent\n" >&2
+    printf "%s\n" "visit https://docs.confluent.io/confluent-cli/current/overview.html to install" >&2
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="switch-ccloud"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --cluster-type)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--cluster-type']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--cluster-type requires an argument: --cluster-type CLUSTER-TYPE" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --cluster-region)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--cluster-region']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--cluster-region requires an argument: --cluster-region CLUSTER-REGION" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --cluster-environment)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_not_empty "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--cluster-environment CLUSTER-ENVIRONMENT" "$(validate_not_empty "$2")" >&2
+            exit 1
+          fi
+
+          args['--cluster-environment']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--cluster-environment requires an argument: --cluster-environment CLUSTER-ENVIRONMENT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --cluster-name)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_not_empty "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--cluster-name CLUSTER-NAME" "$(validate_not_empty "$2")" >&2
+            exit 1
+          fi
+
+          args['--cluster-name']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--cluster-name requires an argument: --cluster-name CLUSTER-NAME" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --cluster-creds)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_not_empty "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--cluster-creds CLUSTER-CREDS" "$(validate_not_empty "$2")" >&2
+            exit 1
+          fi
+
+          args['--cluster-creds']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--cluster-creds requires an argument: --cluster-creds CLUSTER-CREDS" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --cluster-schema-registry-creds)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_not_empty "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--cluster-schema-registry-creds CLUSTER-SCHEMA-REGISTRY-CREDS" "$(validate_not_empty "$2")" >&2
+            exit 1
+          fi
+
+          args['--cluster-schema-registry-creds']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--cluster-schema-registry-creds requires an argument: --cluster-schema-registry-creds CLUSTER-SCHEMA-REGISTRY-CREDS" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.whitelist_filter
+  if [[ ${args['--cluster-type']:-} ]] && [[ ! ${args['--cluster-type']:-} =~ ^(basic|standard|dedicated)$ ]]; then
+    printf "%s\n" "--cluster-type must be one of: basic, standard, dedicated" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_switch_onprem_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_switch_onprem_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="switch-onprem"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 playground_update_version_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -19937,7 +20332,7 @@ playground_repro_bootstrap_parse_requirements() {
           if [[ -z ${args['--pipeline']+x} ]]; then
             args['--pipeline']="\"$2\""
           else
-            args['--pipeline']="${args[--pipeline]} \"$2\""
+            args['--pipeline']="${args['--pipeline']} \"$2\""
           fi
           shift
           shift
@@ -23860,7 +24255,7 @@ playground_topic_produce_parse_requirements() {
           if [[ -z ${args['--validate-config']+x} ]]; then
             args['--validate-config']="\"$2\""
           else
-            args['--validate-config']="${args[--validate-config]} \"$2\""
+            args['--validate-config']="${args['--validate-config']} \"$2\""
           fi
           shift
           shift
@@ -23879,7 +24274,7 @@ playground_topic_produce_parse_requirements() {
           if [[ -z ${args['--producer-property']+x} ]]; then
             args['--producer-property']="\"$2\""
           else
-            args['--producer-property']="${args[--producer-property]} \"$2\""
+            args['--producer-property']="${args['--producer-property']} \"$2\""
           fi
           shift
           shift
@@ -26293,6 +26688,8 @@ run() {
     "history") playground_history_command ;;
     "start-environment") playground_start_environment_command ;;
     "run-ccloud") playground_run_ccloud_command ;;
+    "switch-ccloud") playground_switch_ccloud_command ;;
+    "switch-onprem") playground_switch_onprem_command ;;
     "update-version") playground_update_version_command ;;
     "open") playground_open_command ;;
     "stop") playground_stop_command ;;
