🧠 Add disable-remote-debugging commands #7331

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -109,6 +109,7 @@ playground_usage() {
   printf "%s\n" "$(bold "Debug commands:")"
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                                     "
   printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "debug enable-remote-debugging")             "
+  printf "  %s   🛑 Disable java remote debugging for container\n" "$(green "debug disable-remote-debugging")            "
   printf "  %s   🔐 Testing TLS/SSL encryption using https://testssl.sh/\n" "$(green "debug testssl")                             "
   printf "  %s   ⛑️ Generate a diagnostic bundle with Diagnostics Bundle Tool\n" "$(green "debug generate-diagnostics")                "
   printf "  %s   🎯 Take a java thread dump\n" "$(green "debug thread-dump")                         "
@@ -167,6 +168,7 @@ playground_usage() {
   printf "  %s   🧞 Get current and latest versions available on Confluent Hub for connector(s) used in example\n" "$(green "connector versions")                        "
   printf "  %s   🧑‍💻 open source code url for connector(s) used in example\n" "$(green "connector sourcecode")                      "
   printf "  %s   ✨ Enable java remote debugging for the connector.\n" "$(green "connector enable-remote-debugging")         "
+  printf "  %s   🛑 Disable java remote debugging for the connector.\n" "$(green "connector disable-remote-debugging")        "
   printf "  %s   ♻️  Restart connector\n" "$(green "connector restart")                         "
   printf "  %s   🛑 Stop connector (only available if CP > 7.5)\n" "$(green "connector stop")                            "
   printf "  %s   ⏯️  Resume connector\n" "$(green "connector resume")                          "
@@ -3721,17 +3723,18 @@ playground_debug_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
-  printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "enable-remote-debugging")"
-  printf "  %s   🔐 Testing TLS/SSL encryption using https://testssl.sh/\n" "$(green "testssl")                "
-  printf "  %s   ⛑️ Generate a diagnostic bundle with Diagnostics Bundle Tool\n" "$(green "generate-diagnostics")   "
-  printf "  %s   🎯 Take a java thread dump\n" "$(green "thread-dump")            "
-  printf "  %s   👻 Take a heap dump\n" "$(green "heap-dump")              "
-  printf "  %s   🕵️‍♂️ Take a tcp dump (sniffing network)\n" "$(green "tcp-dump")               "
-  printf "  %s   🚫 Blocking traffic using iptables\n" "$(green "block-traffic")          "
-  printf "  %s   🤎 JVM arguments for SSL, Kerberos or Class Loading\n" "$(green "java-debug")             "
-  printf "  %s   ✂️ jscissors is an instrumentation framework and can help to analyse control flow and perform some specific logging\n" "$(green "jscissors")              "
-  printf "  %s   🛩️ Record flight recorder\n" "$(green "flight-recorder")        "
-  printf "  %s   🧬 Set log level for any package\n" "$(green "log-level")              "
+  printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "enable-remote-debugging") "
+  printf "  %s   🛑 Disable java remote debugging for container\n" "$(green "disable-remote-debugging")"
+  printf "  %s   🔐 Testing TLS/SSL encryption using https://testssl.sh/\n" "$(green "testssl")                 "
+  printf "  %s   ⛑️ Generate a diagnostic bundle with Diagnostics Bundle Tool\n" "$(green "generate-diagnostics")    "
+  printf "  %s   🎯 Take a java thread dump\n" "$(green "thread-dump")             "
+  printf "  %s   👻 Take a heap dump\n" "$(green "heap-dump")               "
+  printf "  %s   🕵️‍♂️ Take a tcp dump (sniffing network)\n" "$(green "tcp-dump")                "
+  printf "  %s   🚫 Blocking traffic using iptables\n" "$(green "block-traffic")           "
+  printf "  %s   🤎 JVM arguments for SSL, Kerberos or Class Loading\n" "$(green "java-debug")              "
+  printf "  %s   ✂️ jscissors is an instrumentation framework and can help to analyse control flow and perform some specific logging\n" "$(green "jscissors")               "
+  printf "  %s   🛩️ Record flight recorder\n" "$(green "flight-recorder")         "
+  printf "  %s   🧬 Set log level for any package\n" "$(green "log-level")               "
   echo
 
   # :command.long_usage
@@ -3783,6 +3786,34 @@ playground_debug_enable_remote_debugging_usage() {
     printf "  playground debug enable-remote-debugging -c broker\n"
     printf "  playground debug enable-remote-debugging -c connect -c broker\n"
     printf "  playground debug enable-remote-debugging --container schema-registry\n  --container ksqldb-server --container control-center\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_debug_disable_remote_debugging_usage() {
+  printf "playground debug disable-remote-debugging - 🛑 Disable java remote debugging for container\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground debug disable-remote-debugging [OPTIONS]\n"
+  printf "  playground debug disable-remote-debugging --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER (repeatable)")"
+    printf "    🐳 Container name\n    \n    🎓 Tip: you can pass multiple containers by specifying --container multiple\n    times\n"
+    printf "    %s\n" "Default: connect"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -5757,6 +5788,7 @@ playground_connector_usage() {
   printf "  %s   🧞 Get current and latest versions available on Confluent Hub for connector(s) used in example\n" "$(green "versions")                        "
   printf "  %s   🧑‍💻 open source code url for connector(s) used in example\n" "$(green "sourcecode")                      "
   printf "  %s   ✨ Enable java remote debugging for the connector.\n" "$(green "enable-remote-debugging")         "
+  printf "  %s   🛑 Disable java remote debugging for the connector.\n" "$(green "disable-remote-debugging")        "
   printf "  %s   ♻️  Restart connector\n" "$(green "restart")                         "
   printf "  %s   🛑 Stop connector (only available if CP > 7.5)\n" "$(green "stop")                            "
   printf "  %s   ⏯️  Resume connector\n" "$(green "resume")                          "
@@ -6238,6 +6270,27 @@ playground_connector_enable_remote_debugging_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground connector enable-remote-debugging\n"
   printf "  playground connector enable-remote-debugging --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_disable_remote_debugging_usage() {
+  printf "playground connector disable-remote-debugging - 🛑 Disable java remote debugging for the connector.\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector disable-remote-debugging\n"
+  printf "  playground connector disable-remote-debugging --help | -h\n"
   echo
 
   # :command.long_usage
@@ -21165,6 +21218,22 @@ playground_debug_enable_remote_debugging_command() {
 }
 
 # :command.function
+playground_debug_disable_remote_debugging_command() {
+
+  # src/commands/debug/disable-remote-debugging.sh
+  containers="${args[--container]}"
+
+  # Convert space-separated string to array
+  IFS=' ' read -ra container_array <<< "$containers"
+
+  for container in "${container_array[@]}"
+  do
+      log "🛑 disable remote debugging for $container"
+      playground container set-environment-variables --container "${container}" --restore-original-values
+  done
+}
+
+# :command.function
 playground_debug_testssl_command() {
 
   # src/commands/debug/testssl.sh
@@ -26864,6 +26933,14 @@ playground_connector_enable_remote_debugging_command() {
   playground connector sourcecode --enable-remote-debugging --compile
 
   log "✨ now you can set breakpoints and use Hot Code Replace feature (see https://devblogs.microsoft.com/java/hot-code-replacement-for-java-comes-to-visual-studio-code/)!"
+}
+
+# :command.function
+playground_connector_disable_remote_debugging_command() {
+
+  # src/commands/connector/disable-remote-debugging.sh
+  log "🛑 disable remote debugging for connector"
+  playground debug disable-remote-debugging --container connect
 }
 
 # :command.function
@@ -37968,6 +38045,13 @@ playground_debug_parse_requirements() {
       shift $#
       ;;
 
+    disable-remote-debugging)
+      action="disable-remote-debugging"
+      shift
+      playground_debug_disable_remote_debugging_parse_requirements "$@"
+      shift $#
+      ;;
+
     testssl)
       action="testssl"
       shift
@@ -38125,6 +38209,72 @@ playground_debug_enable_remote_debugging_parse_requirements() {
         # :flag.case_no_arg
         args['--skip-vs-code-config-display']=1
         shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+}
+
+# :command.parse_requirements
+playground_debug_disable_remote_debugging_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_debug_disable_remote_debugging_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="debug disable-remote-debugging"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          escaped="$(printf '%q' "$2")"
+          if [[ -z ${args['--container']+x} ]]; then
+            args['--container']="$escaped"
+          else
+            args['--container']="${args['--container']} $escaped"
+          fi
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
         ;;
 
       -?*)
@@ -42833,6 +42983,13 @@ playground_connector_parse_requirements() {
       shift $#
       ;;
 
+    disable-remote-debugging)
+      action="disable-remote-debugging"
+      shift
+      playground_connector_disable_remote_debugging_parse_requirements "$@"
+      shift $#
+      ;;
+
     restart)
       action="restart"
       shift
@@ -43920,6 +44077,51 @@ playground_connector_enable_remote_debugging_parse_requirements() {
 
   # :command.command_filter
   action="connector enable-remote-debugging"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_connector_disable_remote_debugging_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_disable_remote_debugging_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector disable-remote-debugging"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -46584,6 +46786,7 @@ run() {
     "tools certs-create") playground_tools_certs_create_command ;;
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
+    "debug disable-remote-debugging") playground_debug_disable_remote_debugging_command ;;
     "debug testssl") playground_debug_testssl_command ;;
     "debug generate-diagnostics") playground_debug_generate_diagnostics_command ;;
     "debug thread-dump") playground_debug_thread_dump_command ;;
@@ -46644,6 +46847,7 @@ run() {
     "connector versions") playground_connector_versions_command ;;
     "connector sourcecode") playground_connector_sourcecode_command ;;
     "connector enable-remote-debugging") playground_connector_enable_remote_debugging_command ;;
+    "connector disable-remote-debugging") playground_connector_disable_remote_debugging_command ;;
     "connector restart") playground_connector_restart_command ;;
     "connector stop") playground_connector_stop_command ;;
     "connector resume") playground_connector_resume_command ;;
