wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1972,7 +1972,7 @@ playground_repro_bootstrap_usage() {
   fi
 
   printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground repro bootstrap [OPTIONS] [ARGUMENTS...]\n"
+  printf "  playground repro bootstrap [OPTIONS]\n"
   printf "  playground repro bootstrap --help | -h\n"
   echo
 
@@ -2004,13 +2004,6 @@ playground_repro_bootstrap_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
-    echo
-
-    # :command.usage_args
-    printf "%s\n" "$(bold "== Arguments ==")"
-
-    echo "  ARGUMENTS..."
-    printf "    Arguments to use by example script\n    \n    Most of examples support to get required options either by using arguments\n    or environment variables.\n    \n    Example with Zendesk:\n    \n    just use <playground run> command and search for zendesk-source<tab>\n    <ZENDESK_URL> <ZENDESK_USERNAME> .sh in this folder\n"
     echo
 
     # :command.usage_examples
@@ -11566,6 +11559,17 @@ playground_run_command() {
       logwarn "❌ --enable-multiple-connect-workers is not supported with ccloud examples"
       exit 1
     fi
+    if [[ $test_file == *"environment"* ]] && [[ $test_file != *"plaintext"* ]]
+    then
+      logwarn "❌ --enable-multiple-connect-workers is only supported with plaintext environment"
+      exit 1
+    fi
+
+    if [ ! -z $PLAYGROUND_ENVIRONMENT ] && [ "$PLAYGROUND_ENVIRONMENT" != "plaintext" ]
+    then
+      logwarn "❌ --enable-multiple-connect-workers is only supported with plaintext environment"
+      exit 1
+    fi
     array_flag_list+=("--enable-multiple-connect-workers")
     export ENABLE_CONNECT_NODES=true
 
@@ -12078,7 +12082,7 @@ playground_run_command() {
         unset 'options[19]'
       fi
 
-      if [ ! -z $PLAYGROUND_ENVIRONMENT ] && [ "$PLAYGROUND_ENVIRONMENT" != "plaintext" ]
+      if ([ ! -z $PLAYGROUND_ENVIRONMENT ] && [ "$PLAYGROUND_ENVIRONMENT" != "plaintext" ]) || ([[ $test_file == *"environment"* ]] && [[ $test_file != *"plaintext"* ]])
       then
         # --enable-multiple-connect-workers only for plaintext
         unset 'options[17]'
@@ -14191,9 +14195,7 @@ playground_repro_bootstrap_command() {
         array_flag_list+=("--pipeline=$sink_file")
       fi
     done # end while loop stop
-
-    IFS=' ' flag_list="${array_flag_list[*]}"
-    playground repro bootstrap --file $test_file $flag_list
+    playground repro bootstrap --file "$test_file" "${array_flag_list[*]}"
     exit 0
   fi
 
@@ -15330,7 +15332,7 @@ EOF
   playground open-docs --only-show-url
   log "🕹️  Ready? Run it now?"
   check_if_continue
-  playground run -f $repro_dir/$repro_test_filename --force-interactive-repro $flag_list ${other_args[*]}
+  playground run -f $repro_dir/$repro_test_filename --force-interactive-repro $flag_list
 }
 
 # :command.function
@@ -24858,22 +24860,16 @@ playground_repro_bootstrap_parse_requirements() {
         fi
         ;;
 
-      --)
-        shift
-        other_args+=("$@")
-        break
-        ;;
-
       -?*)
-        other_args+=("$1")
-        shift
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
-        # :command.parse_requirements_case_catch_all
-        other_args+=("$1")
-        shift
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
 
         ;;
 
