debug thread-dump

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -54,6 +54,7 @@ playground_usage() {
   printf "%s\n" "$(bold "Debug commands:")"
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                             "
   [[ -n $long_usage ]] && printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "debug enable-remote-debugging")     "
+  [[ -n $long_usage ]] && printf "  %s   🎯 Take a java thread dump\n" "$(green "debug thread-dump")                 "
   [[ -n $long_usage ]] && printf "  %s   🧬 Set log level for any package\n" "$(green "debug log-level")                   "
   echo
   printf "%s\n" "$(bold "Container commands:")"
@@ -1150,6 +1151,7 @@ playground_debug_usage() {
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   ✨ Enable java remote debugging for container\n" "$(green "enable-remote-debugging")"
+  printf "  %s   🎯 Take a java thread dump\n" "$(green "thread-dump")            "
   printf "  %s   🧬 Set log level for any package\n" "$(green "log-level")              "
   echo
 
@@ -1203,9 +1205,54 @@ playground_debug_enable_remote_debugging_usage() {
 
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
-    printf "  playground enable-remote-debugging\n"
-    printf "  playground enable-remote-debugging --container broker\n"
-    printf "  playground enable-remote-debugging -c broker\n"
+    printf "  playground debug enable-remote-debugging\n"
+    printf "  playground debug enable-remote-debugging --container broker\n"
+    printf "  playground debug enable-remote-debugging -c broker\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_debug_thread_dump_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground debug thread-dump\n"
+    echo
+
+    printf "  🎯 Take a java thread dump\n  \n  🔖 It will save output to a file and open with text editor set with config.ini\n  (default is code)\n"
+    echo
+
+  else
+    printf "playground debug thread-dump - 🎯 Take a java thread dump\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground debug thread-dump [OPTIONS]\n"
+  printf "  playground debug thread-dump --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    🐳 Container name\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground debug thread-dump\n"
+    printf "  playground debug thread-dump --container broker\n"
     echo
 
   fi
@@ -1244,10 +1291,10 @@ playground_debug_log_level_usage() {
 
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
-    printf "  playground log-level get\n"
-    printf "  playground log-level get -p io.confluent.connect.oracle.cdc\n"
-    printf "  playground log-level get --package io.confluent.connect.oracle.cdc\n"
-    printf "  playground log-level set -p io.confluent.connect.oracle.cdc.logging.LogUtils\n  -l TRACE\n"
+    printf "  playground debug log-level get\n"
+    printf "  playground debug log-level get -p io.confluent.connect.oracle.cdc\n"
+    printf "  playground debug log-level get --package io.confluent.connect.oracle.cdc\n"
+    printf "  playground debug log-level set -p\n  io.confluent.connect.oracle.cdc.logging.LogUtils -l TRACE\n"
     echo
 
   fi
@@ -9140,6 +9187,45 @@ playground_debug_enable_remote_debugging_command() {
 }
 
 # :command.function
+playground_debug_thread_dump_command() {
+  # src/debug_thread_dump_command.sh
+  container="${args[--container]}"
+  filename="/tmp/thread-dump-$container-`date '+%Y-%m-%d-%H-%M-%S'`.log"
+
+  set +e
+  docker exec $container type jstack > /dev/null 2>&1
+  if [ $? != 0 ]
+  then
+      logerror "❌ jstack is not installed on container $container"
+      exit 1
+  fi
+  set -e
+  log "🎯 Taking thread dump on container ${container} for pid 1"
+  docker exec $container jstack 1 > "$filename" 2>&1
+  if [ $? -eq 0 ]
+  then
+      if config_has_key "editor"
+      then
+          editor=$(config_get "editor")
+          log "📖 Opening ${filename} using configured editor $editor"
+          $editor $filename
+      else
+          if [[ $(type code 2>&1) =~ "not found" ]]
+          then
+              logerror "Could not determine an editor to use as default code is not found - you can change editor by updating config.ini"
+              exit 1
+          else
+              log "📖 Opening ${filename} with code (default) - you can change editor by updating config.ini"
+              code $filename
+          fi
+      fi
+  else
+      logerror "❌ Failed to take thread dump"
+  fi
+
+}
+
+# :command.function
 playground_debug_log_level_get_command() {
   # src/debug_log_level_get_command.sh
   ret=$(get_connect_url_and_security)
@@ -9183,7 +9269,7 @@ playground_debug_log_level_set_command() {
       \"level\": \"$level\"
       }" | jq .
 
-      playground log-level get -p "$package"
+      playground debug log-level get -p "$package"
   else
       log "🧬⏭️ Skipping as log level for package $package was already set to $level"
   fi
@@ -11067,7 +11153,7 @@ playground_connector_log_level_command() {
       tmp=$(curl -s $security "$connect_url/connectors/$connector" | jq -r '.config."connector.class"')
       package="${tmp%.*}"
       # log "🧬 Set log level for connector $connector to $level"
-      playground log-level set -p "$package" -l $level
+      playground debug log-level set -p "$package" -l $level
   done
 }
 
@@ -13430,6 +13516,13 @@ playground_debug_parse_requirements() {
       shift $#
       ;;
 
+    thread-dump)
+      action="thread-dump"
+      shift
+      playground_debug_thread_dump_parse_requirements "$@"
+      shift $#
+      ;;
+
     log-level)
       action="log-level"
       shift
@@ -13493,6 +13586,67 @@ playground_debug_enable_remote_debugging_parse_requirements() {
 
   # :command.command_filter
   action="debug enable-remote-debugging"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+
+}
+
+# :command.parse_requirements
+playground_debug_thread_dump_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_debug_thread_dump_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="debug thread-dump"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -16917,6 +17071,7 @@ run() {
     "get-all-schemas") playground_get_all_schemas_command ;;
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
+    "debug thread-dump") playground_debug_thread_dump_command ;;
     "debug log-level") playground_debug_log_level_command ;;
     "debug log-level get") playground_debug_log_level_get_command ;;
     "debug log-level set") playground_debug_log_level_set_command ;;
