Added `--compatibility` to `topic produce`

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -82,9 +82,9 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   💯 Get number of records in a topic\n" "$(green "topic get-number-records")         "
   [[ -n $long_usage ]] && printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "topic display-consumer-offsets")   "
   [[ -n $long_usage ]] && printf "  %s   🔬 Describe topic\n" "$(green "topic describe")                   "
+  [[ -n $long_usage ]] && printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "topic set-schema-compatibility")   "
   [[ -n $long_usage ]] && printf "  %s   📥 Consume topic from beginning\n" "$(green "topic consume")                    "
   [[ -n $long_usage ]] && printf "  %s   📤 Produce to a topic\n" "$(green "topic produce")                    "
-  [[ -n $long_usage ]] && printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "topic set-schema-compatibility")   "
   [[ -n $long_usage ]] && printf "  %s   🆕 Create topic\n" "$(green "topic create")                     "
   [[ -n $long_usage ]] && printf "  %s   ❌ Delete topic\n" "$(green "topic delete")                     "
   echo
@@ -2238,9 +2238,9 @@ playground_topic_usage() {
   printf "  %s   💯 Get number of records in a topic\n" "$(green "get-number-records")      "
   printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "display-consumer-offsets")"
   printf "  %s   🔬 Describe topic\n" "$(green "describe")                "
+  printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "set-schema-compatibility")"
   printf "  %s   📥 Consume topic from beginning\n" "$(green "consume")                 "
   printf "  %s   📤 Produce to a topic\n" "$(green "produce")                 "
-  printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "set-schema-compatibility")"
   printf "  %s   🆕 Create topic\n" "$(green "create")                  "
   printf "  %s   ❌ Delete topic\n" "$(green "delete")                  "
   echo
@@ -2352,6 +2352,47 @@ playground_topic_describe_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--topic, -t TOPIC")"
     printf "    🗳 Topic name\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_topic_set_schema_compatibility_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground topic set-schema-compatibility - 🛡️ Change topic's schema compatibility\n"
+    echo
+
+  else
+    printf "playground topic set-schema-compatibility - 🛡️ Change topic's schema compatibility\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground topic set-schema-compatibility [OPTIONS]\n"
+  printf "  playground topic set-schema-compatibility --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--topic, -t TOPIC")"
+    printf "    🗳 Topic name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--compatibility COMPATIBILITY (required)")"
+    printf "    Schema Registry compatibility rule\n"
+    printf "    Allowed: BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE\n"
     echo
 
     # :command.usage_fixed_flags
@@ -2487,6 +2528,12 @@ playground_topic_produce_usage() {
     echo
 
     # :flag.usage
+    printf "  %s\n" "$(magenta "--compatibility COMPATIBILITY (required)")"
+    printf "    Schema Registry compatibility rule\n"
+    printf "    Allowed: BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE\n"
+    echo
+
+    # :flag.usage
     printf "  %s\n" "$(magenta "--key KEY")"
     printf "    🗝️ Key to use. If not set, no key is used.\n    \n    If the key contain a number, it will be used as starting point and\n    incremented for each record.\n    \n    Example: key1 will start with key1, then key1, etc..\n    Example: mykey-10-suffix will start with mykey-10-suffix then\n    mykey-11-suffix, etc..\n    \n    Otherwise, the key will be same for all records.\n"
     echo
@@ -2519,47 +2566,6 @@ playground_topic_produce_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground topic produce --tombstone --topic a-topic --key mykey\n  \n  playground topic produce -t topic-json --nb-messages 10 << 'EOF'\n  {\n      \"_meta\": {\n          \"topic\": \"\",\n          \"key\": \"\",\n          \"relationships\": []\n      },\n      \"nested\": {\n          \"phone\": \"faker.phone.imei()\",\n          \"website\": \"faker.internet.domainName()\"\n      },\n      \"id\": \"iteration.index\",\n      \"name\": \"faker.internet.userName()\",\n      \"email\": \"faker.internet.exampleEmail()\",\n      \"phone\": \"faker.phone.imei()\",\n      \"website\": \"faker.internet.domainName()\",\n      \"city\": \"faker.address.city()\",\n      \"company\": \"faker.company.name()\"\n  }\n  EOF\n  \n  playground topic produce -t topic-avro --nb-messages 10 << 'EOF'\n  {\n      \"type\": \"record\",\n      \"namespace\": \"com.github.vdesabou\",\n      \"name\": \"Customer\",\n      \"fields\": [\n          {\n              \"name\": \"count\",\n              \"type\": \"long\",\n              \"doc\": \"count\"\n          },\n          {\n              \"name\": \"first_name\",\n              \"type\": \"string\",\n              \"doc\": \"First Name of Customer\"\n          },\n          {\n              \"name\": \"last_name\",\n              \"type\": \"string\",\n              \"doc\": \"Last Name of Customer\"\n          },\n          {\n              \"name\": \"address\",\n              \"type\": \"string\",\n              \"doc\": \"Address of Customer\"\n          }\n      ]\n  }\n  EOF\n  \n  playground topic produce -t topic-json-schema --nb-messages 3 << 'EOF'\n  {\n    \"$schema\": \"http://json-schema.org/draft-07/schema#\",\n    \"additionalProperties\": false,\n    \"$id\": \"http://lh.test/Customer.schema.json\",\n    \"title\": \"Customer\",\n    \"description\": \"Customer description\",\n    \"type\": \"object\",\n    \"properties\": {\n      \"name\": {\n        \"description\": \"Customer name\",\n        \"type\": \"string\",\n        \"maxLength\": 25\n      },\n      \"surname\": {\n        \"description\": \"Customer surname\",\n        \"type\": \"string\",\n        \"minLength\": 2\n      },\n      \"email\": {\n        \"description\": \"Email\",\n        \"type\": \"string\",\n        \"pattern\": \"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$\"\n      }\n    },\n    \"required\": [\n      \"name\",\n      \"surname\"\n    ]\n  }\n  EOF\n  \n  \n  playground topic produce -t topic-proto --nb-messages 3 << 'EOF'\n  syntax = \"proto3\";\n  \n  message Order {\n    float         total = 1;\n    repeated Item items = 2;\n  \n    message Item {\n      string name  = 1;\n      float  price = 2;\n    }\n  }\n  EOF\n  \n  playground topic produce -t vincent-jsql --nb-messages 10 << 'EOF'\n  CREATE TABLE \"notused\".\"notused\" (\n    \"id\" int PRIMARY KEY,\n    \"name\" varchar COMMENT 'faker.internet.userName()',\n    \"merchant_id\" int NOT NULL COMMENT 'faker.datatype.number()',\n    \"price\" int COMMENT 'faker.datatype.number()',\n    \"status\" int COMMENT 'faker.datatype.boolean()',\n    \"created_at\" datetime DEFAULT (now())\n  );\n  EOF\n"
-    echo
-
-  fi
-}
-
-# :command.usage
-playground_topic_set_schema_compatibility_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "playground topic set-schema-compatibility - 🛡️ Change topic's schema compatibility\n"
-    echo
-
-  else
-    printf "playground topic set-schema-compatibility - 🛡️ Change topic's schema compatibility\n"
-    echo
-
-  fi
-
-  printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground topic set-schema-compatibility [OPTIONS]\n"
-  printf "  playground topic set-schema-compatibility --help | -h\n"
-  echo
-
-  # :command.long_usage
-  if [[ -n $long_usage ]]; then
-    printf "%s\n" "$(bold "== Options ==")"
-
-    # :command.usage_flags
-    # :flag.usage
-    printf "  %s\n" "$(magenta "--topic, -t TOPIC")"
-    printf "    🗳 Topic name\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "$(magenta "--compatibility COMPATIBILITY (required)")"
-    printf "    Schema Registry compatibility rule\n"
-    printf "    Allowed: BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE\n"
-    echo
-
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
     echo
 
   fi
@@ -10621,6 +10627,46 @@ playground_topic_describe_command() {
 }
 
 # :command.function
+playground_topic_set_schema_compatibility_command() {
+  # src/topic_set_schema_compatibility_command.sh
+  topic="${args[--topic]}"
+  compatibility="${args[--compatibility]}"
+
+  environment=`get_environment_used`
+
+  if [ "$environment" == "error" ]
+  then
+    logerror "File containing restart command /tmp/playground-command does not exist!"
+    exit 1
+
+  fi
+
+  ret=$(get_sr_url_and_security)
+
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
+
+  if [[ ! -n "$topic" ]]
+  then
+      logwarn "--topic flag was not provided, applying command to all topics"
+      check_if_continue
+      topic=$(playground get-topic-list --skip-connect-internal-topics)
+      if [ "$topic" == "" ]
+      then
+          logerror "❌ No topic found !"
+          exit 1
+      fi
+  fi
+
+  items=($topic)
+  for topic in ${items[@]}
+  do
+    log "🛡️ Set compatibility for subject ${topic}-value to $compatibility"
+    curl $sr_security -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data "{\"compatibility\": \"$compatibility\"}" "${sr_url}/config/${topic}-value"
+  done
+}
+
+# :command.function
 playground_topic_consume_command() {
   # src/topic_consume_command.sh
   topic="${args[--topic]}"
@@ -11065,6 +11111,7 @@ playground_topic_produce_command() {
   forced_value="${args[--forced-value]}"
   generate_only="${args[--generate-only]}"
   tombstone="${args[--tombstone]}"
+  compatibility="${args[--compatibility]}"
 
   tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
   trap 'rm -rf $tmp_dir' EXIT
@@ -11366,6 +11413,8 @@ playground_topic_produce_command() {
           then
               log "--nb-partitions is set, creating topic with $nb_partitions partitions"
               playground topic create --topic $topic --nb-partitions $nb_partitions
+          else
+              playground topic create --topic $topic
           fi
       fi
   else
@@ -11379,6 +11428,11 @@ playground_topic_produce_command() {
           log "💯 Get number of records in topic $topic"
           tail -1 $tmp_dir/result.log
       fi
+  fi
+
+  if [ "$compatibility" != "" ]
+  then
+      playground topic set-schema-compatibility --topic $topic --compatibility $compatibility
   fi
 
   if [[ -n "$key" ]]
@@ -11544,46 +11598,6 @@ playground_topic_produce_command() {
   log "📤 produced $nb_messages records to topic $topic, $ELAPSED"
   set +x
   playground topic get-number-records --topic $topic
-}
-
-# :command.function
-playground_topic_set_schema_compatibility_command() {
-  # src/topic_set_schema_compatibility_command.sh
-  topic="${args[--topic]}"
-  compatibility="${args[--compatibility]}"
-
-  environment=`get_environment_used`
-
-  if [ "$environment" == "error" ]
-  then
-    logerror "File containing restart command /tmp/playground-command does not exist!"
-    exit 1
-
-  fi
-
-  ret=$(get_sr_url_and_security)
-
-  sr_url=$(echo "$ret" | cut -d "@" -f 1)
-  sr_security=$(echo "$ret" | cut -d "@" -f 2)
-
-  if [[ ! -n "$topic" ]]
-  then
-      logwarn "--topic flag was not provided, applying command to all topics"
-      check_if_continue
-      topic=$(playground get-topic-list --skip-connect-internal-topics)
-      if [ "$topic" == "" ]
-      then
-          logerror "❌ No topic found !"
-          exit 1
-      fi
-  fi
-
-  items=($topic)
-  for topic in ${items[@]}
-  do
-    log "🛡️ Set compatibility for subject ${topic}-value to $compatibility"
-    curl $sr_security -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data "{\"compatibility\": \"$compatibility\"}" "${sr_url}/config/${topic}-value"
-  done
 }
 
 # :command.function
@@ -17169,6 +17183,13 @@ playground_topic_parse_requirements() {
       shift $#
       ;;
 
+    set-schema-compatibility)
+      action="set-schema-compatibility"
+      shift
+      playground_topic_set_schema_compatibility_parse_requirements "$@"
+      shift $#
+      ;;
+
     consume)
       action="consume"
       shift
@@ -17180,13 +17201,6 @@ playground_topic_parse_requirements() {
       action="produce"
       shift
       playground_topic_produce_parse_requirements "$@"
-      shift $#
-      ;;
-
-    set-schema-compatibility)
-      action="set-schema-compatibility"
-      shift
-      playground_topic_set_schema_compatibility_parse_requirements "$@"
       shift $#
       ;;
 
@@ -17404,6 +17418,98 @@ playground_topic_describe_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_topic_set_schema_compatibility_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_topic_set_schema_compatibility_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="topic set-schema-compatibility"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --topic | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--topic']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--topic requires an argument: --topic, -t TOPIC" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --compatibility)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--compatibility']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--compatibility requires an argument: --compatibility COMPATIBILITY" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--compatibility']+x} ]]; then
+    printf "missing required flag: --compatibility COMPATIBILITY\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ ${args['--compatibility']} ]] && [[ ! ${args['--compatibility']} =~ ^(BACKWARD|BACKWARD_TRANSITIVE|FORWARD|FORWARD_TRANSITIVE|FULL|FULL_TRANSITIVE|NONE)$ ]]; then
+    printf "%s\n" "--compatibility must be one of: BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE" >&2
+    exit 1
+  fi
+
+  # :command.user_filter
+  filter_error=$(filter_schema_registry_running)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
 
 }
 
@@ -17695,6 +17801,21 @@ playground_topic_produce_parse_requirements() {
         ;;
 
       # :flag.case
+      --compatibility)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--compatibility']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--compatibility requires an argument: --compatibility COMPATIBILITY" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
       --key)
 
         # :flag.case_arg
@@ -17776,97 +17897,15 @@ playground_topic_produce_parse_requirements() {
     printf "missing required flag: --topic, -t TOPIC\n" >&2
     exit 1
   fi
+  if [[ -z ${args['--compatibility']+x} ]]; then
+    printf "missing required flag: --compatibility COMPATIBILITY\n" >&2
+    exit 1
+  fi
 
   # :command.default_assignments
   [[ -n ${args['--input']:-} ]] || args['--input']="-"
   [[ -n ${args['--nb-messages']:-} ]] || args['--nb-messages']="1"
   [[ -n ${args['--nb-partitions']:-} ]] || args['--nb-partitions']=""
-
-  # :command.user_filter
-  filter_error=$(filter_schema_registry_running)
-  if [[ -n $filter_error ]]; then
-    echo "$filter_error" >&2
-    exit 1
-  fi
-
-}
-
-# :command.parse_requirements
-playground_topic_set_schema_compatibility_parse_requirements() {
-  # :command.fixed_flags_filter
-  while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
-      --help | -h)
-        long_usage=yes
-        playground_topic_set_schema_compatibility_usage
-        exit
-        ;;
-
-      *)
-        break
-        ;;
-
-    esac
-  done
-
-  # :command.command_filter
-  action="topic set-schema-compatibility"
-
-  # :command.parse_requirements_while
-  while [[ $# -gt 0 ]]; do
-    key="$1"
-    case "$key" in
-      # :flag.case
-      --topic | -t)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-
-          args['--topic']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--topic requires an argument: --topic, -t TOPIC" >&2
-          exit 1
-        fi
-        ;;
-
-      # :flag.case
-      --compatibility)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-
-          args['--compatibility']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--compatibility requires an argument: --compatibility COMPATIBILITY" >&2
-          exit 1
-        fi
-        ;;
-
-      -?*)
-        printf "invalid option: %s\n" "$key" >&2
-        exit 1
-        ;;
-
-      *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
-
-        ;;
-
-    esac
-  done
-
-  # :command.required_flags_filter
-  if [[ -z ${args['--compatibility']+x} ]]; then
-    printf "missing required flag: --compatibility COMPATIBILITY\n" >&2
-    exit 1
-  fi
 
   # :command.whitelist_filter
   if [[ ${args['--compatibility']} ]] && [[ ! ${args['--compatibility']} =~ ^(BACKWARD|BACKWARD_TRANSITIVE|FORWARD|FORWARD_TRANSITIVE|FULL|FULL_TRANSITIVE|NONE)$ ]]; then
@@ -19569,9 +19608,9 @@ run() {
     "topic get-number-records") playground_topic_get_number_records_command ;;
     "topic display-consumer-offsets") playground_topic_display_consumer_offsets_command ;;
     "topic describe") playground_topic_describe_command ;;
+    "topic set-schema-compatibility") playground_topic_set_schema_compatibility_command ;;
     "topic consume") playground_topic_consume_command ;;
     "topic produce") playground_topic_produce_command ;;
-    "topic set-schema-compatibility") playground_topic_set_schema_compatibility_command ;;
     "topic create") playground_topic_create_command ;;
     "topic delete") playground_topic_delete_command ;;
     "ccloud-connector") playground_ccloud_connector_command ;;
