wip 👾 Add playground connector-plugin sourcecode commands #7214

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -155,6 +155,7 @@ playground_usage() {
   printf "  %s   ☕ List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "connector-plugin search-jar")               "
   printf "  %s   💯 List versions for a connector plugin from confluent hub https://www.confluent.io/hub/\n" "$(green "connector-plugin versions")                 "
   printf "  %s   🆕 List last updated connector plugins from confluent hub https://www.confluent.io/hub/\n" "$(green "connector-plugin display-last-updated")     "
+  printf "  %s   🧑‍💻 work with source code\n" "$(green "connector-plugin sourcecode")               "
   echo
   printf "%s\n" "$(bold "Connector commands:")"
   printf "  %s   🔗 Connector commands\n" "$(green "connector")                                 "
@@ -5476,6 +5477,7 @@ playground_connector_plugin_usage() {
   printf "  %s   ☕ List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "search-jar")          "
   printf "  %s   💯 List versions for a connector plugin from confluent hub https://www.confluent.io/hub/\n" "$(green "versions")            "
   printf "  %s   🆕 List last updated connector plugins from confluent hub https://www.confluent.io/hub/\n" "$(green "display-last-updated")"
+  printf "  %s   🧑‍💻 work with source code\n" "$(green "sourcecode")          "
   echo
 
   # :command.long_usage
@@ -5609,6 +5611,74 @@ playground_connector_plugin_display_last_updated_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground connector-plugin display-last-updated --days 7\n  playground connector-plugin display-last-updated --days 7 --vendor\n  confluentinc\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_plugin_sourcecode_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector-plugin sourcecode\n\n"
+    printf "  🧑‍💻 work with source code\n\n"
+  else
+    printf "playground connector-plugin sourcecode - 🧑‍💻 work with source code\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector-plugin sourcecode COMMAND\n"
+  printf "  playground connector-plugin sourcecode [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "$(bold "== Commands ==")"
+  printf "  %s   🏹 open on github\n" "$(green "open")"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_plugin_sourcecode_open_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector-plugin sourcecode open\n\n"
+    printf "  🏹 open on github\n\n"
+  else
+    printf "playground connector-plugin sourcecode open - 🏹 open on github\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector-plugin sourcecode open [OPTIONS]\n"
+  printf "  playground connector-plugin sourcecode open --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector-plugin, -c CONNECTOR-PLUGIN (required)")"
+    printf "    🔌 Connector plugin name\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connector-tag CONNECTOR_TAG")"
+    printf "    🔗 Connector version to use\n    \n    By default, for each connector, the latest available version on Confluent\n    Hub is used\n    \n    🎓 Tip: set to \" \" in order to select the version dynamically\n"
+    printf "    %s\n" "Conflicts: --connector-zip"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -7989,6 +8059,17 @@ function get_plugin_list() {
     fzf_option_pointer=""
     fzf_option_rounded=""
   fi
+
+    if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
+    then
+        playground generate-connector-plugin-list
+    fi
+
+    if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
+    then
+        logerror "file $root_folder/scripts/cli/confluent-hub-plugin-list.txt could not be generated"
+        exit 1
+    fi
 
   res=$(cat $root_folder/scripts/cli/confluent-hub-plugin-list.txt | cut -d "|" -f 1 | fzf -i --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --cycle --prompt="🔌" --header="select connector plugin" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
 }
@@ -13594,18 +13675,15 @@ playground_generate_connector_plugin_list_command() {
   tmp_file2=$tmp_dir/allmanis.json
 
   curl -s -S 'https://api.hub.confluent.io/api/plugins?per_page=100000' | jq '. | sort_by(.release_date) | reverse | .' > $tmp_file2
-
-  jq -r '.[] | "\(.owner.username)/\(.name)|\(.source_url)"' $tmp_file2 | sort | uniq > $tmp_file
-
+  jq -r '.[] | "\(.owner.username)/\(.name)|\(.source_url)"' $tmp_file2 | grep -v "NA/" | sort | uniq > $tmp_file
   rm -f $tmp_file2
 
+  # confluent only
   cd $tmp_dir > /dev/null
   get_3rdparty_file "confluent-plugin-sourcecode-mapping-list.txt"
   cd - > /dev/null
-
   if [ -f $tmp_dir/confluent-plugin-sourcecode-mapping-list.txt ]
   then
-      # confluent only
       grep -v confluentinc $tmp_file > $tmp_file2
       cat $tmp_dir/confluent-plugin-sourcecode-mapping-list.txt >> $tmp_file2
       cat $tmp_file2 | sort | uniq > $tmp_file
@@ -24436,8 +24514,14 @@ playground_connector_plugin_display_last_updated_command() {
 
   if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
   then
-      logwarn "file $root_folder/scripts/cli/confluent-hub-plugin-list.txt not found. Generating it now, it may take a while..."
+      log "file $root_folder/scripts/cli/confluent-hub-plugin-list.txt not found. Generating it now, it may take a while..."
       playground generate-connector-plugin-list
+  fi
+
+  if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
+  then
+      logerror "file $root_folder/scripts/cli/confluent-hub-plugin-list.txt could not be generated"
+      exit 1
   fi
 
   if [[ -n "$vendor" ]]
@@ -24470,6 +24554,73 @@ playground_connector_plugin_display_last_updated_command() {
       fi
       set -e
   done
+}
+
+# :command.function
+playground_connector_plugin_sourcecode_open_command() {
+
+  # src/commands/connector-plugin/sourcecode/open.sh
+  connector_plugin="${args[--connector-plugin]}"
+  connector_tag="${args[--connector-tag]}"
+
+  if [[ $connector_plugin == *"@"* ]]
+  then
+    connector_plugin=$(echo "$connector_plugin" | cut -d "@" -f 2)
+  fi
+
+  if [[ -n "$connector_tag" ]]
+  then
+      if [ "$connector_tag" == " " ]
+      then
+          ret=$(choose_connector_tag "$connector_plugin")
+          connector_tag=$(echo "$ret" | cut -d ' ' -f 2 | sed 's/^v//')
+      fi
+  else
+      connector_tag="latest"
+  fi
+
+  if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
+  then
+      log "file $root_folder/scripts/cli/confluent-hub-plugin-list.txt not found. Generating it now, it may take a while..."
+      playground generate-connector-plugin-list
+  fi
+
+  if [ ! -f $root_folder/scripts/cli/confluent-hub-plugin-list.txt ]
+  then
+      logerror "file $root_folder/scripts/cli/confluent-hub-plugin-list.txt could not be generated"
+      exit 1
+  fi
+
+  set +e
+  output=$(grep "$connector_plugin|" $root_folder/scripts/cli/confluent-hub-plugin-list.txt)
+  ret=$?
+  set -e
+  if [ $ret -ne 0 ]
+  then
+      logerror "❌ could not found $connector_plugin in $root_folder/scripts/cli/confluent-hub-plugin-list.txt"
+      exit 1
+  fi
+
+  sourcecode_url=$(echo "$output" | cut -d "|" -f 2)
+  if [ "$sourcecode_url" == "null" ] || [ "$sourcecode_url" == "" ]
+  then
+      logerror "❌ could not found sourcecode url for plugin $connector_plugin. It is probably proprietary"
+      exit 1
+  fi
+
+  if [ "$connector_tag" != "latest" ] && [[ "$sourcecode_url" == *"github.com"* ]]
+  then
+      sourcecode_url="$sourcecode_url/tree/v$connector_tag"
+  fi
+
+  if [[ $(type -f open 2>&1) =~ "not found" ]]
+  then
+      log "🔗 Cannot open browser, use url:"
+      echo "$sourcecode_url"
+  else
+      log "🧑‍💻 Openening sourcecode url $sourcecode_url for plugin $connector_plugin in browser for $connector_tag version"
+      open "$sourcecode_url"
+  fi
 }
 
 # :command.function
@@ -40794,6 +40945,13 @@ playground_connector_plugin_parse_requirements() {
       shift $#
       ;;
 
+    sourcecode)
+      action="sourcecode"
+      shift
+      playground_connector_plugin_sourcecode_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       playground_connector_plugin_usage >&2
@@ -41133,6 +41291,157 @@ playground_connector_plugin_display_last_updated_parse_requirements() {
       printf "validation error in %s:\n%s\n" "--vendor VENDOR" "$validation_output" >&2
       exit 1
     fi
+  fi
+
+}
+
+# :command.parse_requirements
+playground_connector_plugin_sourcecode_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_plugin_sourcecode_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    open)
+      action="open"
+      shift
+      playground_connector_plugin_sourcecode_open_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      playground_connector_plugin_sourcecode_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_connector_plugin_sourcecode_open_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_plugin_sourcecode_open_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector-plugin sourcecode open"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connector-plugin | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connector-plugin']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector-plugin requires an argument: --connector-plugin, -c CONNECTOR-PLUGIN" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --connector-tag)
+        # :flag.conflicts
+        if [[ -n "${args['--connector-zip']:-}" ]]; then
+          printf "conflicting options: %s cannot be used with %s\n" "$key" "--connector-zip" >&2
+          exit 1
+        fi
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connector-tag']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connector-tag requires an argument: --connector-tag CONNECTOR_TAG" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--connector-plugin']+x} ]]; then
+    printf "missing required flag: --connector-plugin, -c CONNECTOR-PLUGIN\n" >&2
+    exit 1
   fi
 
 }
@@ -44784,6 +45093,8 @@ run() {
     "connector-plugin search-jar") playground_connector_plugin_search_jar_command ;;
     "connector-plugin versions") playground_connector_plugin_versions_command ;;
     "connector-plugin display-last-updated") playground_connector_plugin_display_last_updated_command ;;
+    "connector-plugin sourcecode") playground_connector_plugin_sourcecode_command ;;
+    "connector-plugin sourcecode open") playground_connector_plugin_sourcecode_open_command ;;
     "connector") playground_connector_command ;;
     "connector status") playground_connector_status_command ;;
     "connector oracle-cdc-xstream") playground_connector_oracle_cdc_xstream_command ;;
