import command

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -46,7 +46,8 @@ playground_usage() {
   echo
   printf "%s\n" "$(bold "Repro commands:")"
   printf "  %s   👷‍♂️ Reproduction model commands\n" "$(green "repro")                                  "
-  [[ -n $long_usage ]] && printf "  %s   ↗️ Export your reproduction models to easily share.\n" "$(green "repro export")                           "
+  [[ -n $long_usage ]] && printf "  %s   📤 Export as tgz file uncommitted reproduction models from the folder of current reproduction model\n" "$(green "repro export")                           "
+  [[ -n $long_usage ]] && printf "  %s   📥 Import tgz file which was created with export command\n" "$(green "repro import")                           "
   [[ -n $long_usage ]] && printf "  %s   🛠  Bootstrap reproduction model\n" "$(green "repro bootstrap")                        "
   echo
   printf "%s\n" "$(bold "Kafka commands:")"
@@ -365,6 +366,43 @@ playground_get_any_file_with_fzf_usage() {
   printf "%s\n" "$(bold "== Usage ==")"
   printf "  playground get-any-file-with-fzf [CUR]\n"
   printf "  playground get-any-file-with-fzf --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "CUR")"
+    printf "    correspond to completion $cur\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_get_playground_repro_export_with_fzf_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground get-playground-repro-export-with-fzf - Return some completion for export tgz files\n"
+    echo
+
+  else
+    printf "playground get-playground-repro-export-with-fzf - Return some completion for export tgz files\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground get-playground-repro-export-with-fzf [CUR]\n"
+  printf "  playground get-playground-repro-export-with-fzf --help | -h\n"
   echo
 
   # :command.long_usage
@@ -925,7 +963,8 @@ playground_repro_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
-  printf "  %s   ↗️ Export your reproduction models to easily share.\n" "$(green "export")   "
+  printf "  %s   📤 Export as tgz file uncommitted reproduction models from the folder of current reproduction model\n" "$(green "export")   "
+  printf "  %s   📥 Import tgz file which was created with export command\n" "$(green "import")   "
   printf "  %s   🛠  Bootstrap reproduction model\n" "$(green "bootstrap")"
   echo
 
@@ -953,11 +992,11 @@ playground_repro_usage() {
 # :command.usage
 playground_repro_export_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground repro export - ↗️ Export your reproduction models to easily share.\n"
+    printf "playground repro export - 📤 Export as tgz file uncommitted reproduction models from the folder of current reproduction model\n"
     echo
 
   else
-    printf "playground repro export - ↗️ Export your reproduction models to easily share.\n"
+    printf "playground repro export - 📤 Export as tgz file uncommitted reproduction models from the folder of current reproduction model\n"
     echo
 
   fi
@@ -975,6 +1014,41 @@ playground_repro_export_usage() {
     # :flag.usage
     printf "  %s\n" "$(magenta "--all")"
     printf "    Export all uncommitted reproduction models\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_repro_import_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground repro import - 📥 Import tgz file which was created with export command\n"
+    echo
+
+  else
+    printf "playground repro import - 📥 Import tgz file which was created with export command\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground repro import [OPTIONS]\n"
+  printf "  playground repro import --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--file, -f FILE")"
+    printf "    🤐 playground_repro_export.tgz file\n    \n    ❕ It must be absolute full path\n    \n    🎓 Tip: use <tab> completion to trigger fzf completion \n            use folder_zip_or_jar (default: ~/Downloads) in config.ini file to\n    configure where to search the files (current folder is always used)\n"
     echo
 
     # :command.usage_fixed_flags
@@ -3999,6 +4073,35 @@ function get_zip_or_jar_with_fzf() {
   folder_zip_or_jar=${folder_zip_or_jar//,/ }
 
   res=$(find $folder_zip_or_jar $PWD -name \*.$type ! -path '*/\.*' | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🍺" --header="ctrl-c or esc to quit" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
+}
+
+function get_playground_repro_export_with_fzf() {
+  cur="$1"
+
+  fzf_version=$(get_fzf_version)
+  if version_gt $fzf_version "0.38"
+  then
+    fzf_option_wrap="--preview-window=40%,wrap"
+    fzf_option_pointer="--pointer=👉"
+    fzf_option_rounded="--border=rounded"
+  else
+    fzf_options=""
+    fzf_option_pointer=""
+    fzf_option_rounded=""
+  fi
+
+  if config_has_key "folder_zip_or_jar"
+  then
+    folder_zip_or_jar=$(config_get "folder_zip_or_jar")
+  else
+    logerror "Could not find config value <folder_zip_or_jar> !"
+    exit 1
+  fi
+
+  folder_zip_or_jar=${folder_zip_or_jar//\~/$HOME}
+  folder_zip_or_jar=${folder_zip_or_jar//,/ }
+
+  res=$(find $folder_zip_or_jar $PWD -name playground_repro_export.tgz ! -path '*/\.*' | fzf --query "$cur" --margin=1%,1%,1%,1% $fzf_option_rounded --info=inline --prompt="🍺" --header="ctrl-c or esc to quit" --color="bg:-1,bg+:-1,info:#BDBB72,border:#FFFFFF,spinner:0,hl:#beb665,fg:#00f7f7,header:#5CC9F5,fg+:#beb665,pointer:#E12672,marker:#5CC9F5,prompt:#98BEDE" $fzf_option_wrap $fzf_option_pointer);echo "$cur@$res"
 }
 
 function get_any_files_with_fzf() {
@@ -8051,6 +8154,14 @@ playground_get_any_file_with_fzf_command() {
 }
 
 # :command.function
+playground_get_playground_repro_export_with_fzf_command() {
+  # src/get_playground_repro_export_with_fzf_command.sh
+  cur="${args[cur]}"
+
+  get_playground_repro_export_with_fzf "$cur"
+}
+
+# :command.function
 playground_get_predefined_schemas_command() {
   # src/get_predefined_schemas_command.sh
   cur="${args[cur]}"
@@ -8819,7 +8930,7 @@ playground_repro_export_command() {
               tar cvfz "$output_filename" $new_files > /dev/null 2>&1
               if [ -f $final_archive ]
               then
-                  log "✅ Exported archive is available: $final_archive"
+                  log "📤 Exported archive is available: $final_archive"
               else
                   logerror "❌ export failed as archive could not be created !"
                   exit 1
@@ -8875,7 +8986,7 @@ playground_repro_export_command() {
               tar cvfz "$output_filename" $new_files > /dev/null 2>&1
               if [ -f $final_archive ]
               then
-                  log "✅ Exported archive is available: $final_archive"
+                  log "📤 Exported archive is available: $final_archive"
               else
                   logerror "❌ export failed as archive could not be created !"
                   exit 1
@@ -8890,6 +9001,48 @@ playground_repro_export_command() {
       fi
   fi
 
+}
+
+# :command.function
+playground_repro_import_command() {
+  # src/repro_import_command.sh
+  file="${args[--file]}"
+
+  DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+  dir1=$(echo ${DIR_CLI%/*})
+  root_folder=$(echo ${dir1%/*})
+
+  if [ ! -z "$OUTPUT_FOLDER" ]
+  then
+    output_folder="$OUTPUT_FOLDER"
+  else
+    output_folder="reproduction-models"
+  fi
+
+  if [ "$output_folder" != "reproduction-models" ]
+  then
+      logerror "❌ OUTPUT_FOLDER $output_folder is not set with reproduction-models, this is the only supported value !"
+      exit 1
+  fi
+
+  if [[ $file == *"@"* ]]
+  then
+    file=$(echo "$file" | cut -d "@" -f 2)
+  fi
+
+  filename=$(basename $file)
+
+  if [ "playground_repro_export.tgz" != ${filename} ]
+  then
+      logerror "file $file is not named playground_repro_export.tgz"
+      exit 1
+  fi
+
+  repro_dir=$root_folder/$output_folder
+  cd $repro_dir
+
+  log "📥 Installing $file"
+  tar xvfz $file
 }
 
 # :command.function
@@ -13467,6 +13620,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    get-playground-repro-export-with-fzf)
+      action="get-playground-repro-export-with-fzf"
+      shift
+      playground_get_playground_repro_export_with_fzf_parse_requirements "$@"
+      shift $#
+      ;;
+
     get-predefined-schemas)
       action="get-predefined-schemas"
       shift
@@ -14000,6 +14160,56 @@ playground_get_any_file_with_fzf_parse_requirements() {
 
   # :command.command_filter
   action="get-any-file-with-fzf"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['cur']+x} ]]; then
+
+          args['cur']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_get_playground_repro_export_with_fzf_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_get_playground_repro_export_with_fzf_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="get-playground-repro-export-with-fzf"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -15141,6 +15351,13 @@ playground_repro_parse_requirements() {
       shift $#
       ;;
 
+    import)
+      action="import"
+      shift
+      playground_repro_import_parse_requirements "$@"
+      shift $#
+      ;;
+
     bootstrap)
       action="bootstrap"
       shift
@@ -15224,6 +15441,69 @@ playground_repro_export_parse_requirements() {
         # :flag.case_no_arg
         args['--all']=1
         shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_repro_import_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_repro_import_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="repro import"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --file | -f)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_file_exists_with_trick "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--file, -f FILE" "$(validate_file_exists_with_trick "$2")" >&2
+            exit 1
+          fi
+
+          args['--file']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--file requires an argument: --file, -f FILE" >&2
+          exit 1
+        fi
         ;;
 
       -?*)
@@ -20321,6 +20601,7 @@ run() {
     "get-examples-list-with-fzf") playground_get_examples_list_with_fzf_command ;;
     "get-zip-or-jar-with-fzf") playground_get_zip_or_jar_with_fzf_command ;;
     "get-any-file-with-fzf") playground_get_any_file_with_fzf_command ;;
+    "get-playground-repro-export-with-fzf") playground_get_playground_repro_export_with_fzf_command ;;
     "get-predefined-schemas") playground_get_predefined_schemas_command ;;
     "bashly-reload") playground_bashly_reload_command ;;
     "run") playground_run_command ;;
@@ -20331,6 +20612,7 @@ run() {
     "open-docs") playground_open_docs_command ;;
     "repro") playground_repro_command ;;
     "repro export") playground_repro_export_command ;;
+    "repro import") playground_repro_import_command ;;
     "repro bootstrap") playground_repro_bootstrap_command ;;
     "get-docker-compose") playground_get_docker_compose_command ;;
     "get-properties") playground_get_properties_command ;;
