Remove version from docker compose yaml files #5634

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -911,6 +911,11 @@ playground_update_readme_usage() {
     printf "    💯 list of tags\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--generate-for-kb")"
+    printf "\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
@@ -11826,6 +11831,7 @@ playground_get_predefined_schemas_command() {
 playground_update_readme_command() {
   # src/commands/update-readme.sh
   tags="${args[--tags]}"
+  generate_for_kb="${args[--generate-for-kb]}"
 
   set +e
   tmp_dir="/tmp/update-readme"
@@ -12064,89 +12070,91 @@ playground_update_readme_command() {
       done #end image_version
     done #end script
 
-    # GH issues
-    if [ "$html_url" != "" ]
+    if [[ ! -n "$generate_for_kb" ]]
     then
-      t=$(echo ${testdir} | sed 's/-/\//')
-      title="🔥 ${t}"
-      log "Number of successful tests: $nb_success/${nb_tests}"
-      if [ ${nb_fail} -gt 0 ]
+      # GH issues
+      if [ "$html_url" != "" ]
       then
-        gh issue list --limit 500 | grep "$title" > /dev/null
-        if [ $? != 0 ]
+        t=$(echo ${testdir} | sed 's/-/\//')
+        title="🔥 ${t}"
+        log "Number of successful tests: $nb_success/${nb_tests}"
+        if [ ${nb_fail} -gt 0 ]
         then
-          echo -e "🆕💥 New issue !\n" >> ${gh_msg_file_intro}
-          msg=$(cat ${gh_msg_file_intro} ${gh_msg_file})
-          log "Creating GH issue with title $title"
-          gh issue create --title "$title" --body "$msg" --assignee vdesabou --label "new 🆕"
-        else
-          echo -e "🤦‍♂️💥 Still failing !\n" >> ${gh_msg_file_intro}
-          msg=$(cat ${gh_msg_file_intro} ${gh_msg_file})
-          log "GH issue with title $title already exist, adding comment..."
-          issue_number=$(gh issue list --limit 500 | grep "$title" | awk '{print $1;}')
-          gh issue comment ${issue_number} --body "$msg"
-          gh issue edit ${issue_number} --add-label "CI failing 🔥" --remove-label "new 🆕"
+          gh issue list --limit 500 | grep "$title" > /dev/null
+          if [ $? != 0 ]
+          then
+            echo -e "🆕💥 New issue !\n" >> ${gh_msg_file_intro}
+            msg=$(cat ${gh_msg_file_intro} ${gh_msg_file})
+            log "Creating GH issue with title $title"
+            gh issue create --title "$title" --body "$msg" --assignee vdesabou --label "new 🆕"
+          else
+            echo -e "🤦‍♂️💥 Still failing !\n" >> ${gh_msg_file_intro}
+            msg=$(cat ${gh_msg_file_intro} ${gh_msg_file})
+            log "GH issue with title $title already exist, adding comment..."
+            issue_number=$(gh issue list --limit 500 | grep "$title" | awk '{print $1;}')
+            gh issue comment ${issue_number} --body "$msg"
+            gh issue edit ${issue_number} --add-label "CI failing 🔥" --remove-label "new 🆕"
+          fi
+          gh_issue_number=$(gh issue list --limit 500 | grep "$title" | awk '{print $1;}')
         fi
-        gh_issue_number=$(gh issue list --limit 500 | grep "$title" | awk '{print $1;}')
-      fi
-      if [ ${nb_success} -eq ${nb_tests} ]
-      then
-        # if all scripts in tests are now successful, close the issue
-        gh issue list --limit 500 | grep "$title" > /dev/null
-        if [ $? = 0 ]
+        if [ ${nb_success} -eq ${nb_tests} ]
         then
-          issue_number=$(gh issue list --limit 500 | grep "$title" | head -1 | awk '{print $1;}')
-          echo -e "👍✅ Issue fixed !\n" >> ${gh_msg_file_intro}
-          msg=$(cat ${gh_msg_file_intro} ${gh_msg_file})
-          gh issue comment ${issue_number} --body "$msg"
-          log "Closing GH issue #${issue_number} with title $title"
-          gh issue close ${issue_number}
+          # if all scripts in tests are now successful, close the issue
+          gh issue list --limit 500 | grep "$title" > /dev/null
+          if [ $? = 0 ]
+          then
+            issue_number=$(gh issue list --limit 500 | grep "$title" | head -1 | awk '{print $1;}')
+            echo -e "👍✅ Issue fixed !\n" >> ${gh_msg_file_intro}
+            msg=$(cat ${gh_msg_file_intro} ${gh_msg_file})
+            gh issue comment ${issue_number} --body "$msg"
+            log "Closing GH issue #${issue_number} with title $title"
+            gh issue close ${issue_number}
+          fi
         fi
       fi
-    fi
 
-    ci=""
-    ci_nb_fail=0
-    ci_nb_skipped=0
-    nb_image_versions=0
-    for image_version in $tags
-    do
-      let "nb_image_versions++"
-      image_version_no_dot=$(echo ${image_version} | sed 's/\.//g')
-      if [ "${TEST_FAILED[$image_version_no_dot]}" != "" ]
-      then
-        gh_issue_number=$(echo $gh_issue_number|tr -d '\n')
-        if [ "${gh_issue_number}" != "" ]
+      ci=""
+      ci_nb_fail=0
+      ci_nb_skipped=0
+      nb_image_versions=0
+      for image_version in $tags
+      do
+        let "nb_image_versions++"
+        image_version_no_dot=$(echo ${image_version} | sed 's/\.//g')
+        if [ "${TEST_FAILED[$image_version_no_dot]}" != "" ]
         then
-          ci="$ci [![issue $gh_issue_number](https://img.shields.io/badge/$nb_success/$nb_tests-CP%20$image_version-red)](https://github.com/vdesabou/kafka-docker-playground/issues/$gh_issue_number)"
+          gh_issue_number=$(echo $gh_issue_number|tr -d '\n')
+          if [ "${gh_issue_number}" != "" ]
+          then
+            ci="$ci [![issue $gh_issue_number](https://img.shields.io/badge/$nb_success/$nb_tests-CP%20$image_version-red)](https://github.com/vdesabou/kafka-docker-playground/issues/$gh_issue_number)"
+          else
+            ci="$ci ${TEST_FAILED[$image_version_no_dot]}"
+          fi
+          let "ci_nb_fail++"
+        elif [ "${TEST_SKIPPED[$image_version_no_dot]}" != "" ]
+        then
+          ci="$ci ${TEST_SKIPPED[$image_version_no_dot]}"
+          let "ci_nb_skipped++"
+        elif [ "${TEST_SUCCESS[$image_version_no_dot]}" != "" ]
+        then
+          ci="$ci [![CP $image_version](https://img.shields.io/badge/$nb_success/$nb_tests-CP%20$image_version-green)](${TEST_SUCCESS[$image_version_no_dot]})"
         else
-          ci="$ci ${TEST_FAILED[$image_version_no_dot]}"
+          logerror "TEST_SUCCESS, TEST_SKIPPED and TEST_FAILED are all empty !"
         fi
-        let "ci_nb_fail++"
-      elif [ "${TEST_SKIPPED[$image_version_no_dot]}" != "" ]
-      then
-        ci="$ci ${TEST_SKIPPED[$image_version_no_dot]}"
-        let "ci_nb_skipped++"
-      elif [ "${TEST_SUCCESS[$image_version_no_dot]}" != "" ]
-      then
-        ci="$ci [![CP $image_version](https://img.shields.io/badge/$nb_success/$nb_tests-CP%20$image_version-green)](${TEST_SUCCESS[$image_version_no_dot]})"
-      else
-        logerror "TEST_SUCCESS, TEST_SKIPPED and TEST_FAILED are all empty !"
-      fi
-    done
+      done
 
-    if [ ${ci_nb_fail} -eq 0 ] && [ ${ci_nb_skipped} -eq 0 ]
-    then
-        ci="[![CI ok](https://img.shields.io/badge/$nb_success/$nb_tests-ok!-green)]($html_url)"
-    elif [ ${ci_nb_fail} -eq ${nb_image_versions} ]
-    then
-        ci="[![CI fail](https://img.shields.io/badge/$nb_success/$nb_tests-fail!-red)](https://github.com/vdesabou/kafka-docker-playground/issues/$gh_issue_number)"
+      if [ ${ci_nb_fail} -eq 0 ] && [ ${ci_nb_skipped} -eq 0 ]
+      then
+          ci="[![CI ok](https://img.shields.io/badge/$nb_success/$nb_tests-ok!-green)]($html_url)"
+      elif [ ${ci_nb_fail} -eq ${nb_image_versions} ]
+      then
+          ci="[![CI fail](https://img.shields.io/badge/$nb_success/$nb_tests-fail!-red)](https://github.com/vdesabou/kafka-docker-playground/issues/$gh_issue_number)"
+      fi
     fi
 
     if [ "$connector_path" != "" ]
     then
       version=$(grep "$connector_path " $tmp_dir/README.txt | cut -d "|" -f 3 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
-      license=$(grep "$connector_path " $tmp_dir/README.txt | cut -d "|" -f 4 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
       owner=$(grep "$connector_path " $tmp_dir/README.txt | cut -d "|" -f 5 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
       release_date=$(grep "$connector_path " $tmp_dir/README.txt | cut -d "|" -f 6 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
       documentation_url=$(grep "$connector_path " $tmp_dir/README.txt | cut -d "|" -f 7 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//' | sed 's/.*(\(.*\))/\1/')
@@ -12155,18 +12163,6 @@ playground_update_readme_command() {
         release_date="unknown"
       fi
 
-      # if [ "$license" = "Confluent Software Evaluation License" ]
-      # then
-      #   type="![license](https://img.shields.io/badge/-confluent%20subscription-black)"
-      # elif [ "$license" = "Apache License 2.0" ] || [ "$license" = "Apache 2.0" ] || [ "$license" = "Apache License, Version 2.0" ] || [ "$license" = "The Apache License, Version 2.0" ]
-      # then
-      #   type="![license](https://img.shields.io/badge/-open%20source-black)"
-      # else
-      #   license=$(echo $licence | tr '[:upper:]' '[:lower:]')
-      #   #typeencoded=$(urlencode $license)
-      #   typeencoded=$(echo "$licence" | sed -e 's/ /%20/g')
-      #   type="![license](https://img.shields.io/badge/-$typeencoded-black)"
-      # fi
       owner_badge=""
       if [ "$owner" != "" ]
       then
@@ -15512,7 +15508,6 @@ playground_repro_bootstrap_command() {
       log "✨ Creating empty file $docker_compose_test_file"
 
       echo "---" > $docker_compose_test_file
-      echo "version: '3.5'" >> $docker_compose_test_file
       echo "" >> $docker_compose_test_file
       echo "# override the services here, example " >> $docker_compose_test_file
       echo "# services:" >> $docker_compose_test_file
@@ -17211,7 +17206,6 @@ playground_debug_enable_remote_debugging_command() {
       log "🐛📂 not deleting tmp dir $tmp_dir"
   fi
   cat << EOF > $tmp_dir/docker-compose-remote-debugging.yml
-version: '3.5'
 services:
   $container:
     environment:
@@ -24399,6 +24393,14 @@ playground_update_readme_parse_requirements() {
           printf "%s\n" "--tags requires an argument: --tags TAGS" >&2
           exit 1
         fi
+        ;;
+
+      # :flag.case
+      --generate-for-kb)
+
+        # :flag.case_no_arg
+        args['--generate-for-kb']=1
+        shift
         ;;
 
       -?*)
