wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -74,6 +74,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "topic display-consumer-offsets")    "
   [[ -n $long_usage ]] && printf "  %s   🔬 Describe topic\n" "$(green "topic describe")                    "
   [[ -n $long_usage ]] && printf "  %s   📥 Consume topic from beginning\n" "$(green "topic consume")                     "
+  [[ -n $long_usage ]] && printf "  %s   Produce to a topic\n" "$(green "topic produce")                     "
   [[ -n $long_usage ]] && printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "topic set-schema-compatibility")    "
   [[ -n $long_usage ]] && printf "  %s   🧞 Easily identify the usage of different schema versions within a topic.\n" "$(green "topic display-schema-id-statistics")"
   echo
@@ -1783,6 +1784,7 @@ playground_topic_usage() {
   printf "  %s   📭 Display content of __consumer_offsets topic\n" "$(green "display-consumer-offsets")    "
   printf "  %s   🔬 Describe topic\n" "$(green "describe")                    "
   printf "  %s   📥 Consume topic from beginning\n" "$(green "consume")                     "
+  printf "  %s   Produce to a topic\n" "$(green "produce")                     "
   printf "  %s   🛡️ Change topic's schema compatibility\n" "$(green "set-schema-compatibility")    "
   printf "  %s   🧞 Easily identify the usage of different schema versions within a topic.\n" "$(green "display-schema-id-statistics")"
   echo
@@ -1958,6 +1960,56 @@ playground_topic_consume_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_topic_produce_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground topic produce - Produce to a topic\n"
+    echo
+
+  else
+    printf "playground topic produce - Produce to a topic\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground topic produce [SCHEMA] [OPTIONS]\n"
+  printf "  playground topic produce --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--topic, -t TOPIC (required)")"
+    printf "    🗳 Topic name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--nb-messages NB-MESSAGES")"
+    printf "    Number of messages to produce\n"
+    printf "    Default: 1\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "$(bold "== Arguments ==")"
+
+    # :argument.usage
+    printf "  %s\n" "$(blue "SCHEMA")"
+    printf "    schema (reads from stdin if empty)\n"
+    printf "    Default: -\n"
     echo
 
   fi
@@ -9491,6 +9543,140 @@ playground_topic_consume_command() {
 }
 
 # :command.function
+playground_topic_produce_command() {
+  # src/topic_produce_command.sh
+  topic="${args[--topic]}"
+  nb_messages="${args[--nb-messages]}"
+
+  schema=${args[schema]}
+
+  if [ "$schema" = "-" ]
+  then
+      # stdin
+      schema_content=$(cat "$schema")
+  else
+      schema_content=$schema
+  fi
+
+  tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
+  schema_file=$tmp_dir/value_schema
+  echo "$schema_content" > $schema_file
+
+  # JSON is invalid
+  if ! echo "$json_content" | jq -e .  > /dev/null 2>&1
+  then
+      set +e
+      jq_output=$(jq . "$json_file" 2>&1)
+      error_line=$(echo "$jq_output" | grep -oE 'parse error.*at line [0-9]+' | grep -oE '[0-9]+')
+
+      if [[ -n "$error_line" ]]; then
+          logerror "❌ Invalid JSON at line $error_line"
+      fi
+      set -e
+
+      if [[ $(type -f bat 2>&1) =~ "not found" ]]
+      then
+          cat -n $json_file
+      else
+          bat $json_file --highlight-line $error_line
+      fi
+
+      exit 1
+  fi
+
+  # value_type
+  value_type=avro
+
+  environment=`get_environment_used`
+
+  if [ "$environment" == "error" ]
+  then
+    logerror "File containing restart command /tmp/playground-command does not exist!"
+    exit 1
+
+  fi
+
+  ret=$(get_sr_url_and_security)
+
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
+
+  bootstrap_server="broker:9092"
+  container="connect"
+  sr_url_cli="http://schema-registry:8081"
+  security=""
+  if [[ "$environment" == *"ssl"* ]]
+  then
+      sr_url_cli="https://schema-registry:8081"
+      security="--property schema.registry.ssl.truststore.location=/etc/kafka/secrets/kafka.client.truststore.jks --property schema.registry.ssl.truststore.password=confluent --property schema.registry.ssl.keystore.location=/etc/kafka/secrets/kafka.client.keystore.jks --property schema.registry.ssl.keystore.password=confluent --consumer.config /etc/kafka/secrets/client_without_interceptors.config"
+  elif [[ "$environment" == "rbac-sasl-plain" ]]
+  then
+      sr_url_cli="http://schema-registry:8081"
+      security="--property basic.auth.credentials.source=USER_INFO --property schema.registry.basic.auth.user.info=clientAvroCli:clientAvroCli --consumer.config /etc/kafka/secrets/client_without_interceptors.config"
+  elif [[ "$environment" == "kerberos" ]]
+  then
+      container="client"
+      sr_url_cli="http://schema-registry:8081"
+      security="--consumer.config /etc/kafka/consumer.properties"
+
+      docker exec -i client kinit -k -t /var/lib/secret/kafka-connect.key connect
+  elif [[ "$environment" == "environment" ]]
+  then
+    if [ -f /tmp/delta_configs/env.delta ]
+    then
+        source /tmp/delta_configs/env.delta
+    else
+        logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
+        exit 1
+    fi
+    if [ ! -f /tmp/delta_configs/ak-tools-ccloud.delta ]
+    then
+        logerror "ERROR: /tmp/delta_configs/ak-tools-ccloud.delta has not been generated"
+        exit 1
+    fi
+    DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+    dir1=$(echo ${DIR_CLI%/*})
+    root_folder=$(echo ${dir1%/*})
+    IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
+    source $root_folder/scripts/utils.sh
+  fi
+
+  case "${value_type}" in
+  avro)
+      docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools random /tmp/out.avro --schema-file /tmp/value_schema --count $nb_messages
+      docker run --rm -v $tmp_dir:/tmp/ vdesabou/avro-tools tojson /tmp/out.avro > $tmp_dir/out.json
+
+      log "payload is"
+      #cat $tmp_dir/out.json
+
+      cat $tmp_dir/out.json | docker exec -e SCHEMA_REGISTRY_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/kafka/tools-log4j.properties" -i $container kafka-$value_type-console-producer --broker-list $bootstrap_server --property schema.registry.url=$sr_url_cli --topic $topic $security --property value.schema="$(cat $tmp_dir/value_schema)"
+
+  ;;
+  avro-with-key)
+
+  ;;
+  json-schema)
+
+  ;;
+  json-schema-with-key)
+
+  ;;
+  protobuf)
+
+  ;;
+  protobuf-with-key)
+
+  ;;
+  none)
+  ;;
+  *)
+      logerror "producer name not valid ! Should be one of avro, avro-with-key, json-schema, json-schema-with-key, protobuf or protobuf-with-key"
+      exit 1
+  ;;
+  esac
+}
+
+# :command.function
 playground_topic_set_schema_compatibility_command() {
   # src/topic_set_schema_compatibility_command.sh
   topic="${args[--topic]}"
@@ -13848,6 +14034,13 @@ playground_topic_parse_requirements() {
       shift $#
       ;;
 
+    produce)
+      action="produce"
+      shift
+      playground_topic_produce_parse_requirements "$@"
+      shift $#
+      ;;
+
     set-schema-compatibility)
       action="set-schema-compatibility"
       shift
@@ -14201,6 +14394,107 @@ playground_topic_consume_parse_requirements() {
   [[ -n ${args['--min-expected-messages']:-} ]] || args['--min-expected-messages']=""
   [[ -n ${args['--grep']:-} ]] || args['--grep']=""
   [[ -n ${args['--timeout']:-} ]] || args['--timeout']="60"
+
+  # :command.user_filter
+  filter_error=$(filter_schema_registry_running)
+  if [[ -n $filter_error ]]; then
+    echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_topic_produce_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_topic_produce_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="topic produce"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --topic | -t)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--topic']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--topic requires an argument: --topic, -t TOPIC" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --nb-messages)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_integer "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--nb-messages NB-MESSAGES" "$(validate_integer "$2")" >&2
+            exit 1
+          fi
+
+          args['--nb-messages']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--nb-messages requires an argument: --nb-messages NB-MESSAGES" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['schema']+x} ]]; then
+
+          args['schema']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--topic']+x} ]]; then
+    printf "missing required flag: --topic, -t TOPIC\n" >&2
+    exit 1
+  fi
+
+  # :command.default_assignments
+  [[ -n ${args['schema']:-} ]] || args['schema']="-"
+  [[ -n ${args['--nb-messages']:-} ]] || args['--nb-messages']="1"
 
   # :command.user_filter
   filter_error=$(filter_schema_registry_running)
@@ -15682,6 +15976,7 @@ run() {
     "topic display-consumer-offsets") playground_topic_display_consumer_offsets_command ;;
     "topic describe") playground_topic_describe_command ;;
     "topic consume") playground_topic_consume_command ;;
+    "topic produce") playground_topic_produce_command ;;
     "topic set-schema-compatibility") playground_topic_set_schema_compatibility_command ;;
     "topic display-schema-id-statistics") playground_topic_display_schema_id_statistics_command ;;
     "ccloud-connector") playground_ccloud_connector_command ;;
