wip #5662

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -78,8 +78,8 @@ playground_usage() {
   printf "%s\n" "$(bold "TCP Proxy commands:")"
   printf "  %s   🏚 TCP Proxy commands\n" "$(green "tcp-proxy")                        "
   printf "  %s   💗 Start the TCP proxy\n" "$(green "tcp-proxy start")                  "
-  printf "  %s   ⏲️ Add milliseconds delay to service response.\n" "$(green "tcp-proxy delay")                  "
   printf "  %s   🧲 Get Zazkia active TCP connections config and stats\n" "$(green "tcp-proxy get-connections")        "
+  printf "  %s   ⏲️ Add milliseconds delay to service response.\n" "$(green "tcp-proxy delay")                  "
   echo
   printf "%s\n" "$(bold "Debug commands:")"
   printf "  %s   🐞 Debug commands\n" "$(green "debug")                            "
@@ -2693,8 +2693,8 @@ playground_tcp_proxy_usage() {
   # :command.usage_commands
   printf "%s\n" "$(bold "== Commands ==")"
   printf "  %s   💗 Start the TCP proxy\n" "$(green "start")          "
-  printf "  %s   ⏲️ Add milliseconds delay to service response.\n" "$(green "delay")          "
   printf "  %s   🧲 Get Zazkia active TCP connections config and stats\n" "$(green "get-connections")"
+  printf "  %s   ⏲️ Add milliseconds delay to service response.\n" "$(green "delay")          "
   echo
 
   # :command.long_usage
@@ -2778,6 +2778,41 @@ playground_tcp_proxy_start_usage() {
 }
 
 # :command.usage
+playground_tcp_proxy_get_connections_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground tcp-proxy get-connections - 🧲 Get Zazkia active TCP connections config and stats\n"
+    echo
+
+  else
+    printf "playground tcp-proxy get-connections - 🧲 Get Zazkia active TCP connections config and stats\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground tcp-proxy get-connections [OPTIONS]\n"
+  printf "  playground tcp-proxy get-connections --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--connection-id CONNECTION-ID")"
+    printf "    🧲 Zazkia TCP connection id\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
 playground_tcp_proxy_delay_usage() {
   if [[ -n $long_usage ]]; then
     printf "playground tcp-proxy delay\n"
@@ -2811,35 +2846,6 @@ playground_tcp_proxy_delay_usage() {
     printf "  %s\n" "$(magenta "--connection-id CONNECTION-ID")"
     printf "    🧲 Zazkia TCP connection id\n"
     echo
-
-    # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
-    printf "    Show this help\n"
-    echo
-
-  fi
-}
-
-# :command.usage
-playground_tcp_proxy_get_connections_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "playground tcp-proxy get-connections - 🧲 Get Zazkia active TCP connections config and stats\n"
-    echo
-
-  else
-    printf "playground tcp-proxy get-connections - 🧲 Get Zazkia active TCP connections config and stats\n"
-    echo
-
-  fi
-
-  printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground tcp-proxy get-connections\n"
-  printf "  playground tcp-proxy get-connections --help | -h\n"
-  echo
-
-  # :command.long_usage
-  if [[ -n $long_usage ]]; then
-    printf "%s\n" "$(bold "== Options ==")"
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -17496,6 +17502,20 @@ EOF
 }
 
 # :command.function
+playground_tcp_proxy_get_connections_command() {
+  # src/commands/tcp-proxy/get-connections.sh
+  connection_id="${args[--connection-id]}"
+
+  handle_onprem_connect_rest_api "curl -s -X GET -H \"Content-Type: application/json\" \"http://localhost:9191/links/\""
+  if [[ ! -n "$connection_id" ]]
+  then
+      echo "$curl_output" | jq -r '.[].links[] | select(.serviceReceiveError != "EOF") | {id, state, stats}'
+  else
+      echo "$curl_output" | jq -r '.[].links[] | select(.id == '$connection_id' and .serviceReceiveError != "EOF") | {id, state, stats}'
+  fi
+}
+
+# :command.function
 playground_tcp_proxy_delay_command() {
   # src/commands/tcp-proxy/delay.sh
   delay_service_response="${args[--delay-service-response]}"
@@ -17521,16 +17541,9 @@ playground_tcp_proxy_delay_command() {
   do
       log "⏲️ Add $delay_service_response milliseconds delay to service response for connection id $id"
       handle_onprem_connect_rest_api "curl -s -X POST -H \"Content-Type: application/json\"  --header 'Accept: application/json' \"http://localhost:9191/links/$id/delay-response?ms=$delay_service_response\""
+
+      playground tcp-proxy get-connections --connection-id $connection_id
   done
-
-  playground tcp-proxy get-connections
-}
-
-# :command.function
-playground_tcp_proxy_get_connections_command() {
-  # src/commands/tcp-proxy/get-connections.sh
-  handle_onprem_connect_rest_api "curl -s -X GET -H \"Content-Type: application/json\" \"http://localhost:9191/links/\""
-  echo "$curl_output" | jq -r '.[].links[] | select(.serviceReceiveError != "EOF") | {id, state, stats}'
 }
 
 # :command.function
@@ -28201,17 +28214,17 @@ playground_tcp_proxy_parse_requirements() {
       shift $#
       ;;
 
-    delay)
-      action="delay"
-      shift
-      playground_tcp_proxy_delay_parse_requirements "$@"
-      shift $#
-      ;;
-
     get-connections)
       action="get-connections"
       shift
       playground_tcp_proxy_get_connections_parse_requirements "$@"
+      shift $#
+      ;;
+
+    delay)
+      action="delay"
+      shift
+      playground_tcp_proxy_delay_parse_requirements "$@"
       shift $#
       ;;
 
@@ -28413,6 +28426,70 @@ playground_tcp_proxy_start_parse_requirements() {
 }
 
 # :command.parse_requirements
+playground_tcp_proxy_get_connections_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_tcp_proxy_get_connections_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tcp-proxy get-connections"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --connection-id)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--connection-id']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--connection-id requires an argument: --connection-id CONNECTION-ID" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--connection-id'] && -n $(validate_integer "${args['--connection-id']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--connection-id CONNECTION-ID" "$(validate_integer "${args['--connection-id']:-}")" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
 playground_tcp_proxy_delay_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -28499,50 +28576,6 @@ playground_tcp_proxy_delay_parse_requirements() {
     printf "validation error in %s:\n%s\n" "--connection-id CONNECTION-ID" "$(validate_integer "${args['--connection-id']:-}")" >&2
     exit 1
   fi
-
-}
-
-# :command.parse_requirements
-playground_tcp_proxy_get_connections_parse_requirements() {
-  # :command.fixed_flags_filter
-  while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
-      --help | -h)
-        long_usage=yes
-        playground_tcp_proxy_get_connections_usage
-        exit
-        ;;
-
-      *)
-        break
-        ;;
-
-    esac
-  done
-
-  # :command.command_filter
-  action="tcp-proxy get-connections"
-
-  # :command.parse_requirements_while
-  while [[ $# -gt 0 ]]; do
-    key="$1"
-    case "$key" in
-
-      -?*)
-        printf "invalid option: %s\n" "$key" >&2
-        exit 1
-        ;;
-
-      *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
-
-        ;;
-
-    esac
-  done
 
 }
 
@@ -34304,8 +34337,8 @@ run() {
     "schema delete") playground_schema_delete_command ;;
     "tcp-proxy") playground_tcp_proxy_command ;;
     "tcp-proxy start") playground_tcp_proxy_start_command ;;
-    "tcp-proxy delay") playground_tcp_proxy_delay_command ;;
     "tcp-proxy get-connections") playground_tcp_proxy_get_connections_command ;;
+    "tcp-proxy delay") playground_tcp_proxy_delay_command ;;
     "debug") playground_debug_command ;;
     "debug enable-remote-debugging") playground_debug_enable_remote_debugging_command ;;
     "debug testssl") playground_debug_testssl_command ;;
