Add latest version from hub in playground connector versions command #3859

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -82,7 +82,7 @@ playground_usage() {
   [[ -n $long_usage ]] && printf "  %s   🧩 Show status of all connectors\n" "$(green "connector status")                  "
   [[ -n $long_usage ]] && printf "  %s   🎨 Show all plugins installed\n" "$(green "connector plugins")                 "
   [[ -n $long_usage ]] && printf "  %s   ⏸️  Pause connector\n" "$(green "connector pause")                   "
-  [[ -n $long_usage ]] && printf "  %s   🧞 Get current version used in example\n" "$(green "connector versions")                "
+  [[ -n $long_usage ]] && printf "  %s   🧞 Get current and latest version available on Confluent Hub for connector(s) used in example\n" "$(green "connector versions")                "
   [[ -n $long_usage ]] && printf "  %s   ♻️  Restart connector\n" "$(green "connector restart")                 "
   [[ -n $long_usage ]] && printf "  %s   ⏯️  Resume connector\n" "$(green "connector resume")                  "
   [[ -n $long_usage ]] && printf "  %s   🗑️  Delete connector\n" "$(green "connector delete")                  "
@@ -2014,7 +2014,7 @@ playground_connector_usage() {
   printf "  %s   🧩 Show status of all connectors\n" "$(green "status")   "
   printf "  %s   🎨 Show all plugins installed\n" "$(green "plugins")  "
   printf "  %s   ⏸️  Pause connector\n" "$(green "pause")    "
-  printf "  %s   🧞 Get current version used in example\n" "$(green "versions") "
+  printf "  %s   🧞 Get current and latest version available on Confluent Hub for connector(s) used in example\n" "$(green "versions") "
   printf "  %s   ♻️  Restart connector\n" "$(green "restart")  "
   printf "  %s   ⏯️  Resume connector\n" "$(green "resume")   "
   printf "  %s   🗑️  Delete connector\n" "$(green "delete")   "
@@ -2139,29 +2139,23 @@ playground_connector_pause_usage() {
 # :command.usage
 playground_connector_versions_usage() {
   if [[ -n $long_usage ]]; then
-    printf "playground connector versions - 🧞 Get current version used in example\n"
+    printf "playground connector versions - 🧞 Get current and latest version available on Confluent Hub for connector(s) used in example\n"
     echo
 
   else
-    printf "playground connector versions - 🧞 Get current version used in example\n"
+    printf "playground connector versions - 🧞 Get current and latest version available on Confluent Hub for connector(s) used in example\n"
     echo
 
   fi
 
   printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground connector versions [OPTIONS]\n"
+  printf "  playground connector versions\n"
   printf "  playground connector versions --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "== Options ==")"
-
-    # :command.usage_flags
-    # :flag.usage
-    printf "  %s\n" "$(magenta "--connector, -c CONNECTOR")"
-    printf "    🔗 Connector name\n    \n    🎓 Tip: If not specified, the command will apply to all connectors\n"
-    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -9212,31 +9206,94 @@ playground_connector_pause_command() {
 # :command.function
 playground_connector_versions_command() {
   # src/connector_versions_command.sh
-  ret=$(get_connect_url_and_security)
-
-  connect_url=$(echo "$ret" | cut -d "@" -f 1)
-  security=$(echo "$ret" | cut -d "@" -f 2)
-
-  connector="${args[--connector]}"
-
-  if [[ ! -n "$connector" ]]
+  if [ ! -f /tmp/playground-run ]
   then
-      log "✨ --connector flag was not provided, applying command to all connectors"
-      connector=$(playground get-connector-list)
-      if [ "$connector" == "" ]
-      then
-          logerror "💤 No connector is running !"
-          exit 1
-      fi
+    logerror "File containing re-run command /tmp/playground-run does not exist!"
+    logerror "Make sure to use <playground run> command !"
+    exit 1
   fi
 
-  items=($connector)
-  for connector in ${items[@]}
-  do
-      log "Current version for $connector:"
-      package=$(curl -s $security "$connect_url/connectors/$connector" | jq -r '.config."connector.class"')
-      curl $security -s -X GET -H "Content-Type: application/json" "$connect_url/connector-plugins" | jq -r ".[] | select(.class == \"$package\").version"
-  done
+  test_file=$(cat /tmp/playground-run | awk '{ print $4}')
+
+  if [ ! -f $test_file ]
+  then
+
+  logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
+  logerror "Make sure to use <playground run> command !"
+  exit 1
+  fi
+
+  # determining the docker-compose file from from test_file
+  docker_compose_file=$(grep "environment" "$test_file" | grep DIR | grep start.sh | cut -d "/" -f 7 | cut -d '"' -f 1 | tail -n1 | xargs)
+  test_file_directory="$(dirname "${test_file}")"
+  docker_compose_file="${test_file_directory}/${docker_compose_file}"
+
+  if [ "${docker_compose_file}" != "" ] && [ ! -f "${docker_compose_file}" ]
+  then
+    docker_compose_file=""
+    logwarn "📁 Could not determine docker-compose override file from $test_file !"
+  fi
+
+  connector_paths=$(grep "CONNECT_PLUGIN_PATH" "${docker_compose_file}" | grep -v "KSQL_CONNECT_PLUGIN_PATH" | cut -d ":" -f 2  | tr -s " " | head -1)
+  if [ "$connector_paths" == "" ]
+  then
+      logerror "not a connector test"
+      exit 1
+  else
+      my_array_connector_tag=($(echo $CONNECTOR_TAG | tr "," "\n"))
+      for connector_path in ${connector_paths//,/ }
+      do
+          full_connector_name=$(basename "$connector_path")
+          connector_name=$(echo "$full_connector_name" | cut -d'-' -f2-)
+
+          connectors=(
+          "$connector_name"
+          )
+
+          output_format="\"🔢 v\" + .version + \" - 📅 release date: \" + .release_date"
+
+          curl -s -S 'https://api.hub.confluent.io/api/plugins?per_page=100000' | jq '. | sort_by(.release_date) | reverse | .' > /tmp/allmanis.json
+
+          connectors_string=""
+          delim=""
+          for conn in "${connectors[@]}"; do
+              connectors_string="$connectors_string$delim\"$conn\""
+              delim=","
+          done
+
+          latest=$(jq '.[] | select(IN(.name; '"${connectors_string}"')) | '"${output_format}"'' /tmp/allmanis.json)
+
+          rm /tmp/allmanis.json
+
+          DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+          dir1=$(echo ${DIR_CLI%/*})
+          root_folder=$(echo ${dir1%/*})
+
+          manifest_file="$root_folder/confluent-hub/$full_connector_name/manifest.json"
+          if [ -f $manifest_file ]
+          then
+              version=$(cat $manifest_file | jq -r '.version')
+              release_date=$(cat $manifest_file | jq -r '.release_date')
+          else
+              logerror "file $manifest_file does not exist"
+              exit 1
+          fi
+
+          current="\"🔢 v$version - 📅 release date: $release_date\""
+          if [ "$current" == "$latest" ]
+          then
+              log "👻 Version currently used for $full_connector_name is latest"
+              echo "$current"
+          else
+              log "🗯️ Version currently used for $full_connector_name is not latest"
+              log "Current"
+              echo "$current"
+              log "Latest on Hub"
+              echo "$latest"
+          fi
+
+      done
+  fi
 }
 
 # :command.function
@@ -13592,20 +13649,6 @@ playground_connector_versions_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
-      --connector | -c)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-
-          args['--connector']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--connector requires an argument: --connector, -c CONNECTOR" >&2
-          exit 1
-        fi
-        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
