open-docs

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -42,6 +42,7 @@ playground_usage() {
   printf "  %s   ⛅ Run any Confluent Cloud (ccloud) example\n" "$(green "run-ccloud")                       "
   printf "  %s   👐 When --file is not provided, simply open last example you ran with <playground run> or <playground run-ccloud>\n" "$(green "open")                             "
   printf "  %s   🛑 Stop currently running example\n" "$(green "stop")                             "
+  printf "  %s   🧑‍🎓 Open Confluent documentation of currently running example\n" "$(green "open-docs")                        "
   echo
   printf "%s\n" "$(bold "Bootstrap commands:")"
   printf "  %s   🛠  Bootstrap reproduction model\n" "$(green "bootstrap-reproduction-model")     "
@@ -856,6 +857,41 @@ playground_stop_usage() {
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_open_docs_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground open-docs - 🧑‍🎓 Open Confluent documentation of currently running example\n"
+    echo
+
+  else
+    printf "playground open-docs - 🧑‍🎓 Open Confluent documentation of currently running example\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground open-docs [OPTIONS]\n"
+  printf "  playground open-docs --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--only-show-url")"
+    printf "    🌐 Only show url\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -7870,7 +7906,7 @@ playground_run_command() {
   log "####################################################"
   SECONDS=0
   cd $test_file_directory
-  trap 'rm /tmp/playground-run-command-used;echo "";sleep 3;set +e;playground connector status;playground connector versions' EXIT
+  trap 'rm /tmp/playground-run-command-used;echo "";sleep 3;set +e;playground connector status;playground connector versions;playground open-docs --only-show-url' EXIT
   touch /tmp/playground-run-command-used
   bash $filename ${other_args[*]}
   ret=$?
@@ -8320,6 +8356,55 @@ playground_stop_command() {
 }
 
 # :command.function
+playground_open_docs_command() {
+  # src/open_docs_command.sh
+  only_show_url="${args[--only-show-url]}"
+  if [ ! -f /tmp/playground-run ]
+  then
+      logerror "File containing re-run command /tmp/playground-run does not exist!"
+      logerror "Make sure to use <playground run> command !"
+      exit 1
+  fi
+
+  test_file=$(cat /tmp/playground-run | awk '{ print $4}')
+
+  if [ ! -f $test_file ]
+  then
+
+      logerror "File $test_file retrieved from /tmp/playground-run does not exist!"
+      logerror "Make sure to use <playground run> command !"
+      exit 1
+  fi
+
+  readme_file="$(dirname $test_file)/README.md"
+  if [ ! -f $readme_file ]
+  then
+
+      logerror "README file $readme_file does not exist"
+      exit 1
+  fi
+
+  string=$(grep "Quickly test " $readme_file)
+  url=$(echo "$string" | grep -oE 'https?://[^ ]+')
+  url=${url//)/}
+
+  if [[ $url =~ "http" ]]
+  then
+      short_url=$(echo $url | cut -d '#' -f 1)
+      if [[ -n "$only_show_url" ]]
+      then
+          log "🌐 documentation is avaliable at $short_url"
+      else
+          log "🌐 opening documentation $short_url"
+          open "$short_url"
+      fi
+  else
+      logerror "Could not find documentation link in README file $readme_file"
+      exit 1
+  fi
+}
+
+# :command.function
 playground_bootstrap_reproduction_model_command() {
   # src/bootstrap_reproduction_model_command.sh
   IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
@@ -8512,7 +8597,8 @@ playground_bootstrap_reproduction_model_command() {
 
   if [[ $url =~ "http" ]]
   then
-    echo "# 🌐 documentation: $url" >> $tmp_dir/intro
+    short_url=$(echo $url | cut -d '#' -f 1)
+    echo "# 🌐 documentation: $short_url" >> $tmp_dir/intro
   fi
   echo "# 🐳 playground website: https://kafka-docker-playground.io" >> $tmp_dir/intro
   echo "# 💬 comments:" >> $tmp_dir/intro
@@ -12344,6 +12430,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    open-docs)
+      action="open-docs"
+      shift
+      playground_open_docs_parse_requirements "$@"
+      shift $#
+      ;;
+
     bootstrap-reproduction-model)
       action="bootstrap-reproduction-model"
       shift
@@ -13848,6 +13941,57 @@ playground_stop_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_open_docs_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_open_docs_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="open-docs"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --only-show-url)
+
+        # :flag.case_no_arg
+        args['--only-show-url']=1
+        shift
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -18546,6 +18690,7 @@ run() {
     "run-ccloud") playground_run_ccloud_command ;;
     "open") playground_open_command ;;
     "stop") playground_stop_command ;;
+    "open-docs") playground_open_docs_command ;;
     "bootstrap-reproduction-model") playground_bootstrap_reproduction_model_command ;;
     "get-docker-compose") playground_get_docker_compose_command ;;
     "get-properties") playground_get_properties_command ;;
