wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -9855,7 +9855,7 @@ playground_topic_produce_command() {
       log "🔮 schema was identified as avro"
       schema_type=avro
   else
-      log "📢 any known schema could be identified, payload will be sent as raw data"
+      log "📢 no known schema could be identified, payload will be sent as raw data"
       schema_type=raw
   fi
 
@@ -9953,7 +9953,7 @@ playground_topic_produce_command() {
       if [[ "$environment" == "environment" ]]
       then
           log "⛅ creating topic in confluent cloud"
-          create_topic $topic
+          playground topic create --topic $topic
       fi
   else
       tail -1 $tmp_dir/result.log
@@ -10133,31 +10133,41 @@ playground_topic_create_command() {
 
   fi
 
-  log "🆕 Creating topic $topic"
-  if [[ "$environment" == "environment" ]]
+  playground topic get-number-records --topic $topic > /tmp/result.log 2>/tmp/result.log
+  set +e
+  grep "does not exist" /tmp/result.log > /dev/null 2>&1
+  if [ $? == 0 ]
   then
-      if [ -f /tmp/delta_configs/env.delta ]
+      set -e
+      log "🆕 Creating topic $topic"
+      if [[ "$environment" == "environment" ]]
       then
-          source /tmp/delta_configs/env.delta
+          if [ -f /tmp/delta_configs/env.delta ]
+          then
+              source /tmp/delta_configs/env.delta
+          else
+              logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
+              exit 1
+          fi
+          if [ ! -f /tmp/delta_configs/ak-tools-ccloud.delta ]
+          then
+              logerror "ERROR: /tmp/delta_configs/ak-tools-ccloud.delta has not been generated"
+              exit 1
+          fi
+
+          DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+          dir1=$(echo ${DIR_CLI%/*})
+          root_folder=$(echo ${dir1%/*})
+          IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
+          source $root_folder/scripts/utils.sh
+
+          docker run --rm -v /tmp/delta_configs/ak-tools-ccloud.delta:/tmp/configuration/ccloud.properties ${CP_CONNECT_IMAGE}:${CONNECT_TAG} kafka-topics --create --topic $topic --bootstrap-server $BOOTSTRAP_SERVERS --command-config /tmp/configuration/ccloud.properties --partitions $nb_partitions ${other_args[*]}
       else
-          logerror "ERROR: /tmp/delta_configs/env.delta has not been generated"
-          exit 1
+          docker exec $container kafka-topics --create --topic $topic --bootstrap-server broker:9092 --partitions $nb_partitions $security ${other_args[*]}
       fi
-      if [ ! -f /tmp/delta_configs/ak-tools-ccloud.delta ]
-      then
-          logerror "ERROR: /tmp/delta_configs/ak-tools-ccloud.delta has not been generated"
-          exit 1
-      fi
-
-      DIR_CLI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
-      dir1=$(echo ${DIR_CLI%/*})
-      root_folder=$(echo ${dir1%/*})
-      IGNORE_CHECK_FOR_DOCKER_COMPOSE=true
-      source $root_folder/scripts/utils.sh
-
-      docker run --rm -v /tmp/delta_configs/ak-tools-ccloud.delta:/tmp/configuration/ccloud.properties ${CP_CONNECT_IMAGE}:${CONNECT_TAG} kafka-topics --create --topic $topic --bootstrap-server $BOOTSTRAP_SERVERS --command-config /tmp/configuration/ccloud.properties --partitions $nb_partitions ${other_args[*]}
   else
-      docker exec $container kafka-topics --create --topic $topic --bootstrap-server broker:9092 --partitions $nb_partitions $security ${other_args[*]}
+      logerror "❌ topic $topic already exist !"
+      exit 1
   fi
 }
 
@@ -10179,6 +10189,16 @@ playground_topic_delete_command() {
     exit 1
 
   fi
+
+  playground topic get-number-records --topic $topic > /tmp/result.log 2>/tmp/result.log
+  set +e
+  grep "does not exist" /tmp/result.log > /dev/null 2>&1
+  if [ $? == 0 ]
+  then
+      logwarn "❌ topic $topic does not exist !"
+      exit 1
+  fi
+  set -e
 
   log "❌ Deleting topic $topic"
   if [[ "$environment" == "environment" ]]
