added playground connector open-docs

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -141,6 +141,7 @@ playground_usage() {
   printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "connector show-config-parameters")              "
   printf "  %s   🔌 List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "connector search-jar")                          "
   printf "  %s   🔌 useful snippets\n" "$(green "connector snippets")                            "
+  printf "  %s   🧑‍🎓 Open connector documentation of currently running conector(s)\n" "$(green "connector open-docs")                           "
   printf "  %s   🧬 Set connect log level\n" "$(green "connector log-level")                           "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "connector create-or-update")                    "
   echo
@@ -4889,6 +4890,7 @@ playground_connector_usage() {
   printf "  %s   🔩 Show all possible configuration parameters of connector\n" "$(green "show-config-parameters")"
   printf "  %s   🔌 List jars for a connector plugin from confluent hub https://www.confluent.io/hub/ Search for specific class and display method signatures\n" "$(green "search-jar")            "
   printf "  %s   🔌 useful snippets\n" "$(green "snippets")              "
+  printf "  %s   🧑‍🎓 Open connector documentation of currently running conector(s)\n" "$(green "open-docs")             "
   printf "  %s   🧬 Set connect log level\n" "$(green "log-level")             "
   printf "  %s   🧑‍🎨  Create or update connector\n" "$(green "create-or-update")      "
   echo
@@ -5463,6 +5465,41 @@ playground_connector_snippets_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground connector snippets --converter avro --dlq\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_connector_open_docs_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground connector open-docs - 🧑‍🎓 Open connector documentation of currently running conector(s)\n"
+    echo
+
+  else
+    printf "playground connector open-docs - 🧑‍🎓 Open connector documentation of currently running conector(s)\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground connector open-docs [OPTIONS]\n"
+  printf "  playground connector open-docs --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--only-show-url")"
+    printf "    🌐 Only show url\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -10669,6 +10706,7 @@ playground_status_command() {
   then
       playground connector versions | grep -v "applying command to all connectors"
       playground connector status | grep -v "applying command to all connectors"
+      playground connector open-docs --only-show-url
       playground connector show-config | grep -v "applying command to all connectors"
       playground connector show-config-parameters --only-show-file-path | grep -v "applying command to all connectors"
   fi
@@ -17570,7 +17608,6 @@ playground_connector_versions_command() {
       log "🎯 Version currently used for confluent platform"
       echo "$current_tag"
 
-      my_array_connector_tag=($(echo $CONNECTOR_TAG | tr "," "\n"))
       for connector_path in ${connector_paths//,/ }
       do
           full_connector_name=$(basename "$connector_path")
@@ -18206,6 +18243,70 @@ playground_connector_snippets_command() {
 }
 
 # :command.function
+playground_connector_open_docs_command() {
+  # src/connector_open_docs_command.sh
+  test_file=$(playground state get run.test_file)
+  only_show_url="${args[--only-show-url]}"
+
+  if [ ! -f $test_file ]
+  then
+
+      logerror "❌ File $test_file retrieved from $root_folder/playground.ini does not exist!"
+      exit 1
+  fi
+
+  # determining the docker-compose file from from test_file
+  docker_compose_file=$(grep "start-environment" "$test_file" |  awk '{print $6}' | cut -d "/" -f 2 | cut -d '"' -f 1 | tail -n1 | xargs)
+  test_file_directory="$(dirname "${test_file}")"
+  docker_compose_file="${test_file_directory}/${docker_compose_file}"
+
+  if [ "${docker_compose_file}" != "" ] && [ ! -f "${docker_compose_file}" ]
+  then
+      logwarn "Skipping as docker-compose override file could not be detemined"
+      exit 0
+  fi
+
+  connector_paths=$(grep "CONNECT_PLUGIN_PATH" "${docker_compose_file}" | grep -v "KSQL_CONNECT_PLUGIN_PATH" | cut -d ":" -f 2  | tr -s " " | head -1)
+  if [ "$connector_paths" == "" ]
+  then
+      logwarn "Skipping as it is not an example with connector"
+      exit 0
+  else
+      for connector_path in ${connector_paths//,/ }
+      do
+          full_connector_name=$(basename "$connector_path")
+
+          manifest_file="$root_folder/confluent-hub/$full_connector_name/manifest.json"
+          if [ -f $manifest_file ]
+          then
+              url=$(cat $manifest_file | jq -r '.documentation_url')
+              name=$(cat $manifest_file | jq -r '.name')
+              url=${url//)/}
+
+              if [[ $url =~ "http" ]]
+              then
+                  short_url=$(echo $url | cut -d '#' -f 1)
+                  if [[ -n "$only_show_url" ]]
+                  then
+                      log "🌐 documentation for connector $name is available at:"
+                      echo "$short_url"
+                  else
+                      log "🌐 opening documentation for connector $name $short_url"
+                      open "$short_url"
+                  fi
+              else
+                  logerror "❌ Could not find documentation link in manifest file $manifest_file"
+                  exit 1
+              fi
+          else
+              logerror "❌ file $manifest_file does not exist"
+              exit 1
+          fi
+      done
+  fi
+}
+
+# :command.function
 playground_connector_log_level_command() {
   # src/connector_log_level_command.sh
   get_connect_url_and_security
@@ -18450,6 +18551,7 @@ playground_connector_create_or_update_command() {
           log "🥁 Waiting a few seconds to get new status"
           sleep 5
           playground connector status --connector $connector
+          playground connector open-docs --only-show-url
       fi
   else
       logerror "❌ curl request failed with error code $ret!"
@@ -27731,6 +27833,13 @@ playground_connector_parse_requirements() {
       shift $#
       ;;
 
+    open-docs)
+      action="open-docs"
+      shift
+      playground_connector_open_docs_parse_requirements "$@"
+      shift $#
+      ;;
+
     log-level)
       action="log-level"
       shift
@@ -28710,6 +28819,57 @@ playground_connector_snippets_parse_requirements() {
 }
 
 # :command.parse_requirements
+playground_connector_open_docs_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_connector_open_docs_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="connector open-docs"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --only-show-url)
+
+        # :flag.case_no_arg
+        args['--only-show-url']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
 playground_connector_log_level_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
@@ -29066,6 +29226,7 @@ run() {
     "connector show-config-parameters") playground_connector_show_config_parameters_command ;;
     "connector search-jar") playground_connector_search_jar_command ;;
     "connector snippets") playground_connector_snippets_command ;;
+    "connector open-docs") playground_connector_open_docs_command ;;
     "connector log-level") playground_connector_log_level_command ;;
     "connector create-or-update") playground_connector_create_or_update_command ;;
   esac
