wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -42,6 +42,7 @@ playground_usage() {
   printf "  %s   🏰 Get an history of the examples which were run with run command and run it again\n" "$(green "history")                                   "
   printf "  %s   🌩️  Switch to ccloud environment.\n" "$(green "switch-ccloud")                             "
   printf "  %s   💺  Switch back from previous environment before switch-ccloud was called.\n" "$(green "switch-back")                               "
+  printf "  %s   💰  Retrieve ccloud costs for a range of dates\n" "$(green "ccloud-costs")                              "
   printf "  %s   ✨ Update current confluent platform or connector(s) with new version(s)\n" "$(green "update-version")                            "
   printf "  %s   👐 When --file is not provided, simply open last example you ran with <playground run>\n" "$(green "open")                                      "
   printf "  %s   🛑 Stop currently running example\n" "$(green "stop")                                      "
@@ -1875,6 +1876,43 @@ playground_switch_back_usage() {
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_ccloud_costs_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground ccloud-costs\n\n"
+    printf "  💰  Retrieve ccloud costs for a range of dates\n  \n  All you have to do is to be already logged in with confluent CLI. It is using\n  https://docs.confluent.io/cloud/current/billing/overview.html#retrieve-costs-for-a-range-of-dates\n  \n  Cost data can take up to 72 hours to become available.\n  \n  Start date can reach a maximum of one year into the past\n  \n  One month is the maximum window between start and end dates\n  \n  For accuracy, Confluent recommends using a start_date that is at least 72\n  hours prior to the current date and time.\n\n"
+  else
+    printf "playground ccloud-costs - 💰  Retrieve ccloud costs for a range of dates\n\n"
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground ccloud-costs [OPTIONS]\n"
+  printf "  playground ccloud-costs --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--start-date START_DATE")"
+    printf "    🗓️ start date in format yyyy-mm-dd\n    \n    Default is 30 days ago\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--end-date END_DATE")"
+    printf "    🗓️ end date in format yyyy-mm-dd\n    \n    Default is 3 days ago\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -12697,6 +12735,51 @@ EOF
   fi
 }
 
+# src/lib/validations/validate_date_format.sh
+validate_date_format() {
+  if [[ ! "$1" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]
+  then
+    logerror "must be in format yyyy-mm-dd"
+    return 1
+  fi
+
+  if [[ "$OSTYPE" == "darwin"* ]]
+  then
+    # macOS: Validate the date format
+    if ! date -j -f "%Y-%m-%d" "$1" &>/dev/null
+    then
+      logerror "must be a valid date"
+      return 1
+    fi
+  else
+    # Linux: Validate the date format
+    if ! date -d "$1" &>/dev/null
+    then
+      logerror "must be a valid date"
+      return 1
+    fi
+  fi
+
+  if [[ "$OSTYPE" == "darwin"* ]]
+  then
+    # macOS: Check if the date is more than one year ago
+    if [[ $(date -j -f "%Y-%m-%d" "$1" +%s) -lt $(date -v-1y +%s) ]]
+    then
+      logerror "must be less than one year old"
+      return 1
+    fi
+  else
+    # Linux: Check if the date is more than one year ago
+    if [[ $(date -d "$1" +%s) -lt $(date -d "1 year ago" +%s) ]]
+    then
+      logerror "must be less than one year old"
+      return 1
+    fi
+  fi
+
+  return 0
+}
+
 # src/lib/validations/validate_dir_exists.sh
 validate_dir_exists() {
   [[ -d "$1" ]] || logerror "<$1> must be an existing directory"
@@ -15818,6 +15901,103 @@ playground_switch_back_command() {
 
   log "🚀 Running example "
   echo $last_two_folders/$filename
+}
+
+# :command.function
+playground_ccloud_costs_command() {
+
+  # src/commands/ccloud-costs.sh
+  start_date="${args[--start-date]}"
+  end_date="${args[--end-date]}"
+
+  if [[ ! -n "$start_date" ]]
+  then
+      if [[ "$OSTYPE" == "darwin"* ]]
+      then
+          start_date=$(date -v-1m +%Y-%m-%d)
+      else
+          start_date=$(date -d "1 month ago" +%Y-%m-%d)
+      fi
+  fi
+
+  if [[ ! -n "$end_date" ]]
+  then
+      if [[ "$OSTYPE" == "darwin"* ]]
+      then
+          end_date=$(date -v-3d +%Y-%m-%d)
+      else
+          end_date=$(date -d "3 days ago" +%Y-%m-%d)
+      fi
+  fi
+
+  tmp_dir=$(mktemp -d -t pg-XXXXXXXXXX)
+  if [ -z "$PG_VERBOSE_MODE" ]
+  then
+      trap 'rm -rf $tmp_dir' EXIT
+  else
+      log "🐛📂 not deleting tmp dir $tmp_dir"
+  fi
+
+  INPUT_FILE="$tmp_dir/out.log"
+
+  log "💰 Retrieve ccloud costs for a range from $start_date to $end_date "
+  confluent billing cost list --start-date "$start_date" --end-date "$end_date" --output json > $INPUT_FILE
+  if [[ $? -ne 0 ]]
+  then
+      logerror "❌ Failed to retrieve ccloud costs with command: confluent billing cost list --start-date $start_date --end-date $end_date --output json"
+      cat "$INPUT_FILE"
+      exit 1
+  fi
+
+  log "💰 costs retrieved successfully. Processing costs from JSON..."
+
+  display_histogram() {
+      local file=$1
+      local title=$2
+
+      total_cost_local=$(awk '{sum += $2} END {print sum}' $file)
+      echo ""
+      echo "$title"
+      echo "---------------------------------"
+      echo "TOTAL COST $file: 💰 $total_cost_local"
+      echo "---------------------------------"
+
+      # Find the maximum value in the dataset
+      max_value=$(awk '{if ($2 > max) max = $2} END {print max}' "$file")
+
+      while read -r line; do
+      label=$(echo "$line" | awk '{print $1}')
+      value=$(echo "$line" | awk '{print $2}')
+      # Calculate the proportion of the value relative to the maximum value
+      proportion=$(echo "scale=2; $value / $max_value * 50" | bc) # Scale to a maximum of 20 emojis with precision
+      bar=$(printf '💰%.0s' $(seq 1 ${proportion%.*})) # Generate the bar based on the integer part of the proportion
+      printf "%-20s | %s (%.2f)\n" "$label" "$bar" "$value"
+      done < "$file"
+      echo ""
+  }
+
+  jq -r '.[] | "\(.product) \(.amount | sub("\\$"; ""; "g") | tonumber)"' "$INPUT_FILE" | \
+  awk '{sum[$1] += $2} END {for (product in sum) print product, sum[product]}' | sort -k2 -n > $tmp_dir/product_costs.txt
+
+  jq -r '.[] | "\(.resource_name) \(.amount | sub("\\$"; ""; "g") | tonumber)"' "$INPUT_FILE" | \
+  awk '{sum[$1] += $2} END {for (resource in sum) print resource, sum[resource]}' | sort -k2 -n > $tmp_dir/resource_costs.txt
+
+  jq -r '.[] | "\(.environment) \(.amount | sub("\\$"; ""; "g") | tonumber)"' "$INPUT_FILE" | \
+  awk '{sum[$1] += $2} END {for (env in sum) print env, sum[env]}' | sort -k2 -n > $tmp_dir/environment_costs.txt
+
+  # Calculate and display the total cost across all products
+  total_cost=$(awk '{sum += $2} END {print sum}' $tmp_dir/product_costs.txt)
+  echo "---------------------------------"
+  echo "TOTAL COST ACROSS ALL PRODUCTS: 💰 $total_cost"
+  echo "---------------------------------"
+
+  # Display histograms
+  display_histogram "$tmp_dir/product_costs.txt" "Histogram: Total Cost per Product"
+
+  display_histogram "$tmp_dir/resource_costs.txt" "Histogram: Total Cost per Resource"
+
+  display_histogram "$tmp_dir/environment_costs.txt" "Histogram: Total Cost per Environment"
+
 }
 
 # :command.function
@@ -26397,6 +26577,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    ccloud-costs)
+      action="ccloud-costs"
+      shift
+      playground_ccloud_costs_parse_requirements "$@"
+      shift $#
+      ;;
+
     update-version)
       action="update-version"
       shift
@@ -30007,6 +30194,106 @@ playground_switch_back_parse_requirements() {
 
     esac
   done
+
+}
+
+# :command.parse_requirements
+playground_ccloud_costs_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_ccloud_costs_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.dependencies_filter
+  missing_deps=
+  # :dependency.filter
+  if ! command -v confluent >/dev/null 2>&1; then
+    printf "missing dependency: confluent\n" >&2
+    printf "%s\n\n" "visit https://docs.confluent.io/confluent-cli/current/overview.html to install" >&2
+    missing_deps=1
+  else
+    deps['confluent']="$(command -v confluent | head -n1)"
+  fi
+
+  if [[ -n $missing_deps ]]; then
+    exit 1
+  fi
+
+  # :command.command_filter
+  action="ccloud-costs"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --start-date)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--start-date']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--start-date requires an argument: --start-date START_DATE" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --end-date)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--end-date']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--end-date requires an argument: --end-date END_DATE" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--start-date'] && -n $(validate_date_format "${args['--start-date']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--start-date START_DATE" "$(validate_date_format "${args['--start-date']:-}")" >&2
+    exit 1
+  fi
+
+  # :flag.validations
+  if [[ -v args['--end-date'] && -n $(validate_date_format "${args['--end-date']:-}") ]]; then
+    printf "validation error in %s:\n%s\n" "--end-date END_DATE" "$(validate_date_format "${args['--end-date']:-}")" >&2
+    exit 1
+  fi
 
 }
 
@@ -40687,6 +40974,7 @@ run() {
     "start-environment") playground_start_environment_command ;;
     "switch-ccloud") playground_switch_ccloud_command ;;
     "switch-back") playground_switch_back_command ;;
+    "ccloud-costs") playground_ccloud_costs_command ;;
     "update-version") playground_update_version_command ;;
     "open") playground_open_command ;;
     "stop") playground_stop_command ;;
