display_ngrok_warning

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -7231,17 +7231,17 @@ function verify_confluent_details()
 
 function check_if_continue()
 {
-    if [ ! -z "$GITHUB_RUN_NUMBER" ]
-    then
-        # running with github actions, continue
-        return
-    fi
-    read -p "Continue (y/n)?" choice
-    case "$choice" in
-    y|Y ) ;;
-    n|N ) exit 1;;
-    * ) logerror "invalid response <$choice>!";exit 1;;
-    esac
+  if [ ! -z "$GITHUB_RUN_NUMBER" ]
+  then
+      # running with github actions, continue
+      return
+  fi
+  read -p "Continue (y/n)?" choice
+  case "$choice" in
+  y|Y ) ;;
+  n|N ) exit 1;;
+  * ) logerror "invalid response <$choice>!";exit 1;;
+  esac
 }
 
 function check_if_skip() {
@@ -10833,6 +10833,33 @@ function handle_onprem_connect_rest_api () {
       logerror "❌ curl request failed with error code $ret!"
       exit 1
   fi
+}
+
+function display_ngrok_warning () {
+  if [ -z "$NGROK_AUTH_TOKEN" ]
+  then
+      logerror "NGROK_AUTH_TOKEN is not set. Export it as environment variable or pass it as argument"
+      logerror "Sign up at: https://dashboard.ngrok.com/signup"
+      logerror "If you have already signed up, make sure your authtoken is installed."
+      logerror "Your authtoken is available on your dashboard: https://dashboard.ngrok.com/get-started/your-authtoken"
+      exit 1
+  fi
+
+  logwarn "🚨WARNING🚨"
+  logwarn "It is considered a security risk to run this example on your personal machine since you'll be exposing a TCP port over internet using Ngrok (https://ngrok.com)."
+  logwarn "It is strongly encouraged to run it on a AWS EC2 instance where you'll use Confluent Static Egress IP Addresses (https://docs.confluent.io/cloud/current/networking/static-egress-ip-addresses.html#use-static-egress-ip-addresses-with-ccloud) (only available for public endpoints on AWS) to allow traffic from your Confluent Cloud cluster to your EC2 instance using EC2 Security Group."
+  logwarn ""
+  logwarn "Example in order to set EC2 Security Group with Confluent Static Egress IP Addresses and port xxxx:"
+  logwarn "group=\$(aws ec2 describe-instances --instance-id <\$ec2-instance-id> --output=json | jq '.Reservations[] | .Instances[] | {SecurityGroups: .SecurityGroups}' | jq -r '.SecurityGroups[] | .GroupName')"
+  logwarn "aws ec2 authorize-security-group-ingress --group-name "\$group" --protocol tcp --port xxxx --cidr 13.36.88.88/32"
+  logwarn "aws ec2 authorize-security-group-ingress --group-name "\$group" --protocol tcp --port xxxx --cidr 13.36.88.89/32"
+  logwarn "etc..."
+
+  if [ "$USER" == "vsaboulin" ]
+  then
+    return
+  fi
+  check_if_continue
 }
 
 # src/lib/validations/validate_dir_exists.sh
