wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.1 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.0.rc1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -1520,8 +1520,8 @@ normalize_input() {
 }
 # :command.inspect_args
 inspect_args() {
+  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
   if ((${#args[@]})); then
-    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
     for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
   else
@@ -1536,14 +1536,6 @@ inspect_args() {
       echo "- \${other_args[$i]} = ${other_args[$i]}"
     done
   fi
-
-  if ((${#deps[@]})); then
-    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
-    echo
-    echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
-  fi
-
 }
 
 # :command.user_lib
@@ -2113,6 +2105,16 @@ function check_if_continue()
         # running with github actions or cloudformation, continue
         return
     fi
+    read -p "Continue (y/n)?" choice
+    case "$choice" in
+    y|Y ) ;;
+    n|N ) exit 1;;
+    * ) logerror "invalid response!";exit 1;;
+    esac
+}
+
+function really_check_if_continue()
+{
     read -p "Continue (y/n)?" choice
     case "$choice" in
     y|Y ) ;;
@@ -5213,7 +5215,7 @@ playground_run_command() {
   # determining the docker-compose file from from test_file
   docker_compose_file=$(grep "environment" "$test_file" | grep DIR | grep start.sh | cut -d "/" -f 7 | cut -d '"' -f 1 | tail -n1 | xargs)
 
-  if [ "${docker_compose_file}" != "" ] && [ ! -f "${docker_compose_file}" ]
+  if [ "${docker_compose_file}" != "" ] && [ ! -f "${test_file_directory}/${docker_compose_file}" ]
   then
     docker_compose_file=""
     logwarn "📁 Could not determine docker-compose override file from $test_file !"
@@ -5294,7 +5296,31 @@ playground_run_command() {
     export ENABLE_KCAT=true
   fi
 
-  log "Starting example with $environment_variables_list"
+  log "Opening ${test_file}"
+  if [ ! -z $EDITOR ]
+  then
+    log "Opening ${test_file} using EDITOR environment variable"
+    $EDITOR ${test_file}
+  else
+    if [[ $(type code 2>&1) =~ "not found" ]]
+    then
+      logerror "Could not determine an editor to use, you can set EDITOR environment variable with your preferred choice"
+      exit 1
+    else
+      log "Opening ${test_file} with code (you can change editor by setting EDITOR environment variable)"
+      code ${test_file}
+    fi
+  fi
+
+  # log "Opening ${test_file_directory}/${docker_compose_file}"
+  # $editor ${test_file_directory}/${docker_compose_file}
+  if [ "$environment_variables_list" != "" ]
+  then
+    log "Run example with $environment_variables_list"
+  else
+    log "Run example with all default values"
+  fi
+  really_check_if_continue
   cd $test_file_directory
   ./$filename
 
@@ -6553,9 +6579,7 @@ parse_requirements() {
   done
 
   # :command.dependencies_filter
-  if command -v docker >/dev/null 2>&1; then
-    deps['docker']="$(command -v docker | head -n1)"
-  else
+  if ! command -v docker >/dev/null 2>&1; then
     printf "missing dependency: docker\n" >&2
     printf "%s\n" "👉 Check documentation https://tinyurl.com/4rpcmpjj" >&2
     exit 1
@@ -6698,8 +6722,6 @@ playground_get_connector_list_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="get-connector-list"
 
@@ -6744,8 +6766,6 @@ playground_get_topic_list_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="get-topic-list"
 
@@ -6789,8 +6809,6 @@ playground_get_examples_list_with_fzf_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="get-examples-list-with-fzf"
@@ -6837,6 +6855,10 @@ playground_run_parse_requirements() {
   done
 
   # :command.dependencies_filter
+  if ! command -v fzf >/dev/null 2>&1; then
+    printf "missing dependency: fzf\n" >&2
+    exit 1
+  fi
 
   # :command.command_filter
   action="run"
@@ -7042,8 +7064,6 @@ playground_bootstrap_reproduction_model_parse_requirements() {
   # :command.environment_variables_default
   export OUTPUT_FOLDER="${OUTPUT_FOLDER:-reproduction-models}"
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="bootstrap-reproduction-model"
 
@@ -7220,8 +7240,6 @@ playground_get_properties_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="get-properties"
 
@@ -7283,8 +7301,6 @@ playground_enable_remote_debugging_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="enable-remote-debugging"
 
@@ -7345,8 +7361,6 @@ playground_get_jmx_metrics_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="get-jmx-metrics"
@@ -7429,8 +7443,6 @@ playground_container_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -7562,8 +7574,6 @@ playground_container_recreate_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="container recreate"
 
@@ -7607,8 +7617,6 @@ playground_container_get_ip_addresses_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="container get-ip-addresses"
@@ -7654,8 +7662,6 @@ playground_container_kill_all_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="container kill-all"
 
@@ -7699,8 +7705,6 @@ playground_container_logs_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="container logs"
@@ -7839,8 +7843,6 @@ playground_container_ssh_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="container ssh"
 
@@ -7923,8 +7925,6 @@ playground_container_exec_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="container exec"
@@ -8043,8 +8043,6 @@ playground_container_restart_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="container restart"
 
@@ -8105,8 +8103,6 @@ playground_container_pause_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="container pause"
@@ -8169,8 +8165,6 @@ playground_container_resume_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="container resume"
 
@@ -8232,8 +8226,6 @@ playground_container_kill_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="container kill"
 
@@ -8294,8 +8286,6 @@ playground_topic_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -8385,8 +8375,6 @@ playground_topic_get_number_records_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="topic get-number-records"
 
@@ -8451,8 +8439,6 @@ playground_topic_display_connect_offsets_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="topic display-connect-offsets"
 
@@ -8497,8 +8483,6 @@ playground_topic_display_consumer_offsets_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="topic display-consumer-offsets"
 
@@ -8542,8 +8526,6 @@ playground_topic_describe_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="topic describe"
@@ -8608,8 +8590,6 @@ playground_connector_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -8720,8 +8700,6 @@ playground_connector_status_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="connector status"
 
@@ -8773,8 +8751,6 @@ playground_connector_plugins_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="connector plugins"
 
@@ -8818,8 +8794,6 @@ playground_connector_pause_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="connector pause"
@@ -8885,8 +8859,6 @@ playground_connector_resume_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="connector resume"
 
@@ -8950,8 +8922,6 @@ playground_connector_delete_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="connector delete"
@@ -9017,8 +8987,6 @@ playground_connector_show_lag_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="connector show-lag"
 
@@ -9082,8 +9050,6 @@ playground_connector_log_level_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -9159,8 +9125,6 @@ playground_connector_log_level_get_parse_requirements() {
     esac
   done
 
-  # :command.dependencies_filter
-
   # :command.command_filter
   action="connector log-level get"
 
@@ -9223,8 +9187,6 @@ playground_connector_log_level_set_parse_requirements() {
 
     esac
   done
-
-  # :command.dependencies_filter
 
   # :command.command_filter
   action="connector log-level set"
@@ -9315,7 +9277,6 @@ initialize() {
 # :command.run
 run() {
   declare -A args=()
-  declare -A deps=()
   declare -a other_args=()
   declare -a input=()
   normalize_input "$@"
