wip

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -62,6 +62,8 @@ playground_usage() {
   printf "  %s   🔰 Schema commands\n" "$(green "schema")                                 "
   [[ -n $long_usage ]] && printf "  %s   🔰 Get all schemas versions for specified subject (if --subject is not specified, all subjects will be used)\n" "$(green "schema get")                             "
   [[ -n $long_usage ]] && printf "  %s   ⏺️ Register a schema in specified subject\n" "$(green "schema register")                        "
+  [[ -n $long_usage ]] && printf "  %s   🛡️ Get subject-level compatibility\n" "$(green "schema get-compatibility")               "
+  [[ -n $long_usage ]] && printf "  %s   🛡️ Set subject-level compatibility\n" "$(green "schema set-compatibility")               "
   [[ -n $long_usage ]] && printf "  %s   🧟 Delete schema\n" "$(green "schema delete")                          "
   echo
   printf "%s\n" "$(bold "Debug commands:")"
@@ -1418,9 +1420,11 @@ playground_schema_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "$(bold "Schema commands:")"
-  printf "  %s   🔰 Get all schemas versions for specified subject (if --subject is not specified, all subjects will be used)\n" "$(green "get")     "
-  printf "  %s   ⏺️ Register a schema in specified subject\n" "$(green "register")"
-  printf "  %s   🧟 Delete schema\n" "$(green "delete")  "
+  printf "  %s   🔰 Get all schemas versions for specified subject (if --subject is not specified, all subjects will be used)\n" "$(green "get")              "
+  printf "  %s   ⏺️ Register a schema in specified subject\n" "$(green "register")         "
+  printf "  %s   🛡️ Get subject-level compatibility\n" "$(green "get-compatibility")"
+  printf "  %s   🛡️ Set subject-level compatibility\n" "$(green "set-compatibility")"
+  printf "  %s   🧟 Delete schema\n" "$(green "delete")           "
   echo
 
   # :command.long_usage
@@ -1533,6 +1537,82 @@ playground_schema_register_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples")"
     printf "  playground schema register --subject test-protobuf << 'EOF'\n  syntax = \"proto3\";\n  \n  package com.github.vdesabou;\n  \n  message Customer {\n      int64 count = 1;\n      string first_name = 2;\n      string last_name = 3;\n      string address = 4;\n  }\n  EOF\n  \n  playground schema register --subject test-avro << 'EOF'\n  {\n      \"type\": \"record\",\n      \"namespace\": \"com.github.vdesabou\",\n      \"name\": \"Customer\",\n      \"fields\": [\n          {\n              \"name\": \"count\",\n              \"type\": \"long\",\n              \"doc\": \"count\"\n          },\n          {\n              \"name\": \"first_name\",\n              \"type\": \"string\",\n              \"doc\": \"First Name of Customer\"\n          },\n          {\n              \"name\": \"last_name\",\n              \"type\": \"string\",\n              \"doc\": \"Last Name of Customer\"\n          },\n          {\n              \"name\": \"address\",\n              \"type\": \"string\",\n              \"doc\": \"Address of Customer\"\n          }\n      ]\n  }\n  EOF\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_schema_get_compatibility_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground schema get-compatibility - 🛡️ Get subject-level compatibility\n"
+    echo
+
+  else
+    printf "playground schema get-compatibility - 🛡️ Get subject-level compatibility\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground schema get-compatibility [OPTIONS]\n"
+  printf "  playground schema get-compatibility --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--subject SUBJECT (required)")"
+    printf "    📛 Subject name\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_schema_set_compatibility_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground schema set-compatibility - 🛡️ Set subject-level compatibility\n"
+    echo
+
+  else
+    printf "playground schema set-compatibility - 🛡️ Set subject-level compatibility\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground schema set-compatibility [OPTIONS]\n"
+  printf "  playground schema set-compatibility --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--subject SUBJECT (required)")"
+    printf "    📛 Subject name\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--compatibility COMPATIBILITY (required)")"
+    printf "    Schema Registry compatibility rule\n"
+    printf "    Allowed: BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -10845,8 +10925,14 @@ playground_schema_register_command() {
           id=$(echo "$curl_output" | jq -r .id)
           version=$(echo "$curl_output" | jq -r .version)
 
-          log "🚪 Skipping as schema already exists with id $id (version $version)"
-          exit 0
+          if [[ -n "$replace" ]]
+          then
+              playground schema delete --subject $subject --version $version --permanent
+
+          else
+              log "🚪 Skipping as schema already exists with id $id (version $version)"
+              exit 0
+          fi
       fi
   else
       logerror "❌ curl request failed with error code $ret!"
@@ -10893,6 +10979,54 @@ playground_schema_register_command() {
   #   --data '{
   #     "mode": "READWRITE"
   # }'
+}
+
+# :command.function
+playground_schema_get_compatibility_command() {
+  # src/schema_get_compatibility_command.sh
+  subject="${args[--subject]}"
+
+  ret=$(get_sr_url_and_security)
+
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
+
+  log "🛡️ Get compatibility for subject ${subject}"
+  curl_output=$(curl $sr_security -s -H "Content-Type: application/vnd.schemaregistry.v1+json" "${sr_url}/config/${subject}")
+  ret=$?
+  set -e
+  if [ $ret -eq 0 ]
+  then
+      error_code=$(echo "$curl_output" | jq -r .error_code)
+      if [ "$error_code" != "null" ]
+      then
+          message=$(echo "$curl_output" | jq -r .message)
+          logerror "Command failed with error code $error_code"
+          logerror "$message"
+          exit 1
+      else
+          compatibilityLevel=$(echo "$curl_output" | jq -r .compatibilityLevel)
+          echo "$compatibilityLevel"
+      fi
+  else
+      logerror "❌ curl request failed with error code $ret!"
+      exit 1
+  fi
+}
+
+# :command.function
+playground_schema_set_compatibility_command() {
+  # src/schema_set_compatibility_command.sh
+  subject="${args[--subject]}"
+  compatibility="${args[--compatibility]}"
+
+  ret=$(get_sr_url_and_security)
+
+  sr_url=$(echo "$ret" | cut -d "@" -f 1)
+  sr_security=$(echo "$ret" | cut -d "@" -f 2)
+
+  log "🛡️ Set compatibility for subject ${subject} to $compatibility"
+  curl $sr_security -s -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" --data "{\"compatibility\": \"$compatibility\"}" "${sr_url}/config/${subject}" | jq .
 }
 
 # :command.function
@@ -17317,6 +17451,20 @@ playground_schema_parse_requirements() {
       shift $#
       ;;
 
+    get-compatibility)
+      action="get-compatibility"
+      shift
+      playground_schema_get_compatibility_parse_requirements "$@"
+      shift $#
+      ;;
+
+    set-compatibility)
+      action="set-compatibility"
+      shift
+      playground_schema_set_compatibility_parse_requirements "$@"
+      shift $#
+      ;;
+
     delete)
       action="delete"
       shift
@@ -17545,6 +17693,159 @@ playground_schema_register_parse_requirements() {
   filter_error=$(filter_schema_registry_running)
   if [[ -n $filter_error ]]; then
     echo "$filter_error" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_schema_get_compatibility_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_schema_get_compatibility_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="schema get-compatibility"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --subject)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--subject']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--subject requires an argument: --subject SUBJECT" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--subject']+x} ]]; then
+    printf "missing required flag: --subject SUBJECT\n" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_schema_set_compatibility_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_schema_set_compatibility_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="schema set-compatibility"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --subject)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--subject']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--subject requires an argument: --subject SUBJECT" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --compatibility)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+
+          args['--compatibility']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--compatibility requires an argument: --compatibility COMPATIBILITY" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--subject']+x} ]]; then
+    printf "missing required flag: --subject SUBJECT\n" >&2
+    exit 1
+  fi
+  if [[ -z ${args['--compatibility']+x} ]]; then
+    printf "missing required flag: --compatibility COMPATIBILITY\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ ${args['--compatibility']} ]] && [[ ! ${args['--compatibility']} =~ ^(BACKWARD|BACKWARD_TRANSITIVE|FORWARD|FORWARD_TRANSITIVE|FULL|FULL_TRANSITIVE|NONE)$ ]]; then
+    printf "%s\n" "--compatibility must be one of: BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, FULL, FULL_TRANSITIVE, NONE" >&2
     exit 1
   fi
 
@@ -22480,6 +22781,8 @@ run() {
     "schema") playground_schema_command ;;
     "schema get") playground_schema_get_command ;;
     "schema register") playground_schema_register_command ;;
+    "schema get-compatibility") playground_schema_get_compatibility_command ;;
+    "schema set-compatibility") playground_schema_set_compatibility_command ;;
     "schema delete") playground_schema_delete_command ;;
     "debug") playground_debug_command ;;
     "debug install-vscode-extension") playground_debug_install_vscode_extension_command ;;
