example must be sink connector example when using a java producer

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -5111,7 +5111,16 @@ playground_bootstrap_reproduction_model_command() {
   then
     if [[ "$base1" != *source ]]
     then
-      logerror "ERROR: basis example <$base1> must be source connector example when building a pipeline !"
+      logerror "ERROR: example <$base1> must be source connector example when building a pipeline !"
+      exit 1
+    fi
+  fi
+
+  if [ "$producer" != "none" ]
+  then
+    if [[ "$base1" != *sink ]]
+    then
+      logerror "ERROR: example <$base1> must be sink connector example when using a java producer !"
       exit 1
     fi
   fi
