🧠 Add playground remove-cp-docker-images #6830

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -48,6 +48,7 @@ playground_usage() {
   printf "  %s   👐 When --file is not provided, simply open last example you ran with <playground run>\n" "$(green "open")                                      "
   printf "  %s   🛑 Stop currently running example\n" "$(green "stop")                                      "
   printf "  %s   🧨 Remove all docker images (including docker volumes)\n" "$(green "remove-all-docker-images")                  "
+  printf "  %s   🧹 Remove all Confluent Platform docker images related to a version (a confirmation will be required for every version present)\n" "$(green "remove-cp-docker-images")                   "
   printf "  %s   🧼 playground is actively caching ccloud details (https://kafka-docker-playground.io/#/how-to-use?id=%%f0%%9f%%8c%%a4%%ef%%b8%%8f-confluent-cloud-examples)\n" "$(green "cleanup-cloud-details")                     "
   printf "  %s   🧑‍🎓 Open Confluent documentation of currently running example\n" "$(green "open-docs")                                 "
   printf "  %s   📜 Open playground changelog (https://kafka-docker-playground.io/#/changelog)\n" "$(green "open-changelog")                            "
@@ -2222,6 +2223,33 @@ playground_remove_all_docker_images_usage() {
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_remove_cp_docker_images_usage() {
+  printf "playground remove-cp-docker-images - 🧹 Remove all Confluent Platform docker images related to a version (a confirmation will be required for every version present)\n\n"
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground remove-cp-docker-images [OPTIONS]\n"
+  printf "  playground remove-cp-docker-images --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--version VERSION")"
+    printf "    🔢 Specific version to remove\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -13478,6 +13506,7 @@ playground_status_command() {
   playground connector status | grep -v "applying command to all connectors"
   playground connector show-config | grep -v "applying command to all connectors"
   playground connector show-config-parameters --only-show-file-path | grep -v "applying command to all connectors"
+  playground connector-plugin display-last-updated
 
   playground topic list
 
@@ -17351,6 +17380,36 @@ playground_remove_all_docker_images_command() {
   docker image rm $(docker image list | grep -v "oracle/database"  | grep -v "db-prebuilt" | awk 'NR>1 {print $3}') -f
   docker system prune -a -f
   docker volume rm $(docker volume ls -qf dangling=true)
+}
+
+# :command.function
+playground_remove_cp_docker_images_command() {
+
+  # src/commands/remove-cp-docker-images.sh
+  version=${args[--version]}
+
+  if [[ -n "$version" ]]
+  then
+      log "🧹 removing Confluent Platform docker images: $version"
+      check_if_continue
+      docker image ls | grep confluentinc | grep $version | awk '{print $3}' | xargs docker rmi -f
+      exit 0
+  fi
+
+  LATEST_TAG=$(grep "export TAG" $root_folder/scripts/utils.sh | head -1 | cut -d "=" -f 2 | cut -d " " -f 1)
+  if [ -z "$LATEST_TAG" ]
+  then
+      logerror "❌ error while getting default TAG "
+      exit 1
+  fi
+
+  for version in $(docker image ls | grep confluentinc | grep -v "<none>" | grep -Ev "latest|2.0.0|$LATEST_TAG"  | awk '{print $2}' | sort | uniq);
+  do
+      log "🧹 removing Confluent Platform docker images: $version (skipping default TAG $LATEST_TAG)"
+      check_if_continue
+      docker image ls | grep confluentinc | grep $version | awk '{print $3}' | xargs docker rmi -f
+  done
+
 }
 
 # :command.function
@@ -27647,6 +27706,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    remove-cp-docker-images)
+      action="remove-cp-docker-images"
+      shift
+      playground_remove_cp_docker_images_parse_requirements "$@"
+      shift $#
+      ;;
+
     cleanup-cloud-details)
       action="cleanup-cloud-details"
       shift
@@ -32002,6 +32068,64 @@ playground_remove_all_docker_images_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+playground_remove_cp_docker_images_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        playground_remove_cp_docker_images_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="remove-cp-docker-images"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --version)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--version']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--version requires an argument: --version VERSION" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -42841,6 +42965,7 @@ run() {
     "open") playground_open_command ;;
     "stop") playground_stop_command ;;
     "remove-all-docker-images") playground_remove_all_docker_images_command ;;
+    "remove-cp-docker-images") playground_remove_cp_docker_images_command ;;
     "cleanup-cloud-details") playground_cleanup_cloud_details_command ;;
     "open-docs") playground_open_docs_command ;;
     "open-changelog") playground_open_changelog_command ;;
