do not open file when run command is used (--open)

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.0.rc1 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -233,8 +233,8 @@ playground_run_usage() {
     echo
 
     # :flag.usage
-    printf "  %s\n" "$(magenta "--skip-editor, -s")"
-    printf "    Skip opening example file with text editor\n"
+    printf "  %s\n" "$(magenta "--open, -o")"
+    printf "    Opening example file with text editor set with EDITOR environment variable\n    (default is code).\n"
     echo
 
     # :flag.usage
@@ -781,7 +781,7 @@ playground_container_logs_usage() {
     echo
 
     # :flag.usage
-    printf "  %s\n" "$(magenta "--open, -o EDITOR")"
+    printf "  %s\n" "$(magenta "--open, -o")"
     printf "    Save output to a file and open with editor passed as argument (default is\n    code).\n"
     echo
 
@@ -1694,8 +1694,8 @@ normalize_input() {
 }
 # :command.inspect_args
 inspect_args() {
-  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
   if ((${#args[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
     for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
   else
@@ -1710,6 +1710,14 @@ inspect_args() {
       echo "- \${other_args[$i]} = ${other_args[$i]}"
     done
   fi
+
+  if ((${#deps[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
+    echo
+    echo deps:
+    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+  fi
+
 }
 
 # :command.user_lib
@@ -5542,7 +5550,7 @@ playground_run_command() {
   root_folder=${DIR_CLI}/../..
 
   test_file="${args[--file]}"
-  skip_editor="${args[--skip-editor]}"
+  editor="${args[--open]}"
   tag="${args[--tag]}"
   connector_tag="${args[--connector-tag]}"
   connector_zip="${args[--connector-zip]}"
@@ -5685,7 +5693,7 @@ playground_run_command() {
     export ENABLE_SR_MAVEN_PLUGIN_NODE=true
   fi
 
-  if [[ ! -n "$skip_editor" ]]
+  if [[ -n "$editor" ]]
   then
     if [ ! -z $EDITOR ]
     then
@@ -6654,7 +6662,22 @@ playground_container_logs_command() {
     docker container logs "$container" > "$filename" 2>&1
     if [ $? -eq 0 ]
     then
-      $editor "$filename"
+      if [ ! -z $EDITOR ]
+      then
+        log "📖 Opening ${filename} using EDITOR environment variable"
+        $EDITOR ${filename}
+      else
+        if [[ $(type code 2>&1) =~ "not found" ]]
+        then
+          logerror "Could not determine an editor to use, you can set EDITOR environment variable with your preferred choice"
+          exit 1
+        else
+          log "📖 Opening ${filename} with code (you can change editor by setting EDITOR environment variable)"
+          code ${filename}
+        fi
+      fi
+    else
+      logerror "Failed to get logs using container logs $container"
     fi
   elif [[ -n "$log" ]]
   then
@@ -7151,7 +7174,9 @@ parse_requirements() {
   done
 
   # :command.dependencies_filter
-  if ! command -v docker >/dev/null 2>&1; then
+  if command -v docker >/dev/null 2>&1; then
+    deps['docker']="$(command -v docker | head -n1)"
+  else
     printf "missing dependency: docker\n" >&2
     printf "%s\n" "👉 Check documentation https://tinyurl.com/4rpcmpjj" >&2
     exit 1
@@ -7308,6 +7333,8 @@ playground_get_connector_list_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="get-connector-list"
 
@@ -7352,6 +7379,8 @@ playground_get_topic_list_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="get-topic-list"
 
@@ -7395,6 +7424,8 @@ playground_get_examples_list_with_fzf_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="get-examples-list-with-fzf"
@@ -7462,7 +7493,9 @@ playground_run_parse_requirements() {
   done
 
   # :command.dependencies_filter
-  if ! command -v fzf >/dev/null 2>&1; then
+  if command -v fzf >/dev/null 2>&1; then
+    deps['fzf']="$(command -v fzf | head -n1)"
+  else
     printf "missing dependency: fzf\n" >&2
     exit 1
   fi
@@ -7495,10 +7528,10 @@ playground_run_parse_requirements() {
         ;;
 
       # :flag.case
-      --skip-editor | -s)
+      --open | -o)
 
         # :flag.case_no_arg
-        args['--skip-editor']=1
+        args['--open']=1
         shift
         ;;
 
@@ -7547,6 +7580,11 @@ playground_run_parse_requirements() {
 
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
+          # :flag.validations
+          if [[ -n $(validate_file_exists "$2") ]]; then
+            printf "validation error in %s:\n%s\n" "--connector-zip CONNECTOR_ZIP" "$(validate_file_exists "$2")" >&2
+            exit 1
+          fi
 
           args['--connector-zip']="$2"
           shift
@@ -7683,6 +7721,8 @@ playground_re_run_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="re-run"
 
@@ -7732,7 +7772,9 @@ playground_bootstrap_reproduction_model_parse_requirements() {
   export OUTPUT_FOLDER="${OUTPUT_FOLDER:-reproduction-models}"
 
   # :command.dependencies_filter
-  if ! command -v fzf >/dev/null 2>&1; then
+  if command -v fzf >/dev/null 2>&1; then
+    deps['fzf']="$(command -v fzf | head -n1)"
+  else
     printf "missing dependency: fzf\n" >&2
     exit 1
   fi
@@ -7913,6 +7955,8 @@ playground_get_properties_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="get-properties"
 
@@ -7974,6 +8018,8 @@ playground_get_all_schemas_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="get-all-schemas"
 
@@ -8024,6 +8070,8 @@ playground_enable_remote_debugging_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="enable-remote-debugging"
@@ -8085,6 +8133,8 @@ playground_get_jmx_metrics_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="get-jmx-metrics"
@@ -8167,6 +8217,8 @@ playground_container_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -8298,6 +8350,8 @@ playground_container_recreate_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="container recreate"
 
@@ -8341,6 +8395,8 @@ playground_container_get_ip_addresses_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="container get-ip-addresses"
@@ -8386,6 +8442,8 @@ playground_container_kill_all_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="container kill-all"
 
@@ -8430,6 +8488,8 @@ playground_container_logs_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="container logs"
 
@@ -8460,21 +8520,9 @@ playground_container_logs_parse_requirements() {
           exit 1
         fi
 
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          if [[ -n $(validate_editor_exists "$2") ]]; then
-            printf "validation error in %s:\n%s\n" "--open, -o EDITOR" "$(validate_editor_exists "$2")" >&2
-            exit 1
-          fi
-
-          args['--open']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--open requires an argument: --open, -o EDITOR" >&2
-          exit 1
-        fi
+        # :flag.case_no_arg
+        args['--open']=1
+        shift
         ;;
 
       # :flag.case
@@ -8567,6 +8615,8 @@ playground_container_ssh_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="container ssh"
 
@@ -8649,6 +8699,8 @@ playground_container_exec_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="container exec"
@@ -8767,6 +8819,8 @@ playground_container_restart_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="container restart"
 
@@ -8827,6 +8881,8 @@ playground_container_pause_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="container pause"
@@ -8889,6 +8945,8 @@ playground_container_resume_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="container resume"
 
@@ -8950,6 +9008,8 @@ playground_container_kill_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="container kill"
 
@@ -9010,6 +9070,8 @@ playground_topic_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -9113,6 +9175,8 @@ playground_topic_get_number_records_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="topic get-number-records"
 
@@ -9177,6 +9241,8 @@ playground_topic_display_connect_offsets_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="topic display-connect-offsets"
 
@@ -9221,6 +9287,8 @@ playground_topic_display_consumer_offsets_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="topic display-consumer-offsets"
 
@@ -9264,6 +9332,8 @@ playground_topic_describe_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="topic describe"
@@ -9329,6 +9399,8 @@ playground_topic_consume_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="topic consume"
 
@@ -9372,6 +9444,8 @@ playground_connector_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -9496,6 +9570,8 @@ playground_connector_status_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector status"
 
@@ -9540,6 +9616,8 @@ playground_connector_plugins_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector plugins"
 
@@ -9583,6 +9661,8 @@ playground_connector_pause_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="connector pause"
@@ -9648,6 +9728,8 @@ playground_connector_restart_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector restart"
 
@@ -9711,6 +9793,8 @@ playground_connector_resume_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="connector resume"
@@ -9776,6 +9860,8 @@ playground_connector_delete_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector delete"
 
@@ -9840,6 +9926,8 @@ playground_connector_show_lag_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector show-lag"
 
@@ -9903,6 +9991,8 @@ playground_connector_log_level_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action=${1:-}
@@ -9978,6 +10068,8 @@ playground_connector_log_level_get_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+
   # :command.command_filter
   action="connector log-level get"
 
@@ -10040,6 +10132,8 @@ playground_connector_log_level_set_parse_requirements() {
 
     esac
   done
+
+  # :command.dependencies_filter
 
   # :command.command_filter
   action="connector log-level set"
@@ -10130,6 +10224,7 @@ initialize() {
 # :command.run
 run() {
   declare -A args=()
+  declare -A deps=()
   declare -a other_args=()
   declare -a input=()
   normalize_input "$@"
