Add playground debug java-debug #5663

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -96,6 +96,7 @@ playground_usage() {
   printf "  %s   👻 Take a heap dump\n" "$(green "debug heap-dump")                    "
   printf "  %s   🕵️‍♂️ Take a tcp dump (sniffing network)\n" "$(green "debug tcp-dump")                     "
   printf "  %s   🚫 Blocking traffic using iptables\n" "$(green "debug block-traffic")                "
+  printf "  %s   🐞 JVM arguments for SSL, Kerberos or Class Loading\n" "$(green "debug java-debug")                   "
   printf "  %s   🛩️ Record flight recorder\n" "$(green "debug flight-recorder")              "
   printf "  %s   🧬 Set log level for any package\n" "$(green "debug log-level")                    "
   echo
@@ -3142,6 +3143,7 @@ playground_debug_usage() {
   printf "  %s   👻 Take a heap dump\n" "$(green "heap-dump")              "
   printf "  %s   🕵️‍♂️ Take a tcp dump (sniffing network)\n" "$(green "tcp-dump")               "
   printf "  %s   🚫 Blocking traffic using iptables\n" "$(green "block-traffic")          "
+  printf "  %s   🐞 JVM arguments for SSL, Kerberos or Class Loading\n" "$(green "java-debug")             "
   printf "  %s   🛩️ Record flight recorder\n" "$(green "flight-recorder")        "
   printf "  %s   🧬 Set log level for any package\n" "$(green "log-level")              "
   echo
@@ -3490,6 +3492,61 @@ playground_debug_block_traffic_usage() {
     printf "%s\n" "$(bold "Examples")"
     printf "  playground debug block-traffic --destination google.com --action start\n"
     printf "  playground debug block-traffic --container broker --destination zookeeper\n  --action start\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+playground_debug_java_debug_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "playground debug java-debug - 🐞 JVM arguments for SSL, Kerberos or Class Loading\n"
+    echo
+
+  else
+    printf "playground debug java-debug - 🐞 JVM arguments for SSL, Kerberos or Class Loading\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "== Usage ==")"
+  printf "  playground debug java-debug [OPTIONS]\n"
+  printf "  playground debug java-debug --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--container, -c CONTAINER")"
+    printf "    🐳 Container name\n"
+    printf "    Default: connect\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--type TYPE (required)")"
+    printf "    - ssl_all: Enable all SSL debugging, i.e -Djavax.net.debug=all\n    - ssl_handshake: Enable SSL handshake debugging, i.e\n    -Djavax.net.debug=ssl:handshake\n    - class_loading: Enable class loading debugging, i.e -verbose:class\n    - kerberos: Enable Kerberos debugging, i.e -Dsun.security.krb5.debug=true\n"
+    printf "    Allowed: ssl_all, ssl_handshake, class_loading, kerberos\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--action ACTION")"
+    printf "    🟢 enable or disable\n"
+    printf "    Allowed: enable, disable\n"
+    printf "    Default: enable\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples")"
+    printf "  playground debug java-debug --type class_loading\n"
+    printf "  playground debug java-debug --container broker --action start\n"
     echo
 
   fi
@@ -7996,7 +8053,7 @@ function maybe_create_image()
       then
         CONNECT_3RDPARTY_INSTALL="if [ ! -f /tmp/done ]; then yum -y install --disablerepo='Confluent*' bind-utils openssl unzip findutils net-tools nc jq which iptables libmnl krb5-workstation krb5-libs vim && yum clean all && rm -rf /var/cache/yum && rpm -i --nosignature https://rpmfind.net/linux/centos/8-stream/AppStream/aarch64/os/Packages/tcpdump-4.9.3-2.el8.aarch64.rpm && touch /tmp/done; fi"
       else
-        CONNECT_3RDPARTY_INSTALL="if [ ! -f /tmp/done ]; then && yum -y install --disablerepo='Confluent*' tcpdump bind-utils openssl unzip findutils net-tools nc jq which iptables libmnl krb5-workstation krb5-libs vim && yum clean all && rm -rf /var/cache/yum && touch /tmp/done; fi"
+        CONNECT_3RDPARTY_INSTALL="if [ ! -f /tmp/done ]; then yum -y install --disablerepo='Confluent*' tcpdump bind-utils openssl unzip findutils net-tools nc jq which iptables libmnl krb5-workstation krb5-libs vim && yum clean all && rm -rf /var/cache/yum && touch /tmp/done; fi"
       fi
     else
       export CONNECT_USER="root"
@@ -17715,6 +17772,11 @@ playground_tcp_proxy_start_command() {
   service_response_corrupt="${args[--service-response-corrupt]}"
   skip_automatic_connector_config=${args[--skip-automatic-connector-config]}
 
+  # keep TAG, CONNECT TAG and ORACLE_IMAGE
+  export TAG=$(docker inspect -f '{{.Config.Image}}' broker 2> /dev/null | cut -d ":" -f 2)
+  export CONNECT_TAG=$(docker inspect -f '{{.Config.Image}}' connect 2> /dev/null | cut -d ":" -f 2)
+  export ORACLE_IMAGE=$(docker inspect -f '{{.Config.Image}}' oracle 2> /dev/null)
+
   docker_command=$(playground state get run.docker_command)
   if [ "$docker_command" == "" ]
   then
@@ -18423,6 +18485,61 @@ playground_debug_block_traffic_command() {
   log "Output of command iptables-save"
   docker exec --privileged --user root ${container} bash -c "iptables-save"
 
+}
+
+# :command.function
+playground_debug_java_debug_command() {
+  # src/commands/debug/java-debug.sh
+  container="${args[--container]}"
+  type="${args[--type]}"
+  action="${args[--action]}"
+
+  # keep TAG, CONNECT TAG and ORACLE_IMAGE
+  export TAG=$(docker inspect -f '{{.Config.Image}}' broker 2> /dev/null | cut -d ":" -f 2)
+  export CONNECT_TAG=$(docker inspect -f '{{.Config.Image}}' connect 2> /dev/null | cut -d ":" -f 2)
+  export ORACLE_IMAGE=$(docker inspect -f '{{.Config.Image}}' oracle 2> /dev/null)
+
+  docker_command=$(playground state get run.docker_command)
+  if [ "$docker_command" == "" ]
+  then
+    logerror "docker_command retrieved from $root_folder/playground.ini is empty !"
+    exit 1
+  fi
+
+  if [[ "$action" == "enable" ]]
+  then
+      case "${type}" in
+          "ssl_all")
+              OPTS="-Djavax.net.debug=all"
+          ;;
+          "ssl_handshake")
+              OPTS="-Djavax.net.debug=ssl:handshake"
+          ;;
+          "class_loading")
+              OPTS="-verbose:class"
+          ;;
+          "kerberos")
+              OPTS="-Dsun.security.krb5.debug=true"
+          ;;
+      esac
+
+      cat << EOF > /tmp/docker-compose.override.java.debug.yml
+services:
+  $container:
+    environment:
+      KAFKA_OPTS: "$OPTS"
+      DUMMY: $RANDOM
+EOF
+      log "🟢 enabling container $container with JVM arguments KAFKA_OPTS: $OPTS"
+      echo "$docker_command" > /tmp/playground-command-java-debug
+      sed -i -E -e "s|up -d --quiet-pull|-f /tmp/docker-compose.override.java.debug.yml up -d --quiet-pull|g" /tmp/playground-command-java-debug
+      bash /tmp/playground-command-java-debug
+
+  else
+      log "🔴 restoring previous JVM arguments for container $container"
+      echo "$docker_command" > /tmp/playground-command
+      bash /tmp/playground-command
+  fi
 }
 
 # :command.function
@@ -29612,6 +29729,13 @@ playground_debug_parse_requirements() {
       shift $#
       ;;
 
+    java-debug)
+      action="java-debug"
+      shift
+      playground_debug_java_debug_parse_requirements "$@"
+      shift $#
+      ;;
+
     flight-recorder)
       action="flight-recorder"
       shift
@@ -30174,6 +30298,111 @@ playground_debug_block_traffic_parse_requirements() {
   # :command.whitelist_filter
   if [[ ${args['--action']:-} ]] && [[ ! ${args['--action']:-} =~ ^(start|stop)$ ]]; then
     printf "%s\n" "--action must be one of: start, stop" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+playground_debug_java_debug_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        playground_debug_java_debug_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="debug java-debug"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--container']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container requires an argument: --container, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --type)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--type']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--type requires an argument: --type TYPE" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --action)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--action']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--action requires an argument: --action ACTION" >&2
+          exit 1
+        fi
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--type']+x} ]]; then
+    printf "missing required flag: --type TYPE\n" >&2
+    exit 1
+  fi
+
+  # :command.default_assignments
+  [[ -n ${args['--container']:-} ]] || args['--container']="connect"
+  [[ -n ${args['--action']:-} ]] || args['--action']="enable"
+
+  # :command.whitelist_filter
+  if [[ ${args['--type']:-} ]] && [[ ! ${args['--type']:-} =~ ^(ssl_all|ssl_handshake|class_loading|kerberos)$ ]]; then
+    printf "%s\n" "--type must be one of: ssl_all, ssl_handshake, class_loading, kerberos" >&2
+    exit 1
+  fi
+  if [[ ${args['--action']:-} ]] && [[ ! ${args['--action']:-} =~ ^(enable|disable)$ ]]; then
+    printf "%s\n" "--action must be one of: enable, disable" >&2
     exit 1
   fi
 
@@ -35314,6 +35543,7 @@ run() {
     "debug heap-dump") playground_debug_heap_dump_command ;;
     "debug tcp-dump") playground_debug_tcp_dump_command ;;
     "debug block-traffic") playground_debug_block_traffic_command ;;
+    "debug java-debug") playground_debug_java_debug_command ;;
     "debug flight-recorder") playground_debug_flight_recorder_command ;;
     "debug log-level") playground_debug_log_level_command ;;
     "debug log-level get") playground_debug_log_level_get_command ;;
