get tag from docker ps

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -14104,9 +14104,16 @@ playground_debug_tcp_dump_command() {
   docker exec $container type tcpdump > /dev/null 2>&1
   if [ $? != 0 ]
   then
+      tag=$(docker ps --format '{{.Image}}' | egrep 'confluentinc/cp-.*-connect-base:' | awk -F':' '{print $2}')
+      if [ $? != 0 ] || [ "$tag" == "" ]
+      then
+          logerror "Could not find current CP version from docker ps"
+          exit 1
+      fi
+
       logwarn "tcpdump is not installed on container $container, attempting to install it"
 
-      if [[ "$TAG" == *ubi8 ]] || version_gt $TAG_BASE "5.9.0"
+      if [[ "$tag" == *ubi8 ]] || version_gt $tag "5.9.0"
       then
         if [ `uname -m` = "arm64" ]
         then
@@ -14175,8 +14182,14 @@ playground_debug_block_traffic_command() {
   docker exec $container type iptables > /dev/null 2>&1
   if [ $? != 0 ]
   then
+      tag=$(docker ps --format '{{.Image}}' | egrep 'confluentinc/cp-.*-connect-base:' | awk -F':' '{print $2}')
+      if [ $? != 0 ] || [ "$tag" == "" ]
+      then
+          logerror "Could not find current CP version from docker ps"
+          exit 1
+      fi
       logwarn "iptables is not installed on container $container, attempting to install it"
-      if [[ "$TAG" == *ubi8 ]] || version_gt $TAG_BASE "5.9.0"
+      if [[ "$tag" == *ubi8 ]] || version_gt $tag "5.9.0"
       then
         docker exec --privileged --user root $container bash -c "yum -y install --disablerepo='Confluent*' iptables"
       else
@@ -14280,9 +14293,16 @@ playground_debug_flight_recorder_command() {
   docker exec $container type jcmd > /dev/null 2>&1
   if [ $? != 0 ]
   then
+      tag=$(docker ps --format '{{.Image}}' | egrep 'confluentinc/cp-.*-connect-base:' | awk -F':' '{print $2}')
+      if [ $? != 0 ] || [ "$tag" == "" ]
+      then
+          logerror "Could not find current CP version from docker ps"
+          exit 1
+      fi
+
       logwarn "jcmd is not installed on container $container, attempting to install it"
 
-      if [[ "$TAG" == *ubi8 ]] || version_gt $TAG_BASE "5.9.0"
+      if [[ "$tag" == *ubi8 ]] || version_gt $tag "5.9.0"
       then
         docker exec --privileged --user root $container bash -c "yum -y install --disablerepo='Confluent*' openjdk"
       else
@@ -14646,7 +14666,13 @@ playground_topic_get_number_records_command() {
           esac
           wc -l /tmp/result.log | awk '{print $1}'
       else
-          if ! version_gt $TAG_BASE "6.9.9" && [ "$security" != "" ]
+          tag=$(docker ps --format '{{.Image}}' | egrep 'confluentinc/cp-.*-connect-base:' | awk -F':' '{print $2}')
+          if [ $? != 0 ] || [ "$tag" == "" ]
+          then
+              logerror "Could not find current CP version from docker ps"
+              exit 1
+          fi
+          if ! version_gt $tag "6.9.9" && [ "$security" != "" ]
           then
               # GetOffsetShell does not support security before 7.x
               get_security_broker "--consumer.config"
@@ -15829,8 +15855,14 @@ playground_topic_produce_command() {
       fi
 
       set +e
+      tag=$(docker ps --format '{{.Image}}' | egrep 'confluentinc/cp-.*-connect-base:' | awk -F':' '{print $2}')
+      if [ $? != 0 ] || [ "$tag" == "" ]
+      then
+          logerror "Could not find current CP version from docker ps"
+          exit 1
+      fi
       log "🏗 Building jar for schema-validator"
-      docker run -i --rm -e TAG=$TAG_BASE -v "${root_folder}/scripts/cli/src/schema-validator":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -v "${root_folder}/scripts/cli/src/schema-validator/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:3.6.1-jdk-11 mvn -s /tmp/settings.xml -Dkafka.tag=$TAG package > /tmp/result.log 2>&1
+      docker run -i --rm -e TAG=$tag -v "${root_folder}/scripts/cli/src/schema-validator":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -v "$root_folder/scripts/settings.xml:/tmp/settings.xml" -v "${root_folder}/scripts/cli/src/schema-validator/target:/usr/src/mymaven/target" -w /usr/src/mymaven maven:3.6.1-jdk-11 mvn -s /tmp/settings.xml -Dkafka.tag=$tag package > /tmp/result.log 2>&1
       if [ $? != 0 ]
       then
           logerror "ERROR: failed to build java component schema-validator"
@@ -17569,7 +17601,14 @@ playground_connector_stop_command() {
   connector="${args[--connector]}"
   verbose="${args[--verbose]}"
 
-  if ! version_gt $TAG_BASE "7.4.99"; then
+  tag=$(docker ps --format '{{.Image}}' | egrep 'confluentinc/cp-.*-connect-base:' | awk -F':' '{print $2}')
+  if [ $? != 0 ] || [ "$tag" == "" ]
+  then
+      logerror "Could not find current CP version from docker ps"
+      exit 1
+  fi
+
+  if ! version_gt $tag "7.4.99"; then
       logerror "❌ stop connector is available since CP 7.5 only"
       exit 1
   fi
