added --open flag to get-all-schemas

diff --git a/scripts/cli/playground b/scripts/cli/playground
--- a/scripts/cli/playground
+++ b/scripts/cli/playground
@@ -943,13 +943,19 @@ playground_get_all_schemas_usage() {
   fi
 
   printf "%s\n" "$(bold "== Usage ==")"
-  printf "  playground get-all-schemas\n"
+  printf "  playground get-all-schemas [OPTIONS]\n"
   printf "  playground get-all-schemas --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "$(bold "== Options ==")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--open, -o")"
+    printf "    🔖 Save output to a file and open with text editor set with config.ini\n    (default is code)\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "$(magenta "--help, -h")"
@@ -7949,27 +7955,72 @@ playground_get_properties_command() {
 # :command.function
 playground_get_all_schemas_command() {
   # src/get_all_schemas_command.sh
-  ret=$(get_sr_url_and_security)
+  open="${args[--open]}"
 
-  sr_url=$(echo "$ret" | cut -d "@" -f 1)
-  security=$(echo "$ret" | cut -d "@" -f 2)
+  function get_all_schemas() {
+    ret=$(get_sr_url_and_security)
 
-  # Get a list of all subjects in the schema registry
-  subjects=$(curl $security -s "${sr_url}/subjects")
+    sr_url=$(echo "$ret" | cut -d "@" -f 1)
+    security=$(echo "$ret" | cut -d "@" -f 2)
 
-  log "Displaying all subjects 🔰 and versions 💯"
-  # Loop through each subject and retrieve all its schema versions and definitions
-  for subject in $(echo "${subjects}" | jq -r '.[]'); do
-    # Get a list of all schema versions for the subject
-    versions=$(curl $security -s "${sr_url}/subjects/${subject}/versions")
+    # Get a list of all subjects in the schema registry
+    subjects=$(curl $security -s "${sr_url}/subjects")
 
-    # Loop through each version and retrieve the schema
-    for version in $(echo "${versions}" | jq -r '.[]'); do
-      schema=$(curl $security -s "${sr_url}/subjects/${subject}/versions/${version}/schema" | jq .)
-      log "🔰 ${subject} 💯 ${version}"
-      echo "${schema}"
+    if [[ -n "$open" ]]
+    then
+      echo "Displaying all subjects 🔰 and versions 💯"
+    else
+      log "Displaying all subjects 🔰 and versions 💯"
+    fi
+    # Loop through each subject and retrieve all its schema versions and definitions
+    for subject in $(echo "${subjects}" | jq -r '.[]'); do
+      # Get a list of all schema versions for the subject
+      versions=$(curl $security -s "${sr_url}/subjects/${subject}/versions")
+
+      # Loop through each version and retrieve the schema
+      for version in $(echo "${versions}" | jq -r '.[]'); do
+        schema=$(curl $security -s "${sr_url}/subjects/${subject}/versions/${version}/schema" | jq .)
+
+        if [[ -n "$open" ]]
+        then
+          echo "🔰 ${subject} 💯 ${version}"
+        else
+          log "🔰 ${subject} 💯 ${version}"
+        fi
+        echo "${schema}"
+      done
     done
-  done
+  }
+
+  if [[ -n "$open" ]]
+  then
+    filename="/tmp/get-all-schemas-`date '+%Y-%m-%d-%H-%M-%S'`.log"
+    log "Opening $filename with editor $editor"
+    get_all_schemas > "$filename" 2>&1
+    if [ $? -eq 0 ]
+    then
+      if config_has_key "editor"
+      then
+        editor=$(config_get "editor")
+        log "📖 Opening ${filename} using configured editor $editor"
+        $editor $filename
+      else
+        if [[ $(type code 2>&1) =~ "not found" ]]
+        then
+          logerror "Could not determine an editor to use as default code is not found - you can change editor by updating config.ini"
+          exit 1
+        else
+          log "📖 Opening ${filename} with code (default) - you can change editor by updating config.ini"
+          code $filename
+        fi
+      fi
+    else
+      logerror "Failed to get schemas"
+    fi
+  else
+
+    get_all_schemas
+  fi
 }
 
 # :command.function
@@ -10611,6 +10662,13 @@ playground_get_all_schemas_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --open | -o)
+
+        # :flag.case_no_arg
+        args['--open']=1
+        shift
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
